### ISSUE TITLE
Improve API interoperability with standard Promise

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1722]
Originally reported by @jzaefferer at: http://bugs.jquery.com/ticket/14510
<p>
Discussed this at the jQuery team meeting in Amsterdam: The spec is still changing a lot (within whatwg and draft pages on github), so we'll wait for it to ship, unprefixed, not behind a flag, in stable browsers first.
</p>
<p>
Once that happened, we should change/fix our implementation to match the spec (and shipped implementation). 
</p>
<p>
Can use .pipe() to continue using any jQuery-specific functionality.
</p>

**Comment by benjamingr** [comment]
Please consider when you're executing a handler to deferred. One of the thing every A+ promise does is always defer execution of handlers so:

```js
myPromise.then(function(){
    log("World");
});
log("Hello ");
```

Will _always_ log "Hello World" on an A+ promise implementation. jQuery on the other hand will log either "Hello World" or "World Hello" _sometimes_ based on whether or not the promise resolved before or after the `then` was called.

This has been a steady source of bugs where developers rely on the order and are exposed to race conditions. I think fixing this mistake in the next major revision of jQuery could _really_ help a lot of developers and help prevent race condition related bugs.

**Comment by dmethvin** [comment]
@benjamingr The changes in #1996 bring `.then` up to Promise/A+, we run the test suite to be sure. We should be landing that soon.

**Comment by benjamingr** [comment]
@dmethvin that landing in jQuery would be _awesome_ - does this means you'll also address `catch` correctly? This is huge - I answer promise questions on StackOverflow pretty often and bringing `then` up to A+ standard would help a ton of people.

I think I got confused by the issue date because it was migrated.

**Comment by dmethvin** [comment]
> does this means you'll also address `catch` correctly?

You mean do we turn exceptions into rejections rather than allowing them to be uncaught? Yes, although we're working on how to report those in some reasonably visible way. It's related to the issue you opened in https://github.com/petkaantonov/bluebird/issues/428, it's just too easy for programming errors to be lost and you see this problem over and over when people start working with Promises. Now imagine that someone drops a Promise-heavy piece of code in their web page that was written by a third party and has some problem. They won't know why it's just not working but has no visible errors.

**Comment by benjamingr** [comment]
Bluebird does a pretty good job of detecting unhandled rejections (a simple heuristic is that those are promises you don't add `done` or a catch handler to in this or the next turn).

I've recently [made a survey](
https://github.com/petkaantonov/bluebird/issues/357#issuecomment-68995997) on how people use Bluebird's `onPossiblyUnhandledRejection` hook (which lets you determine what to do when the library thinks there's a rejection) - the vast majority of people stick to the default behavior which is to log the error the console when the developer can see it [here](http://jsfiddle.net/coak1yud/). 

Note that bluebird does more than just track the rejections (it stitches the stack traces, wraps primitives implicitly for logging and has a much bigger api etc) and you have different important considerations in jQuery (such as file size). So you might not want to implement all the debugging stuff that's in bluebird. Honestly just doing A+ compliance itself is huge and doing A+ compliance and unhandled rejection handling is crossing the line between good news for interoperability and being able to use jQuery as the main promise implementation in a frontend project.

**Comment by paulirish** [comment]
Just FYI, There's a good amount of tooling for native promises.

#### [asynchronous callstacks](http://www.html5rocks.com/en/tutorials/developertools/async-call-stack/) (already available)

![](http://www.html5rocks.com/en/tutorials/developertools/async-call-stack/promises-after.gif)

#### [dedicated promises panel](https://plus.google.com/+UmarHansa/posts/XWHqThx8Tyj) (coming soon)
![image](https://cloud.githubusercontent.com/assets/39191/5828263/dc5d214e-a0b6-11e4-9d54-6d28c07e0d3e.png)

I think it's worth considering using the native Promise impl and falling back to the Deferred code for older browsers. Developers would end up with a more enjoyable debugging experience.

**Comment by dmethvin** [comment]
We're not removing any `jQuery.Deferred` functionality, which we use internally, and the native Promise doesn't have those extensions. Our goal here was to provide standard Promise/A+ behavior for `.then()` and not to implement a native Promise shim. If someone wants native Promise and decent debugging for it is supported on all the platforms they want to use, they should definitely do that instead. It will be a while before platforms like IE8-11 and Android 2.x die, so if people want cross-browser behavior they can use `jQuery.Deferred`.

If someone has a better plan for how to do this, please let us know.

**Comment by benjamingr** [comment]
@paulirish how can a non-native promise hook into that tooling?

**Comment by markelog** [comment]
@dmethvin i guess @paulirish meant that we can use native Promises if they available, then enhance/extend them with our methods.

If i interpreted that right, this would create two code-paths which would increase the size and performance might suffer too (judging by https://github.com/petkaantonov/bluebird/tree/master/benchmark), although i'm not sure if that matters in browser envs or that we can preserve consistency between those routes.

And, as i understand, the only reason for us to consider it is to improve debug process?

**Comment by benjamingr** [comment]
@markelog native promises are really slow but they're still likely much much faster than jQuery promises - at least today.

**Comment by markelog** [comment]
> @markelog native promises are really slow but they're still likely much much faster than jQuery promises 

Pretty sure this is not accurate, `jQuery.Deferred`, currently, should be fastest promises out there, since they don't guarantee async execution and therefore don't wait for next event loop iteration.

**Comment by benjamingr** [comment]
@markelog I'm think you might want to run the benchmarks on that. For fun and glory you can also run Bluebird against itself with the sync (zalgo) build (that does not guarantee async operation). 

Bluebird's petkaantonov actually wrote the sync build just to prove that the performance benefits of not guaranteeing async execution are marginal at best. The trick is that instead of doing something native like using a `setTimeout` every time you want to create async behavior you queue the pending async executions together and batch them in the next turn.

**Comment by markelog** [comment]
>  I'm think you might want to run the benchmarks on that.

Since imp of `jQuery.Deferred` will be compatable with Promise/A+ there is no need for that.

> The trick is that instead of doing something native like using a setTimeout every time you want to create async behavior you queue the pending async executions together and batch them in the next turn.

This is popular trick which used in many Promises libs, but you still need to wait for next iteration.

> So gnerally I'm pretty sure that Bluebird is at least two orders of magnitude faster than jQuery deferreds at the moment.

I see the conclusion not the argument which should let to it.

> Native promises using the microtask queue are probably at least one order of magnitude faster than jQuery

If we would talk about microtasks vs macrotasks that would be relevant, but `jQuery.Deferred` doens't require non of those, code that doesn't require async execution is always faster then alternative.

> feel free to benchmark those.

Besides the points i made above, it doesn't really fair to compare async vs sync execution, since one should be inherently faster then the other.

**Comment by benjamingr** [comment]
@markelog I'll try to be clearer and to the point: Bluebird promises will run circles around jQuery defererds any day even while jQuery uses a sync ("zalgo") execution model (which is thankfully being fixed). This is because bluebird promises consume less memory than jQuery deferred by using flags, less state variables and no closures. 

Here is a _trivial_ microbenchmark in which _no async_ execution is involved at all (so bluebird defers here and jQuery performs nothing asynhronous). This is not a typical load - it's a completely synchronous code: http://jsperf.com/bluebird-vs-jquery-promises

Bluebird performs 10 times faster than jQuery here, and this is the kind of benchmark sync execution is supposed to shine - again, nothing is actually asynchronous here.


For what it's worth even when you disable the async A+ deferral in Bluebird it is only marginally faster.

**Comment by dmethvin** [comment]
Our main focus here is interop per the topic. If someone has perf issues and wants to use Bluebird or native Promise they can do so. I really *do* like native Promise but don't think the 90% of people who use the monolithic jQuery file would appreciate having the weight of two implementations just in order to use them. We have to solve the problem decently for all the platforms we support, all the way back to IE8 and Android 2.3.

**Comment by markelog** [comment]
> nothing is actually asynchronous here.

Tests are, you force benchmark.js execute your tests in async manner i.e. putting them in `setTimeout` call and therefore make jQuery test report later.

I really don't want to argue about this, implementation of `jQuery.Deferred` will change, bluebird has a reputation of crazy optimizations and considered one of the most fastest Promise/A+ impl, so i don't understand what you trying to prove here.

**Comment by markelog** [comment]
and btw

> For what it's worth even when you disable the async A+ deferral in Bluebird it is only marginally faster.

It's not, or shouldn't be, benchmark.js couldn't give exact ops number for async tests, so this diff should fall on margin of error type of thing

**Comment by paulirish** [comment]
@dmethvin sorry for helping derail the conversation. :) 

Oleg understood where I was going with this and.. yes it would require a feature detect and forked codepath (yay, how jQuery!) but would likely end up adding more code complexity (boo!). I think the jQuery position on this kind of thing has been mixed in the past. Users will miss out on the debugging help from tools, but I understand it's not trivial for you to handle this otherwise.

@markelog @benjamingr I carried this conversation about promises performance over here: https://plus.google.com/+PaulIrish/posts/ZBP64F2GEY4 Would love both your feedback.

**Comment by benjamingr** [comment]
Woohoo!! When can we expect this to be in?

**Comment by gibson042** [comment]
It's already in git builds of [compat (formerly 1.x)](http://code.jquery.com/jquery-compat-git.js) and [(formerly 2.x)](http://code.jquery.com/jquery-git.js), and will be in both 3.0 betas following the resolution of our [blockers](https://github.com/jquery/jquery/issues?q=is%3Aopen+is%3Aissue+label%3ABlocker), which will be soon since this was the biggest of them.

**Comment by benjamingr** [comment]
Awesome, thanks a ton :)

**Comment by mzgol** [comment]
The "Behavior Change" label was missing from this ticket - do we have more of those? We should pay attention so that all such tickets have this label applied.
