### ISSUE TITLE
Have $(window).outerWidth() include the scrollbar width

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1729]
Originally reported by antti@… at: http://bugs.jquery.com/ticket/14989
<p>
It is sometimes annoying that $(window).width() or $(window).outerWidth() do not include the scrollbar width in their value. Especially when trying to match the window width to the CSS media queries.
</p>
<p>
Currently e.g. if you have a media query in the CSS such as
</p>
<pre class="wiki">@media screen and (max-width: 1600px) {
  body {background: red;}
}
</pre><p>
When the red background is actually applied to the document by the browser, jQuery tells the window width is less than 1600px (1600 - scrollbar width).
</p>
<p>
This is annoying e.g. in cases where there are some mobile-specific stuff that needs to be done in both, CSS and JS. And they would need to be done at the exactly same width of the document/window.
</p>
<p>
However, plain JavaScript returns 1600 as the window width when asked at the point of the breakpoint as follows:
</p>
<pre class="wiki">console.log(window.innerWidth);
</pre><p>
Is it possible to get either $(window).width() or $(windor).outerWidth() working consistently with the browser's actual width? $(document).width() and $('body').width() will not return the same as "window.innerWidth" either, they return the same as $(window).width() and $(window).outerWidth().
</p>
<p>
Fixing this would greatly help making consistent code with the CSS media queries.
</p>
<p>
Possible workarounds currently are:
</p>
<ul><li>Using plain javascript, i.e. window.innerWidth
</li><li>Checking $('...').is(':visible') for some element that is visible only in the target width
</li></ul><p>
Here's an example of what I mean:
<a class="ext-link" href="http://jsfiddle.net/aq5vb/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/aq5vb/</a>
</p><p>Issue reported for jQuery 2.1.0</p>

**Comment by timmywil** [comment]
@dmethvin Just to sum up, is the idea here to leave `.width(window)` as-is, but add scroll bar width to `.outerWidth(window)`? Although, I think @scottgonzalez still makes a good case against it.

**Comment by dmethvin** [comment]
Actually, I read the comment as, "it looks like doing this is okay." @scottgonzalez can you clarify? I agree it's possible this will break code *somewhere* . On the other hand, if we can't think of any and this is a 3.0 it would be nice to expose some way to get this dimension.

**Comment by scottgonzalez** [comment]
> Actually, I read the comment as, "it looks like doing this is okay." @scottgonzalez can you clarify?

I'll just repeat my summation from earlier:

>  As long as meaningful values are returned, there shouldn't be any problems, but it is possible that this will "break" existing code.

The reason I push break in quotes is because the more common cases of centering will only be off by a few pixels and will probably not be noticeable in most cases.

> I agree it's possible this will break code somewhere . On the other hand, if we can't think of any and this is a 3.0 it would be nice to expose some way to get this dimension.

I've already provided examples of where this would actually break. See https://github.com/jquery/jquery/issues/1729#issuecomment-59856257

**Comment by timmywil** [comment]
@scottgonzalez Don't mean to annoy, but I'm still not clear on your position. It seems to me you've presented arguments for both sides. You said some breaks will barely be noticeable and then reminded Dave that you've listed multiple examples where this would break existing code. Are you for it, against it, or simply neutral?

**Comment by scottgonzalez** [comment]
I'm neutral on it. If the change enables some reasonable use cases, I think it's ok to allow the breaking change in a major release. The userland fix for the breaking change is pretty simple.

**Comment by AurelioDeRosa** [comment]
What's the consensus here? Will you change the behavior in jQuery 3?

**Comment by dmethvin** [comment]
yes, it's on the list.

**Comment by aFarkas** [comment]
Are you really sure, you want to change this? If a developer asks for ``$(window).width()``, he really wants to know how much space is available.

This is actually also true for media queries. It's even possible, that the scrollbar is customized and much larger than ``20``.

The reason why media queries do include the scrollbar is because, media queries need to be calculable without knowing any styles and the document contents itself. (So they don't know, whether ``html, body {overflow: hidden}`` is applied or not for example). 

So it is a necessary shortcoming of the mq API.

Changing the semantics of an existing API to match another less useful API isn't really great. Maybe add a new method, if you think this is so important. 

At the end, I would even then always prefer to use ``matchMedia.matches`` and ``matchMedia.adListener`` (= the right API for this), if I want exact sync in time and semantics with CSS media queries.

**Comment by aFarkas** [comment]
Don't take my comment to serious, in case your plan is to only change semantics of ``outerWidth``/``outerHeight`` and leave ``width``/``height`` as it is, like [suggested here](https://github.com/jquery/jquery/issues/1729#issuecomment-72286007).

**Comment by akamustang** [comment]
There is already an includeMargin parameter, could another option be to add includeScrollbar?

**Comment by thdoan** [comment]
Thanks for the patch, but we're left in an unfortunate situation where `$(window).outerWidth()` is equivalent to `window.innerWidth`, which can be confusing even though `window.innerWidth` itself is counter-intuitive (you would think "inner" leaves out the scrollbar).

**Comment by dmethvin** [comment]
How is that a problem? Can you not get the information you need from jQuery's API?

**Comment by thdoan** [comment]
There's not a problem, just a little bit of potential confusion because jQuery and native use opposite terms ("outer" and "inner", respectively).

**Comment by dmethvin** [comment]
Imagine how much more confusing it would be if jQuery's `.innerWidth()` was larger than its `.width()`!

**Comment by thdoan** [comment]
:) Yeah, that's why I mentioned it's an "unfortunate situation" -- native's `innerWidth` property is counter-intuitive to begin with.

No issues if people stay within the jQuery API to get the window dimensions; it's only when they mix native and jQuery when they see "inner" and "outer" flying around meaning the same thing. Anyway, I was just commenting...no new issues here.

**Comment by yitwail** [comment]
I'm working on a WordPress site, and the version of jQuery it uses returns the same value excluding scrollbar for width(), innerWidth() and outerWidth(), so I just used this workaround:
`Math.max(window.outerWidth, $(window).width())`

**Comment by acjbizar** [comment]
`window.outerWidth != $(window).outerWidth` simply makes no sense. Never has, and never will. Yes, changing it now probably breaks some existing code, but it’s bad design to begin with, so I’d say the sooner, the better. Chances are much of the existing code that uses `$(window).outerWidth` doesn’t work as expected anyway, **because** it doesn’t match `window.outerWidth` (as one would expect). Also, there’s an easy fix if you **do** want the sans-scrollbar width: just use `$(window).width()`.
