### ISSUE TITLE
$('html').outerHeight(true) returns inconsistent results across browsers

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1739]
Originally reported by jon@… at: http://bugs.jquery.com/ticket/12974

<p>
I am receiving inconsistent results between browsers when using $('html').outerHeight(true). My goal is to retrieve the actual rendered height of the document. I am avoiding $(document).height() because if the rendered height is smaller than the window height, the window height is returned. On firefox, $('html').outerHeight(true) works correctly, but on IE8 the window height is always returned. Observe using the example at:
</p>

<p>
<a class="ext-link" href="http://jondufresne.org/test.html" rel="nofollow"><span class="icon">&nbsp;</span>http://jondufresne.org/test.html</a>
</p>

<p>
If I run this in Firefox I see:
</p>

<pre class="wiki">window:561
document:1044
html:1044
body:1028
</pre><p>
Notice the html height matches the document height.
</p>

<p>
If I run this in IE8 I see:
</p>

<pre class="wiki">window:806
document:1272
html:810
body:1256
</pre><p>
Notice the height (approx) matches the window height and not the document height.
</p><p>Issue reported for jQuery 1.8.3</p>

**Comment by FesterCluck** [comment]
There's a small problem here: IE8 will render multiple HTML elements inside of the document node. The easiest way to test this is to literally make a document with 2 html nodes and load it. A second way is to make a standard HTML document, then in javascript create a second one in memory, remove the original from the DOM, append the new HTML node into the DOM, then append the old one. Both will render.

What this really comes down to is that <=IE8 recognizes an element above HTML. A CSS selector of "* > HTML" shouldn't be valid, but it is.

**Comment by dmethvin** [comment]
Sorry, @FesterCluck I'm not following. Is your comment related on how to get the height of the body?

**Comment by FesterCluck** [comment]
document & html should be the same reference point. They're the same thing. "document" doesn't have a height, documentElement does, which IS the HTML node.

window & body are without a doubt independent.

The unfortunate thing here is that IE8 actually makes the two separate. So the question becomes does one code to standard use, or code to accuracy? There are situations which <= IE8 will report different numbers, but the numbers it is reporting are accurate. The problem is the developer doesn't understand how their css is sizing a parent element that shouldn't exist.

This is not to say the OP's test case is one of these. I just mean to point out that, in understanding that these browsers insert a node between documentElement and window, what behavior should be supported?

**Comment by dmethvin** [comment]
Unless there's a regression here, these APIs have been returning the same IE8 values for 6 years. Any change to values that are returned for any of these cases will probably trip up existing code that expects the current values. 

I suspect that what we do for IE8 right now, barring some recent regression, is what we will do until we drop IE8 as a browser.
