### ISSUE TITLE
jQuery.event.fix() may force layout

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1746]
Originally reported by anonymous at: http://bugs.jquery.com/ticket/14147
<p>
Accessing some of the event properties while copying them (like <tt>jQuery.event.fix()</tt> does in <tt>event[ prop ] = originalEvent[ prop ]</tt> at <a class="ext-link" href="https://github.com/jquery/jquery/blob/master/src/event.js#L511" rel="nofollow"><span class="icon">&nbsp;</span>https://github.com/jquery/jquery/blob/master/src/event.js#L511</a>) may force style recalculation and layout.
</p>
<p>
Screenshots of Timeline in Chrome Developer Tools:
<a class="ext-link" href="http://i.imgur.com/Zuh6WDE.png" rel="nofollow"><span class="icon">&nbsp;</span>http://i.imgur.com/Zuh6WDE.png</a>
<a class="ext-link" href="http://i.imgur.com/JWLYF2N.png" rel="nofollow"><span class="icon">&nbsp;</span>http://i.imgur.com/JWLYF2N.png</a>
</p><p>Issue reported for jQuery 1.10.2</p>

**Comment by timmywil** [comment]
The trac issue referred to here is https://github.com/jquery/jquery/issues/1735 on github.

**Comment by jbedard** [comment]
I've updated the change in https://github.com/jbedard/jquery/tree/event_properties.

Originally I was using the event speed test but that has been deleted. I'll try to get a jsperf test going. Probably something which simulates mouse events with different handlers that access different properties? @dmethvin did you have any specific type of test you'd like me to try?

**Comment by dmethvin** [comment]
Yeah, a realistic test is going to be messy here. I guess it might be possible to make a layout change via modifying a class, then fire a MouseEvent for mousemove that goes through our plumbing.

**Comment by jbedard** [comment]
Here's a first attempt: https://jsperf.com/jquery-event-props
Note that is the latest from master without the change ("old") and with ("new").

But I think the class attribute change isn't forcing a relayout, otherwise I think the offsetX test should be much slower then the button test. I'm also not seeing a relayout it in the chrome timeline.

Let me know what you think. We'll probably want a lot more test cases such as handlers that do more then access 0-1 event properties...

**Comment by havenchyk** [comment]
We also noticed about "forced layout"/repaints in FF. Is there any progress regarding this issue?

**Comment by mzgol** [comment]
@havenchyk Not yet. This issue has a "Future" milestone as we're currently focusing on finishing 3.0.0 and there's still a lot to do. Additional perf tests, pull requests with tests confirming they improve performance could make it possible to make 3.0.0 but I wouldn't hold hopes high otherwise.

**Comment by mzgol** [comment]
BTW, the issue @dmethvin linked to, https://bugzilla.mozilla.org/show_bug.cgi?id=626021 is now fixed so maybe getters are not such a huge problem anymore. But still, PRs welcome, especially with perf tests.

**Comment by dmethvin** [comment]
I think this problem on the jQuery side would be fixed by the solution proposed by @jbedard in #2337, at least for jQuery's own event handling code. The original problem is that the layout is dirty coming into the handler. Any attempt in your own code's event handler to read properties that depend on layout will force layout as well. Any high-frequency handler such as mousemove or scroll should defer changes to a requestAnimationFrame handler if possible to throttle the change rate and avoid this kind of problem.

**Comment by havenchyk** [comment]
@dmethvin do you mean that the problem on my side as well? I've disabled all the event handlers in my app and timeline shows me that the most time is taken by `jQuery.event.fix` and it triggers layout and only in the Firefox (Chrome 43 and IE11 work smooth). 

I will be glad to help to determine, if it's really the problem of jQuery. Can I help with something there?

**Comment by dmethvin** [comment]
If you don't have any active event handlers, jQuery shouldn't have an event handler attached either. Can you create a test case at jsbin.com?

**Comment by havenchyk** [comment]
@dmethvin sorry, there were problems with flexbox performance in FF, sorry for disturbing.
