### ISSUE TITLE
Show animations, like $.show() $.toggle() and $.slideDown(), don't respect css display property if initial state is display:none;

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1774]
Originally reported by nicholasbg at: http://bugs.jquery.com/ticket/15159

<p>
When an element that has a class with a css display property that is not its default (for example a &lt;span&gt; with "display:block"), and has an inline style (like "display:none"), setting it to be displayed with something like $.toggle(200) will cause it to not use the class's display property, while $.toggle() will work properly. Even $.toggle(0) will exhibit this behaviour.
</p>

<p>
From what I can tell this bug was introduced in 1.11.0/2.1.0
</p>

<p>
This jsFiddle will demonstrate the bug...
<a class="ext-link" href="http://jsfiddle.net/e8kpg/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/e8kpg/</a>
</p>

<p>
You can see it working normally if you change the jQuery version to something before 1.11.0/2.1.0 or remove the 200 from .toggle(200).
</p>

<p>
This is a very similar case to...
</p>

<p>
Ticket <a class="closed ticket" href="http://bugs.jquery.com/ticket/14824" title="bug: jQuery v1.11 and v2.1 slideUp and slideDown not respecting css display ... (closed: fixed)">#14824</a>
<a href="http://bugs.jquery.com/ticket/14824">http://bugs.jquery.com/ticket/14824</a>
</p><p>Issue reported for jQuery 1.11.1</p>

**Comment by nicholasbg** [comment]
Sorry for coming late but this bug was not fixed on any 1.x or 1.x version of jQuery. As stated in the bug report, you need to make the inline style display none and to add a duration to see the bug in action.

Here is a fork of robertmaxrees 1.11.1 fiddle with the bug (with the above changes) still happening.
https://jsfiddle.net/e8kpg/6/

The bug is fixed in the edge (currently  v3.0.0-pre) and edge compat version though.
