### ISSUE TITLE
JQuery's trigger method doesn't populate currentTarget

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#1783]
Originally reported by ArkadyKarev at: http://bugs.jquery.com/ticket/15198

<p>
This problem (see subject) makes jQuery not completely compatible with some libs, which uses currentTarget. 
</p>

<p>
For example following example will not work correctly:
<a class="ext-link" href="http://jsfiddle.net/makfruit/C5QH3/" rel="nofollow"><span class="icon">&nbsp;</span>http://jsfiddle.net/makfruit/C5QH3/</a>
go to "Vegetables &gt; *Cucumber" and press "Activate next" button. It will perform only radio button changes, but attached handlers will not be triggered. If we will click radio buttons manually, we can see the changes in price and description, etc.
</p>

<p>
The following workaround will help:
var event = jQuery.Event('change'); event.currentTarget = event.target = parent<a class="missing changeset" title="No changeset 0 in the repository">[0]</a>; parent.trigger(event);
but anyway it seems like jQuerry bug. 
</p>

<p>
Also I found the same requests in GWT groups.
<a class="ext-link" href="http://code.google.com/p/google-web-toolkit/issues/detail?id=8634" rel="nofollow"><span class="icon">&nbsp;</span>http://code.google.com/p/google-web-toolkit/issues/detail?id=8634</a>
</p><p>Issue reported for jQuery 2.1.1</p>

**Comment by HemantNegi** [comment]
i think this replicates the problem can u guys have a look at it
http://jsfiddle.net/makfruit/C5QH3/

**Comment by dmethvin** [comment]
That's a LOT of code. Can you modify http://jsbin.com/vaqasuweme/1/edit?html,output to demonstrate the problem? I couldn't find a situation where jQuery isn't already setting the target.

**Comment by markonikolic** [comment]
Hi,

I have found some more details on this issue and a small example that replicates the problem. The example can be found on http://jsfiddle.net/6s6r8ekm/5/ .

The issue is missing event.currentTarget when firing events from jQuery and handling event within GWT code - I don't know about other libraries. GWT expects event.currentTarget set, while jQuery sends different event object depending on the type of handler:

* if it is a jQuery handler, event.cureentTarget is present
* if it is a native handler, there is no event.currentTarget.

Example on jsfiddle demonstrates the problem without GWT. Both types of handlers can be tested and event data is dumped on browser console. Uncomment different handlers, click on 'Run' and observe browser console (changing combo box values does not correctly replicates the problem).

In jQuery code, you can check different behavior for different handler types in trigger function, search for comment 'Fire handlers on the event path'. 

I am not so familiar with jQuery, so I don't know if this is by design or it is a bug.

**Comment by dmethvin** [comment]
Note that `.onXXX` properties are left over from the DOM0 days, the [DOM Level 3 Events spec](http://www.w3.org/TR/DOM-Level-3-Events/) doesn't even mention them and I suspect `currentTarget` isn't set in the Event object because it wasn't originally defined for that case and they had back-compat concerns.

Here is an example with only native functions: http://jsfiddle.net/6s6r8ekm/8/

On Chrome 40 and Firefox 36, the `currentTarget` property is `null` whether it is fired inside native JavaScript or triggered via interaction with the control. 

On Safari 8, the `currentTarget` property is `undefined` for both cases.

On IE11, the `currentTarget` property is `null` when fired by native JavaScript but populated as the `<div>` when triggered via interaction with the control.

So, 7 out of 8 native cases don't set `currentTarget`. Is there a reason jQuery should set the value in the event object passed to `onchange`  if the browsers generally don't?

**Comment by markonikolic** [comment]
I agree with your findings on jsfiddle, however, I have copied the same example to http://jsbin.com/kirufetisu/1/edit?html,js,console,output - and the results are different, `currentTarget` is properly populated. Tested with Chrome 40, Firefox 36 and IE 11, both triggering from code and interaction with the control populates `currentTarget`.

This seems a little bit strange, so I have tested firing native events from Chrome console in gwt application. Internally, gwt uses `.onXXX` properties for setting handlers and it works as expected. So, it seems to me that jQuery should populate `currentTarget` in case of native handlers.

I don't know if `.onXXX` properties are deprecated, if they are not, I beleive they should be covered as well.

**Comment by hunteke** [comment]
I don't know if this is still relevant to folks since 15 months ago, but we encountered this issue during a recent project, and I have a reduced test case (34 lines of HTML/JS, mostly boiler plate HTML and console.log to highlight the issue).

[index.txt](https://github.com/jquery/jquery/files/303520/index.txt)

For reference to the dev who fixes the problem or nixes the bug report, I encountered this in the context of another bug report I just filed, so this file is the same as attached to #3146.

**Comment by dmethvin** [comment]
@hunteke  your test uses inline handlers. That's why currentTarget isn't populated. As mentioned in gh-3146 inline handlers are a wontfix item.
