### ISSUE TITLE
Don't auto-insert tbody?

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#1835]
Now that we're talking breaking changes - jQuery inserts a tbody when appending to an empty table because of a "special" behavior of IE6-7 (http://bugs.jquery.com/ticket/14290). The `master` branch does the same for compat with jQuery 1.x. Should we revert this behavior now that we're dropping IE<8?

**Comment by dmethvin** [comment]
@markelog Do you recall the issues you encountered with the `tbody` problem? Maybe I'm remembering it wrong.

**Comment by markelog** [comment]
That was a long time ago, a bit busy today, will refresh my memory tomorrow

**Comment by markelog** [comment]
> Now that we're talking breaking changes

Doesn't look like one

> because of a "special" behavior of IE6-7

Not exactly

> http://bugs.jquery.com/ticket/14290

Don't understand how this related, it just references `tbody` creation

> I recall @markelog trying to remove more of that in the early days of jQuery 2.0

Was not involve in it, you probably thinking of https://github.com/jquery/jquery/commit/19def21df41d6be6419e4d2480a656d9e1a0e6b7.

<a href="<a href="http://htmlhelp.com/reference/html40/tables/tbody.html">According</a> to html4 spec, `tbody` should always be present, which is true for IE6-7 implementation, `tbody` will be auto-inserted if table created through html serialization (declared in html or through `innerHTML` property), regardless if content is present or not. `tbody` should be created if DOM methods are used, otherwise IE6-7 will improperly render it.

According to html5 spec, `tbody` could be <a href="http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-tbody-element">ommited</a> but will be <a href="http://www.w3.org/html/wg/drafts/html/master/syntax.html#parsing-main-intable">auto-inserted</a> if table has `td`, `th`, `tr` tags.

Modern browsers and IE8+ do not create `tbody` through html serialization for empty table and behave according to specification if there is a specific content, with DOM-methods, `tbody` will not be created, regardless of the content, even Opera 9 and FF 3.6 behave this way.

When `tbody` creation is nessary? For IE6-9, when empty table is statically created and `innerHTML` property is used, you basically can't use `innerHTML` on that node in these environments.

We no longer use `innerHTML` directly on tables (even true for `jQuery#html` method), so this code-path could be safely removed.

**Comment by markelog** [comment]
> When tbody creation is nessary? For IE6-9, when empty table is statically created and innerHTML property is used, you basically can't use innerHTML on that node in these environments.

A bit more info about this is <a href="https://github.com/jquery/jquery/pull/2021/files#r23339660">here</a>

**Comment by fdlk** [comment]
For the record, this *is* a breaking change, affecting the layout of our table in modern browsers.

**Comment by dmethvin** [comment]
@fdlk can you open a new issue that includes a test case?

**Comment by fdlk** [comment]
@dmethvin I've created #2861 with a jsfiddle to demonstrate.

**Comment by mgol** [comment]
This has been reverted so I'm removing the milestone.
