### ISSUE TITLE
Core: Issue while creating dash-delimited nodes 

### ISSUE THREAD

**Issue by LeonardoBraga** [jquery/jquery#1987]
JQuery fails in some cases to create dash-delimited notes:

```javascript
// Works fine and creates the element:
$('<div-d></div-d>');

// Does not create the element:
$('<tr-d></tr-d>');

// ... and it should, since document.createElement works fine too:
document.createElement('tr-d');
```

Reported first here: https://github.com/angular/angular.js/issues/10617

**Comment by markelog** [comment]
So we would be on same page here:
`tr-d` is not a valid html tag name, but since it has a hyphen in it, it is now <a href="http://w3c.github.io/webcomponents/spec/custom/#dfn-custom-element-type">considered</a> as custom element and custom elements are part of web components. 

Characters that could be used in tag name of custom elements are described in <a href="http://www.w3.org/TR/1999/REC-xml-names-19990114/#NT-NCName">xml specification</a>. Like `_` and `.` are also included in that class. So if we fully support custom elements do we need to add tests for names with `_` and `.` characters?

But this discussion could be deferred and i let @dmethvin answer that.

Apart from that, this looks like real use-case and real bug, there is two problems with this particular case: first with `rsingleTag` regexp and second one with `rtagName` one.

Your commit, mentioned in this ticket, would resolve `<tr-d></tr-d>` case, but not `<tr-d></tr-d><tr-d></tr-d>`.

This is why even `div-d` fails `rsingleTag` check, it still works, since `buildFragment` doesn't feel the need to wrap it with special parent tag.

Would you like to send us PR for both?

**Comment by markelog** [comment]
> Would you like to send us PR for both?

Preferable with commits in it, one for core and for manipulation module, don't forget to read http://contribute.jquery.org/ if you feeling up to it

**Comment by LeonardoBraga** [comment]
Thanks for the instructions, and yes, I'd like to submit a PR for it.

Just to be clear and fair, issue was initially reported and patched by @gkalpak on Angular.js repo. It just happened that I bumped into it at the same time and tried to share the load.

**Comment by gkalpak** [comment]
To be even more clear and fair, @elaijuh first [reported][1] it on Angular.js repo.
I submitted a [PR for AngularJS][2] ([as did][3] @richardaday).
<sub>(Seems like a whole lot of people are involved into this one-character addition :laughing: How cool is that ?)</sub>

@LeonardoBraga: I am glad you are sharing the load (since I am not familiar with jQuery's contributing conventions :smiley:).

[1]: https://github.com/angular/angular.js/issues/10617
[2]: https://github.com/angular/angular.js/pull/10618
[3]: https://github.com/angular/angular.js/pull/10619

**Comment by elaijuh** [comment]
cool to see this, thanks all for helping on this.

**Comment by gkalpak** [comment]
Do we know in which version this is going to be included ?
<sub>(Sorry, I am not familiar with jQuery's release process.)</sub>

**Comment by markelog** [comment]
> Do we know in which version this is going to be included ?

3.0

**Comment by mgol** [comment]
This has been backported to `1.12.0` & `2.2.0` so I changed the milestone.
