### ISSUE TITLE
.on(): With descendant selector, event handlers called in unexpected order

### ISSUE THREAD

**Issue by clifforama** [jquery/jquery#2014]
According to http://api.jquery.com/on/, "Event handlers bound to an element are called in the same order that they were bound." However, when two event handlers are bound to the same element, but one is bound with a descendant selector, the handler with the descendant selector always fires first, regardless of the order in which they are bound.

For example: http://jsfiddle.net/sk42f9xx/1/

Tested with jQuery 1.11.0.

**Comment by dmethvin** [comment]
That's expected behavior. Your term "one is bound with a descendant selector" means it's a delegated event. In order to stop propagation on a delegated event before the delegation point, the handlers for descendants must be run before the directly bound events on the same element.

You should think of a delegated event as being bound on the selector point, which is `#sample` in your case. Conceptually, the event is being handled at `#sample` and then bubbling up to `#container`. When you think of it that way the event order seems clear.

If you have some suggestions on how to clarify the documentation you could open an issue with suggested wording on the [docs repo](https://github.com/jquery/api.jquery.com).
