### ISSUE TITLE
css vendor prefix error

### ISSUE THREAD

**Issue by pltnkv** [jquery/jquery#2015]
$().css automaticly add vendor prefixes, but if firstly call "$().css" function with prefixes styles, auto-adding break. Run example in Safari
http://jsfiddle.net/8cf0hyhj/

**Comment by dmethvin** [comment]
Yes, trying this on Safari 8 via Browserstack I agree it's failing. The problem seems to be that if *you* explicitly set the vendor-prefixed property on a style then Safari starts responding to that property on any `CSSStyleDeclaration`. Totally bizarre. Can someone else verify they see this happening in `vendorPropName()` as well?

I don't know that this is something we can fix. Is there a reason you just don't let us do the prefixes for you?

**Comment by mzgol** [comment]
This bug is caused by:
https://github.com/jquery/jquery/blob/740e190223d19a114d5373758127285d14d6b71e/src/css.js#L265

If we don't find the original style property *and* don't find a prefixed one, we return the original one from `vendorPropName()`. This is then saved to `jQuery.cssProps[propertyName]` in the line linked above. The first `.css` setter checks for `msTransform` first and since Safari doesn't recognize `msTransform`, `msMsTransform`, `webkitMsTransform` nor `mozMsTransform`, `jQuery.cssProps.transform` is saved to be `"msTransform"`.

Later when we try to set `transform` to something, we have it cached that it maps to `msTransform` which obviously won't work.

We should fix it.

**Comment by mzgol** [comment]
PR: #2298
