### ISSUE TITLE
Animation on Windows Store Apps

### ISSUE THREAD

**Issue by JCKodel** [jquery/jquery#2062]
In jquery-2.1.3.js, line 5498:

<code> * Try to determine the default display value of an element</code>

at line 5515:

<code>doc = iframe[ 0 ].contentDocument;</code>

always return undefined on Windows Store App, and is used in lines 5518 forward:

<code>doc.write();</code>

then crashes =\

Use case: trying to use jQuery BlockUI within a Windows Store App.

**Comment by dmethvin** [comment]
As I understand the security model there, since Store apps have elevated privileges they don't take kindly to iframes that may have unknown content. Can you provide a jsfiddle that is the same as the smallest sample of code in your Windows Store app that crashes? The code path is [taking it through `defaultDisplay`](https://github.com/jquery/jquery/blob/cdfc2d092afad5a3e5b3978b04b402a1ee9dce79/src/css.js#L177-183) so I suspect it's the [use of `.show()`](https://github.com/malsup/blockui/blob/316f6e5d76a33266970778e80507149d9ef6a02d/jquery.blockUI.js#L402-430) inside BlockUI. But it's always a bad idea to guess.

It may turn out that we eliminate `defaultDisplay` in the process of dealing with gh-2057, but doing that is a breaking change and unlikely to land soon.

**Comment by dmethvin** [comment]
If you can provide a more complete test case, we can reopen.
