### ISSUE TITLE
Double fired mouseenter in chrome

### ISSUE THREAD

**Issue by alexpts** [jquery/jquery#2064]
Version jQuery: any
Browser: chrome 40
Demo: http://jsfiddle.net/alexpts/4res6aey/9/

Native event fired once in chrome. jQuery event fired twice in chrome.

**Comment by dmethvin** [comment]
What are you trying to accomplish? Modifying the contents of an element during the mouseenter/leave itself is pretty dicey. Note this clarification on your fiddle: http://jsfiddle.net/4res6aey/16/

**Comment by alexpts** [comment]
I try replace image to video on mouseenter and back on mouseleave.
Event jQuery and event native behave differently http://jsfiddle.net/4res6aey/18/ (1 fided, not 2 fired) . 

I think it's a lack of older browsers and the script should not in normal browsers to behave as before.
It would be great if the implementation mouseenter would work in older browsers is true (not emulated eventOver).

**Comment by dmethvin** [comment]
So it sounds like you understand that the difference is due to our code to simulate mouseenter through mouseover, which we [have to do](https://github.com/jquery/jquery/blob/45ec73f55618cd080867a98b42b9ab80409cab2e/src/event.js#L706-714) even on Chrome because of some bugs. 

As for *why* the synthesized event double fires, the problem is that there is a mouseover event fired for the IMG after the handler for the DIV removes it. That seems to be required by [W3C event flow](http://www.w3.org/TR/DOM-Level-3-Events/#event-flow), which says "In the DOM event flow, event listeners might change the position of the event target in the document while the event object is being dispatched. Such changes do not affect the propagation path."

For that second event, the mouseenter synthesizer [checks if the related element is a child](https://github.com/jquery/jquery/blob/45ec73f55618cd080867a98b42b9ab80409cab2e/src/event.js#L733) and it isn't because it was *just* removed. Perhaps it could also check whether the related element is even in the document at all to deal with this edge case, but I don't know if that occurs in other situations.

As far as how to work around the issue, could you position the IMG over the element rather than modify the DOM?

**Comment by dmethvin** [comment]
My take on this is that it's a rare edge case that only occurs if the element in the event path is manipulated. There *may* be a fix by checking if the related element was removed from the document as I mentioned above, but there may be side effects to that.

**Comment by alexpts** [comment]
The difference in behavior between the native-event and jquery-event too difficult to consider true.
It is problem DOM event in general, but not jQuery only. Until browsers will not be the same to handle the event, it is difficult to decide which way is correct.

I sent a bug report to firefox this example. If they decide that this is a bug, the chrome does everything right and then it will be a problem as jQuery too. (https://bugzilla.mozilla.org/show_bug.cgi?id=1130823)

**Comment by timmywil** [comment]
It doesn't sound like we have the animus to make a change here. Feel free to reopen if necessary.
