### ISSUE TITLE
Nested table :even and :odd selector returns wrong expected set

### ISSUE THREAD

**Issue by mrducnguyen** [jquery/jquery#2076]
:even and :odd selector returns wrong set of rows on nested table. Latest jQuery version. Issue appears on both latest Chrome and Firefox

Please have a look here: http://jsfiddle.net/hn9fc7pp/

The class which should be added on ":odd" row only is being added to all the rows in the nested table.

When switching ":odd" to ":even", the should-be-even rows in nested table were not selected, but the other rows were selected.

**Comment by dmethvin** [comment]
Looks right to me. Please re-read the docs for `:odd` and ask for help on the forum or StackOverflow.

**Comment by mrducnguyen** [comment]
It will look right because I have a CSS rule to override <td> with colspan. I have modified it a little bit to clearly show what's wrong: http://jsfiddle.net/hn9fc7pp/1/

Thanks for putting your time into this!

Cheers,

**Comment by gibson042** [comment]
@mrducnguyen: [`:odd`](http://api.jquery.com/odd-selector/) is a positional selector, which means that it filters a selection independent of DOM structure. Such selectors are nonstandard, slow, and quite frankly at-risk in future versions. I strongly recommend switching to [`:nth-child`](http://www.w3.org/TR/css3-selectors/#nth-child-pseudo) for cases like this where all siblings are interchangeable, and [`.filter`](http://api.jquery.com/filter/) for general-purpose after-the-fact collection reduction.

So instead of `$('table > tbody').find('> tr:odd').addClass('even-row')`, use one of the following:
* `$('table > tbody > tr').filter(function( i ) { return i % 2 === 1; }).addClass('even-row')`
* `$('table > tbody > tr:nth-child(2n)').addClass('even-row')` (_note that CSS is one-indexed, as opposed to the zero-indexed Javascript_)
* `$('table > tbody > tr:nth-child(even)').addClass('even-row')`

**Comment by mrducnguyen** [comment]
@gibson042, thanks for your suggestions.

I actually found another interesting thing:
```javascript
$('table > tbody').find('> tr:odd').addClass('even-row');
```
and 
```javascript
$('table > tbody').children('tr:odd').addClass('even-row');
```
are actually different,

the use of `.children('tr:odd')` adds the class to row index **0, 2, 4...** and so on, while .`.find('> tr:odd')` adds the class to row index **1, 3, 5...**

**Comment by gibson042** [comment]
That stems from the fact that you have a nested table and is related to #1766—`$('table > tbody').find('> tr:odd')` is in document order, but `$('table > tbody').children('tr:odd')` is not (the nested tr elements follow all the tr elements of the outer table). Which is yet _another_ reason to avoid positional selectors.
