### ISSUE TITLE
Setting the transitionDuration to 0 after it has been set, requires "0ms" instead of 0

### ISSUE THREAD

**Issue by dnmd** [jquery/jquery#2080]
Following [this question on stackoverflow](http://stackoverflow.com/questions/28407643/transitionduration-as-of-jquery-1-11-1-requires-0ms-instead-of-0-by-design-or). In short:

To remove a transitionDuration from an element that already has a transitionDuration applied to it, one would call `.css({ transitionDuration : 0 })` as of jQuery 1.11.1 it requires `css({ transitionDuration : "0ms" })` or in some rare cases completely removing the style attribute.

As the example provides on stackoverflow:
```javascript
var duration = "250ms";

$("#dot").on("click", function(){

    $(this).css({
        transitionDuration: duration,
        transitionTimingFunction: "ease",
        transform: 'translate3d(' + Math.floor(Math.random() * 20) + 1 + 'px, ' 
                                  + Math.floor(Math.random() * 20) + 1 + 'px, 0px)'
    }).text( duration );
 
    // As of jQuery 1.11.1 the second click on the "dot" 
    // still has the initial "250ms" transitionDuration applied to it.
    duration = 0;

});
```
[transitionDuration, set to 0 after 1 click (works) jquery 1.11.0](http://jsfiddle.net/wfmdqz4f/11/)
[transitionDuration, set to 0 after 1 click (**bug?**) jquery 1.11.1](http://jsfiddle.net/wfmdqz4f/7/)
[transitionDuration, set to "0ms" after 1 click (**fix**) jquery 1.11.1](http://jsfiddle.net/wfmdqz4f/8/)

**Comment by dmethvin** [comment]
The root cause is that if you give `.css()` a JavaScript `number` as opposed to a `string`, it tries to be helpful and add `px` to the end of the value. This seemed to do the right thing in 1.11.0 because of a different change further down the method that reset the css property to an empty string before setting the actual value, but if the value had been `10` or some other number it would not have "worked".

The `.css()` method maintains an ever-growing list of properties that are truly unitless in `jQuery.cssNumber` but transitionDuration is not unitless properties. It's just that the one specific value of `0` can lack units and be unambiguous. A numeric value like `10` could mean various different time units.

I wonder if there is any place where the value `0` actually does need units. If not we could simply skip adding `px` for that one case.

**Comment by timmywil** [comment]
> I wonder if there is any place where the value 0 actually does need units. If not we could simply skip adding px for that one case.

+1

**Comment by dmethvin** [comment]
If the experts here are correct, a plain time value of `0` is incorrect so this example is probably not valid and there are no code changes required. 

https://twitter.com/davemethvin/status/567692608282308608

**Comment by dmethvin** [comment]
https://github.com/jquery/api.jquery.com/issues/656
