### ISSUE TITLE
Remove deprecated ajax methods

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2084]
`jqXHR.success | error | complete`. They was deprecated since 1.8. 

Is it time to remove them?

**Comment by dmethvin** [comment]
Would be fine with me. If we are making a lot of changes for Promise/A+ compliance that would also move people towards the standard methods.

**Comment by timmywil** [comment]
Sounds good to me! Let's also open a ticket on jQuery migrate tho.

**Comment by timmywil** [comment]
[Opened](https://github.com/jquery/jquery-migrate/issues/88)

**Comment by markelog** [comment]
Just created docs issue about it too

**Comment by jfbrennan** [comment]
Per the blog post that links here, this change means that `jqXhr.abort()` is no longer an option in jQuery 3? Going forward then, what is the recommended way of cancelling requests?

**Comment by dmethvin** [comment]
@jfbrennan this ticket doesn't say anything about `jqXHR.abort()`.

**Comment by jfbrennan** [comment]
@dmethvin "Per the blog post that links here" it makes it sound like `abort` has been removed along with other non-Promise methods. Sorry for misunderstanding, but I'm not the only one:

(1,443 upvotes and it says `abort` was removed) https://stackoverflow.com/questions/446594/abort-ajax-requests-using-jquery/446626#446626

https://stackoverflow.com/questions/40421186/how-to-abort-a-jquery-3-0-ajax-request

**Comment by dmethvin** [comment]
Can you point (as in a URL) to any official jQuery documentation that says `jQXHR.abort()` is deprecated or removed? I don't know of any. Don't assume that a StackOverflow answer is correct.

**Comment by jfbrennan** [comment]
http://blog.jquery.com/2016/01/14/jquery-3-0-beta-released/ says:

"Removed special-case Deferred methods in jQuery.ajax

jqXHR object is a Promise, but also has extra methods like .abort() so that you can stop a request after it has been made.

As users increasingly embrace the Promise pattern for asynchronous work like AJAX, the idea of having special cases for the Promise returned by jQuery.ajax is an increasingly bad idea."

Kind of implies that `abort` was/is on the chopping block. The SO with 1,443 votes says `abort` was removed and then links to that same blog post so I don't think I'm the only one who is misunderstanding this. 
It might be good for the jQuery team to clarify that although `abort` was mentioned, it wasn't actually removed. I understand SO is not the gospel truth, but there seems to be a somewhat widespread misunderstanding that `abort` is gone and I think that blog post may have been the cause of it.

**Comment by winzig** [comment]
@dmethvin I am updating the SO answer to reflect reality, but can someone clarify what this statement means in the context of `abort`:

> As users increasingly embrace the Promise pattern for asynchronous work like AJAX, the idea of having special cases for the Promise returned by jQuery.ajax is an increasingly bad idea.

Is this statement saying that although not removed at this time, `abort` is seen as a special case on the returned promise, and may be removed down the road?

**Comment by dmethvin** [comment]
@winzig thanks for the help! Yes `abort` is definitely a special case since there is no way to abort a standard `Promise`. There is a withdrawn proposal at https://github.com/tc39/proposal-cancelable-promises but some uses like `fetch` require it just like `$.ajax`. There were two epic threads (https://github.com/whatwg/fetch/issues/27 and https://github.com/whatwg/fetch/issues/447) that finally settled on an implementation for fetch but it just goes to show how hard that problem is.
