### ISSUE TITLE
[Suggestions] Add a new serialization for Html To JSON

### ISSUE THREAD

**Issue by MaleDong** [jquery/jquery#2091]
Hello all:

   It would be nice if I can use JSON formation data to pass where I use $.ajax…….

   I found there were lots of functions extended from jQuery. However, none of them satisfies me because it lacks many functions, I searched for many times on the net, no results. Even I use $.serializeArray(), that doesn't meet my needs.

 I hope this function can:

   1) Either serialize "form" or none "form" Html tags——I mean any tag with "input" types should be serialized to JSON.
    2) For radio button tags with the same name, it should ONLY serialize the choosen one.
    3) For checkbox button tags with the same name, it should return me an array with the choosen multiple values (even none is choosen, make the empty array left).
    4) For the table tag, we should offer customers one choice——isEachRowSeralized. This is a boolean value that indicates whether we need serialize each row as an JSON object, or just serialize the whole table's input values as usual.
    Notice for Point 4——NOT ONLY FOR TABLE tag, but other familiar tags as well.

**Comment by dmethvin** [comment]
This seems like a good idea for a plugin. It wouldn't go into jQuery core.

**Comment by formula1** [comment]
Originally I was going to write an angry rant about how this was dismissed. Here are some facts.

### Form <-> Object

* [This has 600 stars](https://github.com/marioizquierdo/jquery.serializeJSON)
* [This has 404 stars](https://github.com/macek/jquery-serialize-object)
* [This stack overflow question has 750+ upvotes from 3 years ago](http://stackoverflow.com/questions/1184624/convert-form-data-to-js-object-with-jquery)
* [Google results for jquery serialize quickly shows serialize Object](https://www.google.com/search?client=ubuntu&channel=fs&q=jquery+serialize+is+bad&ie=utf-8&oe=utf-8#channel=fs&q=jquery+serialize)

Turning form data into json is common practice and the opposite isn't that uncommon

### Form <-> QueryString

jQuery has a `serialize` function however has no `deserialize` function. Luckilly there are [plugins](https://github.com/kflorence/jquery-deserialize) out there. But it's debatable why serialize would even be in jQuery core if you can't shift something back.  

### QueryString <-> JSON Object

Turning a serialized String into an object and back can be done by numerous libraries

* [qs brought to you by Walmart labs](https://github.com/hapijs/qs)
* [simply put querystring](https://github.com/Gozala/querystring)
* [node core](https://nodejs.org/api/querystring.html)
* [jQuery only implements Object->QueryString](http://api.jquery.com/jquery.param/)
* [But luckilly there are plugins QueryString->Object](https://github.com/chrissrogers/jquery-deparam)


### Why should jquery care?

jQuery is a mix of useful wrappers to avoid browser differences as well as make your life easier. Why is there an animate function?-Because animations are one of the things that really made jQuery popular. Why is there a data function?-Because you can store objects by reference. Why is jQuery still using it's own deferred system instead of Bluebird?-because done makes more sense than then in many cases. If forms weren't part of of the dom, you would be right. However forms are an important peice of the dom, arguably the most important. And to brush off supporting it as a finge usecase seems quite shortsighted

**Comment by MaleDong** [comment]
@dmethvin 

Maybe the jQuery's size is a bit too large..... However this function are TOO important for us and it is frequently used. So for the jQuery's official side, it would be better to offer this;)

**Comment by formula1** [comment]
I would argue if jQueries size is getting too large. Perhaps effects/css need to be moved to a seperate repository. Cross browser compatability for css has also been a huge issue and creating an effective animation suite is not task that wouldn't involve alot of code.

**Comment by dmethvin** [comment]
https://github.com/jquery/jquery/wiki/Adding-new-features

**Comment by formula1** [comment]
* Does $.ajax need jQuery internals or is it just a wrapper? I believe it's just a wrapper.
* Of course it can benefit. But then again, code can always benefit from features. Nowadays jQuery is attempting to be lean and mean.
* Are forms a part of the dom? I believe they are.
* all of these are served by a plugin's, however [As seen in this comment](http://stackoverflow.com/questions/5197090/jquery-form-deserialization-for-all-inputs#comment5841860_5197163) people would generally prefer recreating (a possibly sloppy and/or imperfect) implementation than use a plugin. There can be many reasons, however it comes down to "official" vs "unofficial". Unless it's a giant library or a force to be reckoned with, usually simple scripts are seen as untrustworthy/annoying as you end up have 10 to 15 small files just to get basic functionality. Does jQuery want to support developers recreating a possibly worse wheel? I think that's the point of jQuery, has all the crossbrowser/tools you would use everywhere
* Does it change Existing Api? I don't believe it does.

I fail to see why something like deserialized or serializeObject doesn't make the cut. But for what it's worth, you guys make an excellent product and I'd rather praise than criticize.
