### ISSUE TITLE
jQuery Ajax Basic Authentication `opts.username` `opts.password` not sending auth headers

### ISSUE THREAD

**Issue by MadLittleMods** [jquery/jquery#2116]
The only method to do basic authentication with the jQuery Ajax module is to set the header yourself in `beforeSend`.

Using the [`opts.username` and `opts.password`](http://api.jquery.com/jquery.ajax/) simply does not put an authentication header at all in the request.

Even though pre-baked url auth `user:pass@example.com` is a browser convention, it would be nice to support this feature as well.

[This SO answer](http://stackoverflow.com/a/13584559/796832) talks about the problem with the username and password options and I have confirmed their findings.

Tested with jQuery 1.11.2 (Chrome, Firefox)

I noticed on line 8875 of the built jQuery unminified source that the `username` and `password` options were commented out. I realize this isn't the only spot that defines how they are implemented but just noticing this.

```js
$.ajax({
	//url: 'http://mlm:asdf1234@localhost:8080/api/queues',
	url: 'http://localhost:8080/api/queues',
	username: 'mlm',
	password: 'asdf1234',
	/* * /
	// This the only way I can find that works to do Basic Auth with jQuery Ajax
	beforeSend: function(req) {
		req.setRequestHeader('Authorization', 'Basic ' + btoa('mlm:asdf1234'));
	}
	/* */
}).then(function(data) {
	console.log('data', data);
}, function(err) {
	console.log('err', err);
});
```

---

The request to the API server allowed cross origin requests and I am using the [`npm cors` package](https://www.npmjs.com/package/cors). [Enabling pre-flight](https://www.npmjs.com/package/cors#enabling-cors-pre-flight) or playing with some of the other [configuration options](https://www.npmjs.com/package/cors#configuration-options) had no effect on the responses. Although this is expected because the auth headers weren't being sent by jQuery Ajax.

**Comment by Anshu-xLR** [comment]
I have tried introducing an option to the jQuery.ajax function named "authByHeader" which when set to true would cause jQuery.ajax to set the Authorization header to "Basic Base64Encoded(username:password)".

It is working fine and I have tested the functionality as well on my local machine.
It would be great if the mods could have a look at it.

**Comment by MadLittleMods** [comment]
@Anshu-xLR Link it in your message please.

**Comment by Anshu-xLR** [comment]
@MadLittleMods The link to the commit on my forked repo - bab77bd420ba1f247415bf3fee9a0c55924cc246

**Comment by MattDiMu** [comment]
IE seems NOT to support credentials in the url (any more): https://support.microsoft.com/de-de/kb/834489/en-us and from what I've tested it locally with Win7 and IE11, this seems to be true (didn't work in ie, but in chrome and ff). 

I'm currently using the set headers method as well to mitigate this problem (changes method "get" to "options", however). So yes, an option to let jquery set the headers for you, would be nice (maybe even  default to true, as it doesn't work in IE otherwise?)

@MadLittleMods Your commit seems to work. I think, however, that your "generateBase64" function could be achieved much simpler...according to mdn:
```js
function utf8_to_b64(str) {
    return window.btoa(unescape(encodeURIComponent(str)));
}
```
Source: https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/btoa

**Comment by MadLittleMods** [comment]
@MattDiMu Just to be clear. I didn't make any changes or commits. Anshu-xLR posted a link to his code.

**Comment by MattDiMu** [comment]
Yeah, sorry - I meant @Anshu-xLR ofc.

**Comment by timmywil** [comment]
Thank you for opening an issue. However, it would be quite a bit of code to support such an option and it probably would not get used very much. Besides, I would much rather trust a separate library – that has tests and stays up to date – for the encoding rather than include support for this directly in jQuery. A library like that could be used in conjunction with our headers option...

```js
$.ajax({
    url: 'http://localhost:8080/api/queues',
    username: 'mlm',
    password: 'asdf1234',
    headers: {
        Authorization: library.basicHeader('mlm', 'asdf1234')
    }
});
```

If any team member disagrees, we can reopen.

**Comment by MadLittleMods** [comment]
@timmywil Is there a reason for the `username` and `password` options still being documented? http://api.jquery.com/jquery.ajax/

**Comment by timmywil** [comment]
I'm not sure what you mean. The options are used to open the xhr.

**Comment by MadLittleMods** [comment]
@timmywil What kind of authentication is set when using those options?

[`XMLHttpRequest().open()`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#open()) for reference.

> **user**
> 
>  - The optional user name to use for authentication purposes; by default, this is an empty string. 
> 
> **password**
> 
>  - The optional password to use for authentication purposes; by default, this is an empty string.

**Comment by timmywil** [comment]
Maybe I'm misunderstanding the issue. Is the issue that the username and password options we currently have are useless in this day and age, that they are useful, but only in conjuction with a header setting, or that the header is only necessary sometimes and the options are adequate for certain cases?

**Comment by timmywil** [comment]
cc @jaubourg

**Comment by MadLittleMods** [comment]
@timmywil Those options seem do absolutely nothing for any situation.

**Comment by timmywil** [comment]
@MadLittleMods Then this is my real question: why are they in the xhr spec? Let's see what Julian has to say on the subject and we'll reassess.

**Comment by markelog** [comment]
While we wait for @jaubourg...

> https://support.microsoft.com/de-de/kb/834489/en-us

This is about URLs, not about xhr, passing username and passwords should work, unless you use cross-origin request, then they will be ignored - this issue already come up before, you could read more about it here - https://github.com/jquery/jquery/pull/1614

If don't use cross-origin request, please create a test-case in <a href="http://jsfiddle.net">jsfiddle</a> or on the similar site.

**Comment by timmywil** [comment]
Ah, thanks for that issue @markelog. That helps me tremendously.

**Comment by jaubourg** [comment]
@markelog is perfectly right. Sorry to be late to the party, I have a lot of things to take care at work since I'll take a 3-week vacation starting at the end of this very week.

As usual, this situation can be remedied with a prefilter where you'd check if the request is `crossDomain` and has the `username` and or `password` option then set `headers` option appropriately. Could get a bit hairy if you wanna account for all situations.

**Comment by timmywil** [comment]
> check if the request is crossDomain and has the username and or password option then set headers option appropriately. Could get a bit hairy if you wanna account for all situations.

Right, this is exactly what I wanted to avoid due to the encoding issue. Thank you for the clarification @jaubourg and @markelog.
