### ISSUE TITLE
Unite compat and master branches 

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2139]
As discussed in the meeting.

There is now small size difference between those two branches but it's a headache to support and develop the same functionality, not a lot of sense for users too, since only real divergences of supported environments is IE8.

Probably best suited for post 3.0, but since this ticket is not indented to break back-compat it might makes to consider this change for next minor release.

Although, if we do this, it would be a shame to ditch some work we put into master - like "data" module.

**Comment by timmywil** [comment]
We wouldn't necessarily have to ditch that work. It just makes the build process a little more complicated, but not impossible.

**Comment by mzgol** [comment]
I'm fine with merging the branches but I'd like to still have a release that doesn't support IE8. Otherwise for many jQuery 3.0 will be a downgrade since they're not supporting IE8 and now they'd have a larger library. That would slow down the adoption of the new version.

If we have modules that differ a lot and that will not converge (`ajax/xhr.js`?) we may introduce a convention of naming those files so that in the build process a proper version is chosen for both versions. E.g. `ajax/xhr-new.js` & `ajax/xhr-compat.js`. Otherwise, we'd have to introduce comment directives that would cut out parts of the files if different code is needed in different browsers. Hopefully we wouldn't have a lot of such cases, the separate-files approach seems cleaner.

**Comment by dmethvin** [comment]
Really sad that we haven't saved that much space in master. It always seems that some platform or the other is still holding us back, whether that be Android, PhantomJS, or IE11.

The main trouble spots would seem to be event, ajax and data, maybe the naming @mzgol suggests along with a new build process would solve that. Or maybe it would be better to continue separate branches for 3.0 and then drop IE8 support in 4.0, potentially keeping 3.0-compat supported if you feel that is needed.

Differences in accessing internal data makes cherry picking much more difficult than it should be, so even if we keep the new data implementation we should restore `jQuery._data` or have some other consistent way that modules can get to data across both.

**Comment by gibson042** [comment]
> Otherwise, we'd have to introduce comment directives that would cut out parts of the files if different code is needed in different browsers.

Or real if/else with a syntax-aware build step to let tree-shaking remove unreachable code. Two files is better than two branches, but not by enough for my taste.

**Comment by mzgol** [comment]
> Or maybe it would be better to continue separate branches for 3.0 and then drop IE8 support in 4.0, potentially keeping 3.0-compat supported if you feel that is needed.

Worth noting is that "beginning January 12, 2016, only the most current version of Internet Explorer available for a supported operating system will receive technical support and security updates" (from http://support.microsoft.com/lifecycle/search/?sort=PN&alpha=internet+explorer). This means in 10 months IE8 will be officially unsupported by MS (except in embedded scenarios where XP is still supported but that doesn't count). That means large companies will need to migrate to IE11 with Enterprise Mode support to keep their IE8 apps working & still have security fixes.

So it might be a good idea to just wait a year or so & drop IE8 then instead of opting into a complicated build process and spend time on merging the branches only to drop IE8 shortly afterwards. Time spent on cherry-picking has a chance to be lower than time needed to set up it all and tear it apart later.

**Comment by gibson042** [comment]
> Time spent on cherry-picking has a chance to be lower than time needed to set up it all and tear it apart later.

Right... relative effort is certainly my guiding principle here as well.

**Comment by timmywil** [comment]
Good point @mzgol. Maybe we should just wait until we drop support for IE8 and at the same time deprecate jquery compat altogether.

**Comment by timmywil** [comment]
Per last week's meeting, the decision here is to wait until we drop support for IE, thus deprecating the compat project, which will effectively result in a return to one branch.

**Comment by mzgol** [comment]
@timmywil Please remember to remove a milestone & add a "wontfix" label when closing a bug as "won't fix" :)
