### ISSUE TITLE
IE8 - preventDefault in a timeout now is a blocking error

### ISSUE THREAD

**Issue by robertTop10** [jquery/jquery#2143]
Version - 1.11.2
IE8, if you have a preventDefault inside a timeout, it will now error with 'Member not found' and break any following functionality.

In 1.11.0, a console.error was fired which stated 'jQuery unable to prevent default, as called from within a timeout' and then proceeded as normal.

http://robert-daly.com/top10/jquery.html

**Comment by dmethvin** [comment]
The error from IE8 should be expected. IE8's `event` object only exists for the duration of the event, so by the time the `setTimeout` runs it's gone. If there was a console message as you described it sounds like it would have been coming from underscore and something might have changed there.

**Comment by robertTop10** [comment]
It only started on the project when I upgraded from 1.11.0 to 1.11.2. Underscore hasn't been changed. 

I've updated the test with a native Timeout. Same error. http://robert-daly.com/top10/jquery.html

**Comment by dmethvin** [comment]
Right, so that confirms that the `event` object is not accessible after the function returned. Do you have a test case that shows it working and giving that error on the console? This simpler test case shows that you can't `preventDefault()` on an event that is over: http://jsbin.com/pemure/3/edit

**Comment by robertTop10** [comment]
This is the issue I'm having, the code is exactly the same, only the jQuery version has changed. I'll see if I can create a test case which will fire both cases.

https://www.dropbox.com/s/sghjhmske7hve74/Screenshot%202015-03-13%2015.36.23.png?dl=0

**Comment by dmethvin** [comment]
Well you can see it happens whether jQuery is there or not: http://jsbin.com/pemure/5/edit

Whatever code is in your actual app may have been doing something to mask or prevent the problem, I assume so since that console message appeared. But again it's not jQuery, it's just the way IE8 treats its event object. You have to copy out the properties you want *at event time* and clearly it doesn't even make sense to attempt to `preventDefault` inside a `setTimeout` since the default action has presumably already occurred at an earlier point in time.

**Comment by robertTop10** [comment]
You're right, you can close this ticket.
