### ISSUE TITLE
FireFox animation issue

### ISSUE THREAD

**Issue by TheDavidFactor** [jquery/jquery#2144]
I'm trying to "zoom" an absolutely positioned div out from the center of the page by using top, right, bottom, left percentages from 50% to 10%. After discovering the issue on my own site, I created a fiddle here: http://jsfiddle.net/3mmbz3ko/2/

I've tested in IE (Windows 7) chrome (Windows 7, Fedora 20, Ubuntu 14), FireFox (Windows 7, Fedora 20, Ubuntu 14), Safari mobile (iPhone 4) and chrome mobile (Android 4.4.2) and only FireFox (on all platforms) exhibits the issue: for about the first half of the animate the div moves left and up without growing. and then grows to full size from the new starting point.

Since it only happens in FireFox I thought it might be a FireFox bug, but it didn't start happening until after jQuery 1.7.2 so I decided to start here

**Comment by timmywil** [comment]
This is worth investigating.

**Comment by JohnRodney** [comment]
You can get the desired behavior by animating width and height rather than right and bottom.

**Comment by JohnRodney** [comment]
Well right equals left + width and bottom is top + height... maybe just implement the animation like that in Firefox only.

**Comment by Mr21** [comment]
Hmmm (IMHO) it's not a bug.

There is something incoherent in what you want to do.
At first if you set `left:50%` and `right:50%` you have an element with a size of `0` right?
**But** you try to put an inner border of 3px on each side.
So you try to put an element of `6px` large start a `50%` of the left and termine at `50%` at the right.

If you remove the border, you will see none bug with your "zoom".
**or** if you replace `border` by `outline` you will see no bug too because **out**line (not inner).

**Comment by timmywil** [comment]
@Mr21 The issue here is the difference in behavior in FF. Removing the border doesn't alter the behavior in the test case. And I've confirmed that it works in 1.7.2. For some reason, we're adding about 100% to the right and bottom values during the animation.

**Comment by timmywil** [comment]
Pushing to 3.2.

**Comment by PurvaA** [comment]
@TheDavidFactor 

To fix animation issue in Firefox we need to do following things

- Detect Mozilla browser

- Write 'animate' method for Mozilla browser. This 'animate' method should have 2 additional CSS properties. [This method is almost similar as 'animate' method for other Browsers]

For demo - Please check my fiddle https://jsfiddle.net/ocLssfct/4/.

Also please let me know in case of any further queries/ concern

**Comment by PurvaA** [comment]
@TheDavidFactor

**Comment by PurvaA** [comment]
@TheDavidFactor 

To fix 'animate' issue in Firefox 

- Detect Mozilla Browser

- Write 'animate' method for Mozilla which is almost similar to 'animate' method for other Browsers. This 'animate' method have 2 additional CSS properties.

To elaborate this I created Fiddle.

Please check https://jsfiddle.net/ocLssfct/4/.

Also please let me know in case of any further queries/ concerns

**Comment by gibson042** [comment]
This stems from a difference in [getComputedStyle](https://www.w3.org/TR/cssom-1/#resolved-values) between Firefox and other browsers when values are [over-constrained](https://www.w3.org/TR/css3-box/#abs-non-replaced-width)—the former reporting post-adjusted [used values](https://drafts.csswg.org/css-cascade-4/#used) and the latter returning absolutized but pre-adjusted (a concept which isn't even named by [css-cascade-4](https://drafts.csswg.org/css-cascade-4/#value-stages), since the computed value of [margin properties](https://www.w3.org/TR/css3-box/#the-margin) matches the specified value—and therefore remains a percentage when so specified).

http://jsfiddle.net/3mmbz3ko/17/
