### ISSUE TITLE
Toggle checkboxes should set the checked state of the internal checkbox

### ISSUE THREAD

**Issue by weitzhandler** [jquery/jquery#2157]
Hi,

In [this](http://getbootstrap.com/javascript/#buttons-checkbox-radio) example, which is great, the internal checkbox (and radiobutton) state remains the same.  
The expected behavior, is that when I click the button, the inner checkbox gets `checked` or not accordingly.

I'm looking at the toggle function on bootstrap and I see this is implemented, so why doesn't this work on the bootstrap example page (and in my website).

**Comment by gibson042** [comment]
I don't see a problem on the linked page... the `checked` properties update on every click. Is it possible that you are [confusing the property with the attribute](https://jquery.com/upgrade-guide/1.9/#attr-versus-prop-)?

At any rate, though, there does not appear to be a jQuery issue here. If you believe otherwise, please link to a reduced test case (e.g., on [JSFiddle](http://jsfiddle.net/)) and we'll reevaluate.

**Comment by weitzhandler** [comment]
You're right. There was a problem with my debugger. Sorry for the hassle.
