### ISSUE TITLE
$(obj).trigger() doesn't work on plain JavaScript objects with a length: 0 property

### ISSUE THREAD

**Issue by dougli** [jquery/jquery#2172]
The docs for https://api.jquery.com/trigger/ state that `.trigger()` works on plain JavaScript objects in a pub/sub manner, together with `.on()`. However, this doesn't work whenever the object as a `length` property of `0`. Repro steps below:

**This works:**
```
var obj = {};
$(obj).on('foo', function() {
  console.log('bar');
});
$(obj).trigger('foo');
```

**This doesn't work:**
```
var obj = {length: 0};
$(obj).on('foo', function() {
  console.log('bar');
});
$(obj).trigger('foo');
```

My guess is this is some logic intended to detect arrays that's gone haywire.

**Comment by gibson042** [comment]
That guess isn't far off the mark. Your problem here, though, lies with not with `.on`, but with the constructor—one of its many signatures [accepts an array](http://api.jquery.com/jQuery/#jQuery-elementArray), and our logic identifies any object with numeric length and an element at the highest corresponding index as array-like. So length `0` _always_ looks like an array, and `$({ length: 0 })` is as empty as `$([])` or `$()`.

You can force elements into a collection by explicitly wrapping them in an array, and in so doing will see your `.trigger` succeed: http://jsfiddle.net/xms59noc/
