### ISSUE TITLE
.val(Array) does not assign values from array to different elements

### ISSUE THREAD

**Issue by qnxor** [jquery/jquery#2195]
I'm using v1.11.2. According to the docs and the very last demo from here https://api.jquery.com/val/ when using `.val(arr)`, where `arr` is an array, it should assign the values from the array accordingly to each element returned by the selector. However, it just assigns `arr.toString()` to each instead. See this jsfiddle https://jsfiddle.net/n1ate7ba/

```
<form id="form-id">
<input type="hidden" name="answer" value="-" />
<input type="hidden" name="answer" value="-" />
<input type="hidden" name="answer" value="-" />
<input type="hidden" name="answer" value="-" />
</form>
```
and
```
var arr = ['1','1','1','1'];
$('#form-id').find('[name=answer]').val(arr);
alert($('#form-id').find('[name=answer]')[0].value);
```
I'd expect each `<input>` to have value `"1"` but instead, they have value `"1,1,1,1"`, as if jQuery actually did `.val(arr.toString())`.

My workaround now is to use `.val(function(index,value))` but that's slower:
```
$('#form-id').find('[name=answer]').val(function (index,value) { return arr[index]; });
```

**Comment by gibson042** [comment]
When invoked as a setter, `.val` attempts to apply its argument to each element of the collection **independently**. `.val( array )` specifically affects checkboxes, radio inputs, and select elements to update boolean `checked`/`selected` (instead of string `value`) based on whether or not an element's value appears in the input: [http://jsfiddle.net/08y4q1z0/](http://jsfiddle.net/08y4q1z0/). Your workaround is in fact the correct way to pair up an array of values with elements in a collection.

I've created jquery/api.jquery.com#712 to clarify the documentation.

**Comment by qnxor** [comment]
I see, thanks for clarifying. That wasn't quite clear from the docs, and even the example in the docs sounded as if my understanding was correct.

But still, any reason why not implement the above behavior? I expect the desired behaviour would be to apply each element of the array to each input, rather than `arr.toString()` to all inputs. It would be cool to have.
