### ISSUE TITLE
removeAttr resets the selectedIndex in Firefox

### ISSUE THREAD

**Issue by mAAdhaTTah** [jquery/jquery#2220]
In Firefox, this fiddle shows the selectedIndex being reset to 0 when the removeAttr method is called on it:

http://jsfiddle.net/jamesdigioia/6uz3vwvy/

In Chrome, Safari and IE, it remains -1 and shows nothing selected in the select box.

**Comment by dmethvin** [comment]
The plain-DOM equivalent gives -1: http://jsfiddle.net/6uz3vwvy/3/

**Comment by gibson042** [comment]
Weird. It's caused by our [pre-removal boolean property setting](https://github.com/jquery/jquery/blob/2905961bf75b741937f430ee5b619f11e93a448d/src/attributes/attr.js#L84-L88): http://jsfiddle.net/6uz3vwvy/4/

The rules around select elements and boolean properties are quite complex, so I'm not surprised to see some browser divergence. But maybe we can now take out the special boolean treatment?

**Comment by timmywil** [comment]
Yes, we already have an issue open to do just that. https://github.com/jquery/jquery/issues/1759
