### ISSUE TITLE
Do not expose jQuery.domManip method

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2225]
Since we get this opportunity only in major version, i'm gonna label it as a blocker

**Comment by justinbmeyer** [comment]
Sorry about the late comment, but this is important for CanJS.  

https://github.com/bitovi/canjs/blob/master/util/jquery/jquery.js#L140

It's how we are able to add an "inserted" event everytime new DOM is added to the page.

Anyway, this could be made public again in future releases?

**Comment by dmethvin** [comment]
@justinbmeyer can you open a ticket for this? I think we should look at the problem from a functionality/capability standpoint rather than just re-exposing this internal method.

**Comment by dmethvin** [comment]
@justinbmeyer is CanJS still using .domManip? Since it's an undocumented method we were planning to remove it in 1.12/2.2 but we can extend that to 3.0 if we hear from you in the next day.

**Comment by justinbmeyer** [comment]
Yes, we are still using it.  In about 6 months, we are finally dropping support for browsers that don't support MutationEvents/Observers.  At that point, we won't need it exposed anymore.  Thank you very much for keeping it around.

**Comment by dmethvin** [comment]
Reopening as a reminder

**Comment by mgol** [comment]
The milestone here is a little misleading as we're now planning to drop it only in 3.0.0. :) But OK, it's a good reminder and we can bump the milestone back later.

**Comment by dmethvin** [comment]
All the "Do not expose" tickets may need to be re-exposed for 1.12/2.2 but I figured we should discuss. Rather than reverting the commits it would be easier to simply re-expose each via something like `jQuery.domManip = domManip` and a comment that the method is deprecated and will be removed in 3.0.

**Comment by timmywil** [comment]
Is that needed? These were internal methods.

**Comment by timmywil** [comment]
Fixed in 1.12/2.2

**Comment by timmywil** [comment]
Changed milestone back to 3.0 as they're still going to be privatized in 3.0.

**Comment by justinbmeyer** [comment]
@dmethvin I should have noticed this earlier today.  But I need to overwrite `domManip` so I can get a hook for anytime jQuery modifies the dom.  This doesn't work because changing `jQuery.fn.domManip` doesn't effect all of jQuery's calls to `domManip`.

Is there anyway to get this changed, so that `$.fn.domManip` is being called eveywhere?  

(this hook is far more important than `buildFragment`, it supports our "inserted" and "removed" custom events).

**Comment by dmethvin** [comment]
I think this would need to be discussed with the team. Is this a temporary reprieve for 1.x/2.x, or do you  need a feature to hook DOM changes for 3.0 as well? We're not planning on anything other than patch releases for 1.x/2.x from here on out and weren't expecting to expose any of these for 3.0.

**Comment by justinbmeyer** [comment]
A temporary reprieve.  CanJS 3.0 will start using MutationObservers.  It will be able to support "inserted" and "removed" events without hijacking jQuery.

I could work around this by overwriting all of jQuery's modifier methods.  However, I'd need `$.buildFragment` to be able to convert the `string` arguments to a fragment.

**Comment by justinbmeyer** [comment]
@dmethvin I'm able to work around this.  So no need to add it back.
