### ISSUE TITLE
.click() does not work with Firefox, IE for checkboxes not added to document.body

### ISSUE THREAD

**Issue by antivanov** [jquery/jquery#2245]
Only Chrome works, in IE the 'click' event is not dispatched at all, in Firefox the event is dispatched but the 'checked' property is not properly updated.

Can you, please, take a look? At least the behavior should be consistent between different browsers and probably .click() should work like it does now in Chrome.

#### JSFiddle to reproduce

http://jsfiddle.net/antonivanov2/Lkz2ueg3/4/

##### Output

* Firefox

   jQuery.click detached checkbox: doesn't work
   jQuery.click checkbox: works
   MouseEvent("click") detached checkbox: works
   MouseEvent("click") checkbox: works

* Chrome

    jQuery.click detached checkbox: works
    jQuery.click checkbox: works
    MouseEvent("click") detached checkbox: works
    MouseEvent("click") checkbox: works

* IE

    jQuery.click checkbox: works

**Comment by timmywil** [comment]
@dmethvin could you take a look here? It's interesting that using MouseEvent works differently.

**Comment by dmethvin** [comment]
This looks like a difference in behavior in Firefox itself. Here's a more straightforward repro:

http://jsfiddle.net/7ojbg8bL/

The jQuery `.click()` or `.trigger("click")` is analogous to calling the native DOM `elem.click()` method, which does not seem to work on detached elements in Firefox. If this was a custom event like "myclick" it would be delivered.

Whether we need to fix this particular bug depends on whether Firefox has this on their radar. Maybe @miketaylr knows?

@gibson042 had a patch for fixing some of these issues that happen when we trigger native events and they don't deliver, but I had resisted it because it was quite a bit of code for edge cases.

**Comment by timmywil** [comment]
That makes sense. Given that analysis, I'm inclined to close this wontfix. I've opened an issue on Firefox [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1162146).

**Comment by antivanov** [comment]
Looks like this should not have been closed. Isn't jQuery supposed to fix the browser incompatibilities after all? Otherwise we can just use the standard 'click' method https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click. There might be some workarounds to make this work with Firefox or IE, even using MouseEvent('click').

And the issue is not also just Firefox specific, the behavior is different for the three major browsers: IE, Chrome and Firefox. If this issue is not fixed, then for clicking on detached checkboxes we would have to use standard (buggy) APIs and not jQuery.

**Comment by timmywil** [comment]
From my testing, this issue is Firefox-specific. IE and Chrome have the
same behavior. The workaround to set checked is to use `.attr("checked",
"checked")` or `.prop("checked", true)`. Firefox has quick iterations. If
they fix it, we won't need to add a fix to jQuery 3.0.

**Comment by miketaylr** [comment]
Thanks for filing @timmywil, I just set that bug as a blocker against https://bugzilla.mozilla.org/show_bug.cgi?id=968240.
