### ISSUE TITLE
Forever loop if selector argumen is jquery

### ISSUE THREAD

**Issue by emaniacs** [jquery/jquery#2247]
Hi all

I try to do this `$($)`, nothing happened but cpu usage is increase and then my browser hang.
It was forever loop produced by that code.

**Comment by markelog** [comment]
Yeah, it goes to infinity recursion - execution itself over and over again, since passed argument for funarg is jquery constructor, i have a feeling we did receive ticket like this before, can't find it though.

Technically speaking `$` is a function so it's an acceptable argument, but `$($)` doesn't makes sense.
We can add a guard for that, but i'm not sure we should.

@timmywil?

**Comment by Florian-R** [comment]
@markelog This as already been rejected in #1610

**Comment by mzgol** [comment]
Dupe of gh-2163 and [trac-9681](http://bugs.jquery.com/ticket/9681)

**Comment by emaniacs** [comment]
Hmm,
Sorry i didn't see this issue before.

I just try for fun and report it. :)
