### ISSUE TITLE
console.warn for .hide() and other perf gotchas.

### ISSUE THREAD

**Issue by jdalton** [jquery/jquery#2250]
There's a known [performance issue](https://github.com/jquery/jquery/issues/2057) with `hide` & friends that jQuery [would like to fix](https://github.com/jquery/jquery/pull/2180).

I've seen browsers leverage console warning used to create positive change.
For example Firefox warns of `__proto__` use and this got Zepto to drop it.

<img src="https://cloud.githubusercontent.com/assets/4303/7422629/2ad485e4-ef43-11e4-94f5-622f7bf4fac4.png" width="100%" height="100%">

I think this same technique could be used to deliver a gentle one-off warning about `hide`'s use, or the underlying issue, and recommend an upgrade path.

I'd like to flesh out this idea for browser dev tools here for easier collaboration.

\cc @paulirish

**Comment by dmethvin** [comment]
Based on previous experience with console warnings, people get really crazy if they get a warning and there is no resolution to fix it. So if we can coordinate our work here to make it so that the resolution was to upgrade (for example to jQuery 3.x) it would make life better for everyone! I'm not sure how practical that would be but it would be really interesting to explore.

**Comment by scottgonzalez** [comment]
I'm strongly against this. There are valid uses and it should not warn.

**Comment by jasonkarns** [comment]
I could see this being beneficial in a development build or behind a flag, but would be very upset if jquery were logging from a production build.

**Comment by geedew** [comment]
Deprecation warnings would be okay; if that were feasible. I would request anything like this should be present in an alternate build. Maybe a more chatty 'dev' build could be done for active development notes.

**Comment by dmethvin** [comment]
This isn't a proposal for jQuery to log, it's the browser detecting that you are doing bad things from a perf perspective and warning about it. The one @jdalton gives regarding Zepto is a good one.

**Comment by paulirish** [comment]
I think we should explore this, but don't want to just spam the console on any method that I or someone else called "slow". 

There are two hard parts to this:

1. Detecting the troublesome uses
1. Giving the user realistic guidance on what action to take.

We have to be thoughtful though, as it's a very serious thing to drop warnings into the console. 
(And yes, this is basically a feature request for Chrome/FF devtools teams, rather than something that jquery.js implements)

**Comment by jdalton** [comment]
>(And yes, this is basically a feature request for Chrome/FF devtools teams, rather than something that jquery.js implements)

*ahem Microsoft Edge too

**Comment by paulirish** [comment]
my b! fixed.

**Comment by bloodyowl** [comment]
:+1:

react has the same kind of very expressive warnings & errors, which is really good for both the learning curve, and the upgrades (I love it and lots of people I've spoken to about this love it too). I think this is a good habit, and can be really useful for deprecation & performance warnings for educating users (& of course this should only occur with the production mode).

IMO jQuery has completely failed to educate developers so far, because of a non-explicit API & missing the occasions of reducing the API to get close to the DOM when possible. now would be the time to start be more than an insurance for browser compat.

**Comment by dmethvin** [comment]
> IMO jQuery has completely failed to educate developers so far,

Not sure what this means. The code isn't about education, it's providing functionality via the API. The docs provide more guidance about how and when to use the APIs. The [jQuery Migrate](https://github.com/jquery/jquery-migrate) plugin provides a lot more information about practices and APIs that aren't recommended in new code.

I agree with @paulirish that this can't be a "this API is bad and you should feel bad" message. It needs to be more about providing guidance for fixing problems that can be detected while a page runs.

**Comment by jdalton** [comment]
> I agree with @paulirish that this can't be a "this API is bad and you should feel bad" message. It needs to be more about providing guidance for fixing problems that can be detected while a page runs.

Yap agreed.

**Comment by bloodyowl** [comment]
what I mean is that:

by having "polymorphic" method like `jquery.css` instead of `jquery.getStyle` & `jquery.setStyle`, it makes it more difficult to teach someone who started front-end development with jQuery to name & code explicitly.

by having a completely fucked-up `this` value in `forEach`, `map` & `filter`, same people who are introduced to JavaScript by jQuery got easily confused about `this` conventions in ecma standard methods & jQuery.

by having naming not evolving with convention (like `$.proxy` vs `Function.prototype.bind`) it doesn't help people to catch-up with the spec, and instead adds confusion.

and by not trying to align to the DOM spec (about naming & returned values signature) as close as possible, not educating people to learn how to do it without jQuery might be dangerous. if you have the hope that ideally, jQuery will no longer be necessary in the future, offering people some DOM knowledge becomes a necessity.

**Comment by stucox** [comment]
If you don't want people to use it, deprecate & remove it.

**Comment by miketaylr** [comment]
This kind of info might also be interesting in devtools performance timeline tooling.
(cc @jsantell @victorporof @canuckistani)

**Comment by jdalton** [comment]
> This kind of info might also be interesting in devtools performance timeline tooling.

Cool, thanks for pinging in! May be more suitable there depending on how complicated detection is.

@paulirish  mentioned Chrome may be able to measure the time of the jank and walk the stack and see if it's because of jQuery hidden checking.

**Comment by dmethvin** [comment]
@stucox in general I agree, and we've deprecated/removed several APIs over the years. The problem comes with complex APIs like `$.ajax()` or `$.fn.show()` where behaviors for edge cases cost us a lot in performance, bytes, and/or confusing documentation. We want to keep the baby but throw out the bathwater.

@miketaylr I definitely think this is where devtools can add value. We don't want to spew on the console for opinionated purity-of-code reasons but we want to give people better guidance when they're doing something that is causing bad performance.

**Comment by neemzy** [comment]
@bloodyowl Amen.

Yes, when your library is jQuery, you do have responsibility towards the community ; pretending you don't is straight blind ignorance.

As for the warning, yes, way to go. It helps a lot with React, given it has the advantage of knowing your environment (dev or prod) based on a node.js env variable. You won't be able to do the same, but let's be honest, who "builds" jQuery from source ? Just offer different builds to download and be very explicit about this (I suggest one env variable to rule them all, for similar future cases).

**Comment by timmywil** [comment]
I think the direction is good here, but it doesn't seem like there's anything to be done within jQuery core. The action items are directed at browser development tools. Is that accurate @jdalton?

**Comment by jdalton** [comment]
Correct. I've opened it here for easier cross vendor collaboration and input from jQuery core.

**Comment by timmywil** [comment]
By the way, I should mention here that, in the case of `.show/.hide`, we have [sweeping changes](https://github.com/jquery/jquery/pull/2180) prepared for 3.0.

**Comment by jdalton** [comment]
> By the way, I should mention here that, in the case of .show/.hide, we have sweeping changes prepared for 3.0

Yap, referenced in the first opening comment. One of the things mentioned was coordinating the warning with a release to be able to point devs to solution/workaround for the issue.

**Comment by jsantell** [comment]
Thanks for the heads up, @miketaylr -- pinged a few other Firefox DevToolers to this thread and we'll be looking into any warnings that can be provided when there are faster, optimized alternatives (like the __proto__ case in the OP)

**Comment by markelog** [comment]
> Correct. I've opened it here for easier cross browser vendor collaboration and to get input from jQuery core

Well if you do, then there is mine - 

personally, i resent the statement of `jQuery#(show | hide)` being slow, it simple isn't, DOM API is. Those methods consider great amount of edge-cases to make the end-user happy, now we will cut them out and thus drastically break a lot of use-cases - this is now a necessary sacrifice to make it faster. 

Users though, oh, users will face great issues while updating to the new jQuery since their apps/sites will break in unexpected places, yeah, i wonder who they will blame for it?

But punch line is - we didn't have to do that, if DOM API would have a "right" API, jQuery methods could have been fast and could have been thorough.

I will you give couple examples:

1. Thanks to the @bzbarsky firefox introduced the `window.getDefaultComputedStyle` which given us to avoid <a href="https://github.com/jquery/jquery/blob/172cad80ac635d8900aa6a3504c89f38b320488e/src/css/defaultDisplay.js">this</a> crazy slow logic that is now still used in `jQuery(show | hide)`, but no one standardize this method, no one beside the ff implemented it and honestly, it didn't work right, since we still had to do some hacks to make it work.

2. <a href="https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML">insertAdjacentHTML</a>, great method right? Simplifies and speed up a lot of use-cases? Perfectly aligned with jQuery API, right? <a href="https://github.com/jquery/jquery/pull/1200">No</a>, no it is not, too tricky, lots of edge-cases that were not considered, can't be used.

3. <a href="https://developer.mozilla.org/en-US/docs/Web/API/ElementTraversal">Element Traversal API</a>, in some ways mimics the jQuery traversal API, gotta to be the right API to use inside jQuery? <a href="https://github.com/jquery/jquery/pull/1145">Nope</a>, specification isn't through, doesn't consider non-element nodes and now this API is absolute.

4. `requestAnimationFrame` awesome method to make things faster, but why we had to wait <a href="http://bugs.jquery.com/ticket/9381">four</a> years before reintroducing it? Because without of conjunction with Page Visibility API this method just doesn't bring the needed effect. One edge-case and everything breaks. But while we waited we received all kinds of storms criticism for "slow" jQuery animation API.

I could add a lot more examples like that, like am not gonna be surprised if <a href="https://github.com/jquery/jquery/issues/1868">`Element#closest`</a> try out will have the same fate as examples above, while <a href="https://github.com/jquery/jquery/issues/1765">soon</a> there is great possibility of `jQuery#offset` to be claimed as "slow", i can already imagine nice tweets flowing around blaming us for it.

Yeah, you could say jQuery Core members could have been more active in W3C discussions, could have advocate their position and we do, but most of us do this as a side thing, most of us have real jobs, whereas those spec threads are time consuming, unrewarding and quite possibly - without the expected end-result.

I don't think any warns are necessary, since at least currently, (@timmywil pull you mentioned, already in the this ticket description btw) `jQuery#(show | hide)` takes really weird things while using various APIs to achieve desirable effect, having problems of imagining the code-path you would need to take to predict it "slowness".

I do think right DOM API could have been introduced that would relieve us from very circumstance for warning people about anything.

**Comment by timmywil** [comment]
> One of the things mentioned was coordinating the warning with a release to be able to point devs to solution/workaround for the issue.

Right, I'm just saying that, barring having to revert for reasons unknown at this time, 3.0 should be the right release to point to.

**Comment by paulirish** [comment]
I now have a ticket filed on Chromium for this request: https://code.google.com/p/chromium/issues/detail?id=503853#c4   It's profiling focused, so that the recommendations/warnings are only provided if a problem is detected.

**Comment by neemzy** [comment]
> But punch line is - we didn't have to do that, if DOM API would have a "right" API, jQuery methods could have been fast and could have been thorough.

If that was the case, we would not have needed jQuery in the first place, would we? At least for such simple things.

**Comment by jdalton** [comment]
@paulirish 
> I now have a ticket filed on Chromium for this request

Awesome, thank you!

**Comment by timmywil** [comment]
Since this discussion hasn't continued here, I'll close this ticket. We have different plans for `show/hide` in 3.0 that should still address the performance issue for general cases, but will not address it for all cases. We will not be adding console warnings in jQuery for this, but this ticket wasn't really suggesting that. As for browser vendors, I don't think there should be a warning every time someone uses hide or show, but we seem to have mostly agreed on that part. Browser vendors can/should provide recommendations, but only when there is actually a problem. It may be hard to detect sometimes, but no matter the difficulty in detecting an actual problem, that is their task, and it is a noble one.
