### ISSUE TITLE
Data: align data accessors with the ultimate "Embrace HTML5" direction

### ISSUE THREAD

**Issue by timmywil** [jquery/jquery#2257]
camelCasing in `.data()` has always been problematic. Our attempts to work around camelCasing whenever possible has always caused problems. We've decided to just always camelCase. Not only will our implementation align with the dataset spec, but it makes everything a lot simpler.

I've made a separate issue because #1751 is not broad enough in scope. It only pertains to keys with dashes and digits, which will also be fixed, but in a separate commit.

The solution as @gibson042 laid out in [this comment](https://github.com/jquery/jquery/issues/1751#issuecomment-67721150), is this...

```js
assert.equal( jQuery("<div>").data({ "a-b": 1 }).data( "a-b", 2 ).data( "a-b" ), 2 )
```

And per https://github.com/jquery/jquery/pull/1515#issuecomment-37758521 , we want the "[Embrace HTML5](https://docs.google.com/spreadsheets/d/1gf0vzYGwg7IA7yIkyJs-Jk31SWDogQrBkzPb-xl6u-o/edit?usp=sharing)" option:
* camelCase `data-*` attributes into the data object on first access
* set only camelCase key on `.data( key, val )` (setter)
* camelCase all the added keys on `.data( obj )` (bulk setter)
* look for only camelCase key on `.data( key )` (getter)
* ignore direct manipulation from operations on `.data()`

**Comment by rwaldron** [comment]
I thought I had posted a question when I was mobile this morning, but I guess it didn't go through... 

There is no mention (maybe there is, and I missed it?) of this use case: 

```js
jQuery("<div>").data({ "a-b": 1 }).data(); // => { "a-b": 1}
```


Which is definitely broken now, but if that was intentional (which is fine, I guess), then it needs to be made really clear in the docs. Undoubtedly, there is code that expects to be able to serialize and deserialize that data without jQuery screwing with it.

**Comment by timmywil** [comment]
> `jQuery("<div>").data({ "a-b": 1 }).data();`

Right, we have intentionally broken this case. We will be covering this in the migrate plugin and docs.

**Comment by timmywil** [comment]
That said, `jQuery("<div>").data({ "a-b": 1 }).data("a-b") === 1` still works.
