### ISSUE TITLE
Could :contains support regex? or any other solutions in jQuery?

### ISSUE THREAD

**Issue by alburthoffman** [jquery/jquery#2261]
Hi Guys,

I want to get a list of elements whose text matches a given pattern, and then wrap them to highlight them. It's very useful feature, and I'm not sure jQuery has it. 
instead of writing
```javascript
$("div.logs").each(function(i, ele){
    var $ele = $(ele);
    if($ele.text().match(/^Error/) != null) {
        $ele.wrap("<div class=\"status_red\"></div>");
    }
})
```

And I would prefer writing:
```javascript
$("div.logs:contains_regex('^Error')").wrap(...);
```

**Comment by gibson042** [comment]
You can do this yourself with a custom pseudo, but the selectors will be non-portable and _much_ slower (because they will no longer be recognized as valid by native browser engines). Best practice is to use valid selectors and filter the resulting collection manually, as you have above. You can also make that step explicit, e.g.:
```js
var rError = /^Error/;
function elIsError () {
	return rError.test( jQuery.text( this ) );
}
…
$("div.logs").filter( elIsError ).wrap("<div class=\"status_red\"></div>");
```
