### ISSUE TITLE
`isArrayLike` no longer fails gracefully for null and undefined from 1.11.1 to 1.11.3

### ISSUE THREAD

**Issue by ScottLNorvell** [jquery/jquery#2267]
in 1.11.1, isArrayLike looks like this:

```javascript
function isArraylike( obj ) {
	var length = obj.length,
		type = jQuery.type( obj );

	if ( type === "function" || jQuery.isWindow( obj ) ) {
		return false;
	}

	if ( obj.nodeType === 1 && length ) {
		return true;
	}

	return type === "array" || length === 0 ||
		typeof length === "number" && length > 0 && ( length - 1 ) in obj;
}
```

in 1.11.3, it looks like this:
```javascript
function isArraylike( obj ) {

	// Support: iOS 8.2 (not reproducible in simulator)
	// `in` check used to prevent JIT error (gh-2145)
	// hasOwn isn't used here due to false negatives
	// regarding Nodelist length in IE
	var length = "length" in obj && obj.length,
		type = jQuery.type( obj );

	if ( type === "function" || jQuery.isWindow( obj ) ) {
		return false;
	}

	if ( obj.nodeType === 1 && length ) {
		return true;
	}

	return type === "array" || length === 0 ||
		typeof length === "number" && length > 0 && ( length - 1 ) in obj;
}
```

`"length" in obj` produces the error `TypeError: Cannot use 'in' operator to search for 'length' in 6` when `obj === 6`.  Similarly when `obj` is a `undefined` or `null`. This causes, specifically `$.each` to fail when you accidentally put in a numerical value for `obj`. Not sure if this is an issue, but in 1.11.1, nothing failed when `obj` was accidentally a number. This caused some tests to fail that we've fixed. Thought I'd mention it.

**Comment by dmethvin** [comment]
This is basically a dup of #2242, we don't guarantee that invalid inputs will be silently ignored.

**Comment by gibson042** [comment]
Agreed.

**Comment by timmywil** [comment]
@dmethvin is right, but I'm starting to wonder if it would be nice if we failed silently here. The string case was more obscure, but I would expect that changing the behavior for `null` and `undefined` will be much more problematic.

**Comment by mzgol** [comment]
@timmywil agreed. Also, other implementations like lodash's `_.each` silently ignore things like `null` or `undefined`.

**Comment by gibson042** [comment]
We use `isArrayLike` in three places: `jQuery.each`, `jQuery.map`, and (protected by `Object`) `jQuery.makeArray`. This is now sounding like a request to change the signatures of the former two, despite the fact that both reported instances of passing them invalid input have been corrected. And since correcting such mistakes is usually as easy as adding `|| []` (or `if ( typeof input === "object" )` where correctness and/or performance is _critical_), I don't see the benefit of a change on our end. Quite the opposite, in fact—exceptions from `jQuery.each( nonIterable, fn )` seem like a **good** thing.

**Comment by timmywil** [comment]
> exceptions from jQuery.each( nonIterable, fn ) seem like a good thing

For the cases of numbers and strings, I agree with this, but passing variables that may be `null` or `undefined` at times to `jQuery.each` seems common enough that throwing is just going to be annoying to users. The question is about what is more convenient. If everyone is just going to add `|| []` to their code, we may as well do it in jQuery.

**Comment by dmethvin** [comment]
> The question is about what is more convenient. If everyone is just going to add `|| []` to their code, we may as well do it in jQuery.

That is a good point, but only if we also document that `null` and `undefined` are no-ops. I think that has been the behavior for a while so we *could* do that. I prefer the caller-level change to add `|| []` because it documents to subsequent readers that a `null` or `undefined` value was expected rather than it just happening to work. But if we change the docs at least those old calls are retroactively correct as far as their jQuery API usage goes. :smile:

**Comment by uptoeleven** [comment]
So if an object that without a length attribute is passed into this function, how should this function behave?

**Comment by mzgol** [comment]
@uptoeleven This function is not exposed publicly so you need to ask about a specific public method that you use. And since those methods, like [jQuery.each](http://api.jquery.com/jQuery.each/) are usually documented so that they accept an array, an object and (but only in jQuery 3.0.0) `undefined` or `null` then if you pass in the string you're on your own.
