### ISSUE TITLE
Deprecated `bind`, `unbind`, `delegate`, `undelegate` methods

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2288]
I guess it is time to do this.

1. Move them to `deprecated` module
2. Add warnings into `jquery-migrate`
3. Update the docs

**Comment by arthurvr** [comment]
Yes please! :+1:

**Comment by dmethvin** [comment]
I'm okay with all these todos, although I don't think we'd actually remove them quickly given how much code is still around that uses it. They are very small stubs anyway.

**Comment by mzgol** [comment]
@dmethvin Agreed. I don't think it's worth removing them any time soon because of their extremely small size & widespread adoption but discouraging use seems OK.

That said, with current setup only Migrate users & people looking at the docs will see the warnings; maybe we should do it in Core as well?

**Comment by dmethvin** [comment]
As long as we don't actually remove them any time soon, the warning in Migrate should be fine.

**Comment by markelog** [comment]
Yeah, definitely, no hurry.

**Comment by sabberworm** [comment]
The docs still don’t mention the deprecation even though this issue is closed and it specifically says “3. Update the docs”…

See jquery/api.jquery.com#945.

**Comment by markelog** [comment]
Yeah, you right, although i don't think we should re-open this ticket, let's just discuss this in jquery/api.jquery.com#945? Btw would you like to send us a PR for it? If @teo1978 does not beat you to it?
