### ISSUE TITLE
Firefox: strange behavior when iframe was hidden from inside itself

### ISSUE THREAD

**Issue by kissge** [jquery/jquery#2307]
See this demo with Firefox: http://kissge.github.io/jquery-bug/ (https://github.com/kissge/jquery-bug)
Push the left button, and you'll see that the page scrolls up and down, and the color changes.
The right button is the same button, except the version of jQuery, but clicking this button leads to unexpected behavior.
This happens only with Firefox + jQuery >1.11.2.

**Comment by timmywil** [comment]
What happens if you use http://code.jquery.com/jquery-git1.js?

**Comment by kissge** [comment]
@timmywil 
Still strange behavior, but different from 1.11.2.
http://kissge.github.io/jquery-bug/

**Comment by dmethvin** [comment]
Look a the console, Firefox is giving a NS_ERROR_NOT_AVAILABLE when we try to get the display property of the `html` element. Cross-frame and cross-window access is always dicey even when the two are from the same origin, take a look a the comments in that area and `getStyles()` in particular. 

Instead of having the child frame try to manipulate the parent, can you have it call back to a function in the parent that does the job?

**Comment by kissge** [comment]
Okay, actually I could avoid this problem just by reordering the codes :)
The interesting points were that cross-frame access fails only after the iframe was hidden, and that this problem doesn't occur with older jQuery and with other browsers.
Anyway, as this problem can be easily avoided (e.g. by calling a function in the parent, as @dmethvin mentioned), I don't say this needs to be fixed. It would be natural to leave it as it is.
