### ISSUE TITLE
JSONP in combination with a timeout causes errors

### ISSUE THREAD

**Issue by secrettriangle** [jquery/jquery#2317]
The only solution seems to be to make jQuery leave the callback around for timed-out JSONP calls. Maybe this should be an option?

**Comment by dmethvin** [comment]
Can you provide a test case on jsbin.com or jsfiddle.net showing what you mean?

**Comment by secrettriangle** [comment]
Sure! See [here](http://jsbin.com/worasoxopa/1/edit?html,js,output).

Did I write [timeout-tester](https://github.com/secrettriangle/timeout-tester) for the purpose of this ticket? Maybe. Does that JSbin reproduce the issue? Yes.

**Comment by timmywil** [comment]
Thanks for opening an issue, but I'm confused. That looks like the right behavior, since done should not be called on a timeout.

**Comment by secrettriangle** [comment]
The problem is that `callback2000` gets called after the timeout, but it doesn't exist, as it gets removed after the timeout period. The solution is to keep the callback around after the timeout, but replace it with `$.noop`.

**Comment by markelog** [comment]
Oh, may oh may - 

http://bugs.jquery.com/ticket/8744
https://github.com/jquery/jquery/pull/804
https://github.com/jquery/jquery/pull/667

Sorry

**Comment by secrettriangle** [comment]
I think the decision to remove timed-out JSONP handlers was made in haste. If I'm not mistaken IE6 gives the user a nice warning about script errors. At very least the ability to keep timed-out JSONP handlers around should be optional.

Move to reopen. As of now my application throws errors with no way to handle them other than using a forked version of jQuery.

**Comment by markelog** [comment]
Not in the haste it was discussed for two years or so, see the discussions in those tickets, i was fighting on it to the death. 

I used your 
> throws errors with no way to handle them other than using a forked version of jQuery.

argument couple times, summoned browser vendors, showed that this way is inconsistent and bunch of other things.... maybe in another life.

**Comment by dmethvin** [comment]
So if you're polling every 10 seconds and the JSONP calls continue to time out for a while, there would be a pretty large pile of uncollected `$.noop` function callbacks that might not ever be collected? As I understand it this is only in Firefox, is that correct?

**Comment by secrettriangle** [comment]
@dmethvin I like [this suggestion](http://bugs.jquery.com/ticket/9782#comment:2):
```js
window.jQuery16207753935731721285_1310374972748 = function() {
  delete window.jQuery16207753935731721285_1310374972748;
}
```

This bug affects Chrome as well (have not tested on IE).

**Comment by markelog** [comment]
@dmethvin As i <a href="https://github.com/jquery/jquery/pull/804">said</a> three years ago, chrome is affected too and since Opera dropped their engine some time ago, `timeout` option always generates a error in all supported environments.

Documentation is very outdated yeah - https://github.com/jquery/api.jquery.com/issues/742

> there would be a pretty large pile of uncollected $.noop function callbacks that might not ever be collected? 

Yes, but the same thing happens now too, only instead of the proposed value which would point to the same function, we point it to `undefined` - other thing to discuss - https://github.com/jquery/jquery/issues/2323. It seems proposed solution would eat less memory.

@secrettriangle this is a good suggestion, although it has obvious drawbacks, in case if jsonp request returns something other than js, or js but do not executed callback or just would throw HTTP-timeout error - this function would never be collected.

Now you can workaround this by using your own jsonp-callback name then let jQuery to generate it for you.
