### ISSUE TITLE
Strange behavior with iframes, title-cased CSS, and Chrome/Webkit

### ISSUE THREAD

**Issue by Cleod9** [jquery/jquery#2322]
Migrated from Thread: http://forum.jquery.com/topic/strange-behaviorwith-iframes-title-cased-css-and-chrome-webkit

Long story short - I'm working on a project that is using jQuery to write DOM nodes to an iframe and I found some odd behavior with CSS classes containing capitalized characters. I've narrowed it down to what seems to be an issue with jQuery's `append()` function for `$()`-wrapped HTML, and it affects all versions of jQuery 1.x and 2.x, Chromium/Webkit-based browsers only. See the following JSFiddle using Google Chrome or Safari for the minimal test-case:

http://jsfiddle.net/42t3m7aa/12/

Hopefully the comments are pretty self-explanatory, but as you can see I have a basic CSS class called `.TitleCase` that will color text red. I generate a simple `div` with this class name and add it to the DOM via `append($([html markup here]))`. If I then try to append another DOM node containing that same class name to an `iframe`, it breaks styles from that class in the parent DOM (in other words, the style definitions disappear). There are a bunch of odd workarounds for this that seem to suggest this might be a bug with jQuery.

Workarounds:

- Applying a `setTimeout` to delay the iframe manipulation
- Giving the affected DOM element additional CSS class names or dummy attributes
- Resorting to lowercase CSS class names
- Manually removing and re-adding the class name to the DOM elements
- Passing a string directly to `append()`
- Using another non-jQuery method to generate the element and append it

I suspect the problem lies in how jQuery's `append()` method treats HTML text VS a jQuery object, but i haven't been able to pinpoint exactly why from jQuery's source code.

**Comment by motapc97** [comment]
I reduced your test case: http://jsfiddle.net/42t3m7aa/17/

And I was also able to reproduce the opposite: http://jsfiddle.net/42t3m7aa/18/ (in which the text outside the iframe is red, and the text inside the iframe is red)

**Comment by motapc97** [comment]
I also created another test case in which I use `setTimeout`.

http://jsfiddle.net/42t3m7aa/19/

With a delay of 100ms I don't have any problems, but with a delay of ~50ms, I get different results in differents runs.

![http://i.imgur.com/FTuYWNX.png](http://i.imgur.com/FTuYWNX.png)
![http://i.imgur.com/zEh4mXV.png](http://i.imgur.com/zEh4mXV.png)

I hope this helps.

**Comment by Cleod9** [comment]
@motapc97 Interesting, so switching the `append()` order affects the outcome, and the outcome can become inconsistent with small setTimeout intervals? I wonder if this is some kind of race condition?

**Comment by motapc97** [comment]
@Cleod9

Right. I think the problem is with Chrome, because in other browsers this bug doesn't happen. I tried to replicate the problem using only native methods but unfortunately I couldn't. I'll try again later using some jQuery code to see exactly what causes Chrome to fail.

In any case, the fact that passing a string directly to `append()` solves the problem might mean that it is possible to add something to avoid this bug.

**Comment by gibson042** [comment]
`$iframeBody.append( $( divHtml ) )` is technically invalid because it's trying to append nodes from a foreign document. The failure is arguably a bug in Chrome (especially because it behaves unpredictably in the face of timeouts/breakpoints/etc.), but is definitively not one in jQuery. Being explicit about the ownerDocument (`$iframeBody.append( $( divHtml, $iframeBody[0].ownerDocument ) )`) corrects the issue: http://jsfiddle.net/42t3m7aa/22/

**Comment by Cleod9** [comment]
Thanks for the help @gibson042! Before we close things out, do you think this is something that's worth me reporting to the the Webkit/Chromium teams? I'm fine with changing my approach for my application, but I wonder if this behavior should still be investigated.

**Comment by gibson042** [comment]
I think so. There's definitely some weirdness that they could clean up.
