### ISSUE TITLE
Focusout event is not fired when an element is removed from the DOM in Firefox

### ISSUE THREAD

**Issue by arleytriana** [jquery/jquery#2360]
Currently Firefox (version 38) doesn't support the focusin and focusout events:

[bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=687787)

However, jQuery does. jQuery simulates the focusin and focusout events from the focus and blur events accordingly, but in Firefox, it doesn't get fired when an element is removed from the DOM.

**jQuery version:** 2.1.1
**OS:** Windows 7 Enterprise 64-bit

**Works in browsers:**
Google Chrome 43.0.2357.81 m
Google Chrome canary 45.0.2416.0
Opera 29.0
Internet Explorer 11.0.9600.17801
Safari on iOS 8.3 on iPhone 4S

**Does not work in:**
Firefox 38

Snippet: http://jsbin.com/qukocu/2/edit?html,css,js,output

**Comment by dmethvin** [comment]
I agree on the problem, and it's a good repro, but I'm not sure there is a reasonable way to fix that from jQuery. I'm not even sure DOM Mutation Observers help here because they happen after the fact and by then we probably can't tell whether anything that was removed had the focus. When the element is removed it doesn't appear a focus event fires on `document` when the removed element blurs.

The only solution I can think of is that on any update to the DOM we would have to see if `document.activeElement` is in the subtree being affected and fake the whole focus/focusin sequence. Focus management is a very ugly and bug-prone thing so I'm not sure we want to go there, plus there could be serious performance issues. Are there any other possibilities?

Is it possible to work around this in your app? In general it seems like a bad idea to remove focus from an element that the user may be interacting with.

Ideally, Firefox would just fix [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=687787). Pinging @miketaylr to bring him into the loop.

**Comment by miketaylr** [comment]
Thanks for the ping @dmethvin. Ideally if someone can find a site or two that is broken in Firefox due to a lack of focusin/focusout, I can make a better case for fixing it. ^_^

**Comment by markelog** [comment]
@miketaylr that is the thing, it is known that those events are not widely supported, so ppl use jQuery to use them. 

<b>Important</b> if you do implement those events, please add `onfocusin | onfocusout` properties to the window property - https://github.com/jquery/jquery/blob/a644101ed04d0beacea864ce805e0c4f86ba1cd1/src/event/support.js#L5 since there is no other way to correctly check support for those events.

And other, very important thing, please follow the <b>spec</b> not the Chrome implementation - https://github.com/jquery/jquery/blob/a644101ed04d0beacea864ce805e0c4f86ba1cd1/src/event.js#L755-758

**Comment by DaveStein** [comment]
Hey @miketaylr @dmethvin I was about to say FF is the good case for my use-case and found this ticket. Here is my fiddle:

http://jsfiddle.net/ocxe6qse/

In reality I have a list of LIs. When user hits enter, an LI gets replaced with the value of the input, and another LI gets generated with a new input. That causes this issue.

**Comment by DaveStein** [comment]
PS: My fiddle says FF is the good case so it seems I'm wrong there... but still would be good to have this behave consistently so I can work around it :)

**Comment by arleytriana** [comment]
@dmethvin Yes, it is possible to work around the issue. We implemented a fix, but just for one affected [OpenUI5](https://github.com/SAP/openui5) control, however this issue affect the web platform.

I agree that it is not a good idea to remove an element that has focus, but in complex scenarios it happens.

The best solution I can think of, is to fix the root cause of the problem, which is a bug/missing feature of the Firefox web browser.

@miketaylr
> Firefox is the only browser that still doesn't support focusin and focusout events.
> - Nicholas C.Zakas @nzakas
https://twitter.com/slicknet/status/590186313262870528

**Comment by ipetropolsky** [comment]
There is one more problem: even if focusout is triggered on removed element, jQuery runs only parent's focusout handlers. Example: http://jsbin.com/canenevuru/1/edit?html,js,console

Console output in Chrome 43:
```
"Blur:"
"jQuery focusout on input"
"jQuery focusout on body"
"Native focusout on input"
"Native focusout on body"
"Remove:"
"jQuery focusout on body"  // Missing jQuery focusout on input
"Native focusout on input"
"Native focusout on body"
```

**Comment by dmethvin** [comment]
@ipetropolsky That problem is related to the fact we can't use focusin/out on Chrome because they aren't doing it according to spec, see https://github.com/jquery/jquery/blob/a44cfa00665d21c3197e25c2d63741dc15f6ffb9/src/event.js#L810-817 .

I heard rumors that Microsoft Edge *might* have adopted the non-spec-compliant Chrome behavior which would be a problem, although if Firefox did the same we'd probably just give up and pass through the now-consistent behavior even though it's not in keeping with the standard.

If you're messing with focus this way, I hope you've checked the accessibility implications of doing so.

**Comment by dmethvin** [comment]
I think we resolved this wasn't a jQuery or jQuery-fixable issue so I'll close this.
