### ISSUE TITLE
Refactor effects module

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2378]
As an example, but not to offend anyone, this - https://github.com/jquery/jquery/blob/0019a463bdcb81dc6ba3434505a45774ca27f363/src/effects.js#L84
is something from the horror movie - crazy big cyclomatic complexity with vague logic. 

I mean five nesting `if`'s!

**Comment by timmywil** [comment]
That's fine, but reducing cyclomatic complexity needs to be balanced with performance. I remember John going through all of the methods at one point and just reducing the number of function calls across the board. This increased both the complexity and performance of jQuery methods across the board. That may not be as much of an issue now, tho, since we no longer support IE 6/7.

**Comment by markelog** [comment]
> That may not be as much of an issue now

Yeah, exactly, now function calls shouldn't be expensive, especially, comparing to what we do in them.

**Comment by dmethvin** [comment]
Plus, if the function is simple many of the current browsers will inline the function. Our big complex functions are usually excluded from optimizations because of their size. It's always risky to think too much micro-optimization when the rules are changing, but it's possible in this case that we'd make the code both faster (on modern browsers) and easier to maintain.

**Comment by gnarf** [comment]
(no offense taken) -- that `defaultPrefilter` is super complex... It handles so many corner cases...

**Comment by timmywil** [comment]
Closing in favor of tracking this in the [Roadmap](https://github.com/jquery/jquery/wiki/Roadmap). It is a principle to keep in mind for all modules.
