### ISSUE TITLE
Add `tap` method.

### ISSUE THREAD

**Issue by mlanza** [jquery/jquery#2403]
The `end` method terminates the last filter.  I was never fond of it because there is nothing to force a proper pairing with its opening other than indentation.  This is on the developer.

    $( "ul.first" )
      .find( ".foo" )
        .css( "background-color", "red" )
      .end()
      .find( ".bar" )
        .css( "background-color", "green" );

If we deprecate it in favor of `tap` (from Ruby) then inside a function we can query down however deep we need having the full assurance that when we come out of the function, we'll be right back where we started.  The language semantics enforce this and it clearly presents that one wishes to retain the original scope.

    $( "ul.first" ).tap(function(){
        this.find("foo").css("background-color", "red");
    }).find("bar").css("background-color", "green");

    //or for consistency...
    $( "ul.first" ).tap(function(){
        this.find("foo").css("background-color", "red");
    }).tap(function(){
        this.find("bar").css("background-color", "green");
    });

*The added noise of `function(){}` will go away when ES6 is realized.*

    $( "ul.first" )
      .tap(el => el.find("foo").css("background-color", "red")).
      .tap(el => el.find("bar").css("background-color", "green"));

Whether the function called by tap would pass the context in as `this` and\or the first argument offers some room for discussion.  My examples assume it does both.

Where `end` tells us to return to the former scope after the fact (e.g. somewhere after the original `find`), `tap` tells us up front that we're going to want to maintain the scope.  To my way of thinking stating that earlier is better than later.

It also provides an opportunity for the use of higher-order functions which means a greater potential for reuse.  The `end` method offers no such opportunity.

    function bg(selector, color){
        return function(){
            this.find(selector).css("background-color", color);
        }
    }

    $("ul.first").
        tap(bg("foo", "red")).
        tap(bg("bar", "green"));

Or alternately, provide another version of `find`, `filter`, etc. (though I prefer `tap`):

    $( "ul.first" ).find("foo", function(){
        this.css("background-color", "red");
    }).find("bar").css("background-color", "green");

The added benefit of `tap` is that we can easily see what's being returned from a function:

    function spreadChristmasCheer(el){
        return el.
            tap(bg("foo", "red")).
            tap(bg("bar", "green"));      
    }

So now we can reuse such a function in a number of ways:

    spreadChristmasCheer(el);
    el.tap(spreadChristmasCheer);
    el.find(".christmas-tree").tap(spreadChristmasCheer).find(".presents").remove();

**Comment by dmethvin** [comment]
Isn't this basically the same as using `.each()`? Your `this` is the jQuery object rather than the DOM element, but it's just a question of where the implied loop happens. The cost of `$(this)` is very low, especially for the number of iterations a construct like this would typically do. If you really wanted this it could be a plugin.

There are some documentation issues in describing this method since in all other non-plugin-writer scenarios the `this` is always a DOM element and not a jQuery object. That type of inconsistency can really trip people up and would be another reason not to put it directly in jQuery core.

> I was never fond of this because there is nothing to force a proper opening/closing pair.

There's no need to close if the result isn't needed, e.g. `$("p").find(".warn").addClass("important")`. In most real-life cases I've seen or written, people rarely need complex chains that require coming back to previous stacked results.

**Comment by mlanza** [comment]
Yes, and good point.  I have used `each` in this capacity.  So `each` does suffice now that I'm reminded of it.
