### ISSUE TITLE
Be consistent when checking if the node is connected or not

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2404]
We usually tested it with `jQuery.contains( elem.ownerDocument, elem )`, but now we switching to `elem.getClientRects()`

**Comment by mzgol** [comment]
We currently have four uses of `jQuery.contains` on `master`; one of them is for `find` so it needs to stay, the other three are in [css/curCSS.js](https://github.com/jquery/jquery/blob/842958e7aecd0d75a7ee9e2aaec83457701aa2f3/src/css/curCSS.js#L21), [css/var/isHidden.js](https://github.com/jquery/jquery/blob/842958e7aecd0d75a7ee9e2aaec83457701aa2f3/src/css/var/isHidden.js#L12) & [src/manipulation/buildFragment.js](https://github.com/jquery/jquery/blob/842958e7aecd0d75a7ee9e2aaec83457701aa2f3/src/manipulation/buildFragment.js#L76). Interestingly enough, in [src/css/hiddenVisibleSelectors.js](https://github.com/jquery/jquery/blob/842958e7aecd0d75a7ee9e2aaec83457701aa2f3/src/css/hiddenVisibleSelectors.js#L10) we use `getClientRects()`. :-)

**Comment by markelog** [comment]
Actually, `isHidden` uses `contains` whereas `isHidden` used in `css` and `effects` module. I think we should perf it.

**Comment by gibson042** [comment]
I would request the following for fulfillment of this ticket:
* [css/curCSS.js](https://github.com/jquery/jquery/blob/842958e7aecd0d75a7ee9e2aaec83457701aa2f3/src/css/curCSS.js#L21): no change (`contains` is appropriate because `getComputedStyle` applicability is controlled by attachment, not visibility)
* [css/var/isHidden.js](https://github.com/jquery/jquery/blob/842958e7aecd0d75a7ee9e2aaec83457701aa2f3/src/css/var/isHidden.js#L12): should use the most efficient combination of `contains`, `offsetWidth`+`offsetHeight`, and `getClientRects` (which _hopefully_ omits the former and matches [src/css/hiddenVisibleSelectors.js](https://github.com/jquery/jquery/blob/842958e7aecd0d75a7ee9e2aaec83457701aa2f3/src/css/hiddenVisibleSelectors.js#L10))
* [src/manipulation/buildFragment.js](https://github.com/jquery/jquery/blob/842958e7aecd0d75a7ee9e2aaec83457701aa2f3/src/manipulation/buildFragment.js#L76): no change (`contains` is appropriate because jQuery script evaluation is dependent upon document attachment)
* [src/css/hiddenVisibleSelectors.js](https://github.com/jquery/jquery/blob/842958e7aecd0d75a7ee9e2aaec83457701aa2f3/src/css/hiddenVisibleSelectors.js#L10): should use `isHidden`

**Comment by AVGP** [comment]
Hey @gibson042 - could you elaborate what you expect regarding isHidden?

Should it do more or less the same what hiddenVisibleSelectors does? And how do I know if my solution is "most efficient"?

I'd like to tackle this issue :-)

**Comment by gibson042** [comment]
We care about performance and (compressed) size, but functionality trumps both. What I propose above is moving the `!( elem.offsetWidth || elem.offsetHeight || elem.getClientRects().length )` logic into `isHidden`, then updating hiddenVisibleSelectors to _use_—rather than duplicate—it.

**Comment by AVGP** [comment]
Alright, that was all I wanted to know, because I did understand that we all care about performance and size, but I wasn't sure if "should use the most efficient combination of contains, offsetWidth+offsetHeight, and getClientRects (which hopefully omits the former and matches" meant: "We'll have to figure this out" or "we can reuse what's been in hiddenVisibleSelectors". :)

**Comment by markelog** [comment]
Also, would you mind providing perf test too?

**Comment by AVGP** [comment]
@markelog sure -- could you point me somewhere to figure out how?

**Comment by gibson042** [comment]
@AVGP Yes, and http://jsperf.com/visible-hidden-and-getclientrects (from https://github.com/jquery/jquery/issues/2227#issuecomment-100382971 ) should be a good starting point.

**Comment by AVGP** [comment]
I'd like to take this opportunity to say thanks to you and the entire rest of the jquery community. So helpful, so friendly, so fast! <3

**Comment by timmywil** [comment]
Unfortunately, I don't think this is possible without changing behavior. Effects has a slightly different definition of hidden than a selector should. For instance, we make sure that display is set to none even when it has a hidden parent, which makes sense for animations. That said, we'd be willing to review a PR.

**Comment by gibson042** [comment]
@timmywil I already described exactly how the source should change: https://github.com/jquery/jquery/issues/2404#issuecomment-112906491

Do you disagree with some part of that?

**Comment by timmywil** [comment]
@gibson042 I tried it and found behavior differences.

**Comment by timmywil** [comment]
Effects is treating hidden a little differently than hidden/visible, and I think both are valid. hidden/visible is the most technical (asking, "is the element actually visible on the page?"), but what effects really wants to check for is not really "hidden". It's asking, "should I set display: none?", and that depends on slightly different behavior.

**Comment by gibson042** [comment]
They're intentional; the whole point is to be consistent about visibility (i.e., has layout or—equivalently—`getClientRects()` returns non-empty).

**Comment by gibson042** [comment]
@timmywil can you be more specific about which customer-facing calls change in ways that you consider detrimental?

**Comment by timmywil** [comment]
> can you be more specific about which customer-facing calls

"detrimental" is strong, but animated vs non-animated hide on an element with a hidden parent. Non-animated sets it regardless. Effects sets it because it's not yet set.

**Comment by timmywil** [comment]
It makes sense to me that effects wouldn't care about displays of parents, in case the parent is simultaneously animated, or the parent's display changes mid-animation. I think it's okay that animations work differently than selections. We don't really have a reason for changing it other than consistency, so I'd prefer to let animations do their thing.

**Comment by gibson042** [comment]
I just ran through the cases, and I see what you're saying—animations, and even non-animated `.toggle()`, should look at computed display (ignoring inheritance from ancestors), whereas `:hidden` and `:visible` should check for layout boxes. But I still think there's a little bit of work here:
* Rename `isHidden` to make clear that it ignores ancestry, and is therefore distinct from `:hidden`
* Clarify what to do with disconnected elements. Right now, they're _all_ treated as hidden by CSS/effects methods, but I don't think that should be the case for elements with element parents unless they have inline `display: none` (e.g., the `<p>` in `jQuery("<div><p></div>")`)

The former seems to be part of this thread, but I'm not sure about the latter. Do you want me to open a new issue specific to it?

**Comment by timmywil** [comment]
@gibson042 That'd be great. I can knock out the first real quick.

**Comment by timmywil** [comment]
Name suggestion? Maybe `isShowable`, `shouldSetDisplay`, or `isHiddenWithinTree`?

**Comment by gibson042** [comment]
`isHiddenWithinTree` is the best of those three, and seems to describe the functionality pretty well.
