### ISSUE TITLE
jQuery .animate() sets it's own initial value when animating width to "0%"

### ISSUE THREAD

**Issue by gb056** [jquery/jquery#2442]
jQuery version: 1.11.0 and 1.11.3
Observed in: Chrome 43, IE 11 & FF Developer 40 on Windows 7 64bit

Originally posted on StackOverflow here: http://stackoverflow.com/questions/31181158/jquery-animate-sets-its-own-initial-value-when-animating-width

JSFiddle Example (broken): http://jsfiddle.net/xy1x885n/
JSFiddle Example (fixed): http://jsfiddle.net/xy1x885n/4

-------------------

I'm working on an implementation for a sidebar that slides in from the left, squashing the main content div as it goes.

As you can see from the demo, sliding out works fine but when it comes to sliding back in again the sidebar div is set to 100% width before the animation starts causing a very jarring effect. This is easier to see if you inspect the sidebar element and watch the width css property very carefully.

As Rory McCrossan on the StackOverflow thread points out, replacing `width: "0%"` with `width: 0` solves the issue, leading me to believe this may be a jQuery bug.

**Comment by gibson042** [comment]
When animating in a unit other than the one returned by `getComputedStyle` (here, "px"), we have to compute the starting value in the animation unit (here, "%"), which happens by means of [iterative approximation](https://github.com/jquery/jquery/blob/a644101ed04d0beacea864ce805e0c4f86ba1cd1/src/css/adjustCSS.js#L20-L42). It should be imperceptibly fast, but I don't see anything we can do if it isn't in your case. I second the recommendation to use a unitless 0, because doing so eliminates the mismatch and allows us to skip the starting value computation.
