### ISSUE TITLE
Use element.matches() for event delegation

### ISSUE THREAD

**Issue by OpenGG** [jquery/jquery#2468]
jQuery's event delegation is based on `jquery.event.handlers` method, which is for handler filtering.

If developer uses event delegation `.on(event, selector, fn)`, everytime when event dispatches, `jquery.event.handlers` calls `jQuery(selector)` , gets a collection of delegated targets, then checks them one by one.

The mechanism is basically same as my event delegation implementation based on `.querySelectorAll()`.

But another implementation based on `element.matches()` is times faster. Would jQuery consider using `.matches()` instead?

http://jsperf.com/matches-vs-queryselectorall

**Comment by dmethvin** [comment]
The current event delegation does use `.matches*()` [via jQuery.find which delegates to Sizzle](https://github.com/jquery/jquery/blob/bf591fb597a056bf2fc9bc474010374695b18d1a/src/event.js#L498). I can't really tell from the jsperf what is going on here, but it looks like the first case may be optimized away by the JIT given the numbers. If you have some ideas that speed up delegation, maybe you could implement them as a complete pull request and see whether it makes a difference that way? Check against the unit tests as well, since there are many tricky cases here.

**Comment by dmethvin** [comment]
I'm closing this because I am pretty sure the current code does use `matchesSelector` where possible. For infamous cases like positional selectors it cannot. The jsperf provided isn't looking at any jQuery code.
