### ISSUE TITLE
Microsoft Edge compat

### ISSUE THREAD

**Issue by csuwildcat** [jquery/jquery#2484]
Hey there jQs,

I am going to be the point of contact for library compatibility Edge. Do you know the current compat ranges for jQuery, and any bugs that are blocking operational compat with Edge?

- Daniel

**Comment by mzgol** [comment]
Hi @csuwildcat, thanks for reaching! I've recently added Edge to our support infrastructure, temporarily to the 2nd-grade [periodic run](http://swarm.jquery.org/project/jqueryweekly) instead of [the main one](http://swarm.jquery.org/project/jquery) until all issues are resolved.

There are mostly two issues:
1. #2390 - We have a Sizzle PR (https://github.com/jquery/sizzle/pull/341) from @jdalton. We'd love to not have to make all browsers suffer but until Edge fixes the bug we have to drop the `document.documentMode` guard in applying the workaround.
2. #2389 - missing `window.onfocusin`. This is not critical but it will make jQuery use its own `focusin`/`focusout` emulation instead of the native one. We already do that for Chrome because of bugs in implementing those events (I don't know if Edge kept it's good IE implementation or replicated Chrome bugs there).

In http://swarm.jquery.org/job/942 you can see one more Edge failure, this is one `box-sizing`-related test that already passes in newer builds, it's just that BrowserStack has only a relatively old build, still named Spartan, where it was still an issue.

IMO everything else is fine.

**Comment by csuwildcat** [comment]
I just did a quick review of the items you listed (knew about the focusin detection/polyfill one), and it seems like there's a good idea of what's wrong in each. Focusin is a bummer, and I will escalate that, but are any of these going to present hard stops for people, in your estimation?

**Comment by mzgol** [comment]
> are any of these going to present hard stops for people, in your estimation?

No, I don't think anything here is a hard blocker. Fortunately we've never shipped the workaround for http://bugs.jquery.com/ticket/13936 in version that checked for `document.documentMode`, it was just on `master` so we're good. :+1:

**Comment by mzgol** [comment]
@csuwildcat Is there anything else we can do here? If not, I'd rather move any further conversation about mentioned two bugs to them, i.e. to #2390 & #2389.

**Comment by csuwildcat** [comment]
@mzgol no, this looks good. Now that I have the two relatively minor issues logged I can follow up on them separately from this overall compat confirmation. Thank you!
