### ISSUE TITLE
Input Blur not work for IE, keeps focus but not fire any delegated events anymore

### ISSUE THREAD

**Issue by brainfoolong** [jquery/jquery#2511]
Here is a test suite for both main jquery branches

jquery 1.x branch
https://jsfiddle.net/po6x9763/10/

jquery 2.x branch
https://jsfiddle.net/po6x9763/11/

In the second field "disabled and blur" the field will loose focus in every browser except IE 11 (tested also with IE8 native and all simulated IE 11 versions like 10,9,8).
In IE the focus is still on that field, you can type in, but all delegated events that require a focus not fire anymore like "keyup".

Update: It works well with the brand new Micorosft Edge as expected, only native IE have this problem.

That is a big problem because all things that you do like validation with key events will not trigger but you can still type in anything. And also many other cases, it's on your imagination.

**Comment by mzgol** [comment]
Thanks for the report. Unfortunately, all versions of IE (even IE 11) fire `blur` & `focus` events asynchronously and there is no easy way to work around it generically enough to include the workaround in jQuery.

Good news is it's fixed in the new Microsoft Edge browser but IE 11 will stay as it is forever.

Please also see gh-1758 & [trac-13026](http://bugs.jquery.com/ticket/13026) for previous related bug reports.

BTW, is there any way why you cannot just make the field disabled natively via the `disabled` attribute? This will work even in IE and you don't have to blur the field: https://jsfiddle.net/po6x9763/12/. (it looks differently but you can style that via CSS if needed)

**Comment by brainfoolong** [comment]
Ok, that's weird. Well i know all the other things but in general i cannot disable the fields because i require all my disabled fields to send via post, attribute "disabled" fields are ignored.
I'll do some other stuff to make it working. 
Thx anyway.

**Comment by mzgol** [comment]
Yeah, I wish there was any way to work around it on our side as it's surely a pain to developers. `focus`-related things are hard to fix in a library.
