### ISSUE TITLE
Android 4.0-4.3 special-treats __proto__ in JSON.parse

### ISSUE THREAD

**Issue by mzgol** [jquery/jquery#2515]
Androids 4.0-4.3 (surprisingly Android 2.3 is fine) treats `__proto__` specially in `JSON.parse`:
```js
var o = JSON.parse('{"__proto__": []}');
"length" in o; // true
```
This may lead to security issues if `Array.prototype` is extended (and we only forbid [messing with `Object.prototype`](https://contribute.jquery.org/wont-fix/)):
http://jsbin.com/kuwedo/edit?js,output

Should we work around it? Deleting `__proto__` on the result and using `$.extend` seems to help:
http://jsbin.com/cocena/edit?js,output

**Comment by gibson042** [comment]
If I understand correctly, you're suggesting code changes in `jQuery.parseJSON` to ensure that returned objects/arrays (and recursively, their contents) have the standard prototype chains. Is that right—nothing more and nothing less?

If so, I would oppose it. Anyone willing to pay the code size and performance penalties can duckpunch `jQuery.parseJSON` with a more hardened function, but I'd hate to make that decision universally. And it's not even clear to me that such changes would increase security in practical terms, since proper JSON parsing allows creation of both actual arrays and `{ "length": <N>, … }` array-like objects, not to mention the fact that our function itself is pretty much equal in vulnerability to any property of the global object (e.g., why modify `Array.prototype` when you can modify `jQuery` or its properties directly?).

By the way, how did you find this?

**Comment by mzgol** [comment]
Yes, I thought about modifying `jQuery.parseJSON` but maybe you're right - `JSON.parse` doesn't understand variables so the only way to trick it is via modifying native prototypes in which case, as you've said, we're doomed anyway.

> By the way, how did you find this?

After recent [Android 2.3 non-quoted property name bug](https://github.com/jquery/jquery/issues/2478) I was interested in which browsers are actually ES5-compliant (more or less) so I run the http://test262.ecmascript.org test suite on a couple of them. I knew IE is OK from version 10 but I wasn't sure about Android - it turns out the first version having only a few fails was 4.1; one of these failed tests was checking exactly that.

**Comment by gibson042** [comment]
Right on. :)

**Comment by mzgol** [comment]
OK, since my fears were overblown, I'm closing this issue. Thanks, @gibson042!
