### ISSUE TITLE
Cache `node_modules` folder at travis build

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#2541]
See http://docs.travis-ci.com/user/caching/

**Comment by mzgol** [comment]
I don't think it's a good idea. This can lead to Travis succeeding when `npm install` on a fresh `master` clone will fail because it will install newer dependencies that got broken while Travis has old working ones. I'd guess most of us will also not notice it unless we have a habit of removing `node_modules` locally & reinstalling deps regularly.

OTH, `npm install` on Travis is **really** fast so this won't speed up the build significantly.

**Comment by markelog** [comment]
I guess you forgetting that we have two CIs

**Comment by mzgol** [comment]
> I guess you forgetting that we have two CIs

Good point. But considering that `npm install` is fast on Travis in the jQuery repository (before Promises/A+ tests were added, the whole build completed in 45 seconds), what are the reasons for introducing the cache here?

**Comment by markelog** [comment]
I don't understand the question :-), there is only upside no downside

**Comment by mzgol** [comment]
For me the downside is e.g. that we might miss a broken subdependency if we didn't have commits recently and someone submits a PR. Only when merged we'll notice that Jenkins crashes. Also, one day we might switch to Travis completely and then we won't notice the problem at all?

What are the (visible) upsides? Saving 10 seconds of the build isn't a real upside for me.

**Comment by markelog** [comment]
> Only when merged we'll notice that Jenkins crashes.

This never happened before and chances are, it will never happen. Third party dep of the dep should influence original dep tremendously in order for us to fail. I'm not even sure that happen anywhere ever.

But even if it does, we couldn't do anything in that case, only wait, when dep of the dep would release another version, so that fail would be just noise. We couldn't even downgrade, since original dep could use that bad dep with tilde or caret since the first version.

With conjunction of this question
> Also, one day we might switch to Travis completely and then we won't notice the problem at all?

It seems you try to solve issue that doesn't exist, if that situation would be indeed dangerous, then travis caching feature should be considered dangerous, since if that would be the issue, it would be the issue not only for the node community, but for every community there is.

**Comment by mzgol** [comment]
>> Only when merged we'll notice that Jenkins crashes.
>
> This never happened before and chances are, it will never happen. Third party dep of the dep should influence original dep tremendously in order for us to fail. I'm not even sure that happen anywhere ever.

It did happen for me in my project at least twice. Projects usually depend a lot on sub-dependencies that are wrapped in a Grunt plugin; a plugin is usually a thin wrapper around the library and the library is what matters. For me one of these failures was an ESLint bug in one of the rules that didn't catch one edge case; fixing this bug broke the build for me as I had that specific linting bug in my code.

> But even if it does, we couldn't do anything in that case, only wait, when dep of the dep would release another version, so that fail would be just noise. We couldn't even downgrade, since original dep could use that bad dep with tilde or caret since the first version.

You can pin a sub-dependency version directly and if it fits in the semver range, this will be what's used. (at least it works that way in npm@2). You can apply a temporary shrinkwrap. You can sometimes downgrade the dependency to an older version temporarily. You can temporarily disable the broken functionality so that the build is not broken. Sometimes the plugin releases a new version with a pinned older sub-dependency and you can upgrade to it (I've seen it quite often).

There are a lot of things one can do. The worst is to not know.

> if that situation would be indeed dangerous, then travis caching feature should be considered dangerous, since if that would be the issue, it would be the issue not only for the node community, but for every OSS community there is.

You're generalizing way too much. Ruby modules usually pin subdependencies as that's what `Gemfile.lock` file does. For npm AngularJS uses shrinkwrap + Travis caching so that builds are deterministic (they have *a lot* more deps than we do, though).

BTW, you didn't reply what are visible gains. If there are no gains then even small faults discredit the solution.

**Comment by markelog** [comment]
> It did happen for me in my project at...

So "bug" was already in your code, not in proposed changes (like in pr), but already landed, so as i said, it never happens. And in our case, we would notice that in Jenkins.

> You can pin a sub-dependency...

Honestly, all those options sounds awful to me, you can just wait and do not trush the commit history.

> There are a lot of things one can do. The worst is to not know.

If we are talking about a bug in the dep, then issue would dissappear by itself, so i would prefer not to now.

> You're generalizing way too much. 

Maybe, but if that was the case you afraid of, some projects would be excluded from that danger, yes, but a loot of them would still be vulnerable. 

> BTW, you didn't reply what are visible gains.

I thought i did, it will be faster, in the future, we might try to use babel for example, at least we can try to use exports/imports constructions, babel takes a lot of deps, same story if switch to full server js, express, karma, phantom, etc, same story when we will use WD for integration tests, same story if would have real node tests. If the future is bright, we will have a lot more dev deps.

**Comment by mzgol** [comment]
>> It did happen for me in my project at...
>
> So "bug" was already in your code, not in proposed changes (like in pr), but already landed, so as i said, it never happens.

It doesn't matter where the bug was; the build worked one day and was broken a later without any changes. So please don't say it "never happens" when I exactly described how it **did** happen. o_O

>> There are a lot of things one can do. The worst is to not know.
>
> If we are talking about a bug in the dep, then issue would dissappear by itself, so i would prefer not to now.

Not all issues "disappear by themselves". The one in my project I described is one example of something that never disappears until you fix your own code.

> I thought i did, it will be faster, in the future, we might try to use babel for example, at least we can try to use exports/imports constructions, babel takes a lot of deps, same story if switch to full server js, express, karma, phantom, etc, same story when we will use WD for integration tests, same story if would have real node tests. If the future is bright, we will have a lot more dev deps.

Then we can always enable the cache when it becomes a real problem. But if we have a lot of deps then we might even want to use shrinkwrap. It's hard to project what we'll need to do in the future.

**Comment by markelog** [comment]
> It doesn't matter where the bug was; the build worked one day and was broken a later without any changes.

You missing the point, "never happens" meaning dep of the dep never breaks so significantly, that it would break your build by being broken itself, in your case, dependencies actually fixed itself. 

You might not notice it, but jscs `jquery` preset was updated quite a lot for the past six months, but jquery builds never broke because of it, you know why? Because `grunt-jscs` use only `~` for it jscs dep, and patch versions of jscs never show more errors then previous patch version. Meaning it would never break your code like eslint does, only if you would explicitly ask for it, by putting caret in front of it.

Now yes, some people say for eslint that would makes sense to break your code when edge bug is fixed, but in this case, bug was already in your code, if it would happen with us, like if jshint was implicitly updated, then we wouldn't need to break PR of other contributor, since that might provoke that contributor to fix some unrelated part of the code, then we would have a commit that would do two unrelated things, or two commits under one pr that would do different things or if contributor does not fixed in the PR, we would have a failed pr that we should merge or commit fix asap and ask contributor to rebase.

All of these cases might discourage that contributor to submit the fix at all or continue to work with us. So it would be actually better if we would notice such failure only in jenkins.

**Comment by markelog** [comment]
At previous meeting, we decided to wait on this, if it would become an issue, then we could resurrect this discussion

**Comment by mzgol** [comment]
@markelog 
> This never happened before and chances are, it will never happen.

FYI: It has just happened. A new JSHint has been released and our master is broken. Just like I thought - a Grunt plugin wrapping a library that we use. cc @rwaldron

**Comment by markelog** [comment]
> EDIT 2: JSHint 2.9.0 has been unpublished, the build is green again.

Just like i said :-)
