### ISSUE TITLE
ParseHTML removes content in Windows Store App

### ISSUE THREAD

**Issue by Jonasei** [jquery/jquery#2548]
`tmp.innerHTML` removes certain content from the HTML to be parsed when used in a Windows Store App. This is according to the security restrictions outlined here https://msdn.microsoft.com/en-us/library/windows/apps/hh465388.aspx 

However, this ruins functionality that is dependent on, for example, comments to work, like the virtual element template binding in Knockout.js.

This could be fixed by changing innerHTML with WinJS.Utilities.setInnerHTMLUnsafe when used in a Windows Store App.

**Comment by mzgol** [comment]
We try to support Windows Store Apps but not using APIs that are restricted for security reasons (one example is [setting name & type attributes](https://github.com/jquery/jquery/blob/a644101ed04d0beacea864ce805e0c4f86ba1cd1/src/manipulation/support.js#L13-L14)) but using Windows-specific non-standard APIs is a no-go. After all, the `innerHTML` restrictions were introduced for a reason, we shouldn't just hack around them.

Could you share example code that breaks for you with current jQuery?

**Comment by dmethvin** [comment]
I have to agree with @mzgol here, any API that explicitly has the word `unsafe` in it is trying to tell you something. We shouldn't circumvent those restrictions because we are likely to open security holes. If you use jQuery directly and follow the restrictions listed in that reference, jQuery itself should work properly.

For the case where a framework explicitly depends on things like HTML comments to have semantic meaning when injected into a document, I am not sure there is a really good workaround. We could add some sort of trap door inside jQuery that allows the user to replace `innerHTML` with `setInnerHTMLUnsafe` but that seems irresponsible because at the point where it's used there is not a reliable way to tell "good" calls from "evil" ones.

At present we don't test the Windows Store App scenario but we have been talking with Microsoft about how we can integrate it into our CI environment. We want jQuery to work there but of course, this is not just about jQuery functioning but also Knockout. Whether Knockout can be used in Windows Store apps is not something we'd be testing in our CI, at least not directly, and the Knockout team would need to commit to ensuring that worked.

**Comment by dmethvin** [comment]
I'm going to close this as it seems to be working as intended.
