### ISSUE TITLE
Query.param adds incremented keys to arrays of objects

### ISSUE THREAD

**Issue by niko** [jquery/jquery#2550]
```
decodeURIComponent(jQuery.param( {a:[{a:1},{a:1},1]} ) )
//=> "a[0][a]=1&a[1][a]=1&a[]=1"
```
So the outer `a` gets incremented keys (`0` and `1` in this case) if the value is an object while it doesn't get a key (just an empty `[]`) when the value is a number (or string).
I would have expected
```
//=> "a[][a]=1&a[][a]=1&a[]=1"
```

I tried this with jQuery version 3.0.0-alpha, 2.1.3, 2.1.0, 2.0.2, 1.11.0 and 1.10.1.

http://jsfiddle.net/7nrwL7pg/

**Comment by dmethvin** [comment]
There is no standard governing the way JavaScript objects are encoded into a query string. This behavior has been consistent for many versions so there is no incentive for us to change it and possibly break existing code. Is there a reason to avoid JSON encoding here? That is well defined and most servers have libraries to parse it.

**Comment by niko** [comment]
Yes, there is no standard. But this isn't even consistent. The only possibility to make it consistent and not break exising apps would be to introduce an new flag (like the existing `traditional` flag) defaulting to the old inconsistent behaviour. But I understand if this was considered too much trouble for questionable benefit. Just thought I'd report it because it stroke me odd. I must have overlooked the big yellow boxes in the docs (https://api.jquery.com/jQuery.param) ;)

**Comment by dmethvin** [comment]
The purpose of `.serialize()` and friends is to mimic the way that browsers serialize form inputs. You're into uncharted territory when you pass it complex JavaScript objects. Since JSON already solves this problem and is well-supported, there isn't a lot of reason to come up with a second way to do this.  There is already a yellow-box note suggesting that people use JSON for these cases. 

It looks like you're trying to serialize JavaScript data structures to a string. Would you like to use JSON? 
![Clippy](http://i.imgur.com/m9716fW.png)
