### ISSUE TITLE
Jquery 2.1.4 not supporting in IE 9

### ISSUE THREAD

**Issue by Ganesh1982** [jquery/jquery#2573]
I am get below error in IE 9
SCRIPT438: Object doesn't support property or method 'addEventListener' 

But same is working in if browser version >IE 9

**Comment by NeelBhatt** [comment]
Not all browsers support event capturing (for example, Internet Explorer versions less than 9 don't) but all do support event bubbling. You can try .on() instead!

**Comment by Ganesh1982** [comment]
But my IE version is 9

**Comment by mzgol** [comment]
This report is too vague, we need a reproducible test case on https://jsbin.com or https://jsfiddle.net to be able to debug a problem. You didn't provide any code so we can't know what's wrong for you.

That said, your error seems very basic, it doesn't seem like it could come from jQuery. I'm going to close this report; please look for help on jQuery Forums or Stack Overflow; if something turns out to be a jQuery bug and you have a test case I'll reopen.
