### ISSUE TITLE
(FR) .tail access function

### ISSUE THREAD

**Issue by pyhedgehog** [jquery/jquery#2580]
It's not as easy to get text between sibling elements:
```HTML
<div>text1<span>text2</span>text3 to grab<span>text4</span>text5</div>'
```
If I want to get "`text3 to grab`", I need to write something like this:
```JavaScript
var a = $('span:first-child');
var b = a.parent().contents();
console.log($(b[Array.prototype.findIndex.call(b,function(elem){return $(elem).is(a);})+1]).text());
```
Also I need to add [Array.findIndex polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex#Polyfill).
Let's stole [`tail`](https://docs.python.org/2/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.tail) name for function that will return (and possibly change/add) next text node sibling.

See also cheeriojs/cheerio#743.

**Comment by dmethvin** [comment]
That is true, it's always been hard to manipulate bare text nodes because jQuery wasn't ever meant to do that. For your case, if you have control over the markup you should wrap those in a `<span>` or something so they would be easier to select. I don't see us adding more text-node manipulation, it's a very tricky problem because text nodes don't have the same methods as elements.

**Comment by pyhedgehog** [comment]
Ok. What about adding method/selector for prev/next node sibling in addition for element sibling?

**Comment by dmethvin** [comment]
You can use `.prop("nextSibling")` for that perhaps if it's just one element? I don't think it's worth more API surface.

**Comment by pyhedgehog** [comment]
You only considering situation when one author control both html content and js code. It's not always true. For example one can use jQuery in GreaseMonkey-compatible scripts.
