### ISSUE TITLE
:visible selector including invisible elements

### ISSUE THREAD

**Issue by FesterCluck** [jquery/jquery#2604]
Please see [my comment on #2227](https://github.com/jquery/jquery/issues/2227#issuecomment-141759227)

For quick review, [an example fix addressing the issue](https://github.com/FesterCluck/jquery/blob/master/src/css/hiddenVisibleSelectors.js).

If #2227 is reopened, please close this issue.

**Comment by gibson042** [comment]
An approach like you suggest was tried and abandoned (more than once, in fact) because of cross-browser inconsistencies (see http://bugs.jquery.com/ticket/10406 and http://bugs.jquery.com/ticket/13132). The current model essentially defines `:visible` as having a _position_ in the page, and seems to sidestep both those issues and performance degradations of other implementations You are free to filter selected elements further; another benefit from our perspective is that this is the broadest meaningful definition. Or is your use case one in which the reliance on custom selectors is deeply buried?

**Comment by FesterCluck** [comment]
Not so much. After spending more time with the DOM, it seems this case only really comes up in anchor tags, which already has a resolution with this. One /might/ consider a length > 1, or at least a check on ClientRectList[1].width/height if [0] is hidden, but at this point it's just academic. In all cases I've tested for actual behavior, my suggestion is just overhead. Consider the request withdrawn. Thank you all for your hard work.
