### ISSUE TITLE
Have $(document).ready wait for an event before firing [Need Advice]

### ISSUE THREAD

**Issue by dtracers** [jquery/jquery#2638]
cross posting this issue: https://github.com/webcomponents/webcomponentsjs/issues/411

Basically I need to have any handler attached to $(document).ready not be called until a custom event is triggered

**Comment by mzgol** [comment]
You just need to put your code where you want it to be invoked. If you need to wait for a particular event, just put your `$(document).ready` code in the event handler.

**Comment by dmethvin** [comment]
I think @dtracers is looking for a way to prevent ready from happening on the entire page until all Web Components have initialized. That would be a really bad idea since it would hurt performance. No jQuery code on the main page should be reaching into the state of WCs on the page, and if it needs to know WC state the code should be rewritten. However, I can offer you `jQuery.holdReady()` and hope that you do not use it. Please followup to StackOverflow though since this is not a bug report and we already provide the foot-gun you want.

**Comment by dtracers** [comment]
@dmethvin  that is actually what I was asking for.  Thanks! A library I am using for animations has to set up its code on ready but if the custom elements are not set up before it attaches the handlers then the animations do not work.  So they work in chrome but not with the polyfills.

(mainly happens when using html imports)

**Comment by jaubourg** [comment]
Untested but it should work:

```js
$.ready.promise = $.when( $.ready.promise(), $.Deferred( function( defer ) {
    $( document ).on( "customEvent", defer.resolve );
} ) ).promise;
```

You pretty much replace the ready promise with the union of the old ready promise and another promise that is resolved when the custom event is triggered.
