### ISSUE TITLE
$.parseJSON (value==undefined) 

### ISSUE THREAD

**Issue by bilaridis** [jquery/jquery#2650]
Function parseJSON should have check if data != undefined to return undefined or nothing ...

**Comment by timmywil** [comment]
Thank you for opening an issue. Please ask for support on the [forums](http://forum.jquery.com) or in the #jquery irc channel, or flesh out the issue more and provide a small test case.

**Comment by MartinBring** [comment]
I agree with bilaridis.

Using IE 11 and Microsoft MVC 4 client validation, a checked checkbox gives an error due to data == undefined (unexpected token). It works with Chrome though.

Adding a check for undefined solved it for us.

    // Support: Android 2.3
    // Workaround failure to string-cast null input
    jQuery.parseJSON = function (data) {
        if (data === undefined)
            data = null;
        return JSON.parse(data + "");
    };

**Comment by mzgol** [comment]
@MartinBring jQuery.parseJSON is a polyfill for JSON.parse so we're not going to change how it works. You shouldn't pass undefined to it.

**Comment by MartinBring** [comment]
Hi @mzgol

Thank you for responding so quickly.

I see now that my comment could be interpreted as we are using other script libraries, but we are not. It is not any external part passing undefined, we are just using jquery libraries. So with IE 11 some part of the validation libraries is passing undefined when validating checkboxes (in our case).

So I do not see any different between the existing workaround for Android 2.3 (null) and the proposed one for IE 11 (undefined)?

Kind regards
Martin

**Comment by mzgol** [comment]
Please provide a minimal test case reproducing the issue, without it it's
hard for us to say if the problem lies in jQuery or in a different place.

-- 
Michał Gołębiowski

**Comment by markelog** [comment]
Yeah, it was like that before, this behaviour changed in 1.9, now such input is incorrect, if your validation lib is passing such value, it means it is not compatible with later versions of jQuery, you might want to consider updating it.

> So I do not see any different between the existing workaround for Android 2.3 (null) and the proposed one for IE 11 (undefined)?

Because `null` value is correct JSON :-), just like any other primitive value, like string or number, but `undefined` is not a valid JSON (see http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf). Whereas Android 2.3, follows previous iteration of that specification, which prohibited such values, `jQuery.parseJSON` normalize such behaviour.  

> @MartinBring jQuery.parseJSON is a polyfill for JSON.parse so we're not going to change how it works. You shouldn't pass undefined to it.

Not polyfill though :-), a shim

**Comment by Mouvedia** [comment]
@markelog do you have a link to that draft?
