### ISSUE TITLE
Update event.which to avoid deprecated properties

### ISSUE THREAD

**Issue by khigakisugar** [jquery/jquery#2667]
Version: Master

Description: The `event.keyCode` and `event.charCode are deprecated and used by jQuery's `event.which` https://github.com/jquery/jquery/blob/e99a3ac7066226d00ff5828de596d4a4b3818c0c/src/event.js#L544

For information about the deprecation, please refer to MDN:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode

JS Fiddle (limited usefulness in this case):
http://jsfiddle.net/mqaxhuj3/

**Comment by timmywil** [comment]
Actually, `.which` is also deprecated, but we have it documented so we need to provide support for it. `keyCode` and `charCode` are used to provide that support where `which` is not already provided natively.

**Comment by dmethvin** [comment]
I suspect this report is due to console messages from Firefox? If so, the "lazy-eval" solution in #2337 would fix it since we would only look at those properties if you tried to look at `event.which`.

**Comment by rhoggSugarcrm** [comment]
No, this isn't due to console messages from Firefox - this was just the result of @khigakisugar and I realizing that `KeyboardEvent.keyCode` is deprecated and looking for a better solution.

While the DOM method `KeyboardEvent.which` is marked as deprecated, `event.which` is not listed as deprecated at https://api.jquery.com/event.which/.

IMHO, what would be most helpful, both to us and any other potential future users of `event.which`, would be a deprecation notice on the JQuery web page and some text there recommending something to use instead. `KeyboardEvent.key` isn't really a viable option for us (at least without manually falling back to something else) until Chrome and Safari support for it is finished.

**Comment by dmethvin** [comment]
The W3C unfortunately made a big mess of mouse buttons and key codes over the course of a decade, there are lots of deprecated properties with different values. In order to get a consistent result across all the platforms jQuery has supported over the years starting with Firefox 2 and IE6, we settled on normalizing `event.which`. 

I am not sure how far along the browsers are in supporting for example [the keys standard](http://www.w3.org/TR/DOM-Level-3-Events/#keys-codevalues) but it is always possible to get the raw event values from `event.originalEvent.key` (or `.code`) if it turns out they are finally implemented. That is probably the best path for users to take, and only use `event.which` when they need jQuery's normalization. 

So that does leave us where @timmywil mentioned above, between lazy eval of `event.which` and improved documentation we should have this covered. I've created a ticket at the API repo, if you have some ideas on wording or could test support for the new standard properties that would be awesome!
