### ISSUE TITLE
:target doesn't match elements on initial page load in Chrome and Firefox

### ISSUE THREAD

**Issue by zzzzBov** [jquery/jquery#2679]
I'm able to reproduce this issue in `Firefox 41.0.2` and `Chrome 46.0.2490.80 m`

Basically, selecting `$(':target')` during initial page load to a url that contains a document fragment fails to select the targeted element.

```
<!DOCTYPE html>
<html>
<head>
    <title>:target Bug</title>
    <style>
        :target {
            background-color: red;
        }
    </style>
</head>
<body>
    <a href="#test" id="test">Test</a>
    <script src="http://code.jquery.com/jquery-2.1.4.js"></script>
    <script>
        $(':target').css('color', 'yellow');
        $(location.hash).css('border', '10px solid green');
        console.log('initial page request', document.querySelector(':target'));
        document.body.onload = function () {
            console.log('page load', document.querySelector(':target'));
        }
    </script>
</body>
</html>
```

This is caused by `document.querySelectorAll(':target')` returning `null` before page load (and sometimes it returns `null` after page load). Sizzle pipes the selector through `querySelectorAll`, which produces incorrect results.

I've created a [codepen][1] that shows this behavior. [Please view it in debug mode with the document fragment][2].

[1]: http://codepen.io/zzzzBov/pen/ojygro
[2]: http://s.codepen.io/zzzzBov/debug/ojygro#test

**Comment by dmethvin** [comment]
If `:target` didn't work until DOMContentLoaded fired that wouldn't surprise me. The other situations seem like browser bugs. Have you reported them to Chrome and Firefox?

**Comment by timmywil** [comment]
Looks like a browser bug. @gibson042 should Sizzle test for this and bypass qsa?

**Comment by zzzzBov** [comment]
> If `:target` didn't work until DOMContentLoaded fired that wouldn't surprise me.

From testing, DOMContentLoaded was too early, page load would work...*most of the time*. It was inconsistent.

> Have you reported them to Chrome and Firefox?

I have not. I had just enough time to post this bug report before running off to do other things, I haven't yet had the chance to sort out where to post the issue to FF or Chrome.

From looking at the jQuery source, I recall seeing a buggyQSA check that could be used to skip `querySelectorAll`, but I haven't yet had the time to mock up a possible fix.

**Comment by gibson042** [comment]
I'm seeing a difference between Chrome and Firefox in the _CSS_ handling—the former doesn't apply cascaded `:target` rules until after page load, but the latter does. Such an inconsistency makes me nervous about applying global changes in Sizzle.

**Comment by dmethvin** [comment]
Before we enshrine a solution that's hard to support into the future, it's definitely worth kicking this to the browser guys. If we can get them all to agree on a standard behavior perhaps we can polyfill it until they all get on the same page. Until then I'm with @gibson042 that fixing this in Sizzle seems risky.

**Comment by zzzzBov** [comment]
I guess I'm confused as to why `:target` would ever match anything other than `$(location.hash)` at any point in the page lifecycle. I get it that the node may not exist in the DOM at some points, but once the node exists, is there any compelling reason that `:target` would not select the element?

What risk is there in enforcing this behavior?

**Comment by timmywil** [comment]
@zzzzBov That's just it. Because of the inconsistency between browsers, I believe @gibson042's first reaction is that there are 2 causes. (1) There's disagreement about how the spec is interpreted, which happens a lot. (2) There is no confusion, but the implementation for the selector has been neglected or is still being revised.

If there are outlying circumstances under which `:target` should not match `location.hash`, Sizzle should not enforce behavior that may become invalid in the future.

**Comment by timmywil** [comment]
That said, we can safely say that the browsers have it wrong here, and that the spec is clear enough, we may be able to bypass qsa and rely on `location.hash` in Sizzle.

**Comment by timmywil** [comment]
Bah, I keep leaving out words. *if* we can safely say....

**Comment by dmethvin** [comment]
It seems like `:target` should be good as soon as DOMContentLoaded fires and we could do a buggyQSA test then, but it would be good to find out why the browsers currently disagree. I wonder if QSA's implementation also has problems on hashchange events?

**Comment by zzzzBov** [comment]
http://www.w3.org/TR/css3-selectors/#target-pseudo is the only spec I've found so far, searching for `:target` is a bit awkward, so finding resources about it has been challenging.

I see no reason why `:target` can't resolve to the element as soon as the element exists within the DOM. Am I missing something?

**Comment by gibson042** [comment]
@zzzzBov: I'm not disagreeing with you, and in fact expect this to be fixed by browser updates. But right now, Chrome does not cascade `:target` styles into the page until after it has loaded, and I don't want to jump the gun on them.

**Comment by zzzzBov** [comment]
I've opened bugs for [chromium][1] and [firefox][2]. We'll see where it goes from there.

[1]: https://code.google.com/p/chromium/issues/detail?id=549590
[2]: https://bugzilla.mozilla.org/show_bug.cgi?id=1220167

**Comment by bzbarsky** [comment]
I said this in the Firefox bug, but it's worth pointing out more explicitly here: in practice in Firefox (and I believe Chrome) `:target` matches the element that was last the target of an anchor scroll.  This has nothing to do with what that element's ID is right now (e.g. it could have changed after the element got scrolled to), but everything to do with the intended meaning of `:target` as originally introduced.

There are two relevant specs here: css3-selectors (which defines that `:target` matches something called "the target element" but doesn't define what that is, since that's up to the document language) and HTML, which defines what "the target element" is in an HTML document.  The latter is specified at https://html.spec.whatwg.org/multipage/browsers.html#selector-target but that specification doesn't match any browser behavior, or the initial meaning of `:target`, and is prohibitively expensive to implement anyway; servo tried that and ran into some serious issues.  See the spec issue at https://github.com/whatwg/html/issues/190 tracking that situation.

Back to the observed behavior during load, the problem with defining `:target` as "the element last scrolled to" is that now you depend on when it is the browser decides to scroll to `location.hash` during pageload.  And the answer is that "it depends, because there's no standard for that".  In Gecko, it looks to me like the scroll generally happens from at least end of parse (so `DOMContentLoaded`, though maybe there is an additional trip through the event loop somewhere in there; if people care enough I can dig in and check).  I think it can also happen before then, off some heuristics during pageload that are totally subject to change and shouldn't be relied on.

Making `:target` work reliably starting at `DOMContentLoaded` firing, if it doesn't do that already, seems like a pretty reasonable thing to do.

**Comment by bzbarsky** [comment]
Actually, there might be good reasons to not do the scroll at `DOMContentLoaded` (though again, I think Gecko always does).  The scroll should really happen when you believe your layout is stable, to avoid jumping around on the page, so if you still have stylesheets that are loading by the time `DOMContentLoaded` happens you may want to avoid doing the scroll at that point....

**Comment by gibson042** [comment]
@bzbarsky Are you saying that the element doesn't match `:target` (and therefore doesn't get updated styles) until _after_ the page actually scrolls? Given that the application of those styles could make substantial changes, you generally couldn't guarantee stable layout without them.

**Comment by bzbarsky** [comment]
@gibson042 The precise sequence of events in the `GoToAnchor` function in Gecko (which takes the value of `location.hash` as an argument) is as follows, skipping various complexity around SVG and whatnot:

1. Find the target element.
2. Set that element to be in the "url target" state, so it starts to match `:target`.
3. Try to scroll the element into view.

Trying to scroll something into view will do a best-effort attempt to update layout before doing the scroll.  Best-effort because if the layout update takes too long and the user is trying to interact with the page we will interrupt it part way through and just use whatever we got so far.

**Comment by dmethvin** [comment]
Hmmm. The [example](http://limpet.net/target.html#foo) mentioned in the whatwg ticket bothers me because of the duplicate id values. But if you instead change the id of the current target (the first LI), the CSS does not update `:target` to the next `id="foo"` either. 

So it seems that if we had a naïve implementation of `$(document.hash)` it would not match what the browsers are doing for CSS. We can either have a bug report of "Browsers don't have consistent `:target` and Sizzle doesn't normalize it" or "Sizzle doesn't report the same element for `:target` as the browser does"

**Comment by zzzzBov** [comment]
What I can't wrap my head around is why the styles and scrolling behavior should have any impact on the return value of `document.querySelector(':target')`.

It'd be like saying that I couldn't call `document.querySelector('#test')` because the CSS for that particular selector hasn't finished loading in the external stylesheet.

When I request an element from the DOM, I expect to get the element from the DOM if it's actually there. The current behavior of `:target` only being selectable when the browser feels like it makes `:target` useless from JavaScript because it's unreliable. There is no point at which I can be certain that I will get the element that I'm attempting to select. The simple solution is to never use it, which seems silly and wasteful.

**Comment by dmethvin** [comment]
> The current behavior of `:target` only being selectable when the browser feels like it makes :target useless from JavaScript because it's unreliable.

That may be true. There are other CSS selectors that aren't very useful from JavaScript such as `::before`. If you really want the element selected by `document.hash` just use that.

**Comment by zzzzBov** [comment]
> If you really want the element selected by document.hash just use that.

That's what I've had to do. It complicates compound selectors when you have to switch from something along the lines of `$('.example:target .child')` to `$('.example').filter(location.hash).find('.child')` with no good reason for the complication.

**Comment by dmethvin** [comment]
>  no good reason for the complication

The reason is that *"`:target` selects the same thing as the value of `document.hash` in JavaScript at the current instant"* does not match the semantics or implementation in browsers. So if there's a problem you'd need to get the browsers and/or the standard to change.

**Comment by zzzzBov** [comment]
> you'd need to get the browsers and/or the standard to change.

[I'm working on it](https://github.com/jquery/jquery/issues/2679#issuecomment-152548243).

**Comment by timmywil** [comment]
It sounds like we're counting on browsers to update here. I don't think we're going to apply a global fix in Sizzle, at least not for a while.

**Comment by dmethvin** [comment]
See also https://github.com/whatwg/html/issues/190

**Comment by GGFocus** [comment]
hello
