### ISSUE TITLE
JQuery 1.11.3 Memory Leak on IE8

### ISSUE THREAD

**Issue by arvstract** [jquery/jquery#2685]
Hi Guys,

We're developing a website using asp.net and JQuery v.1.11.3. It has frameset and frames (althought it is unsupported in HTML5). Our target clients use IE8 on Windows XP.

We encountered memory leak in IE8 everytime a page is being rendered by the frame element. I have also read several articles which states that there are memory leaks when using frames in IE8.

So how do I confirm it as a bug? Well first I tried our website on other browsers such as Chrome and Firefox and it seems that memory leak doesn't exists. And then I get back to IE8 and downgrading the JQuery version step by step, I started at 1.11.3, 1.11.2, 1.11.1 and then I stopped at 1.11.0, this is the most current version that the memory leak DOESNT exists.

I haven't bump yet into any articles that has the same problem that I encountered, hope you can shed a light regarding this.

Thank you and more power to the JQuery team!

**Comment by dmethvin** [comment]
For reference, this is a continuation of a  [forum post](http://forum.jquery.com/topic/jquery-v1-11-3-memory-leak#14737000006545033).  @arvstract would you be able to take a look at the diff I posted there and identify possible sources of the leak? It would help us a lot!

**Comment by arvstract** [comment]
hi Dave, to be honest I'm not that familiar on how the internal code of JQuery works so I tried reporting the bug as what I observe in my unit test and hope that the JQuery team can use this as a reference. As of now I'm currently reviewing the URL that you gave me and doing the best that I can to understand the code. And also, can you share some ideas on how I can help on isolating the code that causes the memory leak? Thank you!

**Comment by dmethvin** [comment]
@arvstract Sure, we'd love to get some help from you on this bug since you're seeing it. I mentioned [this change](https://github.com/jquery/jquery/compare/1.11.0...1.11.1#diff-7a031a0a341e84edbc03348dea967f7cL185) in the [full differences between versions](https://github.com/jquery/jquery/compare/1.11.0...1.11.1), if you put that line back does the leak go away? It may have been lost in a cherry-pick.

**Comment by dmethvin** [comment]
Looking at this a bit more I'm pretty sure we lost a few IE8 leak-plugs during the move to make support checks lazy. There should be a `div = body = container = null;` right [here](https://github.com/jquery/jquery/blob/1.11-stable/src/support.js#L54) shouldn't there? Most likely we need them in all the broken-out feature detects for [attributes](https://github.com/jquery/jquery/blob/1.11-stable/src/attributes/support.js), [manipulation](https://github.com/jquery/jquery/blob/1.11-stable/src/manipulation/support.js), [css](https://github.com/jquery/jquery/blob/1.11-stable/src/css/support.js), and [effects](https://github.com/jquery/jquery/blob/1.11-stable/src/effects/support.js), we already have them in [event](https://github.com/jquery/jquery/blob/1.11-stable/src/event/support.js) and [data](https://github.com/jquery/jquery/blob/1.11-stable/src/data/support.js).

**Comment by mzgol** [comment]
It's unrelated to making the support tests lazy, I kept all those checks in badcd1b6f301e6253405f17759c1270549a34e12. The line was removed in b96522acfe2808e5fc3397a620db8845f6987680 by @gibson042, @markelog claimed in https://github.com/jquery/jquery/pull/1518#discussion_r9860193 this bug existed only in unpatched IE6 versions. Was that false?

**Comment by dmethvin** [comment]
I'm not sure ... I see [I was summoned](https://github.com/jquery/jquery/pull/1518#discussion_r9860193) but didn't answer, sorry. 

There is a bug with IE6 SP1 that caused a memory leak with event handlers that was fixed with IE6 SP2 (in 2004!) and several were fixed in IE7, but there is [at least one](http://www.j15r.com/blog/2009/07/12/Memory_Leaks_in_IE8) that applies through IE8. I am not sure whether the patterns we have in there trigger the leak, but it wouldn't surprise me if it did. @markelog do you recall more about it? I mean give me a break here it's been a decade! :smile:

**Comment by markelog** [comment]
I'm not sure, but it seems, in that comment, i might have referenced [this](https://support.microsoft.com/en-us/kb/929874) update, which is 2007.

Although Microsoft [says](https://msdn.microsoft.com/en-us/library/dd361842(v=vs.85).aspx) memory issues should have been solved in IE8, [there is](http://com.hemiola.com/2009/11/23/memory-leaks-in-ie8/) evidence of resurfacing new but different leaks in it. It seems as not our case though, since assigning everything to null (as described in that article) wouldn't help.

What @arvstract is describing, sounds like an [iframe](https://support.microsoft.com/en-us/kb/2714930) issue. I couldn't find any mentions of update with which such fix was released.

But, it shouldn't have matter, because as mentioned in original discussion, if issue is present, it should leak only small amount of memory.

So unless this app is not constantly removing and adding iframes with jquery inside it should work fine. But if app, in fact, does do that, then i wouldn't advice adding this fix back in to support such unusual use case.

**Comment by markelog** [comment]
> but there is at least one that applies through IE8

Sounds not our case, since that case is about expandos

**Comment by dmethvin** [comment]
I agree, I didn't see how it could apply. At this point I think we are waiting for @arvstract to provide some more information about the case where it appears to leak.

**Comment by arvstract** [comment]
Hi @markelog , our website is composed of frameset which is structure more or less like this:

<frameset framespacing="0" border="0" frameborder="NO" cols="*" rows="60,*">
        <frame src="header.aspx" name="__topFrame" scrolling="no" noresize="noresize" />
        <frameset id="__leftFrameSetter" framespacing="0" border="0" frameborder="NO" cols="207,*">
            <frame src="navigation.aspx" name="__leftFrame" scrolling="auto" noresize="noresize" />
            <frame src="<URL's of webforms goes here>" name="__mainFrame" />
        </frameset>
    </frameset>

If you're navigating constantly, the "__mainFrame" will keep on loading pages with JQuery in it, which causes the memory to build up (but not being released) which is not existent on v1.11.0, upon "refreshing" the page the memory clears up.

If this is what you mean by "unless this app is not constantly removing and adding iframes with jquery inside it" then yes, we are constantly removing and adding iframes with jquery in it.

Hi @dmethvin , I'm truly sorry that I'm still unable to provider any information about the bug that I encounter because we have been busy fixing bugs on our website this past few days, we've decided to downgrade to JQuery v1.11.0 for now. And sorry to tell you that I still cannot guarantee yet when I can review and pinpoint on where the issue might possibly occur.

**Comment by arvstract** [comment]
Hi @markelog , our website is composed of frameset which is structure more or less like this:


    <frameset framespacing="0" border="0" frameborder="NO" cols="*" rows="60,*">
        <frame src="header.aspx" name="__topFrame" scrolling="no" noresize="noresize" />
        <frameset id="__leftFrameSetter" framespacing="0" border="0" frameborder="NO" cols="207,*">
            <frame src="navigation.aspx" name="__leftFrame" scrolling="auto" noresize="noresize" />
            <frame src="<URL's of webforms goes here>" name="__mainFrame" />
        </frameset>
    </frameset>


If you're navigating constantly, the "__mainFrame" will keep on loading pages with JQuery in it, which causes the memory to build up (but not being released) which is not existent on v1.11.0, upon "refreshing" the page the memory clears up.

If this is what you mean by "unless this app is not constantly removing and adding iframes with jquery inside it" then yes, we are constantly removing and adding iframes with jquery in it.

Hi @dmethvin , I'm truly sorry that I'm still unable to provider any information about the bug that I encounter because we have been busy fixing bugs on our website this past few days, we've decided to downgrade to JQuery v1.11.0 for now. And sorry to tell you that I still cannot guarantee yet when I can review and pinpoint on where the issue might possibly occur.

**Comment by dmethvin** [comment]
I can imagine that IE8 suffers from memory leaks in that situation because the frameset page is never unloaded and that is when the leak would be cleaned up. But it could also be that I have a vivid imagination, so that's why it would be good to get more info about it and whether putting those null assignments back solves the problem. We don't like to change code without a good test case. In a non-frameset page any leak from the support tests should be minor since they only happen once.

**Comment by markelog** [comment]
Closing for now, if you would provide more info, we can investigate further
