### ISSUE TITLE
$.map vs javascript .map

### ISSUE THREAD

**Issue by Mottie** [jquery/jquery#2690]
jQuey's `$.map` doesn't behave the same as javascript's `.map` when dealing with undefined values in an array ([demo](http://jsfiddle.net/Mottie/ta2nL65x/)):

```js
var x = [,,1,'test'];

console.log( x.map( String ) );
// returns [ undefined, undefined, "1", "test" ]

console.log( $.map( x, String ) );
// returns [ "undefined", "undefined", "1", "test" ]
```

It appears that all versions of jQuery behave in this manner. I would think that in v2.0+, jQuery would internally fall back to javascript's `.map` for arrays.

**Comment by dmethvin** [comment]
Imagine how much code this would break. What would be the benefit?

**Comment by mzgol** [comment]
At one point we might want to deprecate all those helper methods that have native equivalents & stop using them internally. After a few years we might remove them then. But that would change semantics of `jQuery.fn.map` & friends a little so not sure how feasible it is.

This particular use case sounds like an edge case to me, IMO it shouldn't break too much code (as opposed to switching parameter order for `jQuery.fn.each` that would break **everything**). But also because of it being an edge case I don't feel like we have to change it now.

**Comment by gibson042** [comment]
Not even lodash supports sparse arrays. I don't think we should start.

**Comment by dmethvin** [comment]
Plus the differences in `this` value and handling of `undefined`/`Array` returns from the callback. We depend on that behavior internally. If you want the standard JavaScript behavior just use it.
