### ISSUE TITLE
jQuery.when: explore giving .then greater precedence over .promise

### ISSUE THREAD

**Issue by timmywil** [jquery/jquery#2709]
See discussion from [this PR](https://github.com/jquery/jquery/pull/2707#discussion_r44621063). Related to #2018.

We currently have

``` js
if ( resolveValues[ i ] &&
    jQuery.isFunction( ( method = resolveValues[ i ].promise ) ) ) {

    method.call( resolveValues[ i ] )
        .progress( updateFunc( i, progressContexts, progressValues ) )
        .done( updateFunc( i, resolveContexts, resolveValues ) )
        .fail( master.reject );
} else if ( resolveValues[ i ] &&
    jQuery.isFunction( ( method = resolveValues[ i ].then ) ) ) {

    method.call(
        resolveValues[ i ],
        updateFunc( i, resolveContexts, resolveValues ),
        master.reject,
        updateFunc( i, progressContexts, progressValues )
    );
}
```

Putting `.then` before `.promise` breaks some stuff involving expected contexts and resolved values across multiple Deferreds, but handling Deferreds with `.then` might still be preferable.

**Comment by dmethvin** [comment]
This change will also prevent a Deferred from sending progress notifications to the master Deferred, but the behavior of progress events in `$.when` is [not documented]() and the behavior is of questionable use since the client's handler would need to use the context to sort out who was reporting progress. 

If this lands, the only case handled by the `.promise` check would be `.queue()`s, `.animate()` in particular. I suppose some external plugin could be using queues with `$.when` in an exotic way but a major version would be the time to break it.

**Comment by dmethvin** [comment]
Since `$.when` became more back-compatible recently, this is no longer possible I suspect. Should we close it @gibson042 ?

**Comment by gibson042** [comment]
It's targeting 4.0, in which this might be possible. I have no strong feelings about keeping this issue open.
