### ISSUE TITLE
JQuery 2.4.1 async problem

### ISSUE THREAD

**Issue by tmb-github** [jquery/jquery#2712]
This is apparently an old issue, but there's a new wrinkle. Like others have reported on various sites (e.g. StackOverflow), they will occasionally get this JQuery error message:

```Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/```

In my case, the offending code was in the JQuery 2.1.4 file:

```xhr.open( options.type, options.url, options.async; options.username, options.password );```

The relevant information at http://xhr.spec.whatwg.org/ states:

```Developers must not pass false for the async argument when the JavaScript global environment is a document environment.```

I could not find use of xhr.open in any of my own JQuery, so I looked in the JQuery source file itself. And there I found the source of the problem:

```jQuery._evalUrl = function( url ) {
    return jQuery.ajax({
        url: url,
        type: "GET",
        dataType: "script",
        async: false,
        global: false,
        "throws": true
    });
};```

Having `async` set to `false` triggers the console log error on my browsers. By changing it to `true`, the problem (i.e. the console error) disappears. Is there a reason why this is set to false when the specs say that doing so is now bad practice as the feature is being deprecated?

**Comment by gibson042** [comment]
`jQuery._evalUrl` makes synchronous requests to ensure correct sequencing of scripts embedded in HTML during evaluation of calls to [DOM manipulation functions](http://api.jquery.com/category/manipulation/). In other words, the root cause is your reliance—either direct or indirect—upon jQuery to evaluate scripts in inbound HTML. To remove the warnings, remove the scripts.

See also #2126, especially https://github.com/jquery/jquery/pull/2126#issuecomment-78273289 .
