### ISSUE TITLE
Syntax error in `selector` occurs on first event of delegated event

### ISSUE THREAD

**Issue by abozhilov** [jquery/jquery#2720]
Let me illustrate: 

````
 $('#test').delegate('span ? < blow', 'click', function() {})
````

JQuery reports a syntax error in the CSS selector not when the `delegate` is called, instead of that it reports error when the event is released.

**Comment by dmethvin** [comment]
Although `.delegate()` is on its way out, the problem also exists in `.on(event, selector, fn)` when the `selector` has a syntax error. I've changed the title to clarify that.

For standard CSS selectors (which is the most common case), jQuery never parses the `selector` string; it just passes that string on to the DOM `.matchesSelector()` method. If that fails we fall back to parsing the string in Sizzle and that is the point where we would detect the syntax error.

To give the syntax error message a the point where `.on()` or `.delegate()` is called, we'd need to make a call to use the selector, discarding the result. Since so many other errors may exist in the selector (e.g. a non-syntax typo like `"imput[type=text]"` I'm not convinced the benefit justifies the cost.

**Comment by timmywil** [comment]
I'm okay with this behavior. The up-front cost isn't worth it.

**Comment by mzgol** [comment]
I agree with @dmethvin & @timmywil.

**Comment by timmywil** [comment]
That seems like enough of a consensus to close.

**Comment by abozhilov** [comment]
@timmywil the behavior makes debugging harder and it costs nothing to fix it. You can test the selector against freshly created element. So you don't have to drop the result since the result is always empty collection. Anyway.

**Comment by scottgonzalez** [comment]
> @timmywil the behavior makes debugging harder and it costs nothing to fix it.

I feel like debugging isn't really harder. If you just created the event handler, or just changed the selector, you're likely to be testing that the functionality still works. You'll find out rather quickly whether there's a syntax error either way.

**Comment by abozhilov** [comment]
@scottgonzalez why do you advocating broken behavior? In general as early as error is reported is easier for debugging, especially when we talk about syntax errors.

**Comment by timmywil** [comment]
@abozhilov It's not broken behavior. It's a broken selector. This is moot if the selector is valid. It takes actually using the selector to find out if it's invalid, but there's functionally no reason to use it until an element needs to be checked. Yes, it takes longer to realize the selector is invalid, but you find out pretty quickly when you try to use it.

**Comment by dmethvin** [comment]
As soon as you run any unit or integration tests you should see the problem, that is pretty early. If there are no tests it would be a problem that your RUM telemetry could catch since it's an outright thrown error.

**Comment by abozhilov** [comment]
@dmethvin No! All of you missing the entire point. With broken selector the entire app **must not** work. Now there is nothing about the `delegate` in the stack trace. Image if you have to debug the code of someone else who missed to test that part or made some typo? What will you do, find in files? It does not cost anything to fix the issue, but you prefer complicated debugging, right?

**Comment by dmethvin** [comment]
> It does not cost anything to fix the issue

You keep saying that. A zero cost implies we don't need to change anything. Have you modified your copy of jQuery locally to fix it? Can we see your solution?

>  Image if you have to debug the code of someone else who missed to test that part or made some typo? What will you do, find in files?

Sure, why not? The console has the erroneous selector. 
![capture](https://cloud.githubusercontent.com/assets/157858/11212988/6f3c8648-8d07-11e5-9b1a-2375fb06d441.PNG)
If the problem was caused by a recent change to the code base you can further reduce the possible cause by looking at a diff.
