### ISSUE TITLE
Nodes created by src/css/support.js can break the DOM in some PhantomJS environments.

### ISSUE THREAD

**Issue by supernintendo** [jquery/jquery#2741]
jQuery inserts a [`div`](https://github.com/jquery/jquery/blob/487d5ca913c237aafe9efa1179749b46382fddbf/src/css/support.js#L10) into the DOM on page load which is appended to `html`. This element is subsequently removed but the DOM is in an invalid state in the interim since `div` tags are not valid outside of the `body`. This is an issue for web crawlers using PhantomJS as the results of the html may be recorded before the element has been removed, resulting in broken html.

We are experiencing this issue with our single page app at https://househappy.org. When a crawler visits the site, PhantomJS loads the requested page and served the generated html to the crawler. To reproduce, spoof your user agent string to `Googlebot/2.1 (+http://www.googlebot.com/bot.html)` and visit the site. Using your browser's developer tools to inspect the DOM, you can see that all of the tags (`meta` et. al) that belong in the `head` are nested within the `body`. Looking at the source, we can see the culprit is a rogue `div` inserted after `html`. Using `MutationObserver` and `debugger`, I have pinpointed it to the `div` appended by jQuery.

Appending it to the `body` will not maintain compatibility with all environments (in my tests, `body` doesn't always exist when this element is appended). Most crawlers allow you to blacklist elements by selector but I have not had luck in this case (`html > div` should work, but doesn't?). My suggestion is to add a discrete selector to this element to allow it to be easily blacklisted. I am thinking of submitting a PR to address this issue, using a data attribute as a selector (supported by PhantomJS as well as IE7+, avoids collisions with IDs / classes that may be in the wild).

Let me know if you have any thoughts (or if this issue is even worth addressing).

**Comment by gibson042** [comment]
Can you provide more information about the versions of jQuery and PhantomJS you are using, and your process? This statement strikes me as suspect:
> the results of the html may be recorded before the element has been removed

Especially since `computeStyleTests` (the function that adds and immediately removes the div) should only run when a relevant support property is needed, which is quite a strange time to snapshot the DOM. But that's exactly what you seem to be doing:
```sh
$ curl --silent --location \
    --user-agent 'Googlebot/2.1 (+http://www.googlebot.com/bot.html)' \
    https://househappy.org | \
    sed 's/></>\n</g; 3q'
<!DOCTYPE html>
<html style="" class=" js no-flexbox flexboxlegacy canvas canvastext no-webgl touch no-geolocation postmessage websqldatabase no-indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms no-csstransforms3d csstransitions fontface generatedcontent no-video no-audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths">
<div style="position: absolute; left: 0px; width: 100%; ">
</div>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
```

**Comment by mzgol** [comment]
The reason why we moved from attaching test nodes to `body` to `documentElement` is that the former doesn't always exist and the only reliable way to wait for `body` that we have is to wait for document ready. We used to do it before 2.1 but the problem is that then putting your jQuery scripts at the end of the body is not enough, you need to wait for document ready as well; otherwise your code would execute before all the support tests are computed, leading to bugs like http://bugs.jquery.com/ticket/14084.

Now, as for @gibson042 mentioned, since the node is attached & removed synchronously it seems unlikely to get the DOM snapshot in the middle of performing the test... Unless one of them breaks in your PhantomJS for some reason and leaves the DOM in unstable state.

**Comment by supernintendo** [comment]
@gibson042 This was reproduced with jQuery 2.1.4 and PhantomJS 2.0.0. Our Nginx rules catch requests with a specific user agent string (`Googlebot/2.1 (+http://www.googlebot.com/bot.html)`) and proxy-pass to an Express server which loads the page using PhantomJS, responding with the generated HTML. `computeStyleTests` may be getting called as a result of (https://github.com/zurb/foundation-sites)[ZURB Foundation], which is the only part of the application that executes JS on load which would need CSS support properties.

Based on these comments, I believe the test is breaking in PhantomJS causing the element to hang around. Right now I'm trying to remove the element before PhantomJS returns the generated HTML, but I'm unable to select it (I'm pretty sure this is a limitation of PhantomJS). My fork adds a selector (`[data-element="jquery-css-support"]`) to the element which should allow me to select it and remove it (working on this now, I'll update with results).

**Comment by supernintendo** [comment]
After discussing this here I consider this an edge case. Closing this out to try deal with the PhantomJS side of this issue. Thanks.
