### ISSUE TITLE
myForm.trigger('submit') when form contains an element named "submit"

### ISSUE THREAD

**Issue by Ultimater** [jquery/jquery#2755]
If you try to do something like: `<input type="submit" name="submit">`
(I see coders doing this all the time, they're unoriginal and can't think of a better name for a submit button than "submit" so bare with me, I think it would be good to address such users)

Then when calling `myForm.trigger('submit')` for the form which contains this element, it will fail to submit in the same way which `myForm.submit()` fails since it will reference the element rather than the submit function of the form. I believe jQuery should add a check when dealing with "submit" to verify it's indeed a function before calling it. If not, you can still submit the form by grabbing a copy of the function by creating a new form dynamically, grabbing its submit method, then sending the form we want to submit through this function:
`document.createElement('form').submit.call(myForm)`
We could also try to do something like `myForm.constructor.prototype.submit`... but then they might have an element named "constructor" in their form resulting in the same sort of issue. So I believe creating an element for it would be a good solution to grab the submit method and apply it to the function we wish to submit.

**Comment by markelog** [comment]
See http://api.jquery.com/submit/ 

> Forms and their child elements should not use input names or ids that conflict with properties of a form, such as submit, length, or method. Name conflicts can cause confusing failures. For a complete list of rules and to check your markup for these problems, see DOMLint.

**Comment by dmethvin** [comment]
@Ultimater In the times that we've tried this in the past we could not find a solution that was supported in all browsers. The reason the documentation exists is that this has been a problem since the beginning of jQuery, since it's basically not a jQuery problem: https://bugs.jquery.com/ticket/1414

It's possible that the set of newer browsers supported in our 3.0 release are consistent enough to use the trick suggested in that ticket (using the `submit` method from a created `form` and applying it to the form you want to submit). However this affects essentially every important property aliased as a method so there may be many other situations like that in the code base. If you'd like to do some research and report back, maybe it could be solved now when it was impossible before.
