### ISSUE TITLE
Parsing URL

### ISSUE THREAD

**Issue by Fanda36** [jquery/jquery#2770]
Hi,

 I have this code for parsing URL and I maybe found bug.

```
var url = window.location.href;
var a = $('<a>', {
	href: url
})[0];
```

Chrome, Firefox ... have in _a.pathname -> "/user/activity"_

IE have in _a.pathname -> "user/activity"_ (without "/" on start)

**Comment by mzgol** [comment]
Your test case only uses jQuery to construct an element but otherwise doesn't have much to do with jQuery. jQuery doesn't expose pathnames of URLs and you're accessing raw DOM properties.

IE (even 11) is just parsing URLs differently than other browsers. This has been fixed in Edge. See http://jsfiddle.net/51qfxp1w/ for an example using pure JavaScript.
