### ISSUE TITLE
clone() method doesn't work as expected when cloning a textarea on Chrome 47 and IE 11

### ISSUE THREAD

**Issue by jddxf** [jquery/jquery#2776]
According to the api documentation, user data typed into textarea is not copied.
But it does copy the user data on Chrome 47 and IE 11.
Here is a demo http://jsfiddle.net/scatterbrained/770dk4ue/2/

**Comment by Manoj-Roy** [comment]
Print textarea value into it ..
<div></div>

use it :
$(function() {
  var $t = $("<textarea>hello</textarea>");
  $t.val("hi");
  console.log($t);
  console.log($t.val());

  var $copy = $t.clone();
  $('div').html($copy);
  console.log($copy.html());
  console.log($copy.val());
});

**Comment by Manoj-Roy** [comment]
http://jsfiddle.net/manoj_roy/ct48q3ez/2/

I hope it will help you ..

**Comment by jddxf** [comment]
@Manoj-Roy You didn't get me.Your jsfiddle is expected to print "hello" as "hi" wouldn't be copied according to the api documentation of clone().However, it prints "hi" on IE 11 and Chrome 47

**Comment by dmethvin** [comment]
What the docs are trying to say is that jQuery doesn't attempt to change the cloned content of `textarea`s because that could be expensive for large DOMs. If you are cloning something that the user has edited you can either restore the default or copy the current edited state. I don't think we want to try and normalize this, but we could clarify it in the docs.

There is a Firefox bug for this opened in 2004 but it doesn't seem to be getting love: https://bugzilla.mozilla.org/show_bug.cgi?id=230307

/cc @miketaylr

**Comment by timmywil** [comment]
This was a misunderstanding of the docs, but I think the docs are clear enough for the most part. Closing this as there's no change to be made in core.
