### ISSUE TITLE
undefine jquery in AMD environment when noConflict is called 

### ISSUE THREAD

**Issue by chinchang** [jquery/jquery#2784]
Hi

**Scenario:**

An app is using requireJS for dependency management. Also its using a nonAMD jquery plugin that needs `jQuery` on window to work which it specifies as dependency in the requireJS config. The app has a tracking script (say crazyegg) installed too that loads its own jquery, but in noconflict mode.

**Issue:**

Reduced testcase demo: http://plnkr.co/edit/6nxWaGnRHo6xRTiGQQBq?p=preview
- The tracking script loads and executes. It registers "jquery" with requireJS but no `jQuery` or `$` on window is put as its in noconflict mode. All good.
- requireJS loads our jquery plugin. But since it has a dependency on *jquery*, it tries to load *jquery* first.
- But requireJS already has a *jquery* registered with it (which tracking script did) and so it does nothing. No additional jquery is loaded (which should have).
- Now the plugin is loaded and since it expected `jQuery` on window and its not there, it breaks.

**Solutions:**

- `noConflict` method should also unregister *jquery* in the AMD environment. Makes sense because noconflict is meant to remove any traces that the jquery library leaves on the website environment its loaded on.

OR

- Give another method for AMD noConflict which users can call separately.

If the jquery team agrees on either approach, I can take this issue up.

**Comment by timmywil** [comment]
Thank you for opening an issue, but the current behavior is correct. It happens a little differently than you think, tho. jQuery should never be loaded twice. requirejs doesn't try to load another jQuery because one has already been loaded and is still registered as a usable module. The problem has nothing to do with requirejs or AMD. The problem is that you have a plugin that requires a global, but `.noConflict()` was called and it removed the globals. Either adjust the plugin to work with AMD, adjust the tracking script to not run in `noConflict` mode, or, if you have no control over the tracking script source, add back the globals after `noConflict` is called.
