### ISSUE TITLE
Deprecate jQuery.parseJSON

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#2800]
`jQuery.parseJSON` was needed for IE<8 & Android 2.3, apart from that it was kept on both branches mostly so that we're API-compatible between them. Those reasons are no longer valid on `master` so IMO we should deprecate this method and switch all internal uses to `JSON.parse`. We could then remove it in 4.0.

**Comment by gibson042** [comment]
I'm in favor.

**Comment by timmywil** [comment]
+1

**Comment by jaubourg** [comment]
Makes sense: +1.

**Comment by markelog** [comment]
Yepsies

**Comment by markelog** [comment]
Only one concern, if `JSON.parse` would have a bad implementation in some browser (line in Android 2.3 but not really), will not be able to fix.

But it seems pretty improbable

**Comment by dmethvin** [comment]
:+1: 
I think it makes sense to nudge people towards native methods when we have nothing to add. We can add a warning/shim in Migrate for this. If there is a bad or missing `JSON.parse` implementation in some environment people can always shim it or use an older version of jQuery.

**Comment by mgol** [comment]
Assigning to myself.

**Comment by mgol** [comment]
BTW, I don't think we have to wait for 4.0.0, I'd like to do it for 3.1.0 (semver requires bumping only a minor to deprecate and IMO we should follow that).

**Comment by mgol** [comment]
PR: #2948. Let's do it for 3.0.0 (later on we can't move stuff to `src/deprecated.js` as they'd be excluded from the slim build).

**Comment by gibson042** [comment]
> later on we can't move stuff to `src/deprecated.js` as they'd be excluded from the slim build

I don't believe this is true. [Semver dictates](http://semver.org/#how-should-i-handle-deprecating-functionality) that deprecation is a minor version bump, so in our case it might mean that the slim build is more volatile than the full build (which arguably makes sense, since it is explicitly excluding functionality). I think it would be perfectly acceptable to e.g. [deprecate `jQuery.isNumeric`](https://github.com/jquery/jquery/issues/2781#issuecomment-165923869) in jQuery 3.1.0, resulting in its immediate removal from a slim build. Alternatively, we could include deprecated functionality in them (which probably makes more sense now that we're adhering to semver).

All that said, of course, I'm fine with deprecating `jQuery.parseJSON` in 3.0.0.
