### ISSUE TITLE
not()/filter() methods behaves inconsistently for text and comment nodes 

### ISSUE THREAD

**Issue by ballast67** [jquery/jquery#2803]
***On all jQuery version as i can test it***

Thread on Stackoverflow: http://stackoverflow.com/questions/34593399/triple-negation-needed-to-retrieve-text-node

Using `not()` method for elements with nodeType different than 1 gives inconsistent result.
You can check it on [jsFiddle](https://jsfiddle.net/m62syb56/).

e.g  with markup `<div>text node <b>and b element</b></div>`:

```javascript
//returns only <b> element in set
set = $('div').contents().filter(':not(:has(fake), div)'); 
//returns text node and <b> element in set
set = $('div').contents().not(':has(fake), div'); 
```

*I would expect both methods regarding pasted selector to behave the same.*

It seems to be related to not filtering out elements by their nodeType while using complex selector passed to `not()` method but not for `filter()` method where result seems consistent. [Martijn](http://stackoverflow.com/users/951064/martijn) has suggested this edit in internal `winnow()` method:

```javascript
// Implement the identical functionality for filter and not
function winnow( elements, qualifier, not ) {
    //...

    return jQuery.grep( elements, function( elem ) {
        // added comment >>For consistency between filter and not, check for nodeType too<<
        return elem.nodeType === 1 && ( jQuery.inArray( elem, qualifier ) >= 0 ) !== not;
    });
}
```

jQuery (most) methods are designed to work on DOM nodes so i'm not sure this can be qualified as bug.

**Comment by dmethvin** [comment]
> jQuery (most) methods are designed to work on DOM nodes so i'm not sure this can be qualified as bug.

That's the gist of it. Although it's possible to get a text or comment node into a collection via `$()` or the `.contents()` method or by forcing one into the collection with `.add()`, very few methods are designed to do anything with them.

> Please note that although you can pass text nodes and comment nodes into a jQuery collection this way, most operations don't support them. The few that do will have an explicit note on their API documentation page. -- http://api.jquery.com/jQuery/

> The .contents() and .children() methods are similar, except that the former includes text nodes and comment nodes as well as HTML elements in the resulting jQuery object. Please note that most jQuery operations don't support text nodes and comment nodes. The few that do will have an explicit note on their API documentation page. -- http://api.jquery.com/contents/

If you can think of a better place to put this information so people don't try to manipulate text and comment nodes, you could submit a pull request to https://github.com/jquery/api.jquery.com. I did notice that one of the SO answers was from someone who saw that in the docs, so it can be found.

That SO answer also suggests the inconsistency "could be solved by explicitly only ever returning nodeType 1 nodes from the winnow function" so that's a code change we could consider to ensure that text/comment nodes are more consistently wiped from collections.

**Comment by timmywil** [comment]
Closing this issue as a dup of gh-2808, as that one as a PR pointing to it.
