### ISSUE TITLE
IE10 close after require jquery/tinyMCE

### ISSUE THREAD

**Issue by PetrBorisov** [jquery/jquery#2838]
IE10
if page have element with empty 'name' attribute
then after require jquery/tinyMCE  browser close with error
examples:
https://jsfiddle.net/psborisov/xc8eub9b/
https://jsfiddle.net/psborisov/4grfkvpr/

i try also few js libraries, all working good

**Comment by dmethvin** [comment]
Can you link to the TinyMCE bug report for this?

**Comment by timmywil** [comment]
Thanks for opening an issue, but I just checked IE10 (with URL https://jsfiddle.net/psborisov/4grfkvpr/show/ to ensure it's not a jsfiddle issue) and that worked for me. It looks like the crash only happens when trying to edit with jsfiddle. The only way I see to figure out the cause is to keep taking out/adding back code to narrow down what is causing the crash. It is not jQuery alone. It is the combination of jsfiddle and jQuery/tinyMCE, which means jsfiddle is doing something in combination with these libraries that IE10 doesn't like. Unfortunately, I don't think any of our team members have time to figure out what jsfiddle is doing. If this does turn out to be an issue with jQuery, we would welcome a patch.

**Comment by PetrBorisov** [comment]
link for tinyMCE bug report: 
https://github.com/tinymce/tinymce/issues/2631
