### ISSUE TITLE
IE10 crashes after require jQuery.

### ISSUE THREAD

**Issue by cmoneverybody** [jquery/jquery#2844]
Hello.
Your product - it's a best js library, widely used in developing.
Recently problem has been discovered, similar to this: https://github.com/jquery/jquery/issues/2838.
If you connect the jQuery library using requireJS, IE10 browser crashes with an error.
Below is the full source code and screenshots of the error.
source: https://raw.githubusercontent.com/cmoneverybody/test/master/scr1.png
IE version: https://raw.githubusercontent.com/cmoneverybody/test/master/scr2.png
error: https://raw.githubusercontent.com/cmoneverybody/test/master/scr3.png
repository: https://github.com/cmoneverybody/test/tree/master

**Comment by cmoneverybody** [comment]
I forgot to add: The problem occurs only if there is an element on the page with a blank tag.

**Comment by gibson042** [comment]
Thanks for the bug report! I have confirmed the crash, and it appears to be caused by calling `document.getElementsByName` against a document containing elements with an empty name attribute. Note that your document is **not** valid HTML, and in particular that a) `name` is not a valid attribute on [div elements](https://html.spec.whatwg.org/multipage/semantics.html#the-div-element), and b) the `name` attribute on form controls [must not be empty](https://html.spec.whatwg.org/multipage/forms.html#naming-form-controls:-the-name-attribute).

It doesn't look like there's anything we can do.
