### ISSUE TITLE
.hover() throws error in jQuery 2.2.0 where jQuery 2.1.4 worked fine

### ISSUE THREAD

**Issue by efrancis** [jquery/jquery#2851]
When declaring hover events with functions that will be declared later as properties of an object, jQuery 2.2.0 fails where version 2.1.4 and lower worked fine.

Example:

        var controls = {};
        $('#button').hover(controls.bOver, controls.bOut);
        
        controls.bOver = function() {
                $(this).css('background-color', 'red');
        };
        
        controls.bOut = function() {
                $(this).css('background-color', '#00bbff');
        };

If the declarations of controls.bOver and controls.bOut are moved to the top of the script it works. Or if hover is replaced by mouseenter and mouseleave separately, without moving the declarations, it works as well.

The example above also works fine with jQuery versions below 2.2.0, without changing anything.

P.S.: It looks like this happens in Chrome, but not in Firefox.

**Comment by all3fox** [comment]
Please take a look [at this jsfiddle](https://jsfiddle.net/5j7Laefj/) for jQuery 2.1.4

It seems to *not* work, contrary to what you are saying, on Firefox 43.0.4.

However, if you move function declarations above the call to `.hover()`, it works.

**Comment by dmethvin** [comment]
The one line there is equivalent to `$('#button').hover(undefined, undefined);` since the two properties are defined *after* the call. jQuery 2.1.4 silently does nothing with that, but jQuery 2.2.0 throws an error. Since there seems to be a lot of code out there that expects to be able to attach undefined event handlers we added this behavior back, see #2812. Not sure when 2.2.1 is coming out but it should be in the next few weeks.
