### ISSUE TITLE
When you call the $ .fn.trigger, the value of event.currentTarget is changed by the timing.

### ISSUE THREAD

**Issue by nazomikan** [jquery/jquery#2858]
Is this a correct behavior? (v2.x and v1.10.x)

https://jsfiddle.net/nazomikan/qbq65w89/

1:
Enter a value
I press the ok button
Confirm the currentTarget (in console)

2:
Enter a value
Inserted the Enter
Confirm the currentTarget (in console)

1-result:
```html
<button id = "ok"> </ button>
<button id = "ok"> </ button>
```

2-result:
```html
<button id = "ok"> </ button>
#document
```

**Comment by dmethvin** [comment]
All the handlers called during a specific event occurrence share the same `event` object, for example during the bubbling phase. That's why you see a change in the `currentTarget` property. Creating a fully independent deep copy of the `event` object per handler in order to avoid this would be incredibly expensive.

The `event` object should only be accessed during the period the event handler is called. If you need values from the object, save them in your own variables rather than holding a reference to the entire object. In some browsers such as IE8, [the native `event` object ceases to exist](https://bugs.jquery.com/ticket/7278), so code like that example which tries to access it in a `setTimeout` would throw an error.
