### ISSUE TITLE
<tbody> element is no longer getting added for you

### ISSUE THREAD

**Issue by fdlk** [jquery/jquery#2861]
#1835 (Don't auto-insert tbody?) no longer inserts the `<tbody>` element if you don't. One consequence is that this breaks bootstrap layout of tables in modern browsers if you relied on jquery adding the tbody element for you.

* See https://jsfiddle.net/9cj9pr0j/2/ for a demonstration

I've tried Firefox 41.0.2, Safari Version 9.0.2 (11601.3.9), and Chrome Version 47.0.2526.111 and the top table is broken in all three:

<img width="511" alt="screen shot 2016-01-23 at 21 06 07" src="https://cloud.githubusercontent.com/assets/1523838/12532469/3e688f88-c215-11e5-8279-43e00982cdfc.png">

* See https://jsfiddle.net/n3xg1vsd/2/ for a demonstration that this used to work fine in jquery 2.1.0

**Comment by timmywil** [comment]
Thanks for opening an issue. The reason for auto-inserting a `tbody` wasn't because we thought there should be a `tbody` element, but that old IE required it for manipulation with tables to work at all. Given that all of the currently supported browsers do not require a tbody in table elements, we thought it better that users add `tbody` elements when they actually need it.

Nevertheless, this does mean that while we want to keep this behavior for jQuery 3.0, we should probably have the same behavior in 2.2 that we have in 1.12.

**Comment by timmywil** [comment]
Fixed in 2.2-upstream.
