### ISSUE TITLE
JSDOM $.event.trigger does not trigger keyboard events

### ISSUE THREAD

**Issue by lsphillips** [jquery/jquery#2872]
Hello,

It would seem when working with JSDOM I am unable to trigger keyboard events:

```
$(document).keydown(
{
     key : 'Escape'
});
```

However I can trigger by using `EventTarget.dispatchEvent`:

```
document.dispatchEvent(
   new window.KeyboardEvent('keydown',
   {
      key : 'Escape'
   })
);
```

Furthermore I can trigger mouse events like `$(document).click()`.

My JSDOM setup is as followed:

```
var doc = jsdom.jsdom('<html><body></body></html>');

global.doc = doc;
global.window = doc.defaultView;
global.navigator = doc.defaultView.navigator;
global.$ = jQuery(doc.defaultView);
```

I get this issue when running JSDOM v7.2.2 with jQuery v2.2.0 in Node v5.0.0. I hope this isn't me missing something simple!

Thanks!

**Comment by dmethvin** [comment]
The first jQuery example is passing `{ key: 'Escape' }` as the `eventData` argument when triggering, [as documented](https://api.jquery.com/keydown/). That is not the same as constructing a `KeyboardEvent` and setting the `key` argument in the resulting `event` object.

In general it is a good idea to avoid `.keydown` and other shortcut methods if you need to set event data. Instead, create a `jQuery.Event` with the data you want and trigger it via either `.trigger` or `.triggerHandler`.

The code snippets there aren't showing how you're using the triggered event so it's not clear what you mean by "does not trigger keyboard events". A keydown event should be happening even in the first case but probably don't contain the data you expect due to the error I mentioned above.

**Comment by lsphillips** [comment]
Hello,

Sorry, yes that was an error, but the issue still stands. Here is an example, I have rendered a React component into a JSDOM document, this component registers this event handler:

```
document.addEventListener('keydown', function (event)
{
   console.log(event.key);
});
```

I then want to test this, and my first attempt actually was to use `.trigger()` like so:

```
$(document).trigger(
   $.Event('keydown', { key : 'Escape' })
);
```

The event does not trigger the keydown event, I see nothing in my console.

However when I do this:

```
document.dispatchEvent(
   new window.KeyboardEvent('keydown', { key : 'Escape' })
);
```

It triggers and I see some output in my console.

I'm wondering if the issue is that i'm not using jQuery to bind the event handler to the document, however when I triggered a click event the same in a different scenario it trigger the click event.

The full test example:

```
it('does something', function ()
{
      // Setup.
      var doc = jsdom.jsdom( '<html><body></body></html>');

      global.document  = doc;
      global.window    = doc.defaultView;
      global.navigator = doc.defaultView.navigator;
      global.$         = jQuery(doc.defaultView);

      // Render.
      var container = document.createElement('div');
      document.documentElement.appendChild(container);
      reactDOM.render(
            react.createElement(MyComponent), container
      );

      // Act.
      // Does not work.
      $(document).trigger(
          $.Event('keydown', { key : 'Escape' })
      );
      
      // Act.
      // Works.
      document.dispatchEvent(
            new window.KeyboardEvent('keydown', { key : 'Escape'  })
      );
});
```

Thanks.

**Comment by dmethvin** [comment]
> I'm wondering if the issue is that i'm not using jQuery to register the event handler, 

Yes, in general if you use DOM `.addEventListener` you should use DOM `.dispatchEvent`, since they are at the same API level. jQuery's `.trigger` method runs handlers attached by jQuery, but listens for DOM events.

> however when I triggered a click event using jQuery it executes handlers that I registered using React.

I don't see the code so I can't say for sure whether that's expected or not. If it was using an `onclick` attribute on the element then that would be expected because jQuery looks for those.

**Comment by lsphillips** [comment]
Hello,

That makes sense. The triggering of events that was registered by React lead me to believe jQuery was doing something else under the hood, however it was just a side effect of React's implementation.

Closing as it's not an issue.

Thanks!
