### ISSUE TITLE
Update npm dependencies

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#2877]
Many of our dependencies got pretty out of date; it's time to bump them.

**Comment by mgol** [comment]
@leobalter @gibson042 I wanted to update QUnit to the latest 1.20.0 as well but I only managed to use 1.18.0; versions 1.19.0 & 1.20.0 are introducing race conditions to our tests, making a few of them fail randomly on every full test run. Could you have a look? I'm seeing things like:
<img width="426" alt="screen shot 2016-01-27 at 12 41 59" src="https://cloud.githubusercontent.com/assets/1758366/12612771/749211b4-c4f5-11e5-9c28-cac84693656e.png">
<img width="487" alt="screen shot 2016-01-27 at 12 42 26" src="https://cloud.githubusercontent.com/assets/1758366/12612770/74919aa4-c4f5-11e5-99d1-5f34022708ff.png">

**Comment by gibson042** [comment]
Hmmm, are you sure they're race conditions? Because it looks to me like the kind of thing that would pop up in response to _other_ failures, and ultimately stems from the test results HTML appearing in the very document being used as a test fixture. I've thought about this before and never really come to a good approach, but I think the best way is leveraging `supportjQuery`. So for assertions that rely upon document context, e.g. [selector: child and adjacent: All Grandchildren](https://github.com/jquery/jquery/blob/a268f5225cad9ab380494e61a10105cc9eb107e7/test/unit/selector.js#L112), we can do something like
```js
assert.deepEqual(
	supportjQuery( jQuery( "p > * > *" ) ).filter( "#qunit-fixture *" ).get(),
	q( "anchor1", "anchor2" ),
	"All Grandchildren"
);
```

**Comment by mgol** [comment]
There are only a few failures like that but they have to start somewhere, don't they? Something had to have changed in QUnit 1.19.0.

**Comment by gibson042** [comment]
But I'm pretty sure that what changed is the output format. jQuery's broad selection is picking up new elements from the QUnit HTML reporter.
