### ISSUE TITLE
Consider emitting named event when DOM manipulations occur.

### ISSUE THREAD

**Issue by afreidz** [jquery/jquery#2879]
My apologies if this is not the proper forum to submit a potential feature request.  Older browsers do not support some/all of the mutation events.  It would be helpful if jQuery core emitted an event when the DOM has been manipulated.  That way we can subscribe to that event and react to dom structures being added/removed.  This might be similar to the functionality of `$.fn.live` which was deprecated.  So I also understand if there are performance concerns related to this. Thoughts?

**Comment by timmywil** [comment]
Thank you for opening an issue, but even if we wanted to add support for this (I think it should remain as a [plugin](https://github.com/kapetan/jquery-observe)), we are limited by our support of IE9-10 and Android 4.3, which [don't have support for mutation observers](http://caniuse.com/#feat=mutationobserver). Also, `.live` was for event delegation. The reason it was deprecated was because it was usually unnecessary to add event handlers that checked elements all the way up to the `document`. The scope could almost always be limited, hence the switch to `.delegate`, which later could be handled by the now recommended method `.on()`. In other words, no features were lost in the deprecation of `.live`.

**Comment by mgol** [comment]
I've understood it as a request to fire events for DOM manipulation done by
jQuery, for apps that do it all via jQuery so that MutationObserver support
is not necessary. It might be nice as a plugin but there would still have
to be hooks inside of jQuery to make it possible.

**Comment by dmethvin** [comment]
See #2088 and #1736, and the new `jQuery.htmlPrefilter` from gh-2203 might be somewhat related depending on what you're trying to do.

**Comment by afreidz** [comment]
here is my use-case:
i hate pecking around looking for the javascript block that binds things to a particular DOM structure.  It would be nice to use a hard-coded name in a data attribute to relate to a corresponding block of javascript.  so i started developing some code to do so:

DOM:
```
<div id="somethingCool" class="container" data-dom-module="Something-Cool">
    ...
</div>
```
then i wrote some javascript that would fire a callback when it encountered DOM structures with that particular data-attribute:

```
var DOMModule = {};

DOMModule.register = function(name, callback){
    // on page-load, and dom-manip, check to see if the new DOM 
    // has a data-attribute that matches the name parameter
    // if so, "call" the callback
}; 
```
its then possible to link a block of code to the corresponding DOM from above like so:
```
DOMModule.register('Something-Cool', function(){
    alert('a cool dom module was found!');
});
```

the trouble is the ` // on page-load, and dom-manip...` part.  i am able to handle the page-load, but i need some way of asynchronously re-checking as the dom is manipulated post-page-load.  the direction i was heading is by doing a sort of pub/sub with dom manip.  publishing via jquery when dom structures change, and subscribing in the `DOMModule.register` block to asynchronously fire the callback as `data-dom-module`'s are added.

**Comment by afreidz** [comment]
@timmywil thanks for the link to the plugin.  that should help my use case.  the more i thought about it, the more i thought support for mutation observers in older browsers could be something jquery could provide.  but i understand if you would rather keep this as a plugin.  

thanks!

**Comment by dmethvin** [comment]
@afreidz It sounds like you may be trying to do something like [custom elements](http://www.html5rocks.com/en/tutorials/webcomponents/customelements/). If that's what you want I'd definitely recommend trying to use those emerging standards (with shims if needed) or try [Polymer](https://www.polymer-project.org/1.0/docs/start/quick-tour.html) rather than rolling your own implementation.

**Comment by afreidz** [comment]
@dmethvin ... yea i probably should just do that. i always like going thru the process of rolling my own implementation first. that way my choices are truely need-driven rather than popularity-driven. but seems like im running into that "need" ... this was more for developer happiness anyway (as opposed to business need) so polymer may be a bit heavy-handed. anyway, thanks for the suggestions @all!
