### ISSUE TITLE
siblings bug

### ISSUE THREAD

**Issue by dtgxxk** [jquery/jquery#2907]
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript" src="/jquery/jquery.js"></script>
</head>

<body>
  <div>

          <p>
              <input id="name1">
              <span><p>1</p></span>
              <span><p>2</p></span>
              <span><p>3</p></span>
              <span><p>4</p></span>
          </p>

          <div>
              <input id="name2">
              <span><p>1</p></span>
              <span><p>2</p></span>
              <span><p>3</p></span>
              <span><p>4</p></span>
          </div>

</div>

         alert($("#name1").siblings("span").length);
         alert($("#name2").siblings("span").length);

</body>
</html>

**Comment by gibson042** [comment]
It's not clear without a live test case demonstrating what you expected and what you observed, but I'd guess that invalid HTML, rather than jQuery, is at fault. [`<p>` elements](https://html.spec.whatwg.org/multipage/semantics.html#the-p-element) are not allowed to nest, and attempts to do so will result in the closest valid ancestor node adopting them: https://jsfiddle.net/n5d564sm/

Note further that [`<span>` elements](https://html.spec.whatwg.org/multipage/semantics.html#the-span-element) are not allowed to contain `<p>` elements, either, although the consequences of violating that content model are less severe.

I'm going to close this, but feel free to follow up with a JSFiddle or other live case of your own if you believe that to be a mistake, upon which we will reconsider and possibly reopen this issue.
