### ISSUE TITLE
3.0.0-beta1: implement unhandledrejection event

### ISSUE THREAD

**Issue by dwelle** [jquery/jquery#2908]
The `jQuery.Deferred.exceptionHook` implemented in https://github.com/jquery/jquery/issues/2736 has a problem in that it's called irrespective to whether the error has been handled in a `.catch` handler, or not.

Instead, it should behave as follows:

```
// jQuery.Deferred.exceptionHook should be called
$.Deferred().resolve().then(() => {
  throw new Error('xx');
});

// jQuery.Deferred.exceptionHook should not be called
$.Deferred().resolve().then(() => {
  throw new Error('42');
}).catch(() => {});

// jQuery.Deferred.exceptionHook should be called
$.Deferred().resolve().then(() => {
  throw new Error('42');
}).catch(() => {
  throw new Error('42');
});
```

Instead of fixing `jQuery.Deferred.exceptionHook` behavior, I think it'd be best to implement [`unhandledrejection`](https://github.com/tc39/ecma262/pull/76), which is how e.g. Bluebird currently [does it](http://bluebirdjs.com/docs/api/error-management-configuration.html#global-rejection-events).

**Comment by dmethvin** [comment]
We discussed this at  length in team meetings and decided that it would add too much code and reduce performance. If you can show otherwise via a pull request we could consider it. Perhaps having a hook would allow you to implement unhandled rejections in a plugin without enlarging the code code and/or harming performance. Note for example that we [implement stack trace as a plugin](https://github.com/dmethvin/jquery-deferred-reporter) because it cuts performance in half to record the stack trace for every Deferred.

However, let me say that we have had a Promise-like `Deferred` implementation in jQuery for five years now. Given jQuery's popularity and its use by `$.ajax` I have to think it is the most widely used implementation in all of JavaScript.

In all those years I cannot ever remember anyone asking for an unhandled-rejection hook. I think that is because the most common reason people need one is when they are developing and do things like misspell a method name or try to parse invalid JSON. Before jQuery 3.0 those things throw an immediate error on the console; you say, "Oh silly me" and fix them. Now that we are Promise/A+ compliant we swallow those exceptions just like everyone else and it would be cruel to not give developers any clue about their mistakes.

The code examples above are explicitly throwing errors, which is different from implicitly thrown errors like `$.ajjjax` being undefined. Developers rarely expect to misspell things or anticipate that the JSON returned from their server may be malformed. When a thrown error is part of the API contract it is a *lot* easier for a developer to understand they need to handle it. For example, `$.ajax` rejects on cases like 404 and again we haven't received complaints about that.

**Comment by dwelle** [comment]
> In all those years I cannot ever remember anyone asking for an unhandled-rejection hook. [...] Now that we are Promise/A+ compliant we swallow those exceptions just like everyone else [...]

Yea, before 3.0 I didn't need the hook either -- and it's exactly because 3.0 is Promise/A+ compliant (and added `.catch`) that I began to think we should be given the chance to `.catch()` some errors explicitly without the `jQuery.Deferred.exceptionHook` yelling every time.

WTBS, I must agree with you that common use case is misspellings etc. which the developer, should he choose to `.catch()` his own error, would still have to guard against (e.g. by determining in the `catch` callback if the error is the one he expects or it's something truly unexpected), else it would still be swallowed.

Still, when [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) sees wider adoption and is used in conjuction with Deferreds, and `unhandledrejection` gets implemented by browsers, experienced devs might start to want that behavior even in jQuery (meaning, to be able to disable `jQuery.Deferred.exceptionHook`, explicitly `.catch()` their own errors when needed, and have `unhandledrejection` event handle the rest).

Though, what you said about creating a plugin for it, might be the best way to go (at least for now). Still, to be able to do that I'd need to have access to the pool of bound `.catch`/`.then` handlers. Didn't look into it if I can get that in jQuery 3.

**Comment by dmethvin** [comment]
> Yea, before 3.0 I didn't need the hook either -- and it's exactly because 3.0 is Promise/A+ compliant (and added .catch) that I began to think we should be given the chance to .catch() some errors explicitly without the jQuery.Deferred.exceptionHook yelling every time.

You can just remove the hook entirely or add your own that filters differently. This was meant to be a minimal default way to report errors and prevent people from tearing their hair out!

> Still, when Promise sees wider adoption and is used in conjuction with Deferreds, and unhandledrejection gets implemented by browsers, experienced devs might start to want that behavior even in jQuery (meaning, to be able to disable jQuery.Deferred.exceptionHook, explicitly .catch() their own errors when needed, and have unhandledrejection event handle the rest).

Our goal with jQuery 3.0 was to have basic Promise/A+ compatibility without bloating a library that is loaded millions of times a day. If you need different behavior you can, for example `Promise.resolve($.ajax(...)).then(...)` if you know all your platforms support native Promise or you're willing to load the 52KB minified Bluebird library.

> Though, what you said about creating a plugin for it, might be the best way to go (at least for now). Still, to be able to do that I'd need to have access to the pool of bound .catch/.then handlers. Didn't look into it if I can get that in jQuery 3 inside the exceptionHook.

Yes, it requires a bunch of extra bookkeeping that we aren't doing now. Perhaps it can be done with some more strategically placed hooks, I don't know. It definitely seemed like more than we wanted to incorporate into jQuery itself.

I'll close this ticket but if there are ways we can facilitate a better implementation without a big code or performance impact let us know.
