### ISSUE TITLE
.attr( attributeName, value ) turns attribute name to lowercase

### ISSUE THREAD

**Issue by agcolom** [jquery/jquery#2910]
It seems that when using .attr( attributeName, value ), the attributeName is turned to lowercase. This causes an issue when trying to set the viewBox attribute using jQuery. (the attribute has an upper case 'B').

Test cases: 
- setting the attribute without jQuery, using ```setAttribute```:
  - http://jsfiddle.net/jkzvquLw/4/, works as expected
- setting the attribute using jQuery and ```attr()```
  - http://jsfiddle.net/jkzvquLw/1/, doesn't work as expected, because the attribute set is ```viewbox``` (all lowercase) instead of ```viewBox```

**Comment by agcolom** [comment]
Sorry just updated the url for ```setAttribute``` to [http://jsfiddle.net/jkzvquLw/3/](http://jsfiddle.net/jkzvquLw/3/)

**Comment by mgol** [comment]
Thanks for the report. AFAIK this has always been the case. Since 1.12.0/2.2.0 we've made it more conforming to the spec, see my detailed description in this comment: https://github.com/jquery/jquery/issues/2730#issuecomment-157828916. The spec explicitly requires lowercasing the attribute name.

This description applies to HTML so we're doing the right thing but this algorithm doesn't apply to SVGs. jQuery doesn't support SVG manipulation (with rare exceptions), though, so I don't think we have to change anything here, determining current context and applying a different algorithm would be messy.

However, it seems in 3.0.0 we might just as well avoid lowercasing and let the browsers do their magic as it was mostly a problem for old IE. This would make it work automatically.

Thoughts?

P.S. @agcolom Keep in mind, though, that if you use jQuery on SVGs you'll find more & more such cases... And we're not going to support all of them. :) We're not an SVG library.

**Comment by agcolom** [comment]
@mgol yes, thanks for the info. I've just checked the list of html attributes at https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes and all appear to be lowercase. I wonder whether it might be worth adding a note in the docs?

**Comment by mgol** [comment]
We might add a note there but I wouldn't want to end up in a situation where we have explicit warnings against SVG on every other API page. :)

But I'd still want to investigate whether we may drop the lowercasing in jQuery 3.0, regardless of the lack of official SVG support here.

**Comment by dmethvin** [comment]
See #2730 for the trail of tears.

**Comment by mgol** [comment]
@dmethvin Yeah, that issue was that we were lowercasing too much. Perhaps we don't need to do it at all in 3.0.

**Comment by dmethvin** [comment]
@mgol I think that is probably right. We only lowercased in 1.x because of old IE, but couldn't remove it in 2.x for consistency? I can't recall that discussion but it seems like we should try to just remove it altogether in 3.0.

**Comment by mgol** [comment]
> I think that is probably right. We only lowercased in 1.x because of old IE, but couldn't remove it in 2.x for consistency?

Yes, I think that's exactly the case. I'll prepare a patch.

**Comment by mgol** [comment]
An issue: #2914. A PR: #2916. API issue where we can continue to dicscuss how/if we want to document it: #884.

It doesn't seem there are more actionable actions possible against this ticket here so I'm going to close it. Thanks for the investigation, @agcolom & @dmethvin!
