### ISSUE TITLE
.data() getter creates data

### ISSUE THREAD

**Issue by prontiol** [jquery/jquery#2919]
Not sure, if this is intended, but calling `.data()` without arguments creates data object for the given node.
```
> $.hasData($div)
false
> $($div).data()
Object {}
> $.hasData($div)
true

**Comment by dmethvin** [comment]
Yes, it's intended. The only way the method can give you a data object attached to the element is to make one if it's not there. That's why there's `.hasData` to let you check if there's one already.

**Comment by dmethvin** [comment]
Also, the docs mention this: http://api.jquery.com/jquery.hasdata/

**Comment by prontiol** [comment]
Well, docs for `.hasData()` also say: 
> If no data is associated with an element (there is no data object at all or the data object is empty), the method returns false;

But in the test case I provided `.hasData()` returns `true` for an empty object.

**Comment by gibson042** [comment]
Agreed; this is legitimate: https://jsfiddle.net/d6t7mm5w/

**Comment by dmethvin** [comment]
The code is behaving the way we'd want it to though, correct? The docs are wrong.

**Comment by prontiol** [comment]
But why getter does actually create data object? What's the reason?

**Comment by dmethvin** [comment]
Because the `.data()` with no args is defined to return the data object. If one isn't there, it creates one, attaches it to the element, and returns that new empty object.

Ten years ago, the API could have been defined to return `null` or `undefined` for an element with no data and you would have needed to set a new data item explicitly. That's not the way it was defined though, and lots of code no doubt depends on that behavior now. The assumption was that if you were trying to *get* the full data item you actually wanted to use it, and the current behavior makes that simpler. So `jQuery.hasData()` was created as a way to see if there was data on an element without creating it, the presumably less common case.

**Comment by gibson042** [comment]
Ok, @dmethvin is right:
> Note that jQuery's event system uses the jQuery data API to store event handlers. Therefore, binding an event to an element using `.on()`, `.bind()`, `.live()`, `.delegate()`, or one of the shorthand event methods also associates a data object with that element.

In this case, it's [`hasDataAttrs`](https://github.com/jquery/jquery/blob/99e8ff1baa7ae341e94bb89c3e84570c7c3ad9ea/src/data.js#L100) private data. Which makes `jQuery.hasData` essentially useless, but that's a separate issue.

**Comment by dmethvin** [comment]
The goal of `jQuery.hasData` is to give the caller a way to avoid accidentally creating an unneeded data object and it's still useful for that. It doesn't matter whether it's private or public data, just whether there's already an object. I agree that it's useless for a user making inferences such as "Have I put some data on this object? Okay I'll get the object and enumerate it. Hey it's empty, that should never happen!"

**Comment by prontiol** [comment]
I think we just need to fix the docs about `jQuery.hasData` saying it will return `false` for empty data objects, because it is just not true.

**Comment by dmethvin** [comment]
Agreed, just created https://github.com/jquery/api.jquery.com/issues/889
