### ISSUE TITLE
$() throw internal jquery error, only the first time

### ISSUE THREAD

**Issue by Baud21** [jquery/jquery#2934]
Hi,

Figure out this example:
Change, on firefox, the combobox item, throw an error the first time. Works all next change.

```
<script type="text/javascript" src="jquery.min.js"></script>
<script>
function Change(c) {
	var cm=$(c);
	var ok=$(cm.parent);
}
</script>
<select onchange="Change(this)"><option>1</option><option>2</option><option>3</option></select>
```

> TypeError: a is null
> ...return a}n.each({parent:function(a){var b=a.parentNode;return b&&11!==b.nodeType..

**Comment by mgol** [comment]
`cm.parent` in your code is a function (see [the docs](https://api.jquery.com/parent/)). Passing a function to `jQuery` executes the passed function on document ready instead of creating a new jQuery object; see [the docs](https://api.jquery.com/jQuery/#jQuery3).

The trick is that `parent()` expects to be executed as a method and not a regular function which is why it throws - when it's invoked on document ready it loses its context object as there's no way to get that from the function. You'd get the same error if you tried the following:
```js
function invokeCallback(cb) {
    cb();
}
invokeCallback($.fn.parent);
```
or even:
```js
var parent = $.fn.parent;
parent();
```

Also, note that it is discouraged to mix jQuery with inline event handlers; use the `.on()` method instead.
