### ISSUE TITLE
Eliminate the intro/outro nuisance tickets

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery#2975]
Good news! The development best practice of using JSHint or ESLint to check source files is becoming a lot more common now.

Bad news! People are running JSHint and ESLint on jQuery source files and getting error messages on intro.js and outro.js since they are not actually complete files. Examples are #2747, #2819, #2953, and (I think based on Google Translate) #2971.

We should be able to fix this by changing the extension of those two files from `.js` to `.js_partial` or some such. That way they won't be linted by default and the name should provide a clue that they are not complete files.

**Comment by mgol** [comment]
I've been thinking about that recently. If that's possible, I'd prefer to change [the wrapping logic](https://github.com/jquery/jquery/blob/5943f1d7ffef41cc1a99bffe189f6d111fbccfd0/build/tasks/build.js#L30-L33) so that we have a template js file containing both intro & outro that would have a placeholder comment to be replaced by the rest of the build file. That would mean those files, consolidated, could keep their JS extension.

**Comment by dmethvin** [comment]
That would let us lint the combined file; currently the parts are obviously excluded although they are linted once the combined file is created. :+1:

**Comment by mgol** [comment]
> That would let us lint the combined intro/outro file

Yup, that was my thinking. :)

**Comment by timmywil** [comment]
I like it.

**Comment by jaubourg** [comment]
I came to the same conclusion myself! Go for it! :)

**Comment by markelog** [comment]
Don't want to be a downer here, but those linters would still throw error on `wrapper` file :/, since there like unused arguments and a "dead code" for them.

It seems we just complicated the build process :/, again sorry, for the bad mood about this

**Comment by timmywil** [comment]
@markelog We aren't setting eslint rules, so if they're running lint without modifying their own rules, it's going to break regardless. If they're using jshint, it will work because of the pragma at the top.
