### ISSUE TITLE
if there is an es6 version , we can use  import to load a module  and don't need load all the jquery. or if there is a plan ?

### ISSUE THREAD

**Issue by kocokolo** [jquery/jquery#2983]
thank you

**Comment by markelog** [comment]
You mean like with (rollup)[https://github.com/rollup/rollup]? Other builders, like webpack would still include full version of the library, since tree-shaking algo is not fully implemented there, you would just have access to the modules you have exposed.

Also, not sure what do you mean by "es6 version", since you would still use builded transpiled version, which would be an es5 code. Since there is pretty much no environments at the moment that support every new thing in es6. Canary is at 97% though, which is cool.

You can, however, build custom jquery, see (readme)[https://github.com/jquery/jquery#user-content-modules] including only those modules that you would use.

There is also an idea to build web builder, while writing jquery with es6 syntax would probably increase the size, again because of the transpiler.

Hope that answers you question, i'm gonna close this for now, if there is something else, you would be probably better of to check out our (irc)[http://irc.jquery.org/] channels, since github issues are not really for the questions.

Thanks

**Comment by shrpne** [comment]
ES6 modules are on [roadmap](https://github.com/jquery/jquery/wiki/Roadmap)

related issue: #2138
