### ISSUE TITLE
postMessage events support

### ISSUE THREAD

**Issue by kirly-af** [jquery/jquery#3019]
Hi all,

It looks like postMessage events are not completely supported by jQuery.

``` javascript
// sender window
otherWindow.postMessage( "foo", "*" );
```

``` javascript
// receiver window
$( window ).on( "message", function( event ) {
  console.log( event.data ); // undefined
  console.log( event.orignalEvent.data ); // "foo"
});
```

This [StackOverflow post](http://stackoverflow.com/questions/9904490/jquery-doesnt-support-postmessage-event) suggests that the events data is not properly parsed by jQuery.

I did not look how jQuery internally parses events data, but it looks quite trivial to fix :
``` javascript
// jQuery code
// ...
if ( event.type === "message" ) {
  event.data = event.originalEvent.data;
}
``` 

Any thoughts concerning the possible caveats of this kind of fix ?
If not, I will do a proper PR.

**Comment by dmethvin** [comment]
In a jQuery event handler, the `event` object is the normalized jQuery event, and `event.originalEvent` is the original, non-normalized data. For events like `onmessage` which have no real DOM-related content you're right that you will nearly always use only `event.originalEvent` but trying to "un-normalize" for only a few events makes things inconsistent.

Is there a major benefit to attaching these events via jQuery in the first place? Since we're not normalizing anything I don't see one.

**Comment by kirly-af** [comment]
Thank you for your quick reply.

Actually my goal was just to use jQuery eventhandler attachers (especially `.one()`) for their convenience.

In the end I understand your point of view and I admit the benefit is probably too limited to create inconsistencies. Instead, I shall write a wrapper that does not involve jQuery.
