### ISSUE TITLE
`jQuery.param`’s behaviour differs with the one described in the docs

### ISSUE THREAD

**Issue by sowcow** [jquery/jquery#3023]
## docs

http://api.jquery.com/jQuery.param/

As of jQuery 1.8, the `$.param()` method no longer uses `jQuery.ajaxSettings.traditional` as its default setting and will default to `false`. For best compatibility across versions, call `$.param()` with an explicit value for the second argument and do not use defaults.

## actual

https://github.com/jquery/jquery/blob/master/src/serialize.js#L65

```javascript
	// Set traditional to true for jQuery <= 1.3.2 behavior.
	if ( traditional === undefined ) {
		traditional = jQuery.ajaxSettings && jQuery.ajaxSettings.traditional;
	}
```

**Comment by gibson042** [comment]
Nice catch, @sowcow! Would you like to submit a PR?

**Comment by sowcow** [comment]
Yes, I'm looking forward to it.

**Comment by sowcow** [comment]
Probably I should also modify ajax.js, i will check that tomorrow.

**Comment by sowcow** [comment]
I think i'm done, comment if any fixes are needed.

**Comment by dmethvin** [comment]
Everyone agrees this is ready to land? If so I'll land it for master/3.0, update the 3.0 upgrade guide, and submit a docs ticket to change the version to 3.0. Ugh, I guess we'll also need a Migrate ticket.

**Comment by timmywil** [comment]
@dmethvin :+1:

**Comment by dmethvin** [comment]
One thing I just realized, the tests here were covering the case for `jQuery.ajax()` where *it* uses `traditional`. We should add a test or two in `test/unit/ajax.js` that asserts setting `traditional` will encode the parameters properly.

@sowcow would you be able to do that? You can use [this test](https://github.com/jquery/jquery/blob/e5ffcb0838c894e26f4ff32dfec162cf624d8d7d/test/unit/ajax.js#L330-374) as a template because it does something very similar. Just pass in `traditional: true` as one of the ajax parameters and ensure it encodes correctly, you can swipe the encoding cases from the existing tests here.

**Comment by sowcow** [comment]
I'll do that tomorrow.

**Comment by mgol** [comment]
For reference, PR is in #3030.

**Comment by dmethvin** [comment]
sorry @sowcow should have pinged you here since the action item was  here.

**Comment by sowcow** [comment]
sorry, I'm a bit irrational about tests, so i can't do that :snowman:
