### ISSUE TITLE
load() callback "this" breaking in 2.2.0 vs 2.1.4

### ISSUE THREAD

**Issue by blq** [jquery/jquery#3035]
Hi,
"this" in the callback to the load() function changed from 2.1.4 to 2.2.0 in a breaking way.

The documentation at http://api.jquery.com/load/ says: ".. this is set to each DOM element in turn.".
In 2.2.0 "this" is instead the jQuery instance, and not the DOM element.

I tracked it down to this commit: 
https://github.com/jquery/jquery/commit/a4715f4216ace92fba6991106053415e66289686

Regards
/Fredrik Blomqvist

**Comment by gibson042** [comment]
It looks like the [callback invocation](https://github.com/jquery/jquery/blob/99e8ff1baa7ae341e94bb89c3e84570c7c3ad9ea/src/ajax/load.js#L65) should be using `this` instead of `self`. Would you like to open a pull request?

**Comment by mgol** [comment]
@markelog This fix is making it into 1.12.3 & 2.2.3 so the milestone should reflect that. Why did you change that to 3.0.0?

**Comment by markelog** [comment]
And to 3.0 too, whereas master branch is a primary one. So why did you change the milestone, before clarifying?

**Comment by mgol** [comment]
Milestones are used to generate changelogs and for end users it doesn't
matter that 3.0.0 got the fix separately, for them it's fixed in
1.12.3/2.2.3 and just stays fixed in 3.0.0. That's why the older releases
get the milestone and that's what's we've been doing so far.

Also, if anyone, *I* should be the one asking why you changed the milestone
without claryfing.


-- 
Michał Gołębiowski

**Comment by markelog** [comment]
I think correct course of events is important, this issue looks like that the fix is only needed for 2.2-stable, whereas is it would incorrect to assume that.

> for them it's fixed in 1.12.3/2.2.3 and just stays fixed in 3.0.0

That would be an incorrect, offense commit was done against the 3.0 and ported to 2.x/1.x,
not to mentioned to we already released several versions of 3.x, pre-releases but releases nonetheless, which has this bug, now you propose to omit this commit and there by deprive users from this information? All and all i don't understand why you propose to mislead our users, since i assumed you set the milestone by mistake and not on purpose, that is why i have changed the milestone.

This commit should be in both changelogs, milestone, in my opinion should be set on primary branch.

**Comment by mgol** [comment]
I disagree but I don't have anything else to add.

**Comment by blq** [comment]
Thanks for the fix and quick release, now our app works again! :)
