### ISSUE TITLE
Padded strings in ajax headers cause DOM Exception 12

### ISSUE THREAD

**Issue by bradleat** [jquery/jquery#3055]
Left padded or right padded strings given for xhr headers cause "DOM Exception 12" on Safari 9.x.

An example of a header that would cause this error is as follows:

contentType: 'application/json; charset=UTF8 '
or
contentType: ' application/json; charset=UTF8'

Note: these headers would work on Chrome, Firefox, and IE.

This fix is to simple remove the extra padding by using .trim() before setHeaders(...) (on Safari).
I can implement this and submit a pull request myself, I just need some guidance:

- Is this a fix jquery wants to implement?
- If it is, is it better to .trim() on all platforms, or just on Safari?

**Comment by dmethvin** [comment]
AFAICT, [rfc7230](https://tools.ietf.org/html/rfc7230#page-22) defines this type of whitespace as optional and it should be safe to remove. Have you filed a bug with Safari/Webkit? It would be good to know why they added this behavior, assuming it's intentional. And why is the input being padded?

**Comment by bradleat** [comment]
The input wasn't meant to be padded. I have not filed a bug with Safari or Webkit, as they are not misinterpreting any spec (AFAIK), they are just enforcing the spec more strictly than needed. Perhaps instead they should give the user a warning...

The input wasn't meant to be padded, however I thought that it would be useful for the jQuery team to note that other browsers accept the padded input however Safari does not. This may be in the domain of your product.

**Comment by dmethvin** [comment]
> I have not filed a bug with Safari or Webkit, as they are not misinterpreting any spec (AFAIK), they are just enforcing the spec more strictly than needed.

I was interpreting [RFC 7230](https://tools.ietf.org/html/rfc7230), which says, 
```
header-field   = field-name ":" OWS field-value OWS
```
where OWS is [optional whitespace](https://tools.ietf.org/html/rfc7230#section-3.2.3):

>  The OWS rule is used where zero or more linear whitespace octets
might appear.  For protocol elements where optional whitespace is
preferred to improve readability, a sender SHOULD generate the
optional whitespace as a single SP; otherwise, a sender SHOULD NOT
generate optional whitespace except as needed to white out invalid or
unwanted protocol elements during in-place message filtering.

Note that they explicitly say the *sender* SHOULD NOT generate optional whitespace, and the caller to the jQuery method is the sender in my view--jQuery should not be changing the header the caller provided. Note that the term "SHOULD NOT" has a [specific meaning in an RFC](https://www.ietf.org/rfc/rfc2119.txt) and is not the same as "MUST  NOT" so I still think Safari is violating spec. In the spec they even give one case where extra whitespace may validly need to be added.
