### ISSUE TITLE
Check minified code for syntax errors (e.g. by trying to construct an AST)

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#3075]
*\* Description**

Enabling strict mode uncovered an UglifyJS issue (https://github.com/mishoo/UglifyJS2/issues/1052) where it was creating code with SyntaxErrors. Perhaps we should try to generate the AST of the generated minified code to check if it doesn't contain syntax errors.

**Comment by markelog** [comment]
Validate AST? Sounds awfully like a linter to me. I think @gibson042 meant to just check if we can build an AST.

**Comment by mgol** [comment]
@markelog updated the title & description.

**Comment by markelog** [comment]
And it also sounds like, that this could be (if proven viable) implemented on uglify side, like self check of sorts which could be run if correct option is passed (since it would reflect on the performance).

@mishoo what do you think?

**Comment by mishoo** [comment]
@markelog Not sure I understand what's your question, but I do agree that @mgol reported a valid issue on UglifyJS.  We already have a [PR that fixes it](https://github.com/mishoo/UglifyJS2/pull/1053); I didn't have time to look into it yet, though — please test if possible.

**Comment by markelog** [comment]
> Not sure I understand what's your question

We have an idea, which we currently considering to implement in jquery build process - after uglify minifies the source, run it through parser once again and try to build an AST, if AST is builded, then we could be sure that there is no obvious syntax errors.

Yes, we do run minified version through test suite on various set of browsers with browserstack, but because mentioned error was noticed only at that point, we almost reached our cap on that service, which is not preferred, proposed approach might caught such errors on early stage if automated.

And yes, most errors will not be revealed at that stage, but it seems some of them will, like https://github.com/mishoo/UglifyJS2/issues/1052?

I'm wondering if second parser run could be introduced on uglify side as a self check and overall, if you think this idea worth something.

Other option is to run linter on minified version, with limited amount of enabled rules, but running linter on minified version sounds kinda... or is it?

**Comment by kzc** [comment]
A second uglify parse would not have caught this issue:
```
"use strict";

!function() {
    if (window) function i() {}
}();
```
as uglify parses it without error:
```
"use strict";!function(){if(window)function i(){}}();
```
A full-fledged linter from a different parsing code base or testing with PhantomJS is your best bet.

**Comment by mgol** [comment]
This issue doesn't seem actionable now, it seems it requires further research. Should we move it to [the roadmap](https://github.com/jquery/jquery/wiki/Roadmap)?

**Comment by markelog** [comment]
> Should we move it to the roadmap?

Done

**Comment by mgol** [comment]
Re-opening since it's now possible to do such a verification via a plain ESLint run.

**Comment by mgol** [comment]
PR: #4594
