### ISSUE TITLE
$.when should always be synchronous when possible

### ISSUE THREAD

**Issue by marcandre** [jquery/jquery#3100]
IIC, jQuery 3.0 will have `then` be A+ compatible in that callbacks are always executed out of context (e.g with `setTimeout`), while `done` will continue to be executed synchronously whenever possible (eager).

I was double checking that `$.when` kept the eager behavior and discovered that it does, unless there's a single argument:

```
p = $.Deferred()
p.resolveWith(42);
p.done(function() {console.log('A')});
$.when(p).done(function() {console.log('B')});
$.when(p, p).done(function() {console.log('C')});
console.log('D');
```

I was hope to get ABCD, given that the promised is already resolved when the `done` are called, and dreaded ADBC if `$when` was no longer eager. I get worse though. Console is ACDB, which is not acceptable; `$.when(p)` and `$.when(p, p)` should behave the exact same way.

FWIW, I personally disagree with Promise/A+'s rule 2.2.4 and I hope jQuery keeps all behavior eager (except for `then` to comply with A+) and gives us an eager version of `then` (could be `pipe`, but with the correct semantics for callbacks return values).

I did not investigate any further, but it looks related to #3059.

**Comment by markelog** [comment]
@gibson042 Did we discuss this before? Did we want to make `done` async or sync? I agree arguments shouldn't change affect on it.

**Comment by gibson042** [comment]
It's important to realize that `jQuery.when` is polymorphic—multi-argument calls being analogous to ES6 `Promise.all` and other calls being analogous to ES6 `Promise.resolve`. It's unfortunate that their similarity led to a shared function name in jQuery, but they _are_ distinct. And although `done` itself remains eager, general-case `jQuery.when( value )` is necessarily not because of its reliance on `.then` to unwrap secondary thenables as `Promise.resolve` does. And I don't want to introduce a `jQuery.when( nonThenable )` exception, which really would introduce an inconsistency.

I also disagree with Promises/A+ 2.2.4, but that is insufficient justification to abandon compatibility which has been demanded for so long.

**Comment by dmethvin** [comment]
I know @gibson042 has rightly railed about this several times, I'm too lazy to dig it up. 

In the pre-3.0 implementation there was a special case of "If there is only one argument, and it is a `Deferred` rather than a plain value, return that argument." In 3.0 we are accepting any type of `then`ables as arguments, so it would make the `$.when` behavior even more bizarre because if you passed in a `then`able we'd need to convert it to a `Deferred` to meet the API contract, right? That means there always has to be a hidden async `then`inside `$.when` for this to not be a tear-your-hair-out behavior.

**Comment by markelog** [comment]
So, `jQuery.when` is always async right?

**Comment by markelog** [comment]
> So, jQuery.when is always async right?

I answer myself here - no it is not.

Discuss this with @gibson042 on irc, it seems there is motivation to make this call always async regardless of the arguments, opened a different issue for that - https://github.com/jquery/jquery/issues/3102
