### ISSUE TITLE
Finds the elements of an object which satisfy a filter function

### ISSUE THREAD

**Issue by danielwheeler1987** [jquery/jquery#3110]
Hello, I was wondering if it would be a good idea to summit a PR which allows grep filter an object as well. This will remove the need to do something like this:

$.grep(Object.keys(options), function (k) { return options[k].group == something; })

Would love some feedback!!

**Comment by dmethvin** [comment]
jQuery's built-in utility methods are primarily meant to serve the needs of jQuery internally, and we've exposed some of them since they can be useful to others. Since we're not using a feature like the one you describe, and because it could be done as a plugin or even independently of jQuery, it doesn't meet our bar for [adding new features](https://github.com/jquery/jquery/wiki/Adding-new-features). For something like that you may also want to look into lodash, it's got a great set of methods for filtering data.
