### ISSUE TITLE
Empty value of cloned input element changed to type 'hidden' is lost

### ISSUE THREAD

**Issue by doits** [jquery/jquery#3125]
This is a corner case indeed, but it happened to me just now, so ...

## What works

I have a pre filled input field on page load:

    <input type="text" value="test" id="test">

The input field is then changed, e.g.

    $('#test').val('something')

Then I clone the element and change it to hidden type:

    var $clone = $('#test').clone()
    $clone.attr('type', 'hidden')

... and I look at the cloned val:

    $clone.val() // -> 'something'

Everything fine. The clone has the same value as the original input.

## What does not work

If I change the value of the original not to `something`, but empty it (by hand or by js) ...

    $('#test').val('')

... and do everything else like before, the val of cloned input field is:

    $clone.val() // -> 'test'

... - it is the value of the original input on page load! It should be empty, of course.

**Fiddle:** https://jsfiddle.net/m7yndayg/1/

If I do not change the cloned type to `hidden`, it works as expected.

So it fails only if these conditions are met:

1. the original input has a non empty value attribute
1. the original input is cleared after page load
1. the type of the clone is changed to hidden

Happens on 2.2.3, 1.12.2 and 3.0.0-alpha1. Tested with Firefox 48.0a2 here.

**Comment by dmethvin** [comment]
Ref: https://html.spec.whatwg.org/multipage/forms.html#the-input-element

Note that under "IDL attributes and methods" the value of a `hidden` input is defined as "default" and the one for `text` is defined to be "value", you can see the definitions in the spec. By changing the `type` you've changed the required behavior.

**Comment by doits** [comment]
@dmethvin thanks for the fast response and explanation.

I played around a little bit and maybe you can explain me the following behaviour (https://jsfiddle.net/m7yndayg/3/), which I fear is correct by spec but I do not understand atm:

```
  <input type="text" value="test" id="test">

  var $input = $('#test')
  $input.val('something')
  
  var before_type_change_value = $input.get(0).getAttribute('value')
  $input.attr('type', 'hidden')
  var after_type_change_value = $input.get(0).getAttribute('value')

  before_type_change_value // test
  after_type_change_value // something
```

Before type change, `getAttribute('value')` gives the default value (from `<input value="test">`), even though the value property was changed by `.val('something')` - so far so good. But then after the type change, the attribute `value` is `something` - shouldn't it still be `test`, too, because the only the attribute `type` changed and the attribute `value` wasn't touched at all? For me it looks like the attribute `value` is synced with the property `value` on type change.

I know this has probably nothing to do with jquery any more, but I'm still interested why it is like this, so sorry for being OT.

**Comment by dmethvin** [comment]
The way you can tell if it has to do with jQuery is to give the example a try with standard DOM methods and see if the same thing happens. That's what the spec means in that table when it references https://html.spec.whatwg.org/multipage/forms.html#concept-fe-value, the property is the internal state. For type=hidden it specifically says to use the *attribute*: https://html.spec.whatwg.org/multipage/forms.html#dom-input-value-default

Note that jQuery's `.val()` sets/gets the value *property* and you are getting/setting the value *attribute* which often is not the same thing because of various 1990s compat rules.

**Comment by doits** [comment]
You are correct it has nothing to do with jquery (https://jsfiddle.net/m7yndayg/4/), but I still do not understand it. Browsers behave same though (Firefox, Chrome, Safari), so it seems to be correct.

```
<input type="text" value="test" id="test">

var input = document.getElementById('test')
input.value = 'something'

var before_type_change_value = input.getAttribute('value')
input.setAttribute('type', 'hidden')
var after_type_change_value = input.getAttribute('value')

before_type_change_value // test
after_type_change_value // something
```

If using `input.setAttribute('value','something')` instead of `input.value = 'something'` both values before and after type change are `something`, so it seems to have something to do with the *property* value indeed (because `input.value =` changes the *property*, too, if I understand this correctly).

**Comment by dmethvin** [comment]
It's doing what the spec says to do and using the attribute. I suspect the logic behind it is that there is no need for a hidden input to have a dynamic state since users cannot modify it directly. By changing the type on the fly you're breaking that assumption. It's not likely many people have encountered this case because IE8 and earlier didn't even allow you to change input types so most people avoid it in their code.
