### ISSUE TITLE
Studying the evolution of JQuery's project

### ISSUE THREAD

**Issue by gustavopinto** [jquery/jquery#3138]
Hi there, 

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. JQuery was in my list. 

To further analyze the impacts of JQuery’s migration, we analyzed the git log commit history of your project in terms of _number of contributions_, _number of newcomers_, and _number of contributors per month_. The following figure presents a temporal perspective regarding these three measures. 

![jquery](https://cloud.githubusercontent.com/assets/235062/15755667/a70604e0-28b2-11e6-85bc-356b86e67510.png)

Given the numbers presented in the graphic, we would like to ask JQuery developers the following questions:

1. What motivated the project to open its source code at Github? How do you evaluate the benefits of this migration?
2. Does this snapshot make sense? Did you find any inconsistency on the data?
3. Do you have any internal policy to promote/attract/retain newcomers? If so, do them succeed?
4. Why there was a slope on the number of newcomers that joined the project? 

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by timmywil** [comment]
Thanks for submitting this issue. We can continue discussion, but since it not a code issue, I'm going to close it.

1. jQuery has always been open source, because we love open source. The migration to GitHub was a no-brainer due to its popularity and ease-of-use.
2. Interesting that the graph suggests we've had more newcomers since moving to GitHub. As far as comparisons, I'm not sure we have internal data, just the [GitHub graphs](https://github.com/jquery/jquery/graphs/contributors).
3. We encourage new people to contribute through our conferences, summits, in-person conversations, jQuery websites, social media, and other avenues. I couldn't say which are the most successful for certain, but I suspect that the developers summits and organic conversation in person have played the biggest roles in attracting newcomers.
4. I don't see a slope so much as a lot of up and down. It does seem like there was a burst of newcomers at the end of 2012, but I couldn't say what contributed to that.

Thanks.

**Comment by scottgonzalez** [comment]
> I don't see a slope so much as a lot of up and down. It does seem like there was a burst of newcomers at the end of 2012, but I couldn't say what contributed to that. Although, it was the first year we held conferences outside the US.

The end of 2012 was our [first developer summit](http://events.jquery.org/2012/developer-summit/).
