### ISSUE TITLE
$(sel).click() fires multiple events

### ISSUE THREAD

**Issue by hunteke** [jquery/jquery#3146]
### Description ###

For a test case, we had implemented a function utilizing `$( selector ).click()`.  This broke some assumptions another programmer had made (good, we corrected those).  Meanwhile, while researching why currentTarget was not set for this test case, we discovered that click() was firing not one, but two events.  Here is actual output from our reduced test case (attached below):

#### Native Click
```
Click Handler: MouseEvent {isTrusted: true, screenX: 94, screenY: 165, clientX: 94, clientY: 55…}
index.html:10     Event type:          click
index.html:11     Event target:        <div id=​"parent">​…​</div>​
index.html:12     Event currentTarget: <div id=​"grandparent" onclick=​"clickHandler(event)​;​">​…​</div>​
```
#### Generated with jQuery 2.2.4
```
index.html:16 Native button click event:  MouseEvent {isTrusted: true, screenX: 95, screenY: 200, clientX: 95, clientY: 90…}
index.html:17   Delaying jQuery generated click ...
index.html:19   ... Generating jQuery click
index.html:9 Click Handler: n.Event {type: "click", timeStamp: 1465332138698, jQuery22406390061249255916: true, isTrigger: 3, namespace: ""…}
index.html:10     Event type:          click
index.html:11     Event target:        <div id=​"child">​Child - Click in here for native event​</div>​
index.html:12     Event currentTarget: undefined
index.html:9 Click Handler: MouseEvent {isTrusted: false, screenX: 0, screenY: 0, clientX: 0, clientY: 0…}
index.html:10     Event type:          click
index.html:11     Event target:        <div id=​"child">​Child - Click in here for native event​</div>​
index.html:12     Event currentTarget: <div id=​"grandparent" onclick=​"clickHandler(event)​;​">​…​</div>​
```

### Link to test case ###

Complete, self-contained test case (34 lines of HTML/JS, 2 functions):
 * [index.txt](https://github.com/jquery/jquery/files/303510/index.txt)

Apologies for text file, GitHub doesn't appear to accept HTML.

**Comment by dmethvin** [comment]
There is an old ticket in bugs.jquery.com that I can't find at the moment. This is due to the use of `onclick` attributes for the handler. Note that we don't execute `addEventListener` handlers, but early in jQuery's history it was decided to try and run `onclick` handlers as part of `.trigger()`. One side effect of this is that when you use `.trigger()` we manually run both jQuery and inline `click` handlers, then if you don't `preventDefault` we try to run the DOM `click()` method. That method tries to run the handlers again and we can [block the duplicate runs of the jQuery handlers by remembering `jQuery.event.triggered`](https://github.com/jquery/jquery/blob/e06fda69f00082b44fd39ce8e851f72d29999011/src/event.js#L144). We can't do that for inline handlers.

Note that [we call inline handlers a wontfix issue](https://contribute.jquery.org/wont-fix/#inline-event-handlers) due to this. If you find the ticket in the old bug tracker I can add it to the wontfix page or update it somehow to indicate this occurs.

**Comment by mgol** [comment]
@dmethvin That made me think: since we generally consider inline handlers iffy, why won't we just stop invoking them on `trigger`?

**Comment by dmethvin** [comment]
As always it's mostly about compat. For 4.0 I am experimenting with splitting out the triggering of an event from the calling of a method like the DOM `.click()` that happens to fire events and the "default action". Even the standard is [a bit muddled](https://github.com/whatwg/html/issues/1394) about these things and how they relate.
