### ISSUE TITLE
Inconsistent call sequence of $.when with single promise

### ISSUE THREAD

**Issue by marcandre** [jquery/jquery#3149]
I fear the ⚡  thunder of the JavaScript gods ⚡ , but I'll still venture to ask: what output should the following produce?

```
deferred = $.Deferred()
deferred.done(function() { console.log('A') })
$.when(deferred).done(function() { console.log('B') })
$.when(deferred, deferred).done(function() { console.log('C') })
deferred.resolve()
console.log('D')
```

I get the 'ABCD' I was hoping for in jQuery 2.x, 3.0.0-beta1, but in 3.0.0-rc1 I now get 'ACDB'.

Although I don't particularly care about it, I'll mention that if using `then` instead of `done`, in 3.0.0-rc1 I get 'DACB', when I was expecting 'DABC', for the same reasons I imagine.

I remember the polymorphic nature of `$.when`, but I feel this has more to do with argument passing than with calling order. Indeed, the native equivalent give me 'dabc':

```
var resolve;
p = new Promise(function(r) { resolve = r })
p.then(function() { console.log('a') })
Promise.resolve(p).then(function() { console.log('b') })
Promise.all([p, p]).then(function() { console.log('c') })
resolve()
console.log('d')
```

cc @gibson042 
*/ducks for cover*

**Comment by gibson042** [comment]
The short answer is "don't rely on the sequence of potentially asynchronous operations". But there is also a longer answer.

We've decided that `jQuery.when( singleValue )` is a casting operation analogous to `Promise.resolve`, particularly including unwrapping secondary thenables (i.e., that when `singleValue` is thenable and fulfills with a thenable—which is not possible with native `Promise` but _is_ possible with `jQuery.Deferred` and others—the object returned by `jQuery.when` fulfills with the ultimate fulfillment value of the sequence rather than an intermediate thenable). In order to acheive that, [we need to invoke `.then`](https://github.com/jquery/jquery/blob/de71e9755fc0b5d45ee3fa1bac5481c2466dad6e/src/deferred.js#L371-L376), _forcing_ asynchronicity as a side effect. So the logging of `B` in your example gets delayed.
