### ISSUE TITLE
Deprecate jquery.fx.interval

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#3154]
Since for most browsers we will use rAF, this thing will became pointless when support for them will be dropped

See http://api.jquery.com/jquery.fx.interval/

**Comment by mgol** [comment]
👍 I was thinking the same when I was submitting this WIP PR for using the rAF timestamp in effects.

**Comment by scottgonzalez** [comment]
We have one reference to `$.fx.interval` in jQuery UI, [inside tooltip](https://github.com/jquery/jquery-ui/blob/3c860f95aa43c7844883f4417247d2aa6c482151/ui/widgets/tooltip.js#L329-L334). This is obviously very easy to update, either by hard-coding `13` or switching to `requestAnimationFrame()`.

Switching to `requestAnimationFrame()` would mean that we'd stop working in IE <= 9. While our next version (1.12.0) officially drops support for IE < 11, we're trying not to actively break support until 1.13.0. For this one case, it doesn't seem worth it to add the overhead of feature detection to conditionally use `requestAnimationFrame()`.

Because of this, I plan on just swapping in `13` where we use `$.fx.interval`. But before I do that, I wanted to see if there was any other way we could handle this and stay in sync with the actual animation. As far as I can tell, we're not actually in sync right now, so if there's not, it doesn't really matter. The reason we don't just do this inside the actual animation call is because the logic around showing the tooltip is abstracted away (see the [call to `_show()`](https://github.com/jquery/jquery-ui/blob/3c860f95aa43c7844883f4417247d2aa6c482151/ui/widgets/tooltip.js#L322) and the [implementation of `_show()` inside the base widget](https://github.com/jquery/jquery-ui/blob/3c860f95aa43c7844883f4417247d2aa6c482151/ui/widget.js#L670-L709)).

This definitely shouldn't affect the deprecation, just wondering if there's a better way to do what we're doing.

**Comment by dmethvin** [comment]
> I wanted to see if there was any other way we could handle this and stay in sync with the actual animation. ... This definitely shouldn't affect the deprecation, just wondering if there's a better way to do what we're doing.

Right now it's polling with the `:visible` selector on roughly every frame, which could be forcing style recalcs and possibly layouts. How about if you set a "don't try to set the position" flag that was cleared by a custom `.queue()` call after they `.delay()` that is [here](https://github.com/jquery/jquery-ui/blob/3c860f95aa43c7844883f4417247d2aa6c482151/ui/widget.js#L692)? The call could show the element and set its position, then the animation continues on normally.

**Comment by dmethvin** [comment]
We can put in a deprecation for this in Migrate immediately but the deprecation warning would be triggered any time that jQuery 3.x took the `setTimeout` path. What supported browsers don't have `rAF`?

**Comment by mgol** [comment]
> What supported browsers don't have rAF?

IE 9 & Android Browser (all). That's it.

**Comment by mgol** [comment]
We could always UA-sniff for IE 9 (`!(document.documentMode > 9)`) and not display the warning there. Is there an easy way to view the Android Browser console?

**Comment by dmethvin** [comment]
In Migrate I guess I can just avoid the warning if there is no `rAF`, which would just mean that  particular one would not show up in IE9 and Android. That's not so bad.

**Comment by mgol** [comment]
Ah, yeah, obviously, that's way better than UA-sniffing, I don't know what I was thinking. 😄

**Comment by dmethvin** [comment]
Docs PR submitted, I'll close this now.
