### ISSUE TITLE
Uncaught TypeError: n.easing[this.easing] is not a function

### ISSUE THREAD

**Issue by teo1978** [jquery/jquery#3160]
To reproduce: call animate() with an invalid value for the easing parameter, e.g. "kjbdkjbdbd".

Expected: a meaningful exception with a sensible error message such as "Unknown easing type 'xxxxx'" and whose first or second item in the stacktrace is the line of code calling animate().

Observed: an uncaught exception very deep inside jQuery's code, difficult to debug.

Uncaught exceptions are by definition bugs. For god's f***ing sake, check the sanity of input values.

**Comment by dmethvin** [comment]
I will note that Google does a pretty good job of diagnosing this at a cost of zero bytes in the library.

> Uncaught exceptions are by definition bugs.

Yes, but the question is, whose bugs?

> For god's f***ing sake, check the sanity of input values.

The range of insane values is infinite, and would require a lot of extra bytes to check. What are you suggesting for this check?

**Comment by matteosistisette** [comment]
> > Uncaught exceptions are by definition bugs.
> Yes, but the question is, whose bugs?

Of whoever wrote the line of code that throws. In this case, the library. If I call a library function with an invalid argument, that's a bug in my code, but if the error message isn't something of the kind "Invalid argument 'xxx' for function 'yyy'", thrown directly by the library function that I'm calling with the wrong argument, then the library has a bug too. (I'm simplifying a bit, this is obviously not always exactly and as simple as this, but I think you get what I mean).

> I will note that Google does a pretty good job of diagnosing this at a cost of zero bytes in the library.

And I will note that jQuery does a pretty bad job of not diagnosing it. Just to be clear: from the error message it's fairly easy to figure out that somewhere I used a somewhat wrong easing. It's not as easy to spot WHERE I did that, and it's close to impossible to figure out WHAT was the wrong easing that I passed as parameter. It's vital that the error message contains the invalid **value**.

> The range of insane values is infinite,

But the range of sane values isn't, right? Also, please don't pretend you're stupid. You don't need to check either the invalid or valid values one by one. Even if both ranges *are* infinite, there's certainly some invariant, or rule, that must hold and can be checked.

> and would require a lot of extra bytes to check. What are you suggesting for this check?

I'm not sure, because I don't know the internals of jQuery. if I knew that I would fix it and do a PR.
But I have a couple of ideas:
1) is it that difficult to check whether the value is a valid??
2) Let's suppose it is. Then just wrap the code that uses the value inside a try-catch block. If you catch an exception, you know that an easing can't be created with tha value, and you can issue a sensible error message containing the actual value.

The most annoying part of the issue is that you get an error that says
> n.easing[this.easing] is not a function

and the most valuable piece of information that you need is what the heck was the value of this.easing is (which I assume is the invalid string I passed).

Note that, even if I go up the stack trace until I find the line of *my* code that triggered the exception (which is far from trivial, because the stack trace is quite convoluted, goes in and out of the library, and you have to inspect a few places until you find it), that does not necessary tell me what the invalid value was, because it could be a variable. So yes, Google does a pretty good job on its side, but in the end it's pretty useless.

By the message 
> n.easing[this.easing] is not a function

it looks like you are doing something like `n.easing[this.easing](/*perpahs some params*/);`

So why not start by something like (consider it as almost pseudocode):
```
if (typeof n.easing[this.easing] != "function") {
  throw new Error("Unknown easing '"+this.easing+"'");
}
```
This would be *a lot* better; but it's just a starting point, because most probably that value has been stored without checking its sanity a lot earlier at a much higher level (judging by the depth of the stack trace).

**Comment by dmethvin** [comment]
Think of how many different places in jQuery where you can call a method with an incorrect argument. If we add a message for every one we would increase the size of the library much larger than what it is.   I understand that it would be very nice if every time anyone passed a bad argument we could give an essay on why it was bad and explain what they probably meant to do, but it just isn't practical to do that.

**Comment by teo1978** [comment]
I can't believe you are even arguing against something so obvious. 

This is just writing libraries 101: you write a function, the first thing you do is check the validity of the inputs, you don't blindly use whatever comes in. Not as a general rule, anyway. 

You may decide to omit the checks for the sake of efficiency and code footprint, when you are not trading off too much debuggability. I understand you can do that in a lot of cases in jQuery, where debugging whatever error may occur is trivial anyway. But this is definitely not one of those cases. Here you get an error that is just impossible to debug. That's unacceptable. If one has to spend hours debugging a trivial error, the library is just unusable.

**Comment by dmethvin** [comment]
> This is just writing libraries 101: you write a function, the first thing you do is check the validity of the inputs, you don't blindly use whatever comes in.

Nothing is so black and white. jQuery is loaded trillions of times per day so the size of the file does matter. The way the bug is reported here indicates that the minified version of jQuery is being used, which is probably why it's so hard to debug for you. This is another tradeoff of size/performance vs debuggability. 

> Here you get an error that is just impossible to debug. 

That's not true at all. You get an error message on the console which provides a location. Set a breakpoint there and the value of `this.easing` shows the incorrect name. Maybe it would have been clearer with the non-minified file but we provide both and can't control what people use when they try to track down bugs.

**Comment by teo1978** [comment]
> Nothing is so black and white.

I know, but I don't think you appreciate how dark gray this case is.

> > Here you get an error that is just impossible to debug.
> That's not true at all.

I thought it was obvious that by "impossible" I meant "way harder than it should be".

> You get an error message on the console which provides a location

Yeah, the location is all you have, but
- the error message is not relevant to the true nature of the error (this is because the error wasn't caught at the level it should have to, and an invalid value has been allowed to propagate deep down into the most low level part of the library code)
- the value is not provided
- even the location is not so significant, because you have to crawl up like a dozen levels in the stack trace and it's not even easy to figure out how much.

> the minified version of jQuery is being used, which is probably why it's so hard to debug for you

If there was a decent error reporting at the level where it should, that wouldn't even be an issue.

> Set a breakpoint there and the value of this.easing shows the incorrect name

That is if the error happens to be systematically reproducible.

**Comment by dmethvin** [comment]
I don't think this discussion is going to resolve anything so I'll lock the thread. I've given the reasons why we don't provide detailed API violations and you disagree which is your right, but it won't change [our approach](https://github.com/jquery/jquery/wiki/API-design-guidelines).
