### ISSUE TITLE
TriggerFunctionClick - ('a') Link Doesn't Work

### ISSUE THREAD

**Issue by Slb-Sbsz** [jquery/jquery#3168]
### Description ###
The function ".trigger('click')" doesn't work with "a" (Links) elements.

### Link to test case ###
http://codepen.io/slbbox/pen/aZZZWL

**Comment by dmethvin** [comment]
Yes, this is a place where jQuery doesn't run the DOM `.click()` method but it does trigger the `click` event on any handlers that are present. It has been this way forever because browsers weren't consistent about whether there was a `.click()` method on a link until recently, so for consistency we couldn't run the method. Making it run the method now would probably break code.

In most cases you can achieve the same thing with `window.location = this.href` but it looks like you're doing a download, I am not sure if that works consistently across browsers. See the discussion in [trac-11326](https://bugs.jquery.com/ticket/11326) and the hook created in 14b09ef98eb11aae04c028a3b3d7af116c7d2c20

**Comment by Slb-Sbsz** [comment]
I gave an alternative in a comment after the trigger function.
You can use javascript "document.getElementById("aDrctDwnld").click();".
Not is a problem, i only wanted present this situation, the download was an example, i was doing something similar when i saw that.
Thanks for answer.

**Comment by dmethvin** [comment]
OK, great!
