### ISSUE TITLE
Exceptions silently swallowed in $(fn)

### ISSUE THREAD

**Issue by pyalot** [jquery/jquery#3174]
### Description ###
If an exception is thrown in an event handler (such as $.ready), it is silently swalloed.

There are many cases in which exceptions are used to indicate errors for situations that are not code errors, for instance:

```javascript
var foo = function(arg){
  var result = parseFloat(arg);
  if(isNaN(result)){ 
    throw new Error('not a number');
  }
};
```

Exceptions like that may be cought by the user, such as when the number is user-input. But they may also indicate errors in the usage of the code (such as foo('123') ), in which case catching them is counter productive since they can't be debugged anymore.

### Link to test case ###
http://jsbin.com/bazaxixihe/edit?html,js,output

**Comment by Havunen** [comment]
This caused lot of headache for us! (reverted back to 2.2.4) Please fix.

**Comment by dmethvin** [comment]
Our document ready handler has been implemented via Deferred for a while, the change here is that we are using the Promise/A+-compatible behavior in 3.0. 

The reason this case isn't well handled is most likely that nobody on the team uses that style of explicitly throwing constructed errors expecting to get an error message on the console. Note that if you did have a `catch` somewhere up the call chain and handled the error it should still work fine. You would also get an error message on the console if the error was due to an error implicitly thrown by the browser, such as `ReferenceError`, because of [`jQuery.Deferred.exceptionHook`](https://github.com/jquery/jquery/blob/58c6ca9822afa42d3b40cca8edb0abe90a2bcb34/src/deferred/exceptionHook.js).

I see a few remedies here. One is that jQuery can add a `.catch()` to the end of the `jQuery.ready` chain before we fire it internally, so we can at least log that something bad happened. There shouldn't be any compatibility concerns there either. I think the stack will be lost at that point but in the example above you'd at least get a message `"Error: not a number"` on the console.

Another option for users who prefer noise over silence is to add a modified [`jQuery.Deferred.exceptionHook`](https://github.com/jquery/jquery/blob/58c6ca9822afa42d3b40cca8edb0abe90a2bcb34/src/deferred/exceptionHook.js) that logs all errors including thrown ones. It would just mean removing the check for error type there. I don't think that's appropriate for the default though. People who use the `throw new Error(...)` pattern as a simple rejection method in Promises would get all kinds of console noise.

**Comment by mgol** [comment]
> I see a few remedies here. One is that jQuery can add a .catch() to the end of the jQuery.ready chain before we fire it internally, so we can at least log that something bad happened. There shouldn't be any compatibility concerns there either. I think the stack will be lost at that point but in the example above you'd at least get a message "Error: not a number" on the console.

I was thinking about the same. While I think we can require developers to know that if they rely on the `jQuery.ready` promise they have to handle errors themselves as that's what's generally happening in Deferreds now (and we can't really avoid it), if you're using `$(fn)` or some other equivalent form, I think jQuery should handle the errors internally, catch & re-throw in a timeout so that the error is normally logged to the console.

**Comment by dmethvin** [comment]
Also note that the previous 2.x behavior was problematic, just in a different way. If you attached 5 document ready handlers and the first threw an uncaught error like @pyalot's example, the other 4 handlers *would not run*. Now they are independent so all 5 will run.

> jQuery should handle the errors internally, catch & re-throw in a timeout so that the error is normally logged to the console.

I would have to contemplate the code a bit more, but do we have the stack we want to dump at that point? Last time I looked at it, my impression was that we did not and would have to track some sort of per-instance error stack property making the bookkeeping a lot more complex. That's why I added the quick and dirty logging of error types that seemed like they were due to developer mistakes.

**Comment by timmywil** [comment]
>  if you're using $(fn) or some other equivalent form, I think jQuery should handle the errors internally, catch & re-throw in a timeout so that the error is normally logged to the console.

This could be a good workaround.

**Comment by nicklou** [comment]
What about giving the ability to pass an (optional) "exception" callback as argument instead of chaining up the exception? For instance:

```javascript
$(function(){
  throw new Error('Erro thrown');
}, function(error) { // "Exception" callback
  console.log(error.message);
  // This code is executed when an internal exception took place.
});
```

That way, the exception should not chain up till thrown outside the ```$()```, instead, the dev could handle such case inside the specific callback.

(Please note I am a new user and still learning about contributing on jquery, but the solution above seemed logical to me, and thought to share).

**Comment by scottgonzalez** [comment]
> One way to look at it is that the ready handler signature would now be $( ready_handler, error_handler )

I just want to note that you should be very clear in the documentation that this is not the equivalent of `.then()` on the ready promise (which the signature makes it look like) since rethrowing in the error handler of the promise would have the same results as the original throw.

**Comment by nicklou** [comment]
@dmethvin This seems to be a very nice solution, and I will take a look on what it needs in order for it to become implemented (any advice on this would be appreciated). @scottgonzalez  you are absolutely right that this is similar to the ready promise, so we should specify that it is ```$( ready_handler, exception_handler )``` in the documentation and make clear that the exception_handler is only invoked in throwing/exception conditions.

**Comment by mgol** [comment]
Let's discuss it on Monday, sounds like 3.1.0 material.

**Comment by nicklou** [comment]
@dmethvin @scottgonzalez @mgol  noticing that all of you are jQuery foundation members, please consider me for contributing/helping on this, as I find it really interesting and a first class opportunity of starting contributing on jQuery (even if it's in "deep waters").

**Comment by mgol** [comment]
@nicklou Sure, a PR would be welcome! Let us know if you have any questions.

**Comment by nicklou** [comment]
Ok, I have written some code, ready for pull request relevant to `ready.js`, wondering though if such functionality needs to be supported on `ready-no-deferred.js` - if you consider so, please tell me.

In general, what I have done is a small modification to `Deferred.then` function in `deferred.js`: I am passing another argument, called `onException`, a function takes one argument, the exception `error` object. I then wrap the `handler.appy(...)` inside `mightThrow` call that is responsible for the call of the fullfilment function with a `try-catch` clause, and call the `onException` in the `exception` block. I also have modified the `init.js` so that someone can pass the exception function using the `$(ready_handler, error_throwed_handler)`.

This is the logic I have followed in general. Please express any concerns on this, as I would like to make a pull request with code as much efficient as possible. Also, do I need to write a test for the functionality implemented?

Thank you in advance.

**Comment by mgol** [comment]
PR: #3210.
