### ISSUE TITLE
jQuery 3.0 breaks sourceMaps

### ISSUE THREAD

**Issue by pyalot** [jquery/jquery#3175]
### Description ###

jQuery 3.0's "error translation" does not take into account source maps, and generally malformats the traceback, making it harder to read exceptions.

**Comment by mgol** [comment]
Could you provide more details? Are you talking about the [Deferred's `exceptionHook`](https://github.com/jquery/jquery/blob/3.0.0/src/deferred/exceptionHook.js) or sth else?

**Comment by pyalot** [comment]
I'm talking about the fact that console.warn is used instead of bubbling the exception to the browsers exception handler which will nicely format the exception and display it with appropriate source map links.

I don't know what jQuery does excactly, but the "output" it produces trough its own console.warn is:

* Not foldable
* Not well formatted
* Hard to read
* Breaks source maps (i.e. does not link to the source appropriately)

jQuery should not translate errors that occur and prevent the browser from displaying them, that is very, very, very bad practice and unproductive for JS development.

**Comment by mgol** [comment]
How would you bubble the exception to the browser? [The Promises/A+ spec](https://promisesaplus.com/) that we're now following mandates that exceptions occurring in `.then` handlers have to be swallowed & turned into promise rejections so it doesn't go directly to the browser. The only thing we can do is to log it ourselves which we're now doing. Perhaps browsers could learn how to format the stack trace logged manually which would resolve the source map issue. Otherwise, we're open to proposals on how to improve the current situation but it's not that simple.

**Comment by pyalot** [comment]
If it comes down to a choice between being able to effectively develop or using promises, developing wins everytime. If the promises spec is unusable at its present state for development, then it shouldn't be used.

**Comment by mgol** [comment]
> If the promises spec is unusable at its present state for development, then it shouldn't be used.

This would be a good discussion to have a few years ago but now that ES6 promises follow this spec, most new DOM standards are written using these promises and almost every promise library follows it, we couldn't have maintained the previous jQuery behavior for interoperability purposes. Some libraries even started to blacklist jQuery's Deferreds because they weren't behaving interoperably.

The ship has sailed; we can try to improve the current situation as much as possible _while staying within a standard_ but we're not going to switch to a non-compliant implementation again.

**Comment by pyalot** [comment]
This is the situation. A library, or a retarded specification, breaking development is unacceptable, absolutely. If everybody involved in that "untertaking" didn't see that coming from a mile away, it's to be considered suspect, and harmful. Since jQuery now joined that club, apparently, it's considered harmful.

You cannot break JS development, ever, period, end of story, EOL, EOD, the end. If you do, you cannot expect people to continue using whatever crap breaks it.

I hope I make myself perfectly crystal clear.

**Comment by mgol** [comment]
Please read our [Code of Conduct](https://jquery.org/conduct/); be respectful and avoid words like "retarded".

Im going to close it now as this thread doesn't seem to bring any constructive proposals to the table.

**Comment by pyalot** [comment]
That's cool, you're willingly and maliciously breaking source maps and refuse to address the issue. Duly noted. Duly noted indeed.

**Comment by dmethvin** [comment]
Not true, we only refuse to address hostile, rude and impolite comments. We're discussing your other ticket in a civil way so far, please don't ruin that one.
