### ISSUE TITLE
 Under IE10 can't submit form with submit() method

### ISSUE THREAD

**Issue by XiaoMuCOOL** [jquery/jquery#3189]
Bug Reports:
   Under IE10 can't submit form with submit() method

### Description ###
//html code
&lt;button type="button" class="btn" onclick="importDate()">import&lt;/button>
&lt;form id="importDocForm" action="limitsetimportExcel" method="post" enctype="multipart/form-data" class="hide">
	&lt;input name="file" type="file" />
&lt;/form>

//js code
function importDate(){
	var file = $("input[name='file']");
	file.click();
}
var file = $("input[name='file']");
file.on("change",function(){
	if(file.val()!=null && file.val()!=''){
                //here: i want submit form,but it can't
		$("#importDocForm").submit();
	}else{
		alert('select file');
	}
});

If you can solve, I would be very grateful.

**Comment by pradeekyahvi** [comment]
if(file.val()!=null && file.val()!=''){ , what is the syntax here??,file.val()!=''

**Comment by mgol** [comment]
Could you please provide a test case that works in other browsers but not IE10 at https://jsfiddle.net/?

**Comment by dmethvin** [comment]
We can reopen if there is a good test case submitted.

**Comment by rogersillito** [comment]
I think I've just reproduced this - although I don't have time to submit a test case just now.  I'm using jquery-1.11.3.  My design involves:

1.  clone a form, call empty() on the cloned form
2.  append a hidden field to the clone 
3.  call submit() on the clone

To get this working in IE10, instead of just calling submit() - step 3, I had to:
- add a submit button to the cloned form
- append the cloned form to the document body
- call click() on the appended submit button

(workaround inspired [by this blog post](http://www.onvural.net/melih/thoughts/2010/07/jquery-form-submit-ie-bug/))
