### ISSUE TITLE
jQuery 3 - window load inside ready state will not be triggered

### ISSUE THREAD

**Issue by eisbehr-** [jquery/jquery#3194]
### Description ###
In jQuery 3.0.0 I got the issue, that a window load callback inside a ready state gets not triggered anymore. I think this is because it's async since 3.0.0. But this is used in jQuery plugins, to be only executed after all page content is loaded. And this is often wraped in a ready state by users.

### Example Code ###
https://jsfiddle.net/vpm59qws/
```JS
$(function() {
    $(window).on("load", function() {
        console.log("this will not be triggered");
    });
});
```

**Comment by dmethvin** [comment]
I agree this can happen, but not sure how to "fix" it without making ready completely synchronous again which brings back other demons.

**Comment by eisbehr-** [comment]
What does a ready state bring, if you can't execute all features in it?
As far as I know, it's best practice to wrap all stuff in such ready function. And I'm pretty sure `load` events are not that rarely used ...

**Comment by dmethvin** [comment]
It's definitely not best practice to wrap everything in a ready. Things that can be done outside a ready should be done there, such as initializing ajax requests, so you don't introduce unneeded delays. Similarly you can't "execute all features" just because the HTML document is ready. 

The tickets open because I also believe that there could be issues with this, but we'd prefer to act on evidence rather than incorrect assertions. See also gh-3197.

**Comment by eisbehr-** [comment]
It's not the problem that it is late or async. The problem is, that it will be executed never! It makes v3 pretty useless in my eyes, like for plugin developers. Because you can't prevent users to do things in a ready state. And such essential as a load event should always work.

I'm currently thinking about how to solve this even on an async execution. Maybe like tracking the load event within the library itself, and when something is bind to `load` afterwards, it will be executed immediately.

**Comment by dmethvin** [comment]
You're not adding any additional information here. Please stop. The reason it never executes is because ready occurs after the one-time load event occurs.

**Comment by john2014** [comment]
Hi Dave, this bug seemed unusual. So I did some more tests:

1. If we change $(window) to $(document), nothing fires https://jsfiddle.net/f73ar30v/1/

2. If we change $(window) to $("iframe"), nothing fires: https://jsfiddle.net/3hzy7Lrj/

3. If we change $(window) to $("body"), nothing fires

 Any idea why this is happening?

4. Really weird: Changing #1,#2,#3 back to $(window), nothing fires. Is this a bug with that website?

**Comment by timmywil** [comment]
To be clear, we understand what's causing this. We recently made ready handlers fire asynchronously. This has advantages that are hard to give up. The disadvantage is that the ready handler can sometimes fire after the load event if the load event fires quickly enough. The side effect you're seeing in this issue is that you're binding a load event handler after the load event has already fired.

The fix is to bind the load outside of ready.

```js
$(function() {
  // Things that need to happen when the document is ready
});

$(window).on("load", function() {
  // Things that need to happen after full load
});
```

**Comment by dmethvin** [comment]
@timmywil Agreed, and that ensures that the onload runs at all. However, it doesn't ensure that the ready code always and consistently runs before the onload code. I can imagine situations where that might be important, for example a plugin that initializes its DOM on ready but does some further work once the page has loaded entirely. We can recommend solutions for that but we need to document it. We should also determine whether there are cases that become hard to write (or existing code causing widespread breakage) because of the situation.
```js
$(window).on("load", function(){
   $.ready.then(function(){
      // Both ready and loaded
   });
})
```

**Comment by timmywil** [comment]
@dmethvin The load event is already "both ready and loaded", but I see what you mean.

Perhaps we could restore the "ready" event and give that the same treatment we give the "load" event. The behavior would differ from $(function(){}) in that we couldn't guarantee execution of multiple ready event handlers if one has an exception, but the behavior would be same as "load" event handlers.

**Comment by dmethvin** [comment]
> The load event is already "both ready and loaded", but I see what you mean.

Yeah, I'm counting on the async nature to defer the "both ready and loaded" code to the next turn, which gives the ready code a chance to run in the situation where it hasn't run yet, as we saw in gh-3197.

**Comment by scottgonzalez** [comment]
What is an actual use case for a plugin that must listen to the `load` event and the timing between `load` and `ready` matters?

**Comment by eisbehr-** [comment]
> What is an actual use case for a plugin that must listen to the load event and the timing between load and ready matters?

Additional content loading plugins often wait until all basic media is loaded, before start doing further actions, so they wait until `load`. And plugins are very often (_nearly always in the wild?!_) initialized in a ready state. And for plugin developers, there is no way to _break out_ a ready state. But it's not just plugins. It's every `load` event in a ready state that a developer out there wrote.

And it's not the timing in between, what's the problem. It's the fact that `load` inside of a ready state is never reached. What is even some kind of breaking change between 1.X/2.X and 3.X.

**Comment by scottgonzalez** [comment]
Those plugins should not be binding to `load` on initialization, which can happen many times within a single page. They should be binding immediately and tracking that internally.

As for the non-plugin case, I don't see why you would bind to `load` inside `ready`. Just bind to `load` and you'll be fine. Without specific use cases that require both, I see no reason to change anything.

**Comment by Anorionil** [comment]
This change broke code on our website. Basically we load HTML from the server using the load function. Inside this HTML is a `<script>` that is exectuted. This script used to always be executed before the onload callback triggered from the AJAX request.

Page script:

```
window.foo = {};
$element.load("test.php", function(){
  console.log(foo.bar);
});
```

On server:

```
<script>
$(function(){
  foo.bar = "test";
});
</script>
```

Log output:
`undefined`

We have quite a lot of code that is dependent on the order being consistent. It's a big enough change that we've decided to rollback to 2.2.4. We hope a change will be made in the next jQuery release to fix this.

If you need further information, let us know!

**Comment by dmethvin** [comment]
Ajax requests can complete before the document is ready. They may not be doing so in your code, on  your page, with jQuery 2.2.4, but it certainly can happen. This issue is about document ready versus window onload.

**Comment by nicklou** [comment]
Would it make sense for backward compartibility reasons to support two implementations, both sync and async, having ```on()``` being sync and adding an ```onAsync()``` to the API, with the recommendation of using the second one in the documentation?

**Comment by dmethvin** [comment]
Two implementations with different semantics just makes the problem worse though. As a plugin writer you don't know which one you're going to get. We'd also need to document that whole situation to explain it could either be sync or async. At that point the choice for a plugin that helps their users the most is to assume it's async so that the code works either way.

**Comment by eisbehr-** [comment]
@dmethvin I actually don't understand how this helps plugin developers anyway. You want to document the bahavior, okay. But for a developer this means, he can't use window load in a plugin anymore. Because the chance a user wrap it in a ready state is too high. What can a developer do, to prevent this situation whenever window load is needed or wanted in a plugin?

And telling the users to not use a ready state will maybe cause other problems. Imo you can't tell every user when to use ready, and load and when not. And then split it up to versions of jQuery too. For me, `load` is actually dead. I can't implement and use it anymore, because of this behavior. For now, I reverted all my projects back to 2.2.4 and ignore 3. And for plugins I have to evaluate the options first and see how to change them. I think I have to remove this event.

**Comment by dmethvin** [comment]
@eisbehr- @timmywil described one way to do it [above](https://github.com/jquery/jquery/issues/3194#issuecomment-228556922) and I described [a second way](https://github.com/jquery/jquery/issues/3194#issuecomment-228562930). If there are popular plugins that can't be fixed with one of those the authors can discuss other solutions with us.

**Comment by eisbehr-** [comment]
Both are not a solution for plugins, it only descripes the problem. A plugin can't break out this behavior, if the user wrote a ready state around initialization.

Like your solution: If I would write this in a plugin, how does it solve the problem, if the user put a ready state around it? If I'm right, the window load will not be triggered and everything is the same as before.

```JS
// plugin
$.fn.foo = function() {
    $(window).on("load", function() {
        // possible never reached
        $.ready.then(function() {});
    });
};

// user
$(function() {
    $(".bar").foo();
});
```

**Comment by scottgonzalez** [comment]
> A plugin can't break out this behavior, if the user wrote a ready state around initialization.

See https://github.com/jquery/jquery/issues/3194#issuecomment-228635307

**Comment by eisbehr-** [comment]
@scottgonzalez thanks for. Somehow missed it. But ...

> Those plugins should not be binding to load on initialization, which can happen many times within a single page. They should be binding immediately and tracking that internally.

What do you mean by "track this internally". I'm currently have no idea, how to track this. Can you provide me an example?

> As for the non-plugin case, I don't see why you would bind to load inside ready. Just bind to load and you'll be fine. Without specific use cases that require both, I see no reason to change anything.

Well, thats the point I mentioned before. A plugin developer can't prevent that the code is wrapped in a ready state. You're correct, window load alone would work in general.

**Comment by scottgonzalez** [comment]
```js
(function() {
  var windowLoaded = false;

  $(window).on('load', function() {
    windowLoaded = true;

    // If you need to do any initialize on window load, do it here.
    // If you need to run code per plugin instance on window load, then just
    // create a promise at the same scope as `windowLoaded` and resolve it here.
    // You can then add callbacks to that promise during plugin initialization.
  });

  $.fn.myPlugin = function(options) {
    // Do whatever you need to do on plugin initialization.
  };
})();
```

Again, without specific use cases, it's hard to say what you need to do. But there is no reason a plugin developer should ever be listening for the `load` event on a window inside the initialization of the plugin. That's just an incorrect implementation that happens to work for many pages.

**Comment by dmethvin** [comment]
In particular, if a plugin or other jQuery code is lazy-loaded on a page after the both the DOMContentLoaded and load events have fired, the plugin would never see the load event. The ready code will run of course, since it's not an event but instead a state. I think that makes this behavior enough of an anti-pattern that we shouldn't try to encourage it.

**Comment by timmywil** [comment]
We should document this anti-pattern.

**Comment by dmethvin** [comment]
Good point, I guess in the API entry for `.ready()`?

**Comment by timmywil** [comment]
Perhaps in `.load` as well. Maybe one of those warnings that can be shared between pages.

**Comment by Manoj-Roy** [comment]
I agree about @timmywil
