### ISSUE TITLE
API version unclear

### ISSUE THREAD

**Issue by yairEO** [jquery/jquery#3200]
Don't want to be a di*k about it, but it's unclear from the [API page](https://api.jquery.com/) to which jQuery version it applies to.

Clicking on the left menu (in "categories") on [jQuery 3](https://api.jquery.com/category/version/3.0/) leads you to a page pointing to the [upgrade-guide](https://jquery.com/upgrade-guide/3.0/)

it would be best if there was an easy UX way to change the API a user is viewing according to some dropdown selection by version, because right now I have no idea what API is for...

Thanks for reading!

**Comment by mgol** [comment]
Basically, every article applies to all jQuery versions. When there are API differences, it's described on the particular page (see the [.data() docs](https://api.jquery.com/data/) for example). If an API was [introduced](https://api.jquery.com/on/) or [deprecated/removed](https://api.jquery.com/live/), it's also mentioned to which versions those changes apply.

**Comment by dmethvin** [comment]
> Don't want to be a di*k about it, but it's unclear from the API page to which jQuery version it applies to.

If you go to any entry it tells you when the signature was added or removed.

> Clicking on the left menu (in "categories") on jQuery 3 leads you to a page pointing to the upgrade-guide

That's because the main reason to have a major version is the breaking changes. The upgrade guide describes the changes. many of which are subtle and difficult to describe in the context of the standard API docs. Many relate to undocumented behavior which we think some programs may be depending upon.

> it would be best if there was an easy UX way to change the API a user is viewing according to some dropdown selection by version, because right now I have no idea what API is for...

The API docs are available as XML which has all the data. If you have some ideas on how to display it in a different way you could [open an issue](https://github.com/jquery/api.jquery.com/issues) but it is probably not worth doing that unless you would like to do a significant amount of the design and work.
