### ISSUE TITLE
In Edge 14 Preview setting a style property to a whitespace-only value resets it to the default

### ISSUE THREAD

**Issue by mgol** [jquery/jquery#3204]
### Description ###
Edge 14 is breaking the jQuery 3.0.0 test suite in the Edge preview 14.14342.
```js
var style = document.createElement('div').style;
style.position = 'absolute';
style.position = ' ';
console.log(style.position); // logs '', should log 'absolute'
```
This works correctly if you set the property to a non-whitespaced invalid value like:
```js
style.position = 'fake property';
```
It also works fine in Edge 12 & 13 as well as any other popular web browser.

### Link to test case ###
https://jsfiddle.net/o9yee8yd/3/

I originally reported it at https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7961792/ but it was closed as "External" without any real further explanation. @jacobrossi @jdalton could you elaborate?

cc @dmethvin

**Comment by jdalton** [comment]
I believe I have an internal bug filed on this. I'll be able to dig it up Mon.

**Comment by mgol** [comment]
Great, thanks @jdalton! Please keep us posted.

**Comment by jdalton** [comment]
@mgol Does this effect jQuery APIs?

**Comment by jdalton** [comment]
\cc @FremyCompany

**Comment by FremyCompany** [comment]
Hey, I want t apologize for the comment that said the bug had been marked as External. I just had a look at our internal history for the bug, and what happened is that I duped this bug to an internal one (```Partner New Comments: Duping to our internal bug```) that was already tracking this issue, but that isn't exposed externally. Not sure which bot / person got it wrong, but we should investigate to make sure it does not happen anymore; I might have done something wrong.

That being said, John is asking the right question here. When this bug surfaced (~6 months ago), and while our first reflex was that we wanted to fix any regression impacting the jQuery test suite, we discovered like you did that only pure whitespace resulted in the issue. As such, it had been decided to prioritize other bug fixes on top of that one. Since we didn't hear of any report of the issue impacting a live site in further investigations, that decision wasn't reverted since then.

We definitely want to fix this bug, but it is extremely unlikely this will make it for the next release of Edge, which as you know is bound to happen soon, with the first anniversary of windows 10 approaching. 

Live sites suffering from this issue would definitely help defend the case for a fix but the window is closing rapidly.

**Comment by mgol** [comment]
I don't think this affects jQuery APIs outside of unit tests. That said, we usually try to have all supported browsers pass all tests if possible. Sometimes we make exceptions for browsers with fast release cycles like Firefox or Chrome as they can fix it faster than we could propagate our version with a workaround but Edge is not releasing that fast.

We might resort to doing a support test and mapping a pure-whitespace value to an empty one if the test failed.

I'll mark this for discussion within the Core team.

**Comment by mgol** [comment]
PR: #3308

**Comment by mgol** [comment]
The problem with this PR is that it treats all whitespace-only values as invalid and that's not always the case. For instance, there's very common `content: " "` on pseudo-elements. jQuery doesn't support setting/getting styles from pseudo-elements so that one may not be the most important but there are others like [list-style-type](https://developer.mozilla.org/en/docs/Web/CSS/list-style-type) which accepts custom values. Maybe Edge doesn't support any such property or maybe it only has this bug if a whitespace-only property is invalid; in any case, this PR is too dangerous.

We're just going to skip this one test in Edge 14. Hopefully it will be fixed in v15 (@jdalton, looking at you! ;)).

**Comment by mgol** [comment]
Edge 17 has fixed the issue, a relevant PR to restore the test there: #4101.
