### ISSUE TITLE
3.0.0: function camelCase does not check validity of input

### ISSUE THREAD

**Issue by IndexOverflow** [jquery/jquery#3211]
Upon upgrading from 2.2.3 to 3.0.0 my Angular application crashed. Turns out the error was caused from the "camelCase" function inside 3.0.0. Not sure exactly how, but it seems that through a selector the function is called upon with a "$scope" (object) as input. This causes a crash as the camelCase function assumes all input is a (valid) string. 

I'm not sure if this is something you want to be validated, and even if so nor am I sure on how you prefer to validate inputs (I used the built-in "$.type" to add validation).

https://jsfiddle.net/c32f6zbz/1/

**Comment by timmywil** [comment]
This looks like expected behavior to me. One of the changes we made in 3.0.0 was allowing invalid input to error, rather than failing silently. Failing silently can make it very difficult to debug issues–potentially serious ones. I don't think we need to change anything in jQuery, but I would consider opening an issue in Angular, if they haven't addressed it already. I suggest putting together a test case with angular to show them how $scope is getting passed to the camelCase function.

**Comment by mgol** [comment]
I have an Angular app that uses jQuery 3.0 and it works correctly. The Angular repo passes its unit & e2e test suites with jQuery 3.0 as well. Are you sure the problem doesn't lie in your code?
