### ISSUE TITLE
Event.relatedTarget = null in FF 47.0

### ISSUE THREAD

**Issue by rkralston** [jquery/jquery#3220]
### Description ###
`    jQuery(this.advanced_degrees.element.nativeElement).find('input.ui-select-search.input-xs')
      .blur((event) => {
        if (!event.relatedTarget || !event.relatedTarget.classList.contains('ui-select-choices-row-inner')) {
          this.waitForIt(this.advanced_degrees.clickedOutside());
        }
      });
`

This is TypeScript. event is a jQuery.Event object from the onBlur event. It is set in Chrome but not FF 47.0 or IE 11.0.10586.0

Just tested 3.0.0 with Chrome & same results.

### Link to test case ###

https://plnkr.co/edit/bbI3WvLK3pBIDxuinGqM

**Comment by dmethvin** [comment]
Your example doesn't seem to include jQuery?

**Comment by rkralston** [comment]
My bad, I was switching out versions and forgot to leave on in. I have readded 3.0.0. I tested all the way down to 2.0.0 with the same results.

**Comment by dmethvin** [comment]
I agree `event.relatedTarget` is null but it also looks like `event.originalEvent.relatedTarget` is null which is where it is copied from. If something is getting it wrong it's not jQuery. However I'm not sure you are focusing another element in which case the null is correct. (Search https://html.spec.whatwg.org/ for "related event target".) Try making a simple non-jQuery repro, and also see if the related target is correct if you focus into another form element for example.

**Comment by rkralston** [comment]
You have to focus another element to blur unless you click out of the browser window. In that case, a null is appropriate.





On Wed, Jul 6, 2016 at 3:40 PM -0500, "Dave Methvin" <notifications@github.com> wrote:





I agree `event.relatedTarget` is null but it also looks like `event.originalEvent.relatedTarget` is null which is where it is copied from. If something is getting it wrong it's not jQuery. However I'm not sure you are focusing another element in which case the null is correct. (Search https://html.spec.whatwg.org/ for "related event target".) Try making a simple non-jQuery repro, and also see if the related target is correct if you focus into another form element for example.

---

**Comment by rkralston** [comment]
I can get that element from chrome and ff and edge . I have to look elsewhere in ie 11 and safari.





On Wed, Jul 6, 2016 at 3:40 PM -0500, "Dave Methvin" <notifications@github.com> wrote:





I agree `event.relatedTarget` is null but it also looks like `event.originalEvent.relatedTarget` is null which is where it is copied from. If something is getting it wrong it's not jQuery. However I'm not sure you are focusing another element in which case the null is correct. (Search https://html.spec.whatwg.org/ for "related event target".) Try making a simple non-jQuery repro, and also see if the related target is correct if you focus into another form element for example.

---

**Comment by dmethvin** [comment]
> You have to focus another element to blur unless you click out of the browser window. In that case, a null is appropriate.

I don't think that's true, since the `body` ends before the `window` does. If you click in an area below the `body` but still inside the `window` you're not clicking on an `Element` but will still blur the input.

Regardless, can we agree that some browsers are not providing information to jQuery that can be used to identify `relatedTarget` and therefore this is not fixable inside jQuery? I've pinged some Mozilla folks for their opinion.

**Comment by cyberdees** [comment]
CC’ing Mozilla folks: @miketaylr @digitarald @bzbarsky @annevk @kentuckyfriedtakahe @cyberdees

**Comment by bzbarsky** [comment]
The `relatedTarget` for a blur event is the element that now has focus, no?

If you're clicking somewhere that doesn't actually take focus, so that nothing has focus after the click, then null seems appropriate.

I just tried a simple testcase like this:

    <input onblur="console.log(event.relatedTarget); setTimeout(() => console.log(document.activeElement), 0)">
    <input>
    Click the first input, then this text.

in Chrome and I get null for `relatedTarget`.  The testcase at https://plnkr.co/edit/bbI3WvLK3pBIDxuinGqM?p=preview (linked above) also has identical behavior in Firefox and Chrome...  So what's the Firefox issue, exactly?

**Comment by rkralston** [comment]
FF lists the next major release for having that parameter.

Based on the discussion, it seems the consensus that blur does not need this feature.

Here are some SO cases requesting it:
http://stackoverflow.com/questions/121499/when-onblur-occurs-how-can-i-find-out-which-element-focus-went-to
http://stackoverflow.com/questions/11544554/get-the-clicked-object-that-triggered-jquery-blur-event
http://stackoverflow.com/questions/4901899/action-on-blur-except-when-specific-element-clicked-with-jquery

Many others exist.

My use case is cleaning up Multi-selects and closing the list of options when the user clicks out.

Based on the discussion so far, it looks like I will need to implement a work around b/c blur is not going to support this?

It looks like @bzbarsky's code above is probably the best work around.

**Comment by dmethvin** [comment]
> Based on the discussion, it seems the consensus that blur does not need this feature.

I think the consensus was that `null` is valid for `event.relatedTarget` within a blur event in cases where no `Element` is going to receive focus, per [the spec](https://html.spec.whatwg.org/multipage/interaction.html#focus-management-apis). Maybe the test case isn't demonstrating the issue adequately?

I'm going to close this issue because I don't think there's a jQuery problem to be solved here, but if you find a case that works differently in plain DOM than jQuery feel free to post and we can re-evaluate.
