### ISSUE TITLE
Skip running ESLint on Node 0.x (was: Do not build jquery on 0.x node versions)

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#3222]
### Description ###
ESLint no longer supports those versions, so we are locked on 2.x, wouldn't bringing this up otherwise.
Big con about this is that most users use older 0.10 version. Big pro is that version will not be supported soon.

If we drop it, i suppose we can just document it? 

We support it as i recall because of the assumption that some people use custom builds in such environment, right?
To check this hypothesis we can look for the stats of custom builds and decide through them?

**Comment by mgol** [comment]
Too bad we didn't do it before the 3.0 release...

We haven't been running jsdom tests on Node <4 for a while and that includes Promises/A+ compliance tests so we're not actually testing if jQuery even runs in such a configuration; I assume it's only about building jQuery then and not using it? Our Jenkins server has recently switched to Node 4 on most projects so the infrastructure is taken care of.

I'd feel safer if, for now, until Node 0.10 & 0.12 is dropped by upstream (0.10 on 2016-10-01, 0.12 on 2016-12-31), we just skipped running ESLint on Node <4 (I assume it will install fine everywhere since it doesn't have native dependencies or postinstall hooks depending on a newer Node).

**Comment by markelog** [comment]
> we just skipped running ESLint on Node <4 

Yeah, we could do that, although it would require some hacking and unpleasantness in grunt file

**Comment by timmywil** [comment]
Per meeting, skip running eslint on Node < 4. Dropping these version from travis has been moved to the roadmap for later.

**Comment by mgol** [comment]
I'll take it.

**Comment by markelog** [comment]
Oh man, you thief! :).

Would you mind update eslint while you do it?

**Comment by mgol** [comment]
@markelog: Sure! PR readyL #3225.
