### ISSUE TITLE
jQuery.ajax() with cache: false mangles URL with _ parameter

### ISSUE THREAD

**Issue by FarSeeing** [jquery/jquery#3229]
`jQuery.ajax()` with `cache: false` option adds/replaces `_` parameter but it mangles URL with already defined parameter: when trying `example.com?_=1&foo=bar` the actual request with be sent to `example.com&foo=bar?_=...`

```javascript
// This works fine:
$.ajax({
  url: 'example.com?_=1&foo=bar'
});

// This fails:
$.ajax({
  url: 'example.com?_=1&foo=bar',
  cache: false
});
```

Tested with 3.x

[Test case](http://jsbin.com/medisokupo/1/edit?html,js,console,output)

Update: the original issue was about `cache: true` when it should be `cache: false`.

**Comment by dmethvin** [comment]
Confirmed, when `cache: false` is given it results in `example.com&foo=bar`. 

@FarSeeing is it a problem for your uses that we are removing the actual `_=1` parameter? Fixing this bug will still remove it.

**Comment by FarSeeing** [comment]
No, not a problem at all. The only thing that bothers me is that query parameters get malformed: `domain&params`

**Comment by dmethvin** [comment]
OK, good. I suspect this hasn't been noticed or reported before because our own code appends the cache buster to the end and that case works fine, even when the request is resubmitted.

**Comment by prmces** [comment]
Hi Guys, 

I also have the same problem. I found that the anti cache parameter is changed as the first parameter when a url is called twice in a row..

The first time is something like this.. 
Original: ?param1=0&param2=1
AntiCached:  ?param1=0&param2=1&_=123131231

The second request, we have this (See that the anticache parameter now is the first parameter)
Original ?_=123131231&param1=0&param2=0 
Anticached &param1=0&param2=1?_=123131231

I also saw a commit with some changes as ranticache and remptyquery variables on this issue.

I tried those changes in my code, but only worked when I changed the replace of the rantichache by a question mark "?". 
The ranticache regex is removing the first & after the ?_=123131231, and adding the ? as a character replacement will work because the replace(remptyquery,"") will do the job if the anticache parameter isthe last paramter.

cacheURL = cacheURL.replace(rantiCache, "**?**").replace(remptyQuery, "");

Hope it could help a little bit

Paulo Costa
