### ISSUE TITLE
.param() function ignores Set object

### ISSUE THREAD

**Issue by fetis** [jquery/jquery#3232]
Hi. It looks like .param() function used fro all AJAX requests ignores the Set object. Tested with 3.0.0 version.

Here's the code 

```
let s = new Set([1,2]);

let params = {
  set: s,
  arr: [...s]
}

console.log($.param(params))
```

Output is `"arr%5B%5D=1&arr%5B%5D=2"`. I'm expecting `"arr%5B%5D=1&arr%5B%5D=2&set%5B%5D=1&set%5B%5D=2"`

It's still the question should we serialize Set as Array. But I think it's the closest Set representation in case of GET request.

Here's the live demo http://codepen.io/fetis/pen/JKrdvX?editors=1111

**Comment by dmethvin** [comment]
The [API page](http://api.jquery.com/jquery.param/) says:

> Note: Because there is no universally agreed-upon specification for param strings, it is not possible to encode complex data structures using this method in a manner that works ideally across all languages supporting such input. Use JSON format as an alternative for encoding complex data instead.

It was never the goal of `.param()` to serialize every type of JavaScript object in some custom way, can you suggest improvements to that note to clarify?

**Comment by fetis** [comment]
I don't have improvements for note. And it sounds for me like talking about structures that comes from application logic, not from language itself.

I think we need to serialize Set object (and probably Map also).

My arguments're next:
1. It's standard JS object
2. jQuery already serializes another standard object - Array
3. The format can be same as in array
3. The more complex structures then set are serialized already, like this example from docs 
```
$.param({ a: { b: 1, c: 2 }, d: [ 3, 4, { e: 5 } ] });
// "a[b]=1&a[c]=2&d[]=3&d[]=4&d[2][e]=5"
```

**Comment by mgol** [comment]
Array is a very fundamental JavaScript object and it's JSON-compatible so we support it, for every other type we'd basically have to define serialization logic and it would be impossible to de-serialize it to the same complex type; that's why we're not doing it.

> The more complex structures then set are serialized already, like this example from docs
> ```
$.param({ a: { b: 1, c: 2 }, d: [ 3, 4, { e: 5 } ] });
// "a[b]=1&a[c]=2&d[]=3&d[]=4&d[2][e]=5"
```

This is not really a more complex structure; this is just an object that has objects and arrays as values. Such an object is easy to serialize.

**Comment by dmethvin** [comment]
Right, what's really happening here is that a `Set` is being converted to an `Array` for serialization. Rather than asking the API to pick one serialization method for `Set`, `Map`, `ArrayBuffer`, etc. and add code for that, it seems better to have the caller choose their preferred method, convert to an Array, then restore it back if that's what they want.

**Comment by fetis** [comment]
I got your point, guys. Currently JSON serialization for Set returns always empty set `{}`
So until it's not defined on browser level theer's nothing to do. I need to go and bump browser developers first :) Thanks for your time.
