### ISSUE TITLE
Simple ImageZoom jquery code not working in 3.1.0

### ISSUE THREAD

**Issue by rotsen49** [jquery/jquery#3241]
Hi 

I have been trying for two days now to make the ImageZoom jquery plugin to to work with 3.1.0 but have failed. It works very well in 2.1.4 and I have tried to use the migration tool 3.0 to find out where the error is but it points me to code that should not be firing. 

I am using the latest firefox browser.
 
The ImageZoom code is embedded in the fiddles
 
Not working with jquery-3.1.0:
https://jsfiddle.net/rotsen49/kq6ekw74/

Working with jquery-2.1.4:
https://jsfiddle.net/xg7dpLja/2/

Any help with my problem would greatly be appreciated.

Sincerely
Nestor G. Torres

**Comment by mgol** [comment]
Bugs in your code might be causing errors thrown from inside jQuery. In this case it's enough to look at the stack trace or to enable "Pause on exceptions" in Chrome DevTools and then going through the stack to your code; you'd see the error happens because of:
```js
$(this).offset();
```
in your code; please read: https://jquery.com/upgrade-guide/3.0/#breaking-change-invalid-input-to-the-offset-method.

Note that this kind of questions is better suited for Stack Overflow. We can't be debugging other peoples' code; bug reports should be based purely on jQuery code with small reproducible test cases, without use of external libraries.

**Comment by dmethvin** [comment]
Also it appears that plugin has been abandoned, it hasn't been updated in almost 2 years and has almost no interest in terms of watchers or stars.

https://github.com/0401morita/imagezoom-plugin

From a quick look at the code, it is using several deprecated and/or removed features. If you aren't able to fix them yourself you should find a different plugin that is actively supported by its author(s).
