### ISSUE TITLE
Checkbox check-uncheck through attr and removeAttr doesnt work for second time.

### ISSUE THREAD

**Issue by rishabhdev** [jquery/jquery#3242]
### Description ###
```
<div id="container">
  <input type="checkbox">
  <input type="checkbox">
  <input type="checkbox">
  <input type="checkbox">
</div>
<button type="button" id="addAll">add all</button>
<button type="button" id="removeAll">remove all</button>

```

```
$("#addAll").click(function() {
  $("#container input:checkbox").attr('checked', 'checked');
});
$("#removeAll").click(function() {
  $("#container input:checkbox").removeAttr('checked');
});
```

Running above code, for the checking unchecking second time nothing happens. Even though attributes are added and removed normally. Using native setAttribute and removeAttribute works fine.
### Link to test case ###

https://jsfiddle.net/jz5p57k9/

**Comment by dmethvin** [comment]
Can you link to your test case that includes a native version, so we can see the difference?

**Comment by rishabhdev** [comment]
https://jsfiddle.net/jz5p57k9/

**Comment by timmywil** [comment]
The checked attribute is only for setting the initial state of the checkbox, per the [spec](https://html.spec.whatwg.org/multipage/forms.html#attr-input-checked). It seems that browsers are ignoring this, but I still recommend using `.prop('checked', true)` instead of `.attr`. However, there is no difference in behavior with [jQuery edge](https://jsfiddle.net/timmywil/7vjy63qv/), so this is not an issue with current code.

**Comment by timmywil** [comment]
Or, perhaps the [dirty checkedness](https://html.spec.whatwg.org/multipage/forms.html#concept-input-checked-dirty) is only changed when the checked IDL is changed. Click a checkbox and it should not be changed by add/removeAll.

**Comment by timmywil** [comment]
In 2.1.4, we were still setting the `checked` IDL along with the attribute, for back-compat. Makes sense that 3.0+ works as expected.
