### ISSUE TITLE
Expressions of form $superset.not($subset) are incorrectly length 0

### ISSUE THREAD

**Issue by jimevans4000** [jquery/jquery#3243]
### Description ###

Expressions of form $setDiff = $superset.not($subset) are incorrectly length 0, when the JQ objects have string contents.  Works correctly with DOM contents.

EXPECTED: $setDiff has all items in superset that are not in subset
ACTUAL: $setDiff is empty when elements are strings.

In (at least) Win7 Chrome and FF, this works correctly in 2.2.4, but not 3.0.0 or 3.1.0.  See minimal test case below.

### Link to test case ###
http://jsbin.com/dizixiduhe/2/edit?html,js,output

**Comment by mgol** [comment]
An array of string is not supported as an input to `jQuery` so the result of passing such an array is undefined. See https://api.jquery.com/jQuery/ for what's supported.

**Comment by jimevans4000** [comment]
Digging a bit more, this is a dupe of #3147 .  

As that filer noted, this would merit a mention in the [3.0 Upgrade Guide](https://jquery.com/upgrade-guide/3.0/) , as this usage has been widely advocated on sites like SO, including accepted answers with hundreds of upvotes, which are among the top results when googling [jQuery set difference](https://www.google.com/search?q=jQuery%20set+difference).

I see that those SO results have been recently edited to say "no longer works in JQ3", but that doesn't help all the people who are upgrading existing code.  For them, a note in the upgrade guide would be appropriate (and would have saved us some time).

May I suggest that this be reopened as a doc bug, to update the Upgrade Guide?

**Comment by mgol** [comment]
I'm not sure if we should dive into undocumented APIs in the upgrade guide... In any case, the repo for the jquery.com site, where the upgrade guide is located, is at https://github.com/jquery/jquery.com/; if you want to discuss documenting the change somehow, that's the correct place.

**Comment by dmethvin** [comment]
@jimevans4000 If the note was in the upgrade guide, would you have found it? If people are getting the "answer" on SO I'm not sure that a note in the upgrade guide will help fix that.

There are a lot of mediocre StackOverflow answers using undocumented functionality or giving just plain bad advice. If you used a particular answer can you post a comment in the SO thread asking that it be edited by someone to reflect that it's unsupported, regardless of jQuery version? That is, it has always been wrong even if it happened to work in the past.

Issues can be filed against the upgrade guide at https://github.com/jquery/jquery.com/issues  but even better would be to make a PR since I'm not sure how to address this with words in the upgrade guide. jQuery has never been a replacement for lodash or underscore, any usage of the sort in that example is way outside jQuery's intended use as a DOM library.

**Comment by jimevans4000** [comment]
>  If the note was in the upgrade guide, would you have found it?

@dmethvin  Actually, yes.  When upgrading, we scanned our codebase for each issue noted in the Guide.  

>  If people are getting the "answer" on SO I'm not sure that a note in the upgrade guide will help fix that.

The upgrade guide helps with the case where the code (from SO or wherever) was written months or years ago, and now the upgrade means it won't work anymore.  

>  I'm not sure how to address this with words in the upgrade guide. 

I'll give that some thought.  If I can come up with something worthwhile, I'll file an issue or PR as you suggested.

Of course, this is not such a big deal now that it's established that it's not a code bug.  I appreciate all the prompt responses!
