### ISSUE TITLE
Deferred failFilter and exceptionHook not called for exception in doneFilter

### ISSUE THREAD

**Issue by mkleehammer** [jquery/jquery#3264]
jQuery 3.1.0

      var p = new $.Deferred();
      p.then(function() {
        console.log('in then');
        throw new Error('error');
      }, function() {
        console.log('in fail');
      })
        // .catch(function(reason) {
        //   console.log('in catch:', reason);
        // });
      p.resolve();

When this is executed, an exception is thrown in the done filter, but since the fail filter is not called nothing is logged (specifically the "in fail" does not get logged).

I was hoping "in fail" would be called.  If I add the catch, it *does* get called.

I'm not sure what is supposed to happen here, but I can say it is very difficult to debug Deferreds now.  I know the upgrade guide recommends adding catches everywhere, but it is sometimes difficult when dynamically chaining promises.

**Comment by mkleehammer** [comment]
I forgot to mention, the example also does not call Deferred.exceptionHook.  That's what made is so difficult to find.

**Comment by dmethvin** [comment]
When an error is thrown in a `.then`'s first function, it's important to realize the *promise has already settled* (resolved or rejected). The second function to `.then` only applies *before the promise settles* so that is why your code is not called, and why a later `.catch` executes. This is standard Promise/A+ behavior so it would be best to discuss and explore somewhere like StackOverflow. We are only implementing it as it's been defined.

The reason `Deferred.exceptionHook` is not called is because you explicitly did a `throw new Error()` rather than this being an error such as `SyntaxError` or `RangeError` implicitly thrown by the browser and indicative of a programming mistake. If you are explicitly throwing generic `Error`s you should `.catch` them further down the chain.

If jQuery logged a message by default in cases where people used `throw new Error()` for signaling, the console verbosity would be very annoying. However, you can [override `Deferred.exceptionHook`](https://github.com/jquery/jquery/blob/76c5237cc408c01ae67f5c68d39ed6f1e4ef8003/src/deferred/exceptionHook.js) to do exactly that if you want.

**Comment by mkleehammer** [comment]
Thanks.  This was example code, of course.  The actual exception was raised by Handlebars for a misspelled / unknown helper (e.g. "{{bogus xyz}}") so I don't remember the actual type.

I'll override exceptionHook - I forgot it whitelisted exceptions to log.

On that topic, though, it isn't clear to me why it would be annoying to log all uncaught errors.  (Perhaps I'll find out once I override ;). Is that a common pattern or something?  In my case, it was an exception that I forgot could happen so I would really want to know about it.  Perhaps switching from a whitelist to a blacklist would be help people catch more errors.

Anyway, thanks for the reminder about how exceptionHook works.

**Comment by dmethvin** [comment]
> On that topic, though, it isn't clear to me why it would be annoying to log all uncaught errors. (Perhaps I'll find out once I override ;). Is that a common pattern or something? 

The problem is knowing when a rejection is truly uncaught. There is no rule saying that a `.catch()` has to be attached to a promise immediately, so an exception may cause the promise to reject before the `.catch()` is attached. 

It's possible to do the bookkeeping required to track exceptions over time like this, but it's also quite a bit of code.  Instead of burdening everyone with that code, jQuery added a couple of hooks. Native ES6 Promise implementations can do this better since they don't have the same size/perf constraints as jQuery, so if you only need to support about [75% of the installed base](http://caniuse.com/#feat=promises) you could use `Promise.resolve(deferred).then(...)` etc.

**Comment by cums4you69** [comment]
Stop sending me emails
