### ISSUE TITLE
$.when.done in 3.x breaks backward compatibility with 2.x

### ISSUE THREAD

**Issue by kvet** [jquery/jquery#3296]
### Description ###

How to maintain full compatibility for existing code with 3.x release. In attached example is shown case where $.when behaves absolutely different with 2.x release.

We have to support both versions of jQuery 2.x and 3.x, but now we see only one way - write own version of $.when that behaves same in both versions.

### Link to test case ###

2.x - https://jsfiddle.net/mpcteamkvet/qh6Lfhzn/
3.x - https://jsfiddle.net/mpcteamkvet/jmykr166/

**Comment by dmethvin** [comment]
We're allowed breaking changes in major version updates, so that's not a problem. 

The main issue is that long ago we defined `$.when()` to play the role of both `Promise.resolve()` and `Promise.all()`. Our long term goal is to split those apart but for now when you call `$.when()` with one arg it's similar to `Promise.resolve()` and otherwise its `Promise.all()`. So you can get consistent behavior across versions with this change, maybe @gibson042 has other suggestions.
```js
$.when(d1, 1).done(function() {
	console.log(2);
});
```
References:
 - https://jquery.com/upgrade-guide/3.0/#breaking-change-and-feature-jquery-when-arguments
 - http://api.jquery.com/jquery.when/ (note mentions of "single" and "multiple"
 - https://github.com/jquery/jquery/issues/3102#issuecomment-216628681

**Comment by gibson042** [comment]
@dmethvin is right. See https://github.com/jquery/jquery/issues/3149#issuecomment-224748406 for details.
