### ISSUE TITLE
[v1] Safari bug - $option.attr('selected', 'selected')

### ISSUE THREAD

**Issue by Andarist** [jquery/jquery#3298]
Code is far from ideal, I've found it in our legacy code and this bug was really hard to track as we get reported this issue from our customer and couldn't reproduce it for a while.

Test case:
https://jsfiddle.net/6y091fqq/3/

It's working in Chrome, but aint in Safari (Version 9.0.2 (11601.3.9) on OS X). I've fixed it by just using `$('select').val(value)`. But thought it might be addressed at the core.

**Comment by mgol** [comment]
The `.attr()` setter doesn't work that well with dynamic input properties; we've been warning against it since jQuery 1.9: https://jquery.com/upgrade-guide/1.9/#attr-versus-prop-

There have been other similar issues, e.g. #3180. Fixing issues like that consistently would be hard and it's a misuse of the API anyway so we direct people to `.prop()` itself.

**Comment by dmethvin** [comment]
All developers need to understand the difference between *attributes* and *properties*. the same way they need to understand the difference between *HTML* and *DOM*. Yes it can be confusing, jQuery's early attempts to hide the difference just made things worse.
