### ISSUE TITLE
`:visible` changes in `2.2.X`

### ISSUE THREAD

**Issue by kirschre** [jquery/jquery#3338]
I'm working on updating an application from jQuery `2.1.1` to `2.2.4`. In doing so I noticed that some of our `:visible` selectors were failing with the newer version - specifically in cases where we have an empty span (with no height and no width, due to its children using e.g., `display:none`).

The docs for [:visible](https://api.jquery.com/visible-selector/) do state that this change would come into effect with jQuery `3.0.0`, but it seems to have gotten applied to `2.2.X` as well (see: 79bcb29), which was breaking for my application.

Here's a [jsbin](http://jsbin.com/yagemefeji/1/edit?html,js,output) demonstrating the issue.

First observe that with jQuery `2.1.4` loaded, each of the test cases are not considered `:visible`, which is consistent with the docs, given that each has a size of `0x0`. Then change the jQuery version to `2.2.4` and note that now all but one case is considered `:visible`, despite the element size not having changed.

**Comment by timmywil** [comment]
Thanks for opening an issue! However, considering how finicky the `:visible` selector has always been, I can't say this is a critical bug. And the 2.x branch is now only receiving critical patches. The workaround here is to either stick with 2.1.1, edit the visible selector in user code, or use a [filter](http://api.jquery.com/filter/) instead-recommended. http://jsbin.com/pewedo/edit?html,js,output

I think the 2.2.4 and 3.x code is technically more correct because we are determining visibility in a way more in line with what the browser thinks of as visible (through the use of `getClientRects`).

Finally, browser support is the same between the 2.x and 3.x branches. I would recommend upgrading to jQuery 3.1.1. The [upgrade guide](https://jquery.com/upgrade-guide/3.0/) and the [migrate plugin](https://github.com/jquery/jquery-migrate/#README) can help a lot if you encounter any issues.

**Comment by mgol** [comment]
> Finally, browser support is the same between the 2.x and 3.x branches.

"the same" is a little stretch; we've dropped Opera 12.1x, Safari older than "Current - 1" & iOS 6 in jQuery 3.0.0. Those browsers have very limited market share currently, though; what's important is IE version support is the same so very few people should be blocked by us dropping these few browsers in 3.0.

**Comment by kirschre** [comment]
Thanks for the info - I'm planning on upgrading to jQuery 3, so I knew I would have to make these changes at some point anyway. Just wanted to bring it to your attention.

I agree that `getClientRects()` seems like a more correct way to check visibility than directly checking the element size. At the same time, out of curiosity, what's the rationale for considering an element with a `0x0` bounding box as visible? The distinction between "has no bounding box" and "has a bounding box with no size" doesn't seem very significant to me. If you had any relevant issues/docs/resources handy I'd be interested in skimming them.
