### ISSUE TITLE
:invalid pseudo selector is not recognized on a certain case

### ISSUE THREAD

**Issue by maisumakun** [jquery/jquery#3350]
### Description ###

`$('input,select,textarea').filter(':invalid')` causes Following error:

```
Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: invalid
```

`:invalid` is a [pseudo class defined in HTML5](https://www.w3.org/TR/html5/single-page.html#selector-invalid), and for some usage `:invalid` works well (like `$('input:invalid')`).

### Link to test case ###

[jsFiddle](https://jsfiddle.net/83y4sj61/)

* jQuery version - 3.1.1, 2.2.4
* Browser - Google Chrome 53.0.2785.143 m (64-bit), Firefox 49.0.1 (Both on Windows 7 x64)

**Comment by gibson042** [comment]
`:invalid` is not a selector currently supported by Sizzle, and therefore not by jQuery: http://api.jquery.com/category/selectors/ . But it will work with `jQuery(…)` selections on many clients (though [not IE9](http://caniuse.com/#feat=form-validation)) because that call relies upon `querySelectorAll`.
