### ISSUE TITLE
$.param() and mixed item array indexing

### ISSUE THREAD

**Issue by nocon** [jquery/jquery#3358]
Hi, I'm facing an issue with the way $.param() serializes arrays containing mixed items. If my array contains both strings and complex objects, only complex objects receive proper indexes, while strings just have []. This doesn't play well with my backend's model binding (I use .NET MVC).

Example:
`var model = { items: [
    { item: "indexed"},
    "<- why is there no index here?",
    { item: "indexed"}
	]
};
console.log(decodeURIComponent($.param(model)));`

https://jsfiddle.net/bv5r1qr4/.

Is this behaviour intended? Is it possible to force indexing of all items?

**Comment by dmethvin** [comment]
That's a really strange data structure.

Note that there's no standard governing how a complex data structure should be serialized to a querystring, since that kind of thing never happens in an HTML form.

This is essentially a dup of #3286. My advice for a workaround would be to either serialize the information yourself using `jQuery.param()` or restructure the data to be regular.
