### ISSUE TITLE
Closure declaration ready state not working 

### ISSUE THREAD

**Issue by Karan1458** [jquery/jquery#3360]
Browsers affected : Chrome, Safari and Vivaldi(1.4.589.38)
jQuery versions : 1.12.3, 1.12.4 
Websites Platform : WordPress
### Description ###
Closure declaration for ready state is not working properly. affected my many websites. 

Generally, I used to declare the jQuery code as 
`(function($) {
    "use strict";
    // all coding here
})(jQuery);
`

From few days, this thing stops working. Now, I forced to use the following : 
`jQuery(document).ready(function($) {
          //all coding here
});`

### Link to test case ###
jsbin code : 
http://jsbin.com/yidemiloqa/edit?html,js,console,output

For some reasons, I can't share the other sites coding.

Thank you

**Comment by gibson042** [comment]
Thank you for reporting an issue with a test case. However, it appears to be working as expected (in that the event handler is registered but throws a "services_vars is not defined" ReferenceError when invoked, since `services_vars` is in fact not defined). As to your topic, the recommended pattern for executing code upon DOM ready is [`jQuery( callback )`](http://api.jquery.com/jQuery/#jQuery3): http://jsbin.com/cucerefono/edit?html,js,console,output

Because there doesn't appear to be an issue with jQuery itself (and even if there were, we're no longer supporting the 1.x or 2.x lines), I think you'll find better help at [StackOverflow](http://stackoverflow.com/questions/tagged/jquery).
