### ISSUE TITLE
delay() bug

### ISSUE THREAD

**Issue by wmlgl** [jquery/jquery#3381]
### Link to test case

http://sandbox.runjs.cn/show/z35h7tre
### browser

MS Edge 25.10586
Chrome 51.0.2704.106 m

**Comment by krshubham** [comment]
[An alternate fix](https://output.jsbin.com/fapoqasixi)

Due to the async nature of the setTimeout function, it just leaves the function being called into stack trace and since you have both the values of stop function set to true which means that it takes it to the end of the any animations present in the stack.

Hence, to come over it just call the functions with same values in pair.

Hope this helps!

**Comment by timmywil** [comment]
I'm not sure the practical use case here. Either use `delay` or `setTimeout`. Trying to interrupt the `delay` seems like it could cause issues that I don't think we should be guarding against.
