### ISSUE TITLE
jQuery Validation Plugin considers multiple empty space as valid to pass required field validation

### ISSUE THREAD

**Issue by cheonhyangzhang** [jquery/jquery#3390]
Bug Reports:
  *  Required fields should mean user need to input something. Just putting spaces should not pass required validation.
  *  https://jqueryvalidation.org/files/demo/ Try in the demo, when put name field with only a few spaces, then click "submit" no error message showed. It thinks input with spaces only pass the required validation.
  *  I believe this happens across all browser.

Test cases and test site is provided above.

### Link to test case ###
 https://jqueryvalidation.org/files/demo/

Source code can be views
http://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.js

**Comment by mgol** [comment]
Thanks for the report. However, the code for the jQuery Validation plugin is maintained at https://github.com/jzaefferer/jquery-validation so please submit the issue there.

**Comment by cheonhyangzhang** [comment]
@mgol   oops  sorry wrong place. Thanks for the link for right repo.

**Comment by 123jhon** [comment]
Enviado desde mi smartphone BlackBerry 10.                                                                                                                                                                                                                De: Michał GołębiowskiEnviado: lunes, 7 de noviembre de 2016 04:55 p.m.Para: jquery/jqueryResponder a: jquery/jqueryAsunto: Re: [jquery/jquery] jQuery Validation Plugin considers multiple empty space as valid to pass required field validation (#3390)Thanks for the report. However, the code for the jQuery Validation plugin is maintained at https://github.com/jzaefferer/jquery-validation so please submit the issue there.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jquery/jquery","title":"jquery/jquery","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jquery/jquery"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mgol in #3390: Thanks for the report. However, the code for the jQuery Validation plugin is maintained at https://github.com/jzaefferer/jquery-validation so please submit the issue there."}],"action":{"name":"View Issue","url":"https://github.com/jquery/jquery/issues/3390#issuecomment-258975038"}}}


Declinación de Responsabilidades: Los servicios de MISENA son soportados tecnológicamente por © Google y ofrecidos por el Servicio Nacional de Aprendizaje – SENA de manera gratuita a los aprendices e instructores de programas de formación titulada, las opiniones que contenga este mensaje son exclusivas de su autor y no representan la opinión del Servicio Nacional de Aprendizaje o de sus autoridades. El receptor deberá verificar posibles virus informáticos que tenga el correo o cualquier anexo, razón por la cual el SENA no es responsable de los daños causados por cualquier virus transmitido en este correo electrónico.Los contenidos, textos, imágenes, archivos enviados en este mensaje son responsabilidad exclusiva del remitente y no reflejan ni comprometen de ninguna manera a la institución. No se autoriza el uso de esta herramienta para el intercambio de correos masivos, cadenas o spam, ni de mensajes ofensivos, de carácter político, sexual o religioso, con fines de lucro, con propósitos delictivos o cualquier otro mensaje que se considere indebido o que vaya en contra de la Ley.
