### ISSUE TITLE
Can't use $(this) in each() function

### ISSUE THREAD

**Issue by IFEIFEI** [jquery/jquery#3391]
If I use jquery like this 

```
dom=$(doc) //doc is a string of html code 
dom.find(selector).children("input").each(e=>{
  console.log($(this).text());
});
```

In this code segement,I can't use this to get the proper text of the input element.

**Comment by mgol** [comment]
This is just how arrow functions work - they don't have their own `this` binding so it can't point to the current element. You can always use the first arrow function parameter (`e` in your code) instead of `this`.

In any case, there is no jQuery issue here. Please direct further queries about such topics to Stack Overflow or jQuery Forums. Thanks!
