### ISSUE TITLE
jqXHR.getResponseHeader

### ISSUE THREAD

**Issue by PSPvZ** [jquery/jquery#3403]
### Description ###

jqXHR.getResponseHeader fails to combine multiple HTTP headers with the same name. Instead, it only returns the value of the last HTTP header. This clashes with the specification of [XMLHttpRequest.getResponseHeader](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getResponseHeader), which states: "If there are multiple response headers with the same name, then their values are returned as a single concatenated string, where each value is separated from the previous one by a pair of comma and space."

The issue seems to occur only on Internet Explorer (I encountered it on IE11); calling IE's own XMLHttpRequest.getRequestHeader implementation does return the correct result, 

 From what I can tell Firefox 50 already combined the two headers into one before calling the XMLHttpRequest completion callback, inadvertently allowing jQuery to return the correct result.

Tested in jQuery 3.1.1.

### Link to test case ###

I have no test-environment that can easily set multiple headers with the same name, unfortunately.

**Comment by gibson042** [comment]
The problem seems to be misimplementation of [`getAllResponseHeaders`](https://xhr.spec.whatwg.org/#the-getallresponseheaders()-method) (on which we [rely](https://github.com/jquery/jquery/blob/f18ca7bfe0f5e3184bf1ed55daf1668702c5577a/src/ajax/xhr.js#L109)) in at least IE11, but I otherwise agree with this assessment.

@PSPvZ, would you be willing to submit a PR updating our [`getResponseHeader`](https://github.com/jquery/jquery/blob/f18ca7bfe0f5e3184bf1ed55daf1668702c5577a/src/ajax.js#L461) to something like `responseHeaders[ match[ 1 ].toLowerCase() ] = (responseHeaders[ match[ 1 ].toLowerCase() ] || []).concat( match[ 2 ] ); … return match == null ? null : match.join( ", " )`?

**Comment by pankajpatel** [comment]
Hello,
I tried to create a test for this which can be seen here: http://jsbin.com/vofipib/edit?js,console
Can I contribute on this issue?

**Comment by gibson042** [comment]
> Can I contribute on this issue?

Yes! https://contribute.jquery.org/commits-and-pull-requests/

**Comment by Andrei15193** [comment]
> The problem seems to be misimplementation of [`getAllResponseHeaders`](https://xhr.spec.whatwg.org/#the-getallresponseheaders()-method) (on which we [rely](https://github.com/jquery/jquery/blob/f18ca7bfe0f5e3184bf1ed55daf1668702c5577a/src/ajax/xhr.js#L109)) in at least IE11, but I otherwise agree with this assessment.
> 
> @PSPvZ, would you be willing to submit a PR updating our [`getResponseHeader`](https://github.com/jquery/jquery/blob/f18ca7bfe0f5e3184bf1ed55daf1668702c5577a/src/ajax.js#L461) to something like `responseHeaders[ match[ 1 ].toLowerCase() ] = (responseHeaders[ match[ 1 ].toLowerCase() ] || []).concat( match[ 2 ] ); … return match == null ? null : match.join( ", " )`?

@gibson042, done: https://github.com/jquery/jquery/pull/4173
