### ISSUE TITLE
Should not be catching and then re-throwing "ready" exceptions

### ISSUE THREAD

**Issue by david-mark** [jquery/jquery#3427]
### Description ###

Catching and then re-throwing exceptions has two issues:

1. Makes finding and correcting mistakes much harder. Need a live stack trace and paused code, not a later report logged by a timeout (which isn't of much use for debugging). Most app code exists (or at least starts) in "ready" callbacks, so this is absolutely crucial.

2. It allows the app to continue when we know it is in an unknown state. That's bad news in development and in production. An exception should stop the show *immediately*.

Already know the counter-argument and the answer is simply: the `ready` method is not a "polyfill". We don't have to mimic browsers to a T here (and doing so creates the above issues).

The re-throw is a recent change, but it does very little to address the issues that always existing in catching exceptions in "ready" callbacks.

Will correct the related code in my fork shortly.

### Link to test case ###

There is no test case for this. It's simply an undesirable behavior that should be corrected.

**Comment by mgol** [comment]
Since jQuery 3.0.0 `jQuery(callback)` will always execute the callback asynchronously; previously it was sometimes doing it synchronously and sometimes not which makes for a confusing API so we decided to make it uniformly async. We don't plan to change this behavior back.

What's hard in finding the issue? While you'll get less of the stack trace from jQuery, you should still see the line that threw the error so debugging it shouldn't be harder.

For example, with this `test.js` running after the DOM was ready:
```js
jQuery( function() {
	throw new Error();
} );
```
in jQuery 2 you'd see:
<img width="409" alt="screen shot 2016-12-04 at 01 46 25" src="https://cloud.githubusercontent.com/assets/1758366/20863200/8471ed2a-b9c3-11e6-9bba-c63a3960a478.png">
and in jQuery 3:
<img width="297" alt="screen shot 2016-12-04 at 01 46 19" src="https://cloud.githubusercontent.com/assets/1758366/20863202/8bc23558-b9c3-11e6-8e26-b8a1e9fc3f21.png">

The jQuery 3 version doesn't hide any important information IMO.

**Comment by david-mark** [comment]
> What's hard in finding the issue? While you'll get less of the stack trace from jQuery, you
> should still see the line that threw the error so debugging it shouldn't be harder.

It's not just about debugging as the code should stop immediately. Once one "ready" callback goes, it's time to halt. What possible reason is there to continue once the code has gone off the expected path?

This goes for all callbacks. As for debugging, it's far better to catch the issue so you can inspect variables. This comes from experience. Consider that some exceptions may occur sporadically, in which case you will be out of luck if it doesn't recur immediately. It comes from experience debugging complex applications. It's not practical to break on caught exceptions (in debuggers that allow that option) and it sucks when a caught exception allows the rest of the code to proceed and possibly obscure the cause.

**Comment by mgol** [comment]
> It's not just about debugging as the code should stop immediately in any event.

There is a lot in JavaScript that happens asynchronously and, as a rule, an uncaught error in async code doesn't stop code execution outside of the current async context. This doesn't have a lot to do with jQuery but with the language itself.

> Ultimately, it comes down to why catch them at all?

I've already answered that question. We want the callback to be always invoked asynchronously instead of sometimes synchronously and sometimes not. We don't plan to change that back.

Thanks for your suggestion but since it seems that this issue is about making the ready back sometimes synchronous and we don't plan to do it, I'm going to close it.

**Comment by david-mark** [comment]
> There is a lot in JavaScript that happens asynchronously and, as a rule, an uncaught error in
> async code doesn't stop code execution outside of the current async context. This doesn't
> have a lot to do with jQuery but with the language itself.

That's false. Unless using workers, ECMAScript is single-threaded. ;)

> I've already answered that question. We want the callback to be always invoked
> asynchronously instead of sometimes synchronously and sometimes not. We don't plan to
> change that back.

None of that has anything to do with catching exceptions. In fact it's even more important to catch them during asynchronous operations where the cause will likely be harder to track down later. These are the ones that can be sporadic as well.

> Thanks for your suggestion but since it seems that this issue is about making the ready back > sometimes synchronous and we don't plan to do it, I'm going to close it.

I'm afraid you have completely missed the point here. :(

**Comment by dmethvin** [comment]
> Once one "ready" callback goes, it's time to halt.

Gack, no! We don't want the ready handler be a single point of failure for the entire page. We were there in previous versions and it caused a lot of trouble. Note also that the native DOMContentLoaded events do not behave this way, they continue to run additional handlers even if previous ones throw errors. We are aligning our behavior with that. 

>  What possible reason is there to continue once the code has gone off the expected path?

The reason is that on a modern web page, "the code" often isn't written by one person. It's a combination of plugins or code fragments that work independently on different parts of the page and have different ready handlers. In the face of hostile code such as ad blockers and browser add-ons there is a good chance that something will break on some combination of browser, platform, and add-ons. I do not want my charitable donation form to break just because of a rare failure in a tooltip plugin that is not essential to the functionality of the page.
