### ISSUE TITLE
Multiple scripts on domManipulation appendTo with uiDialog

### ISSUE THREAD

**Issue by PhoenixFnX** [jquery/jquery#3431]
I'm opening this issue from a file comment to @timmywil.
I'm using jquery and jqueryui and a post request that appends a result in a dom element.
I didn't manage to get it simpler

```
<script type="application/javascript">
	$(function () {
		$.post("test2", function (data) {
			$(data).appendTo($("#container"));
		});
	})
</script>
<div id="container"></div>
```

When the post requests returns : 

```
<div id="the_dialog" style="display: none;">
	<script type="text/javascript">
		$(function () {
			$('div#the_dialog.ui-dialog-content').dialog("destroy").remove();
			$("div#the_dialog").dialog();
		});
		alert(1);
	</script>
	<script type="application/javascript">
		alert(2);
	</script>
	Hello
</div>
```

There is no alert(2).

This line 185 prevent the response from running the alert(2). 
https://github.com/jquery/jquery/blob/2.2.4/src/manipulation.js#L185

When I debug after the alert(1), I'm having this screenshot :
![image](https://cloud.githubusercontent.com/assets/993122/20844094/7a3a4c4a-b8be-11e6-9fa6-1919d32f2076.png)

You can see there are 2 scripts but the second one gets `dataPriv.access( node, "globalEval" ) == true`

**Comment by gibson042** [comment]
Works for me: https://jsfiddle.net/9k3ztm42/

Can you try tweaking that fiddle until you recreate the failure?

**Comment by markelog** [comment]
Since there is no response from owner of the ticket for quite some time now, i'm closing this

**Comment by PhoenixFnX** [comment]
Hello, 

Sorry for being toolong.
Can you have a look to this fiddle ?

https://jsfiddle.net/jk54y34q/

**Comment by gibson042** [comment]
Here's an abridged summary of what happens for `$( htmlText ).appendTo( element )`:
* Construct nodes from the HTML text
* Identify (and temporarily disable) contained script elements
* Insert nodes into the DOM
* For each script (in order),
  * Re-enable
  * If in-document and not already evaluated, evaluate

BUT in this case, the first script invokes jQuery UI's `.dialog()` on an ancestor of later scripts _before_ they are evaluated, which applies DOM manipulation to the ancestor—a process that assumes all in-document script elements have already been evaluated (as is the case for static content) and marks them accordingly. By the time the outer call gets around to looking at the later script, the inner call has already marked it as evaluated, so it is skipped over.

The weight of the code required to fix this issue is probably too great for us to justify adding (especially since script evaluation is an undesirable legacy behavior), but it can be easily worked around by moving scripts outside the manipulated ancestor: https://jsfiddle.net/jk54y34q/6/
