### ISSUE TITLE
1.12.4 accessing local binary file does not work 

### ISSUE THREAD

**Issue by v1nce** [jquery/jquery#3458]
paste this script into a LOCAL FILE

$.get({
  url:'foo.binary',
  processData:false,
  complete:function (data) { },
  success:function (data) { },
  dataType:'binary'
  }
 );

I expected to enter the success function. It won't (at least in chrome) because chrome returns 0 as http code for a local successful file access.

There was a (incomplete) fix in https://bugs.jquery.com/ticket/8125

The same patch should be applied at line 9781 in function done

		// Callback for when everything is done
		function done( status, nativeStatusText, responses, headers ) {
                ...
                        // Determine if successful
			isSuccess = status >= 200 && status < 300 || status === 304;

**Comment by gibson042** [comment]
We are no longer maintaining 1.x versions. I believe this is a non-issue in the current 3.1.1 codebase because the XMLHttpRequest transport onload handler [maps 0 to 200](https://github.com/jquery/jquery/blob/2d4f53416e5f74fa98e0c1d66b6f3c285a12f0ce/src/ajax/xhr.js#L99) before sending it to the AJAX callback, but please report back if I'm mistaken.
