### ISSUE TITLE
Order of Deferred callback are different with older version and Promise/A+

### ISSUE THREAD

**Issue by npiron** [jquery/jquery#3465]
### Description ###

I déclare two deferreds. 
One callback for the first Deferred, and a second Callback that wait both callback.
if i resolve theses deferred in order
I have in jquery 1.9 the same order as the order of resolve.
in jQuery 3 the callback that wait both is always call first.

### Link to test case ###

jQuery 1.9 : https://jsfiddle.net/zzskuhj0/
jQuery 3 : https://jsfiddle.net/zzskuhj0/1/
Native Promise/A+ : https://jsfiddle.net/drd72nks/

**Comment by mgol** [comment]
Thanks for the report with test cases. I modified them so that they log to the console instead of alerting and that include performance metrics and also swapped jQuery 1.9 (which is *really* old) to 2.2.4:

jQuery 2.2.4: https://jsfiddle.net/zzskuhj0/8/
jQuery 3.1.1: https://jsfiddle.net/zzskuhj0/6/
Native Promise: https://jsfiddle.net/drd72nks/2/

What's the most concerning for me is that in jQuery 3.1.1 performance really suffers; the code is very simple and yet the first done callback is invoked after about 50 milliseconds in Chrome 55; that's a lot.

**Comment by mgol** [comment]
I have an impression it's a side-effect of #3000. What do you think, @gibson042?

**Comment by gibson042** [comment]
The main issue here is mixing single- and multiple-argument `jQuery.when` calls (cf., yet again, https://github.com/jquery/jquery/issues/2018#issuecomment-70531678 ), although it's not a great idea to use the legacy `done` method for callback registration if you care about Promises/A+.

The short answer is that we don't guarantee callback execution order across deferreds, but in this case it can be recovered by [dropping the unnecessary `jQuery.when`](https://jsfiddle.net/zzskuhj0/11/) or [introducing a dummy argument](https://jsfiddle.net/zzskuhj0/10/).
