### ISSUE TITLE
Can't set stroke-opacity style on SVG elements

### ISSUE THREAD

**Issue by mitchgrasso** [jquery/jquery#3471]
### Description ###
Can't set stroke-opacity style on SVG elements because strokeOpacity is not included in the cssNumbers hash to prevent automatically adding "px" to property.

$(".my_svg_shape").css("stroke-opacity", 0.5) fails to set property but $(".my_svg_shape.css("stroke-opacity") correctly returns value.

### Link to test case ###

https://jsbin.com/xigohex/3/edit?html,js,console,output

**Comment by dmethvin** [comment]
Since SVG isn't the focus of the jQuery HTML library and we generally [don't support it](https://github.com/jquery/jquery/wiki/Won't-Fix#svg-or-vml), I don't think this is a bug. However, if you want to use jQuery to set this SVG property, you can [add it to cssNumber](https://api.jquery.com/jQuery.cssNumber/) yourself.  

Note that we aren't maintaining the 1.x or 2.x branches anymore, so even if we were to add this it would only go into a future 3.x branch. If you are writing code such as a plugin that needs to work with older versions you would need to add it yourself anyway.

**Comment by mitchgrasso** [comment]
Thanks, I did patch it myself but jquery 3.1.1 does have fillOpacity (which is SVG specific i believe) in cssNumber so I'm not sure why it wouldn't have strokeOpacity as well.

**Comment by dmethvin** [comment]
There is a large list of SVG CSS properties [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute) and there are definitely others like strokeMiterlimit` that don't have units. Putting `fillOpacity` here was a mistake IMO unless we're going to go through and add them all. The ticket for when it was added is [trac-9548](https://bugs.jquery.com/ticket/9548) and the unit test doesn't use SVG.

Also to be clear, the `jQuery.cssNumber` list is only used when you pass in a real number rather than a string. Strings are always unmolested so you can always just convert to a string. There's more discussion of why we want to avoid this whole mess over in gh-2795.
