### ISSUE TITLE
Url parameter eval as JS in Jquery Ajax 3.3.1, 2.2.4 and 1.12.4

### ISSUE THREAD

**Issue by dfmadrid** [jquery/jquery#3506]
In relation to dangerous response eval in jQuery get function refereced in #2432, as far as I see, 3.x, 2.x and 1.x are still vulnerable to XSS  (or is a different attack vector) if url parameter is under attacker's control and data uris are used. You don't even need to set up an external website to exploit the flaw:

For Jquery 3.1.1:
$.ajax({"url":"data:text/javascript;,alert(document.cookie)//", "dataType": "jsonp"});

For jQuery 2.2.4:
$.ajax({"url":"data:text/javascript;,alert(document.cookie)//"});
$.ajax({"url":"data:text/javascript;,alert(document.cookie)//", "dataType": "jsonp"});

For jQuery 1.12.4
$.ajax({"url":"data:text/javascript;,alert(document.cookie)//"});
$.ajax({"url":"data:text/javascript;,alert(document.cookie)//", "dataType": "jsonp"});

https://jsfiddle.net/david_sdt/o3bke6es/

**Comment by mgol** [comment]
If you allow third parties to modify your JS code you've already lost, the attacker can insert whatever code they want. The original issue was that you loaded a URL expecting a harmless JSON (so there was no third party code) and it suddenly started sending scripts which jQuery was then evaluating. This has been fixed.

**Comment by dfmadrid** [comment]
Ok, I respect your criteria but I don't see any difference. In both cases an attacker must control de content of the url parameter passed to jQuery.ajax, in #2432 to redirect to a website under his control that answers the scripts with his malicious code.

**Comment by mgol** [comment]
In #2432 the attacker doesn't control your code; in particular, they *do not* control the contents of the `url` property; you yourself pass the URL to the attacker's page as the parameter to the `$.ajax` `url` property. The attacker just changes the sent contents from a harmless JSON to a script. The jQuery user may not suspect that jQuery will then listen to the new mime type and execute the script which is why we fixed the issue.

In your case the attacker has to have control not just over some foreign domain from which you load stuff but they have to control what you pass as `url` in your code. If they control that, they can insert any code they want. To change that we'd basically have to ban data-urls completely and they have valid use cases.
