### ISSUE TITLE
computeStyleTests() memory leak (reference to removed div)

### ISSUE THREAD

**Issue by flexphperia** [jquery/jquery#3520]
### Description ###

In jquery 3.1.1 there is a small memory leak.
At the end of  `computeStyleTests()` function there is a `div = null;` that releases reference to div used for some measurements, but we have also variable `container` that is never nulled so it holds reference to another div that is not used.

It should look like this (2 ending lines of `computeStyleTests()`):
```
div = null;
container = null;  <---- new line
```

**Comment by markelog** [comment]
These hack were all over the place in place for IE < 9 browsers, since their gc couldn't handle circular references, but we no longer support such environments.

In the case your provided, `div` in question wouldn't be removed from the memory since it still be present in the outer scope of `computeStyleTests` function. 

Same with `container` yes, but that `div` also serves as singleton guard whereas `container` does not, we could nullify it too, but it would add to gzip size and practically would decrease memory consumption just a by a bit. Not to mention that with `computeStyleTests` logic this variable should be picked up by modern gc in form of optimization after possible second execution of `computeStyleTests` method, but that is speculation of course.

Because of these reasons I don't think we need to do that
