### ISSUE TITLE
Promise bug on UIWebView, iOS

### ISSUE THREAD

**Issue by sebastienvillar** [jquery/jquery#3535]
Bug: `This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.`

This is a bug we encountered in our app when going from jQuery 2.2.2 to 3.1.1
I've tracked down the problem to this commit: 5cbb234dd3273d8e0bbd454fb431ad639c7242c1
It arises in `Ready`. We hit this when the promise resolves.
Unclear how this can happen since JS is single-threaded.

**Comment by dmethvin** [comment]
Imagine you are in our position trying to understand what you are reporting. What information would you need in order to help fix the problem? Does the report above provide enough information? 

There was an issue template provided. Did you delete it?

What you describe as `Bug` is not a string contained in the jQuery source file. Have you looked in your source to see where this string appears?
