### ISSUE TITLE
Catch is a reserved word - IE9

### ISSUE THREAD

**Issue by thomaswelton** [jquery/jquery#3544]
From this commit `.catch` was added
https://github.com/jquery/jquery/commit/ad6a94c3f1747829082b85fd53ee2efbae879707

Catch is a reserved word in IE9 and throws an error.

Expected result: jQuery loads without error
Actual result: "Expected identifier" error is thrown
Browsers affected: IE9

**Comment by mgol** [comment]
I'll copy my comment from the commit:

> It's fine. If IE 9 didn't allow properties named as reserved words, there would be a parse error and jQuery wouldn't even load. We have an extensive test suite and we'd see it failed in such a spectacular way.
>
> It works as it should: https://jsbin.com/zoyale/edit?html,js,output

Make sure you're not using quirks mode or an older document mode. This is more Stack Overflow material, though.

**Comment by thomaswelton** [comment]
Ok, moving the conversation into this thread.

This seems like the only instance in jQuery core when .catch is used instead of setting the callback in the second parameter of the .then method

**Comment by mgol** [comment]
Many things in jQuery may fail in quirks mode, not parsing the library is just one problem of many others. Quirks mode in IE 9 is basically IE 5.5 and we haven't supported this browser for ages. We don't test IE 9 in quirks mode and we don't plan to (there is even no easy way to do that in our testing infrastructure) so such breakages may happen in any time. Therefore, I don't see any gain in changing that. If you need to support quirks mode and you accept you'll have to deal with all the bugs that result from this decision, you may maintain your own copy of jQuery with workarounds you need.

**Comment by thomaswelton** [comment]
I have no requirement to support quirks mode.
I noticed the error this morning, and due to the fact this is the only instance where `.catch` appears to be used in the core figured it was worth reporting.
Also wanted to let you know in by commenting against your commit because as you mentioned this error would not have been picked up by your automated tests.

Seeing as `.catch` is effectively just an alias I figured it'd have been a straight forward change.

**Comment by mgol** [comment]
This same `catch` breaks on Android 2.3 but we left it as it is anyway. It's not always clear if it's better for jQuery to not crash completely when the rest of the library is buggy on a particular browser. In this case, IE 9 in quirks mode will have the old event model which jQuery 2+ doesn't support at all so it's completely broken there. In such a case it's even better to sometimes completely crash and leave the site in it's default non-JS mode rather than try to kind-of run but leave the site in a totally unpredictable state.

If someone supports IE 9 in quirks mode then they shouldn't use jQuery 2+ in the first place.
