### ISSUE TITLE
[Feature] avoid repetitive usage of "ele.off().on()"

### ISSUE THREAD

**Issue by NE-SmallTown** [jquery/jquery#3578]
At now,if we want just **bind**(not execute) an event,we have to use `$(selectorString).off(eventType).on(eventType, function () {...})`,or create a variable to record such as:

```
var hasBind = false;
function foo() {
  if(hasBind) return;

 $(selectorString).on(eventType, function () {...});
 hasBind = true; 
}
```

And then call foo in our module.But both of them are not good ways to solve the demand of "once bind".

So,maybe we can add a plugin or internal method to do this?

I notice that [jQuery-4.0-Event-Design](https://github.com/jquery/jquery/wiki/jQuery-4.0-Event-Design) doesn't mention this and [some issues](https://github.com/jquery/jquery/issues/1866) had discuss this but no result.

**Comment by dmethvin** [comment]
It seems like the ticket you referenced, #1866, didn't get a lot of interest and nobody created a plugin. That would seem to indicate this isn't a common need, or if it is there is a relatively easy way to do it via the logic in existing applications. Note that if you're frequently adding and removing elements in a container it's usually better to use delegation rather than directly binding events, and in that case there would be no problem.

**Comment by NE-SmallTown** [comment]
Yup,thanks for you reply,but I still think that "via the logic in existing applications" will crate many boilerplate code :cry:
