### ISSUE TITLE
Firefox Session Restore - Incorrect Load Order

### ISSUE THREAD

**Issue by deckar01** [jquery/jquery#3585]
### Description ###

The document load event triggers before Firefox has finished restoring the page. This results in events listeners being triggered for the DOM updates Firefox makes to the page while restoring the page state.

### Link to test case ###

2.2.4: https://output.jsbin.com/qomowiviru

3.2.1: https://output.jsbin.com/hoxogigoba

### Steps to reproduce ###

 1. Load a test page in Firefox (latest 52.0.1)
 2. Check one or more check boxes
 3. Quit Firefox (not just the tab)
 4. Start Firefox
 5. Select "History" > "Restore Previous Session"

### Expected behavior ###

The body onload event should trigger, then the jQuery load event should trigger, and no change event should trigger for the checkboxes.

### Actual behavior ###

The jQuery load event triggers, then change events trigger for checkboxes, then the body onload event triggers.

### Notes ###

If the code is hosted with caching enabled, version 3.2.1 will properly execute the load event after the body onload event. This can be reproduced by hosting the examples locally on a server that with relaxed caching headers. jsbin disables caching, so in these test cases, both versions fail.

**Comment by deckar01** [comment]
I'm starting to wonder if this is a Firefox bug. It is the document's DOMContentLoaded event that is triggering jQuery to load. Other browsers restore their page state before executing DOMContentLoaded.

> The DOMContentLoaded event is fired when the initial HTML document has been completely loaded and parsed...
>
> https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded

**Comment by mgol** [comment]
The body onload should definitely happen *after* jQuery ready (with a possible exception in situations where the page is extremely simple and load fires quickly), that's the whole point of jQuery ready: the load event waits for all resources to load while jQuery ready only for the document structure.

The operation order seems OK to me here - first we get the document structure so jQuery ready is called; then change event handlers are triggered and, in the end, the load event happens. Even if in this case the order between the change and the load events firing was different, insert any image in your document and load would, again, be the last one.

As for the change event firing at all, that's not something we can do anything about; that's Firefox decision, perhaps to allow JavaScript code to react to the default checkbox state changing after document ready; otherwise a lot of pages would be left in a broken state, especially sites using single page application frameworks like Angular or Ember.

**Comment by deckar01** [comment]
> ... that's Firefox decision, perhaps to allow JavaScript code to react to the default checkbox state changing after document ready...

I opened [mozilla/firefox#1349264](https://bugzilla.mozilla.org/show_bug.cgi?id=1349264) to report this behavior. I am fairly confident it is a bug.
