### ISSUE TITLE
$.each doesn't work when key is 'length'

### ISSUE THREAD

**Issue by BarrieShieh** [jquery/jquery#3588]
$.each( { name: "John", **length1: 0** }, function(i, n){
        alert( "Name: " + i + ", Value: " + n );
 });

this code works fine.

$.each( { name: "John", **length: 0** }, function(i, n){
        alert( "Name: " + i + ", Value: " + n );
});

this one doesn't work.

I found 1.11.2 and 3.2.0 have such issue. Probably other versions have too.
Chrome 57.0.2987.98

**Comment by vivekmarakana** [comment]
It's because `$.each(obj, callback)` checks for `obj.length` to iterate over key-value pairs, and here you have defined `length: 0`

Following code works properly:
```
$.each( { name: "John", length: 2 }, function(i, n){
    alert( "Name: " + i + ", Value: " + n );
});
```

However, we need to find solution to this as `length: <non-zero>` works properly and `length: 0` does not.

**Comment by mgol** [comment]
Thanks for the report.

`jQuery.each` has long worked on array-likes, meaning that if an object has a `length` property it iterates over it like over an array. Under https://api.jquery.com/jQuery.each/ you can see the note:

> <b>Note:</b> The <code>$.each()</code> function internally retrieves and uses the <code>length</code> property of the passed collection. So, if the collection has a property called <code>length</code> — e.g. <code>{bar: 'foo', length: 10}</code> — the function might not work as expected.

I think this could be improved so I opened https://github.com/jquery/api.jquery.com/issues/1032.

If you need to iterate over all keys of objects having the `length` property, `jQuery.each` is not the correct solution.

**Comment by BobStein** [comment]
I gather this can never be "fixed" because that might break existing implementations. My conclusion is never to use $.each() on objects, because someday an object of mine may happen to have a member named 'length' with a value exactly zero and then $.each() will treat it like an empty array, with hard to explain consequences.

Test case:  `$.each({foo:1, length:0, bar:2}, console.log)` (There is no log output.)

Details:  https://stackoverflow.com/a/49652688/673991

**Comment by dmethvin** [comment]
@BobStein yes, if you don't want object array-likes to be treated as arrays then you would need to use a different mechanism. Possible alternatives include `for-in` or `for-of`, each of which have their own drawbacks as far as the properties enumerated or the browser support.

**Comment by ryonlabaw** [comment]
After years of working with jquery, I just ran into this problem today. I am working with a json data feed that contains a "length" field.  The looper function linked by BobStein works well. 
Maybe jquery should think about fixing this in some fashion, or at least documenting the issue on the $.each page?

**Comment by dmethvin** [comment]
@ryonlabaw It is documented, as mentioned above. We can't "fix" it without breaking documented behavior. Since there are plenty of other alternatives today it doesn't make sense to change it, since if you do want array-like iteration on an object (for example, a NodeList) the current behavior is desired.
