### ISSUE TITLE
crazy alert on focusin event

### ISSUE THREAD

**Issue by bsbak** [jquery/jquery#3591]
### Description ###
alert was looped on focusin event
tested on query 3.1.1 and 3.2.0
chrome 56.0.2924.87 (latest)
### Link to test case ###
[jsfiddle](https://jsfiddle.net/wofvh8k0/)

**Comment by mgol** [comment]
My guess would be that displaying an alert defocuses the input and clicking OK on it focuses it again, triggering the event handler which displays an alert and so on.

If you'd like this behavior changed, report it to Chrome. I don't think we can and should do anything here, especially that this example shouldn't really happen in real world. In most cases alerts create poor user experience, especially ones that display if you try to focus an input.

If you want to workaround it, set a flag to check if the alert was already displayed and don't display it otherwise.

**Comment by bsbak** [comment]
@mgol ok, ty
