### ISSUE TITLE
jQuery.toggleClass should treat a null switch as falsey

### ISSUE THREAD

**Issue by diggabyte** [jquery/jquery#3613]
### Description ###
A `null` switch value for `jQuery.toggleClass` is treated as if it is `undefined`. 

`$foo.toggleClass('bar', null)` works the same as `$foo.toggleClass('bar')`

Expected: 
`null` switch should be treated as 'falsey' 

Actual:
`null` switch is treated as if it is `undefined`

**Comment by timmywil** [comment]
As documented, only boolean values are allowed.

**Comment by diggabyte** [comment]
@timmywil I understand that Boolean is currently documented. What I am proposing is a change for a future release. Any reason to not consider this other than "that's how it is right now"?

**Comment by dmethvin** [comment]
if you want `null` to be `false` can you use `$foo.toggleClass('bar', possiblyNull || false)`? Making the signature more complicated can be risky, especially with 10 years of documentation all over the Internet.

**Comment by diggabyte** [comment]
If non-Boolean values are unacceptable, then an error should be thrown rather than treating those values as `undefined`

**Comment by diggabyte** [comment]
I will treat swallowing invalid args as a separate issue and allow #3613 to remain closed.

**Comment by mgol** [comment]
Accepting non-boolean values via casting to bools would get us closer to the `classList` API. Something to consider.

Of course the cost of breaking some existing code also exists.

**Comment by diggabyte** [comment]
Yeah, good point. 

Agreed that there is a cost consideration for a breaking change. But said change may also fix some existing broken code as well.

**Comment by timmywil** [comment]
We've had a good number of breaking changes recently. I lean towards leaving this one alone.

**Comment by dmethvin** [comment]
jQuery would be a LOT bigger if it checked all args and explicitly threw an error for any that weren't defined in the API. I can't imagine that we'd fix existing broken code by changing this, API changes almost always break the behavior of code that someone thought was working okay (even if it was only that way by accident).

The requirement that the second arg be a true Boolean has been that way since the feature was [implemented in 2008](https://github.com/jquery/jquery/commit/0a8f96ac3d37f637ab433c037d4f807e8ef94bbe). At the time we had the convention of using `undefined` to flag missing args; over the past few years we've tended towards `arguments.length` instead. I would prefer leaving this alone though, it's been this way forever and I've outlined above a simple thing that a caller can do to get the behavior they want.

**Comment by diggabyte** [comment]
Yeah, I just looked into the use of throwing errors and realized it's used very rarely in the library. So no problem skipping that suggestion.

Although casting to Boolean would move closer towards the `classList` API (as noted by @mgol), it sounds like the potential for breakage here outweighs the benefits.

Thanks for the feedback. I'm cool with leaving it closed.

**Comment by mgol** [comment]
> At the time we had the convention of using `undefined` to flag missing args; over the past few years we've tended towards `arguments.length` instead.

The spec treats `undefined` as a missing value, i.e. `toggle('foo', undefined)` behaves like `toggle('foo')` but `toggle('foo', null)` like `toggle('foo', false)`. So it seems to align with our previous behavior.

In any case, I'm fine with leaving it as-is as well.

**Comment by diggabyte** [comment]
> The spec treats undefined as a missing value, i.e. toggle('foo', undefined) behaves like toggle('foo') but toggle('foo', null) like toggle('foo', false).

@mgol `toggle('foo', null)` does *not* behave like `toggle('foo', false)`. That was the reason I reported this issue initially.

**Comment by mgol** [comment]
> @mgol `toggle('foo', null)` does not behave like `toggle('foo', false)`.

It does. I wrote about the classList API, not jQuery.

**Comment by diggabyte** [comment]
> It does. I wrote about the classList API, not jQuery.

Oops, sorry, I misunderstood. I didn't catch the lack of `$` there 👍
