### ISSUE TITLE
Shortcut function for input form event

### ISSUE THREAD

**Issue by Mynyx** [jquery/jquery#3639]
It would be helpful to have a shortcut .input() function for the input form event as it already exists for the other form events e. g. the change event.

**Comment by timmywil** [comment]
Thank you for opening an issue, but we recommend using the `.on`, `.off`, and `.trigger` methods rather than the event aliases. There are other events we don't have aliases for, and we don't think it's worth it to maintain a list of all possible events. Such a list would require deprecating and removing aliases for events that may have lost support in some of our supported browsers as time goes on, which makes maintaining such a list even less feasible.
