### ISSUE TITLE
Deprecate `cssProps` property

### ISSUE THREAD

**Issue by markelog** [jquery/jquery#3653]
After https://github.com/jquery/jquery/pull/3569/files it will became useless basically and since we never documented we can remove it.

But it's better to be on the safe side and deprecate it first and remove it in the next major

**Comment by timmywil** [comment]
I did the PR for this, but @mgol noted that accessing the object directly rather than with `jQuery.cssProps` has the potential to break the case where `jQuery.cssProps` is replaced rather than amended. Also, I couldn't find any mention of this property in our documentation. I'm inclined to just leave this as-is since if we can't move it to deprecated js and there's nothing to be done in migrate/API, there's nothing to do here.

**Comment by markelog** [comment]
So do we intended to expose it in the next major as well? If not should we create an issue with "Remove jQuery.cssProps"?

**Comment by dmethvin** [comment]
It looks to me that this isn't one of those "documented undocumented" features. I didn't see any sign that it had been discussed on StackOverflow for example. Unfortunately for searching the names `cssprop` and `cssprops` are somewhat common as variable names so it's possible I missed some. 

I'm fine with either way as far as removal for 4.0, it seems safe. I just created an issue for Migrate.
