### ISSUE TITLE
clicking an element has different behaviour to calling element.trigger('click')

### ISSUE THREAD

**Issue by znewsham** [jquery/jquery#3660]
### Description ###
See http://stackoverflow.com/questions/43814426/jquery-triggerclickevent-behaves-differently-to-clicking-the-item?noredirect=1#comment74669606_43814426 for discussion

clicking an element (e.g., canvas) has different behaviour to calling element.trigger('click')

as an example:

HTML
`<canvas id="test" width=100 height=100></canvas>`

JavaScript
`
document.getElementById("test").onclick=function(e){
    e.stopPropagation();
}

document.onclick = function(e){
 alert("should not be triggered");
}
`

Click the canvas - nothing happens, open the console and type `$("#test").trigger('click")` - you get an alert.

### Link to test case ###
https://jsfiddle.net/v9eyr97x/1/

**Comment by mgol** [comment]
Inline event handlers are not supported: https://github.com/jquery/jquery/wiki/Won't-Fix#inline-event-handlers.

**Comment by znewsham** [comment]
The behaviour exists with addEventListener too:
https://jsfiddle.net/v9eyr97x/2/

**Comment by dmethvin** [comment]
Yeah, it even happens without jQuery. https://jsfiddle.net/v9eyr97x/13/

**Comment by znewsham** [comment]
@dmethvin It doesn't, you have to click on the canvas to see the issue (I made the canvas white so its more obvious) https://jsfiddle.net/v9eyr97x/14/

**Comment by mgol** [comment]
@znewsham Your test case is broken as it doesn't include jQuery. I fixed it & added the `trigger` invocation and no alerts appears: https://jsfiddle.net/v9eyr97x/19/.

**Comment by znewsham** [comment]
@mgol I hate to beat a dead horse, but: https://jsfiddle.net/v9eyr97x/27/

It's slightly different, `trigger("mouseup")` doesnt work when addEventListener is used. Though, it does work when `onmouseup = function(){}`. Additionally, `$("#test")[0].dispatchEvent(new MouseEvent("mouseup"))` does

**Comment by dmethvin** [comment]
jQuery's `.trigger()` doesn't fire event listeners attached with `.addEventListener()`. The jQuery event system is a layer on top of the DOM events. There is no way for jQuery to know which elements have which DOM events attached, or even whether the event being fired is an event known to the browser like `click` vs a user-defined event like `clack`. That list varies by browser.

The reason an event like `click` works like you want in some cases is because jQuery runs the DOM's `.click()` method on the element *if it is present*. 

For more discrepancies between inline handlers and W3C event listeners that can impact jQuery's behavior, see #2918, #3146, and https://github.com/jquery/jquery/issues/1783#issuecomment-77187697,
