### ISSUE TITLE
show() and hide() problems

### ISSUE THREAD

**Issue by publicocean0** [jquery/jquery#3672]
show and hide work in too much easy way.

if a div is display:flex

and i call .show it set display:block

instead internally hide and show might set the initial  computed display value
and reset after it.

the good behaviour   it seams to work but not always.... 

probably hide call  dont has internally a variable for it

**Comment by publicocean0** [comment]
i gave a look to the code , in fact there is a bug inside 
dataPriv.set( elem, "display", display );
you set it when you call hide
but not when you set show

**Comment by alecpl** [comment]
Works for me. Please, create jsfiddle.net example. What browser and what version of jQuery?

**Comment by publicocean0** [comment]
sorry but how can work if i explained the bug?

**Comment by mgol** [comment]
We don't support jQuery 1 & 2 anymore, try jQuery 3.2.1.

> sorry but how can work if i explained the bug?

The explanation is not clear enough. That's why we always ask for a minimal test case at https://jsfiddle.net or https://jsbin.com.

Since this was reported against jQuery 2 and there is no test case I'm going to close the issue. If you still see it with jQuery 3 *and* have a test case demonstrating the problem we can reopen.
