### ISSUE TITLE
Guthub API not working for jQuery

### ISSUE THREAD

**Issue by praisedpk** [jquery/jquery#3675]
Hi,

https://api.github.com/repos/jquery/jquery/releases and https://api.github.com/repos/jquery/jquery/releases/latest
do not return list of releases, while the same works fine for many other repos. Is this an issue with how jquery team uses github for releases, or there is something different with this repo?

Thanks.

**Comment by timmywil** [comment]
Thanks for opening an issue. First, we do not do releases on this repo anymore. We've isolated that to a separate repo. See https://github.com/jquery/jquery-dist. However, releases aren't returned from the GitHub api on that repo either because we do not draft release notes on GitHub but on the jQuery blog. Regardless, you can simply use https://api.github.com/repos/jquery/jquery-dist/tags instead.
