### ISSUE TITLE
form.prop('action') returns form > input[name="action"] instead of action attribute

### ISSUE THREAD

**Issue by contreforme** [jquery/jquery#3691]
### Description ###
i have the following

&lt;form method="post" action="?foo=bar"&gt;
    &lt;input type="hidden" name="action" value="baz"/&gt;
    &lt;input type="submit" value="send"/&gt;
&lt;/form&gt;

now consider this

$('form').on('submit',function(){
    console.log($(this).prop('action'));
});

should result in string

'?foo=bar'

but returns

[object HTMLInputElement]

### Link to test case ###
http://jsbin.com/jaxibuzayu/edit?html,js,console,output

**Comment by dmethvin** [comment]
Notice that `$(form)[0].action` has the same problem which indicates it's not something caused by jQuery. See #3101, #2755, ... several more years of similar tickets ... and [trac-1414](https://bugs.jquery.com/ticket/1414) from 10 years ago. It's not something jQuery can fix across browsers and it's not something that is easy to document at jQuery's level because it applies to all the jQuery APIs. See https://kangax.github.io/domlint/ . Web developers need to understand this problem whether they use jQuery or not.
