### ISSUE TITLE
outerHeight() differs between chrome and IE11

### ISSUE THREAD

**Issue by nick1377** [jquery/jquery#3698]
### Description ###
The outerHeight() differs between Chrome and IE11.
In the test case below the height shows as 23 in chrome but 25 in IE11.

### Link to test case ###
https://jsfiddle.net/179d0uek/12/

**Comment by timmywil** [comment]
Thanks for opening an issue. But, the result is correct because you have a border on both the outer div and inner div, so it's really 10 + 2 + 2 = 14.

**Comment by nick1377** [comment]
Can you reopen this issue. The test case was bad and I had the issue slightly wrong but it is a bug. I provided a better test case and fixed the title and description a bit.

**Comment by dmethvin** [comment]
Please work the test case down to a minimum, removing css and HTML elements/attributes that don't affect the result.

**Comment by nick1377** [comment]
Done. The new test case is now only what is needed to reproduce the issue.

**Comment by mgol** [comment]
Thanks for the updated test case. I confirm the behavior in IE changed in jQuery 3.2.0.

**Comment by dmethvin** [comment]
Here's what I see in the IE11 inspector:
![image](https://user-images.githubusercontent.com/157858/27312893-0c3823c6-5539-11e7-8e7a-90c1e262aea1.png)
Notice the `offset 2`, I assume that's coming from the default stylesheet and if you add `cellpading=0 cellspacing=0` to the `<table>` it goes away. There's no guarantee that all browsers will have the same default stylesheet and even if they did it's possible the measurements might be different due to things like font substitution.

**Comment by mgol** [comment]
@dmethvin The biggest issue is that behavior in IE changed in jQuery 3.2.0 so it looks like an unintended breaking change.

**Comment by gibson042** [comment]
The problem seems to hinge on phantom &lt;tr> borders in IE: https://jsfiddle.net/179d0uek/15/ . Now to investigate the reason...
