### ISSUE TITLE
Accessing Input element Value field via 'val()' is unintuitive!

### ISSUE THREAD

**Issue by sscholle** [jquery/jquery#3734]
### Description ###
The long established convention of accessing the Input fields 'value' is done using the named attribute called 'value'. Jquery should NOT be trying to re-invent the wheel. Having a function call of 'val()' is unintuitive and requires the first time user of this function to look up in the Manual to see what happened to the 'value' attribute in jQuery..... not great. Additionally, Stackoverflow seems to be trying to solve problems that should not exist in the first place.

So please, make 'value' attribute accessible again.

Thank you.

### Link to test case ###

not applicable

**Comment by mgol** [comment]
jQuery doesn't use getter properties in most places and this is consistent with the rest of the jQuery API. Most people using jQuery knows about `.val()` so changing that would only create unnecessary churn. We also have `.attr()` insteaf of `.getAttribute()`, `.on()` instead of `.addEventListener()` etc.

I'm sorry but this is not something we're going to do.

**Comment by dmethvin** [comment]
@sscholle I'm not even sure what you're asking for, which is again why we ask for a test case. There's not even any pseudo-code explaining how you expect this to work, or links to the StackOverflow issues. It would make no sense to have something like `$("#myinput").value = "25"` because that would be setting an `input` property on the jQuery collection so I assume you're not asking for that.

If you don't like `.val()` you can easily get to the attribute via `("#myinput").attr("value")` or `$("#myinput").prop("value")`. They do what `myinput.getAttribute("value")` or `myinput.value` would do.
