### ISSUE TITLE
Uncaught TypeError: url.indexOf is not a function

### ISSUE THREAD

**Issue by jonhue** [jquery/jquery#3763]
### Description ###

I added jquery with yarn (`yarn add jquery`) and imported it into my project:

```js
import 'jquery'
```

Now the developer console says:

> Uncaught TypeError: url.indexOf is not a function
>     at jQuery.fn.init.jQuery.fn.load (jquery.js?eedf:9823)
>     at eval (webpack-internal:///252:33)
>     at Object.eval (webpack-internal:///252:5)
>     at eval (webpack-internal:///252:6)
>     at eval (webpack-internal:///252:11)
>     at Object.<anonymous> (application-1a1aae5f973d47057402.js:2920)
>     at __webpack_require__ (application-1a1aae5f973d47057402.js:20)
>     at eval (webpack-internal:///224:25)
>     at Object.<anonymous> (application-1a1aae5f973d47057402.js:2623)
>     at __webpack_require__ (application-1a1aae5f973d47057402.js:20)

To make sure I am using the latest version of jQuery i ran `yarn upgrade jquery`.

I got this message:

> warning Pattern ["jquery@^3.2.1"] is trying to unpack in the same destination "C:\\Users\\Jonas\\scoop\\persist\\yarn\\cache\\v1\\npm-jquery-3.2.1-5c4d9de652af6cd0a770154a631bba12b015c787" as pattern ["jquery@>1.9.0"]. This could result in a non deterministic behavior, skipping.
warning fsevents@1.1.2: The platform "win32" is incompatible with this module.

Dunno if that could have anything to do with the error. Still at the end it installed that jquery version:

    └─ jquery@3.2.1
    Done in 11.25s.

**Comment by dmethvin** [comment]
So are you looking for help with installing jQuery via yarn? If so you'd be better off asking a question on StackOverflow. It's not related to a jQuery bug, and that is what this repo is about.

**Comment by jonhue** [comment]
@dmethvin This is a bug as far as I can see. yarn was just the vehicle, I installed jQuery with. Just wanted to mention it.

**Comment by mgol** [comment]
If it was just about requiring jQuery in Node, we could look at it. But there are many moving pieces here, e.g. the Webpack bundling. I'm using jQuery in my Webpack apps and it works fine so whatever happens in your app just importing jQuery is not the only pre-requisite.

That's why Stack Overflow & other similar venues are better places to help with debugging it. If there really is an issue in jQuery here, such debugging would point you to what's exactly broken which we could then fix. And it's very likely that the cause of this issue is something different than jQuery.

For now the only way for us to resolve it is to help you with debugging your app. And the jQuery bug tracker is not the correct place for that action.

**Comment by Dwood15** [comment]
I'm getting the same problem from npm, inside: `jQuery.fn.load = function( url, params, callback ) {
	var selector, type, response,
		self = this,
		off = url.indexOf( " " );`

"url.indexOf() is not a function"
