### ISSUE TITLE
XSS possible in test/data/jsonp.php

### ISSUE THREAD

**Issue by tomnomnom** [jquery/jquery#3767]
### Description ###
The file `test/data/jsonp.php` outputs the `callback` parameter unescaped, this coupled with a lack of `Content-Type` header allows Cross Site Scripting.

Although the script is only *meant* for testing purposes, a Google search reveals that the file has been deployed to several sites across the web; presumably where the entire jquery repository has been cloned.

I believe that adding a `Content-Type: application/javascript` header, while not a perfect solution, will help prevent more sites from inadvertently acquiring this vulnerability.

**Comment by timmywil** [comment]
Thanks for opening an issue, but the proper fix here is for users not to host the test files. The ajax tests are about to get a revamp anyway, but I don't think it's practical to expect all of the tests to be host-able. `git clone` is not a recommended installation method.

**Comment by dmethvin** [comment]
@tomnomnom Also note that this is our development repo which has a lot of things that shouldn't be cloned into a production environment. There is also https://github.com/jquery/jquery-dist that contains only the release files. As @timmywil says, only someone doing a custom build should ever need to clone this repo and there's no reason for them to expose it on a server.  If you want to provide some other info on what you found you can send it to security (at) jquery.com and we can take a look.

**Comment by tomnomnom** [comment]
@dmethvin I've sent an email as suggested, thank you.

I'm aware that users aren't *meant* to clone the repo for deployment, but some of them *have*. IMO it would be better to fix the issue than to rely on users always doing the right thing, because they demonstrably do not.

**Comment by mgol** [comment]
@tomnomnom Removing the file would not fix the issue but only mask it. We can't think of a possible XSS for every file we commit to the repo as the whole repository is not designed to be secure when publicly exposed. We'd rather not pretend we can make it secure, especially that further changes to this repo (like #3744) will introduce more XSS issues for people deploying the whole repo anyway.

There's only one way to fix the issue - to do it on the sites end by stopping deployment of the whole repository.

**Comment by Krinkle** [comment]
For the record, I do think we'd be open to addressing **server** vulnerabilities given we run it publicly in some ways ourselves as well and it'd be annoying if someone could attack our Jenkins build server through this.

However, client vulnerabilities don't apply to the build server. The issue detailed in this report is not in itself a vulnerability. It allows one to echo plain text into a JavaScript file dynamically served from the build server. That is intentional.

In itself, this isn't an attack surface given that web browsers don't grant cross-origin rights to a foreign script. Loading JavaScript from domain A on a page in domain B runs the same way as if it would run from domain B (think about CDNs), it doesn't provide any cross-origin access to domain A. (Unlike, e.g. cross-origin HTML in an iframe).

If someone were to host `jsonp.php` on a production server that both 1) isn't static, and 2) uses secure cookies on the same domain, it would not pose a threat. It would first require there to be an HTML page on the same server that has actual XSS vector (e.g. something that allows arbitrary HTML injection on that page, which in turn enables the attacker to insert a script tag for jsonp.php or somehow change the url of an existing script tag).

**Comment by tomnomnom** [comment]
@Krinkle I'm afraid that's not true; `jsonp.php` does not set a `Content-Type` header, and so is interpreted as `text/html` by browsers. No other XSS vector is required.

I've hosted `jsonp.php` here as an example: `http://tomnomnom.uk/jsonp.php?callback=%3Cimg%20src=x%20onerror=alert(document.domain)%3E`

Try going to that link in Firefox (Chrome's XSS auditor kicks in despite the lack of `X-XSS-Protection` header, but Firefox's does not).

**Comment by Krinkle** [comment]
@tomnomnom Aye, yeah, in fact, PHP even outputs that content-type explicitly by default.

I do think we should still have a test that confirms `jQuery.ajax` is able to run a JSON-P response in a `<script>` tag if its content-type is "wrong". However, we can make it so that that particular test has a hardcoded callback name, or only supports a whitelisted pattern for callback name.

**Comment by timmywil** [comment]
@Krinkle I can't assign you for some reason. But keep in mind I don't want to get into a bottomless pit of possible vulnerabilities caused by people using the repo in unusual ways. Another point here is that even if we add a guard for this, that guard would not necessarily propagate to everyone that may be hosting the whole repo. They would have to pull changes. And if the `.git` folder is being hosted, I can't even guess all the crazy stuff that could be exposed.

**Comment by timmywil** [comment]
@Krinkle If you'd still like to tackle this, you're welcome to. Closing patchwelcome tho.
