### ISSUE TITLE
$.ajax converts requests into jsonp request when data includes "??"

### ISSUE THREAD

**Issue by hdra** [jquery/jquery#3798]
### Description ###
Calling `$.ajax` when the data includes `??` and `dataType` set to `'json'` it turns the request into a jsonp request. 

This causes additional `accept` headers to be sent, and an additional `script` to be added into the `dataTypes` array. The latter in turn causes the `text script` converter to be used to parse the response from the server, which would throw an error.

From what I can tell, this is caused by the `ajaxPrefilter` for the `json jsonp` datatype, where `rjsonp = /(=)\?(?=&|$)|\?\?/;` is used to test the request data, which would match any string that contains `??`. 

Currently I worked around the issue by explicitly setting `jsonp` to `false`, but I couldn't think of why this should be the case. 

### Link to test case ###
```
// OK
$.ajax({
  url: 'https://httpbin.org/post',
  type: "POST",
  dataType: 'json',
  data: JSON.stringify({foo: 'bar'})
}).done(function(r){
  console.log(r);
});

// Not OK
$.ajax({
  url: 'https://httpbin.org/post',
  type: "POST",
  dataType: 'json',
  data: JSON.stringify({foo: 'bar??'})
}).done(function(r){
  console.log(r);
});
```

**Comment by dmethvin** [comment]
If you're passing a data string with the default form-urlencoded encoding, a `??` should not appear in the string because a method like `UREncodeComponent` would have changed it to `%3F%3F`. You need to either encode your string or change the content type. There are plenty of examples on StackOverflow and elsewhere, for example https://stackoverflow.com/questions/12693947/jquery-ajax-how-to-send-json-instead-of-querystring .
