### ISSUE TITLE
jQuery ajax removes empty arrays from data

### ISSUE THREAD

**Issue by mcrampon** [jquery/jquery#3807]
### Description ###
- What I expected :
jQuery ajax sending correctly an array, even if empty.
I couldn't find any RFC saying it should or shouldn't be sent though. If you know of one, I'd be happy to read it.
- What happened :
Sent data doesn't contain the empty array.

### Link to test case ###
https://jsfiddle.net/40oe0rsf/

**Comment by dmethvin** [comment]
You're right that there's not an RFC governing the encoding of a JavaScript object to a query string. People no doubt depend on the current behavior since it's been this way for a decade. If you need a well-defined spec I would advise using JSON. You could try the `traditional: true` setting to see if that works for your case.

**Comment by mcrampon** [comment]
`traditional: true` does not add the empty arrays.
An additional option to jQuery ajax would not change the current behavior and would add the possibility to send accurate data. I'm not very good at naming things, but something like `keep_empty_arrays: boolean`, with a default to `false` ?
