### ISSUE TITLE
FeatReq: Add new API for ::before and ::after tags

### ISSUE THREAD

**Issue by pstein** [jquery/jquery#3819]
In the past I already asked in forums on how to peek into a ::before CSS rules e.g. for example in 
```
<div>
<span> ::before </span>
....
</div>
```
with a CSS declaration like

`span::before { content: "foobar"; }`

I learned that this is not possible resp. only with difficulties.

Since there are more and more CSS stylesheets out there with ::before and ::after tags it becomes more and more important to access them by jQuery.

So jQuery should provide a new API for them in the next release.

As a first step it would be sufficient not to modify but only to check for the presence of them
E.g. (see sample above) find simply all <span> elements which have such a ::before clause. 
Afterwards I want to remove these elements.

The coming jQuery API should make the following possible/valid:

$("div span::before").remove();

**Comment by dmethvin** [comment]
Since there can be a large performance difference between native selectors (which can be processed via the native `querySelectorAll` method) and jQuery selector extensions (which require Sizzle code) we no longer consider selector extensions. However, the Sizzle engine provides [an extension API](https://github.com/jquery/sizzle/wiki#-extension-api) that lets you add features if you'd like.
