### ISSUE TITLE
Use the new fetch API

### ISSUE THREAD

**Issue by maxibanki** [jquery/jquery#3826]
### Feature Request / Improvement ###
Hi,
What do you think about using the new `fetch()` API, which is already implemented in all major browsers. It should be used by default when the `window.fetch()` function is available and can be explicitly deactivated by using a parameter. All major browsers have been supporting this feature for some time. 
I'm not so familiar with the jQuery codebase (only used it) so maybe this cannot be implemented due some missing features e.g.

For the full Browser Compatibility and usage check out the documentation here:
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by dmethvin** [comment]
What is the benefit of using fetch? When this feature is done, how will the code work better?

**Comment by maxibanki** [comment]
- Promise based
- Streaming responses
- Response Promise provides methods such as text(), json(), blob(), arrayBuffer()
- Newer means better? Idk

Sorry, this was I think a very random weird issue. The advantages are not sooo huge, but I think the implementation is much cleaner as the one with XMLHttpRequest.

**Comment by dmethvin** [comment]
I don't know that any of those could be used compatibly within the `jQuery.ajax` implementation. We already return Promises (via `jQuery.Deferred`) so there's no improvement there. We'd have to expose the `Stream` somehow. We already have `dataType` which performs functionality similar to the fetch data type methods.

I think the best way to do this would be via a new API rather than stacking new functionality on top of `jQuery.ajax`. It's not even clear whether there would be a dependency on jQuery at all in the implementation, but if so it could be [done as a plugin](https://github.com/jquery/jquery/wiki/Adding-new-features) to explore the feature before locking it into a version. With that in mind I don't think this is something the core team has to manage or build.
