### ISSUE TITLE
ready callback might be called after load event fired

### ISSUE THREAD

**Issue by tndev** [jquery/jquery#3852]
### Description ###

Under certain circumstances the callbacks in the following code would be called in an unexpected order:

```
window.addEventListener('load', function(e) {
  console.log('native load');
}, true);

document.addEventListener('DOMContentLoaded', function(e) {
  console.log('native DOMContentLoaded');
}, true);

$(function() {
  console.log("jquery: ready");
});

$(window).on("load", function() {
  console.log("jquery: loaded");
});
```

I would always expect the following output:

```
native DOMContentLoaded
native load
jquery: ready
jquery: loaded
``` 

But it is possible to create a test case where the output is like this (`load` and `ready` are switched).

```
native DOMContentLoaded
native load
jquery: loaded
jquery: ready
``` 

Personally I would say that the order `jquery: loaded` followed by `jquery: ready` should never happen for the given code, but that might be opinion based, therefore, I don't want to insist on this opinion, but I think you should at least adjust the following section in the documentation to point out this behaviour:

[.ready()](https://api.jquery.com/ready/)
> Note that although the DOM always becomes ready before the page is fully loaded, it is usually not safe to attach a load event listener in code executed during a .ready() handler 

In my opinion this section currently only targets the issue #3194, and not the snipped above.
### Link to test case ###

[https://jsfiddle.net/4hq6k579/1/](https://jsfiddle.net/4hq6k579/1/)

**Comment by georgeliuyu** [comment]
what`s this?

**Comment by gibson042** [comment]
It would be a mistake to assume a direct connection between the window "load" event and asynchronous jQuery ready callback invocation—they can happen in either order, with the latter in particular affected not just by native events, but also by when and how jQuery is loaded. We can't even guarantee that it follows native "DOMContentLoaded", because we rely on standards compliance of the browser to do so.

Given that we are extremely unlikely to add guarantees around the behavior, can you open an issue or pull request at https://github.com/jquery/api.jquery.com if you feel like the documentation does a poor job of expressing that?
