### ISSUE TITLE
Event handlers executed after removal

### ISSUE THREAD

**Issue by sanniassin** [jquery/jquery#3879]
### Description ###
When you attach two event handlers for the same event type and target and then remove second handler inside the first one, it'll be still executed regardless of removal. Doesn't happen with add/removeEventListener.

Can make a PR.

### Link to test case ###
https://codepen.io/sanniassin/pen/JOQdmP

**Comment by timmywil** [comment]
Thanks for opening an issue. However, this is expected behavior. Use `event.stopImmediatePropagation` to keep the second handler from executing. https://codepen.io/anon/pen/ZadeVJ

**Comment by dmethvin** [comment]
This is a dup of #2094 btw. Even though someone looking for the `removeEventListener` behavior might consider it a bug fix to change this, I suspect we wouldn't dare do it until the next major (4.0). At that point we'll most likely have redone the jQuery event plumbing to have one DOM event per jQuery event so it would be "fixed" due to that. Of course a bunch of other assumptions people have based on the current implementation will be broken by that as well.

**Comment by sanniassin** [comment]
Thanks for clarification.
