### ISSUE TITLE
Does jQuery cache cause memory leak?

### ISSUE THREAD

**Issue by sreejith-ms** [jquery/jquery#3925]
Hi,

I already asked this question on [SO](https://stackoverflow.com/q/48022098/) but no one replied. 

In my SPA page the events are bind using jQuery (1.10.2) on the page load.

```
$("#myDivId").click(function (event) {                
});
```
```
//some events are bind by using .on()
$("#myDivId2").on("click", function (event) {
})
```
I'm diagnosing the app for memory leak issues and I'm testing by just navigating the pages back and forth. While looking the heap snapshot there are many detached dom trees caused by jQuery. 
![jquery-cache-detached-dom](https://user-images.githubusercontent.com/13817581/34610675-2971b806-f248-11e7-8082-c148161164e6.png)

![jquery-cache](https://user-images.githubusercontent.com/13817581/34610705-40b8bc8a-f248-11e7-81c7-c5d0bfb6846f.png)

The $.cache size is growing when I'm navigating to the pages. Is this a potential memory leak?
I also tested with unbinding the events before the page load.

`$("#myDivId").unbind("click");`
When I'm unbinding events the $.cache size is stable. So if I need to unbind every events I have to do that on every pages. Why $.cache holds the dom even after the dom is removed from the document?

Do I need to add any other info like test fiddle?

**Comment by timmywil** [comment]
I can't say for sure without a test case, but it looks like you're re-binding the handler each navigation. If it's a single page and not a full page reload, the previous handler would still be there. If that's the case, then it's expected behavior. You'd have to remove the element with jQuery somehow for jQuery to know to get rid of the handler.
