### ISSUE TITLE
jQuery doesn't optimize attribute selector with 'contains'

### ISSUE THREAD

**Issue by NN---** [jquery/jquery#3938]
This selector works noticeable faster since it is optimized to document.querySelectorAll:

```js
jQuery("[id=xyz]") // 20ms
```

```js
jQuery("[id=xyz]:contains('xyz')") // 2000ms
```

**Comment by dmethvin** [comment]
So are you asking for a faster `:contains()`? Not sure what the bug or issue is. here.

**Comment by NN---** [comment]
The problem is not with contains.
The problem is that jQuery doesn't parse "[id=xyz]" part in the "[id=xyz]:contains('xyz')" as a valid selector for querySelectorAll and takes slow path.

**Comment by dmethvin** [comment]
Oh so this is related to your other ticket? Again I'm not sure what impact that has on real code. Your timings are most likely based on some tight loop with high iterations.

**Comment by NN---** [comment]
While it is correct, I still don't see a reason to make such code pessimization when it can be greatly improved with simple regex change.

**Comment by dmethvin** [comment]
Sure, give it a try if you want. Keep in mind that the additional regex complexity shouldn't reduce performance for the common case.

**Comment by NN---** [comment]
Of course.
Btw, is there any option to store parsed selector structure ?
Current jQuery implementation parses the selector string each time it runs.

**Comment by dmethvin** [comment]
Most of this plumbing is already in Sizzle for the case of complex selectors. We don't want to reimplement it inside jQuery just to further optimize rare cases. Long term @gibson042 has proposed merging Sizzle into jQuery but if anything I think that would eliminate the need for many of these optimizations.

**Comment by NN---** [comment]
Btw, what is expected time for 3.3.0 release?

**Comment by timmywil** [comment]
Thank you for opening an issue. Trying to pull out the valid bits and running them separately is an idea we've had before, but it gets extremely complicated. Besides, `:contains` is one of those selectors that has the potential to check a lot of stuff and be slow. I doubt running the attribute part separately would make much of a difference in performance. The slow part here *is* the invalid part, and there's not much we can do about that except to recommend not giving `:contains` too big of a block of text.

**Comment by NN---** [comment]
jQuery(“[id=x]”).find(“:contains(‘y’)”) works much faster than one selector due to optimization to querySelectorAll in the first part.
It can be easily split and optimized in jQuery.

I am going to do it by myself, it is not so hard.

**Comment by timmywil** [comment]
If it's much faster, it would definitely not be because `[id=x]` is run through qsa. It would be because `:contains` has less text that it's working on, and the learning site recommends doing things like this for `:contains` and other Sizzle extensions for that very reason. However, Sizzle will do that already for certain simple selectors, like ID and class so we already take care of some of the most common cases. I just don't think it's worth adding attribute to that.

Also, I don't think you realize the implications behind your suggestion. If you're going to run every valid part of a selector through qsa or matches, then you should do it for more than just selectors like this. And that is a complete rewrite of Sizzle. To be honest, that's exactly what may happen in the future, but that's a roadmap thing, not a simple enhancement.

**Comment by NN---** [comment]
Well, yes.
I always thought jQuery is working in such way and holds parse tree cache to not parse selectors each time.
It was surprise for me to see a more naïve implementation.

Btw, my performance issues are in reality due to bad design and I am going to make drastically less queries.
