### ISSUE TITLE
outerWidth of svg yields NaNpx. Previously yielded a number.

### ISSUE THREAD

**Issue by AlexEdgcomb** [jquery/jquery#3964]
### Description ###

On v3.3.1, `outerWidth()` of an `svg` yields `NaNpx`.

I expected a number. Prior versions (e.g., v3.2.1) yielded a number.

Issue reproduces on each OS/browser combo I tried: Mac/{Chrome, Firefox, Safari} and Windows/{Edge, Firefox, Chrome}.

### Link to test case ###

v3.3.1: https://jsfiddle.net/u9pk0gdq/1/ (yields `NaNpx`)

v3.2.1: https://jsfiddle.net/378suvLg/ (yields a number)

**Comment by gibson042** [comment]
Hmm, interesting. SVG elements don't have `offsetWidth` or `offsetHeight`, so `boxModelAdjustment` gets NaN when trying to calculate their scroll gutters. This can be fixed by adding an `|| 0` in the final `delta` adjustment and covering SVG dimension getters with unit tests. Would you like to contribute a PR, @AlexEdgcomb?

**Comment by AlexEdgcomb** [comment]
@gibson042 , I appreciate the offer, but I'll pass this round. Thanks!

**Comment by mgol** [comment]
@jonathanv3232 GitHub doesn't allow to assign issues to people without commit access to the repo so we can't set you but feel free to take a shot at a PR!

**Comment by kktam** [comment]
Submitted [PR](https://github.com/jquery/jquery/pull/4025) for the fix.
