### ISSUE TITLE
Edge 16 fails "manipulation" tests

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#3971]
```
# Fail
95. manipulation: html(script type module)
Expected 4 assertions, but 0 were run
```

1. <http://swarm.jquery.org/result/2607403> (20 Jan 2018; 294a3698811) - Fail
2. <http://swarm.jquery.org/result/2606429> (19 Jan 2018; f2349aee9) - Fail
3. <http://swarm.jquery.org/result/2605519> (19 Jan 2018; 9a7cc801f) - Last pass

```
# Last pass
manipulation: html(script type module) (4)
 evaluated: module
 evaluated: inner module
 evaluated: module with src
 evaluated: inner module with src
```

**Comment by timmywil** [comment]
Edge 16 passes for me in browserstack. Looks like the test is flakey here.

**Comment by mgol** [comment]
Yeah, after restarting it manually in TestSwarm it succeeds as well. Sounds like a flake but we should still make it less flakey.

**Comment by Krinkle** [comment]
This seems fine now.

**Comment by Krinkle** [comment]
Oops, still happening every other run or so.

**Comment by timmywil** [comment]
There are some swarm failures in issues and some that are not. Rather than opening an issue for every failure, we will track them in the meeting agenda with a link to a swarm job. This will give us a history of swarm failures through the meeting notes and have the advantage of being a little less tedious. Also, swarm failures are often more an indication of something wrong with the test rather than something wrong with jQuery Core itself. And, swarm failures are not urgent. They simply must be addressed before a release. Please be assured there's no danger of releasing without all greens (or maybe one or two reds that we are absolutely certain do not necessitate a core change as opposed to a test change).
