### ISSUE TITLE
Synchronous XMLHttpRequest warn with jQuery.fn.load and jQuery.html (jQuery.parseHTML)

### ISSUE THREAD

**Issue by brcontainer** [jquery/jquery#3975]
Version tested: 3.3.1 and dev (3.3.2-pre)

### Description ###

When i try load external document like this:

index.html:

```
<div id="container">Loading...</div>
<script>
$("#container").load("content.html");
</script>
```

content.html:

```javascript
<div>foo bar</div>
<script src="foo.js"></script>
```

I get this *warning*:

```
[Deprecation] Synchronous XMLHttpRequest
[Deprecation-Synchronous-XMLHttpRequest.zip](https://github.com/jquery/jquery/files/1712414/Deprecation-Synchronous-XMLHttpRequest.zip)
 on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

"Trackback":

```
- send @ jquery.js:9488
- ajax @ jquery.js:9206
- jQuery._evalUrl @ jquery.js:9367
- domManip @ jquery.js:5759
- append @ jquery.js:5898
- (anonymous) @ jquery.js:5992
- access @ jquery.js:3939
- html @ jquery.js:5959
- (anonymous) @ (index):7
```

This is because the `options.ascyn` is `false` when load scripts from `<script>` in `.html()` and `.load()`

### Link to test case ###

[Deprecation-Synchronous-XMLHttpRequest.zip](https://github.com/jquery/jquery/files/1712425/Deprecation-Synchronous-XMLHttpRequest.zip)

**Comment by dmethvin** [comment]
This is working as it always has since `.load()` was created. The warning is coming from the browser, not jQuery. The API is guaranteeing that if you attempted to use the loaded HTML in the line of JavaScript after the `.load()` it would be available. If the request is changed to an async request, jQuery can no longer guarantee that the loaded HTML is available. Worse, there is no mechanism available via `.load()` to indicate when the HTML has been loaded.

If you do not want to receive this warning from the browser, you will need to rewrite the `.load()` call as an async `jQuery.ajax()` call that injects the HTML into the document. We cannot change `.load()` in a minor version since it is a breaking change. It's not even clear whether it makes sense to try and fix this API, it may be simpler to deprecate/remove it and give people instructions on how to rewrite it into `jQuery.ajax()` calls. For example if you have this:

If the injected HTML has embedded `<script>` tags, which from the stack trace is probably the case here, you should remove them from the HTML and inject the scripts directly in your own code. Those scripts cannot act on the injected HTML until that HTML is loaded.

So as an example if you had this HTML in fragment.html:

```html
<input type=checkbox name="check1">
<script src="myscript.js"></script>
```

and this jQuery in your main HTML file:

```js
$("#content").load("fragment.html");
$("#content input[type=checkbox]").attr("checked", "true");
```

Change it to something this:
```html
<input type=checkbox name="check1">
```

```js
$.ajax({
   url: "fragment.html",
   dataType: "html",
   success: function(html) {
      $("#content").html(html);
      $.getScript("myscript.js", function() {
         $("#content input[type=checkbox]").attr("checked", "true");
      });
   }
});
```
Note that there can be cases where synchronously injected HTML is used far away from the point where it is injected, so the rewrite may not be as obvious as this case. 

Does this seem really complicated, and/or are you working with code you don't understand in a plugin you didn't write or code that you got from StackOverflow? If so, ignore the console warning and keep your existing code. If you need further help you could check out StackOverflow.

https://stackoverflow.com/questions/24639335/javascript-console-log-causes-error-synchronous-xmlhttprequest-on-the-main-thr

**Comment by seductiveapps** [comment]
dmethvin, that would (potentially) require a lot of rewriting of app code by jQuery users.
my entrypoint into this mess is jQuery.parseHTML(), which i use as follows after content has loaded using a simple ajax GET of some php output:
`jQuery('#siteContent').html('').append(jQuery.parseHTML(data, document, true));`
data being the php output.

i've been able to solve this problem for my own site, and i'd like to share that solution with you.

i have a different approach that does not require as much rewriting of app code by jQuery users.
- it turns out[1] already eval()s the script content
- you could add a callback function parameter to jQuery.parseHTML() if you'd add to jQuery.ajax() in the [1] use case, a statement (after the eval of the script content) that unlocks [2] (by waiting for a variable defined by jQuery.parseHTML() in [2b] instead of sa.s.c.settings.contentLoaded) and then calls the new callback parameter of jQuery.parseHTML().
- you can add the same callback functionality to other use cases as they pop up in the jQuery bugreports.
- [2] is a useful addition to jQuery, i'm donating it to the jQuery developers and community.

[1]
`jQuery._evalUrl = function( url ) {
    debugger;
	return jQuery.ajax( {
		url: url,

		// Make this explicit, since user can override this through ajaxSetup (#11264)
		type: "GET",
		dataType: "script",
		cache: true,
		async: true, // NO LONGER ALLOWED TO BE FALSE BY BROWSER
		global: false,
		"throws": true
	} );
};
`

[2] [2b] sa.m.waitForCondition() usage example
`
delete sa.s.c.settings.contentLoaded; // sa.s.c = seductiveapps.site.code

// load the content asynchronously, which, after all content and accompanying js is loaded and eval()-ed, sets sa.s.c.settings.contentLoaded to true.

sa.m.waitForCondition ('content loaded?', function () {
  return sa.s.c.settings.contentLoaded;
}, function () {
  // at this point, the content and all accompanying js is fully loaded, you can now do whatever is needed with the content
}, 50);
`
[2] [2a] sa.m.waitForCondition() definition
`	
waitForCondition : function (label, condition, callback, frequency, context) {
	// used (for instance) to let a page wait for vividDialogs to be fully initialized before showing the site's components.
	// see the source of http://seductiveapps.com for a demo
		var _fncn = 'sa.m.waitForCondition(): ';
		if (typeof label!=='string') { sa.m.log ( { error : _fncn+'invalid label' } ); return false;};
		if (typeof condition!=='function') { sa.m.log ( { error : _fncn+'invalid condition' } ); return false; };
		if (typeof callback!=='function') { sa.m.log ( { error : _fncn+'invalid callback' } ); return false; };
		if (typeof frequency=='undefined' || frequency<200) frequency = 200; // prevents excess stress on js engine

/*
		if (label.stacktrace === undefined) {
			try { 
				var a = {}; 
				if (a.debug) {
					a.debug(); 
				} else {
					throw new Error("myError");
				}
			} catch(ex) { 
				var stacktrace = (
					sa.m.globals.log.doStackTraces.forAllCode
					|| sa.m.globals.log.doStackTraces.forCodePath[codePath]
					? (sa.m.userDevice.isFirefox ? ex.stack.split('\n') : ex.stack)
					: '[no stacktrace provided]'
				)
			};
			label.stacktrace = stacktrace;
		};
*/		
		var r = condition(context);

/*
		var dbgMsg = 
			_fncn + label + '\n' 
			+ 'condition : ' +condition+ ' = ' + (r?'true':'false')+ '\n' 
			+ 'callback : ' + callback; 
		var dbgData = {
			startStacktrace : label.stacktrace,
			label : label,
			condition : condition,
			callback : callback,
			frequency : frequency//,
			//conditionAsText : '' + condition,
			//callbackAsText : '' + callback,
		};
		sa.m.log (1, dbgData);
*/

		if (r) {
		// condition()==true, we're done waiting
			clearTimeout (sa.m.settings.waitForCondition[label]);
			delete sa.m.settings.waitForCondition[label];
			if (typeof sa.tracer!=='undefined') callback.ua = sa.tracer.findUA(arguments);
			callback();
		} else {
		// condition()==false, more waiting
			if (!sa.m.settings.waitForCondition[label]) { // prevents double checks & activations of callback().
				sa.m.settings.waitForCondition[label] = setTimeout (sa.m.traceFunction(function () {
					clearTimeout (sa.m.settings.waitForCondition[label]);
					delete sa.m.settings.waitForCondition[label];
					sa.m.waitForCondition (label, condition, callback, frequency, context); 
				}), frequency);
			} 
		}
},`

**Comment by dmethvin** [comment]
It's hard to read the solution here because it looks like it's changes to the minified file which doesn't have variable names that mean anything. In fact, those names can change each time jQuery is rebuilt! The original source code is here in the repo, it would be much clearer to describe the changes in regards to that.

Few users call `jQuery.parseHTML()` directly. Pretty much any jQuery API that accepts HTML can potentially have a `<script>` tag in it, not just `$.fn.load()`. Any reference to an external script must be evaluated sync in order to work in a way compatible with existing jQuery code, and only a major version bump in jQuery could change that.

Without describing the internal changes to jQuery itself, can you show what a user would put into their own code for the example I gave above in order to make their synchronous code work asynchronously?

**Comment by timmywil** [comment]
I agree with @dmethvin's assessment here and we are unlikely to make significant changes to avoid this warning.
