### ISSUE TITLE
Element Lifecycle | New event "afterLoaded" and "beforeUnloaded" on DOM elements

### ISSUE THREAD

**Issue by JohannesBeiser** [jquery/jquery#3981]
### Description ###
So far there is no option to react to the removal of an Element.
Also we can not react to elements after they are added.
Having something like a lifecycle to DOM elements would be great
Mutation Observer could come in handy here maybe?

### Example ###

In Javascript/TS I create a couple of elements like `$a = $("<div><span>Some Text</span></div>")`

At some point they are are added to the DOM, now it would come in really handy if we could react to this so we can give our element some more properties that were impossible to assign before it was loaded into the DOM. For example we now can calculate elements width which we couldn't do right after the creation of the element in Javascript since it was not in the DOM yet.

Furthermore it would be powerful I think to do the following:
`$("#div1").on("beforeUnload", function)`
There are many use cases where this would come in handy.

Let me know if this does / doesn't make sense.
If you think that would be great to have I would start building up a concept

**Comment by dmethvin** [comment]
The best way to do this would be to use [Mutation Observers](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver). Modeling them as events doesn't really work because mutation notifications are batched asynchronous to the actual insert/remove operation. There used to be some non-standard [mutation events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events) in some browsers that do just what you're describing but they're a horrible performance drag specifically because they're synchronous and per-action.

**Comment by JohannesBeiser** [comment]
Ahh okay thanks, but for my own use I could achieve what I described without events with Mutation Observer only?

**Comment by dmethvin** [comment]
Probably not exactly as you described. If some code unrelated to the caller wants to catch something before it's inserted into the document and mess with it (as opposed to modifying it soon after it was inserted) that would need to be a synchronous interface. I think any design that needs to do that is not a good design, but you're welcome to experiment.
