### ISSUE TITLE
jQuery 3.3.1: function position( ) returning wrong values for properties "left" and "top"

### ISSUE THREAD

**Issue by programmer-mf** [jquery/jquery#3984]
Hi, the scenario where we got aware of the following issue, is much too complex for a post here and moreover, it is company property. ;)

So here an in its extent highly reduced example where you can reproduce at least that jQuery's function position( ) returns different values for properties "left" and "top" from version 3.3.1 on:

```html
<html>
  <head>
  
    <!-- Inclusion of jQuery -->
	
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	
	<!-- Compare the results in the alert box with those in any -->
	<!-- other jQuery version as 3.2.1, 2.2.4, 1.6.3 and so on. -->
	<!-- Here you find all hosted jQuery libraries at Google:
	<!--    https://developers.google.com/speed/libraries/ -->
	
<script>
	
$( document ).ready ( function ( ) {
		
	var id = $( '#row-2' );
	alert( 'id.position( ).top: ' +
	       id.position( ).top + ' - id.position( ).left: ' +
		   id.position( ).left );
		
} );
	
</script>
	
<style type="text/css">
    .tableCell { border-width: 1px; border-style: solid; border-color: #a05020; padding: 50px; }
</style>
	
  </head>
  <body>
	 
   <table>
      <tr>
         <td class="tableCell">
	    Cell 1
	 </td>
       </tr>
       <tr>
          <td id="row-2" class="tableCell">
             Cell 2
          </td>
       </tr>		   
   </table>

  </body>
</html>
```

With all tested jQuery versions except 3.3.1, you get the result:

> id.position( ).top: 132 - id.position( ).left: 10

Exclusively with jQuery 3.3.1 you get:

> id.position( ).top: 124 - id.position( ).left: 2

Divergences are still much bigger in our business code, all values fall down to zero and no container lands any longer where it actually belongs to...
Can you tell me if there is any CSS property / relation which plays a central role from jQuery version 3.3.1 on (although I cannot find any note on https://api.jquery.com/position/ ) or if it has to be seen & fixed as a bug in this version?

bye, MF

**Comment by timmywil** [comment]
Thanks for opening an issue. We prefer to see reduced test cases rather than whole applications so no worries there.

It has been seen as a bug fix to match native behavior. The spec defines an offsetParent as the closest element with non-static position *or* a table, td, or th element. In your case, the table is the native offsetParent (http://jsbin.com/vamufed/edit?html,js,console). We have an issue to track the update to docs [here](https://github.com/jquery/api.jquery.com/issues/1081). If all else fails, you can get the offset of the ancestor you desire and the offset of the td element and subtract (e.g. http://jsbin.com/huhiled/3/edit?html,js,console).
