### ISSUE TITLE
iOS 7 fails "css" test

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#4019]
This test has been consistently failing in iOS 7 since December 2017 (possibly earlier, no data that far back).

```
module css
test 37. css: css('width') should work correctly with browser zooming (1, 0, 1)
  assert 1. elem.css('width') works correctly with browser zoom
    Expected: "100px"
    Result: "121.81818175315857px"
```

<img width="1010" alt="screen shot 2018-03-23 at 19 32 32" src="https://user-images.githubusercontent.com/156867/37859440-f8f87b04-2ed0-11e8-9939-ab9c17abbf60.png">

* http://swarm.jquery.org/job/7011 / <http://swarm.jquery.org/result/2691198> (2 days ago)
* ...
* http://swarm.jquery.org/job/6563 / http://swarm.jquery.org/result/2562773 (25 Dec 2017)
* ...

**Comment by Krinkle** [comment]
Reminder - this is still (deterministically) failing on current master.

http://swarm.jquery.org/project/jquery • http://swarm.jquery.org/job/7700 • http://swarm.jquery.org/result/2893285 (1 Aug 2018).

**Comment by timmywil** [comment]
There are some swarm failures in issues and some that are not. Rather than opening an issue for every failure, we will track them in the meeting agenda with a link to a swarm job. This will give us a history of swarm failures through the meeting notes and have the advantage of being a little less tedious. Also, swarm failures are often more an indication of something wrong with the test rather than something wrong with jQuery Core itself. And, swarm failures are not urgent. They simply must be addressed before a release. Please be assured there's no danger of releasing without all greens (or maybe one or two reds that we are absolutely certain do not necessitate a core change as opposed to a test change).
