### ISSUE TITLE
Syntax error caused by `$("input:enabled:invalid")`. (unrecognized expression: unsupported pseudo: invalid)

### ISSUE THREAD

**Issue by yuji38kwmt** [jquery/jquery#4021]
#### Steps to reproduce
1. Create following html file.

```html
<input type="text" required value="test">
<input type="text" required>
<input type="text" required disabled> 
```

2. Run following javascript in Chrome or IE11 Console.

```js
$("input:enabled:invalid").length;
```

Then following error caused.

```txt
Error: Syntax error, unrecognized expression: unsupported pseudo: invalid
    at Function.Sizzle.error (jquery-3.3.1.js:1541)
    at PSEUDO (jquery-3.3.1.js:1888)
    at matcherFromTokens (jquery-3.3.1.js:2437)
    at Sizzle.compile (jquery-3.3.1.js:2591)
    at Sizzle.select (jquery-3.3.1.js:2677)
    at Function.Sizzle [as find] (jquery-3.3.1.js:845)
    at jQuery.fn.init.find (jquery-3.3.1.js:2873)
    at new jQuery.fn.init (jquery-3.3.1.js:2983)
    at jQuery (jquery-3.3.1.js:139)
    at sample.html:36
```

#### Environment
* jQuery 3.3.1
* Windows 10

|Browser| Result |
|:--:|:--|
|Google Chrome 65.0.3325.181| Error |
|Internet Explorer 11.309.16299.0| Error |
|Microsoft Edge 41.16299.248.0|OK|
|Firefox 59.0.1|OK|

#### Expected action

I expected that `$("input:enabled:invalid").length;` returns `1`.

### Link to test case ###

https://codepen.io/yuji38kwmt/pen/ZxJvQW

**Comment by timmywil** [comment]
Thank you for opening an issue! However, the `:invalid` selector is not officially supported in jQuery. It works natively, but Sizzle doesn't trust native qSA with `:enabled/:disabled` due to a certain qSA bug in Chrome. There are a couple workarounds.

1. Add a form validation jQuery plugin that also adds support for `:invalid/:valid` selector extensions, like jquery-validate.
2. Use `.filter(':invalid')` instead to rely on native `matchesSelector` and bypass Sizzle altogether.

**Comment by yuji38kwmt** [comment]
Thanks!

**Comment by chrobaks** [comment]
$('input').filter(':invalid').length; doesn't work. This is the error message:
Error: Syntax error, unrecognized expression: unsupported pseudo: invalid
