### ISSUE TITLE
Form serializations doesn't work if you have <input name='elements'/> in that form

### ISSUE THREAD

**Issue by Boorj** [jquery/jquery#4022]
Reproduction:
---
Example here: https://jsfiddle.net/qcx2zxs1/

### tl;dr
1. create a form with `<input name='elements'/>`
2. try to serialize form by `.serialize()` (which uses `.serializeArray()`)
3. you will get only `elements` input value.

This happens because of this line:
https://github.com/jquery/jquery/blob/master/src/serialize.js#L102

Configuration
---
Jquery edge. Actually, repro works on any jquery that i tested. Looks, that line is present in history since the very first commits.

**Comment by dmethvin** [comment]
This doesn't work with bare DOM either. https://bugs.jquery.com/ticket/14594

https://kangax.github.io/domlint/

**Comment by Boorj** [comment]
But can't we just change 
```js
var elements = jQuery.prop( this, "elements" );
// to something like this:
var elements = jQuery(this).find('[name]');
```
to aggregate all fields?

**Comment by dmethvin** [comment]
The [comment line above](https://github.com/jquery/jquery/blob/73d7e6259c63ac45f42c6593da8c2796c6ce9281/src/serialize.js#L101) indicates this is an extension point that allows external code to change things by altering `jQuery.propHooks.elements` so that can't just be removed. It would have to be incorporated into the new logic somehow.

We only want to serialize form elements (`input`, `datalist`, etc.), not all elements with a `name` attribute. More specifically, we only want to serialize form elements that belong to the enclosing form. As of HTML5 it is possible for an `input` element to have a `form` *attribute* that makes it belong to another form, so an assumption that form fields in the form's subtree are fair game does not hold. The `elements` property takes that into account so currently we get it for free.

Here's a test case to experiment on, remove the input named `elements` or change its `form` attribute and watch the difference: http://jsbin.com/fapuwib/edit?html,js,console 

There are no doubt ways to work around this but I *think* they require some pretty expensive searching to get right.
