### ISSUE TITLE
select text of hidden textarea in IE11

### ISSUE THREAD

**Issue by atarsh** [jquery/jquery#4026]
### Description ###

The version(s) of the jQuery project that are affected - 2.2.4. works fine with jquery 1.12, 1.9.
The browser (or browsers) that you are able to reproduce the bug in, including version numbers. - IE11
The operating system (or operating systems) you experienced the bug on. - Windows 8.1
Step-by-step instructions on how to reproduce the issue, including any required system configuration changes - text area inside a div element > $('#div').hide() > $('#text').select() 

A description of what you expect to happen, and what actually happens.
expected: no error, text is selected.
actual: error: SCRIPT16389: Incorrect function. text is not selected, as can be seen if calling $('#div').show() now.

### Link to test case ###
https://jsfiddle.net/sL09e7zw/16/
click "hide", then "select text".

**Comment by mgol** [comment]
Thanks for the report & a reproduction!

I don't know if we can do anything about it here. The same happens without jQuery: https://jsfiddle.net/sL09e7zw/16/. We could only wrap us [calling the native method](https://github.com/jquery/jquery/blob/3.3.1/src/event/trigger.js#L148) in a try-catch but then we could be catching real errors as well.

**Comment by timmywil** [comment]
We discussed this in the meeting. The reason no error is thrown in 1.9.1 is because we had a try/catch. However, it still didn't "work" in 1.9.1. In other words, it never selected text. We don't think there's anything we can do here. We can't force the browser to select hidden text and we want to avoid catching errors as much as possible.
