### ISSUE TITLE
Can you explain what is this line that is causing some lag on my code.

### ISSUE THREAD

**Issue by MiguelQueiroz** [jquery/jquery#4073]
So after a long debugging on my app, related to rendering events on a calendar that apparently uses this deferred line, ( https://github.com/jquery/jquery/blob/821bf34353a6baf97f7944379a6459afb16badae/src/deferred.js#L230
 ) i ask what is the function of window.setTimeout(process) why is this in a timer with no seconds?

Is that some sort of hack to solve another issue? because on android chrome, i noticed that this would delay the execution on some of my code functions, in 1.5 seconds ( which for our application is high), this only happens in android chrome.

removing the timer, and calling the process() does solve the lag...

**Comment by dmethvin** [comment]
The [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout) show that the "seconds" are optional and that page explains what happens when it is omitted. The purpose is to wait until the next turn of the event loop before the action occurs. 

Explaining the code or debugging other people's code is really not the purpose of this issue tracker, but you could post some subset of the calendar code on StackOverflow so that a larger group of people can help you debug it.
