### ISSUE TITLE
Security Vulnerability 

### ISSUE THREAD

**Issue by sb-rustam** [jquery/jquery#4075]
Hello,

Currently we using the jQuery-1.11.1 library on our website and the Google Chrome browser Audits tool detects them as vulnerable. Please find this link for more details:

https://snyk.io/vuln/npm:jquery?lh@1.11.1

Can you please confirm if this is a legit issue? If so, then would you please advise hot to fix it?

Thank you,
Rustam.

**Comment by dmethvin** [comment]
Yes, old versions may contain security vulnerabilities or bugs that are fixed by the latest version. If you need more specifics about whether a particular issue actually affects your code base you should have it analyzed by a security professional. The jQuery core team does not provide those services.
