### ISSUE TITLE
Wrong $(window).innerHeight() and $(window).outerHeight() on mobile after scroll

### ISSUE THREAD

**Issue by tendermario** [jquery/jquery#4081]
Tested on Chrome on an android phone connected to my computer with [remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/).

**Expected behavior:**
When I am scrolling through the page, `$(window).innerHeight()` (and `outerHeight()`) should be equal to the height of the browser page.

**Actual behavior:**
On a mobile device, the returned value for `$(window).innerHeight()` seems to be the same as the innerHeight on page load, which has the top address bar visible to make the screen smaller.

E.g.:
On page load, innerHeight() returns `560` for me. The page height is correct.
On scroll event, innerHeight() still returns `560`. The browser has collapsed the address bar and the innerHeight is now `616` for me.

Open http://jsbin.com/vevicuvoxu/1/ on a phone and scroll down.

![screen shot 2018-05-17 at 3 33 59 pm](https://user-images.githubusercontent.com/12423598/40207144-d8ac2944-59e7-11e8-80dd-14e1289a1e0e.png)

**Work around:** `window.innerHeight` is still showing the correct value, so I had to use that for now.

**Comment by timmywil** [comment]
Despite the confusion caused by the naming, the workaround here is to use `.outerHeight` which maps to `window.innerHeight` in the source. This is because `.outerHeight` includes scrollbar width/height. `.innerHeight` and `.height` use `document.documentElement.clientHeight`, which apparently does not adjust when the address bar collapses. There's a bit of extra weirdness when it comes to mobile, but since the workaround here is so simple, I'm inclined to close.
