### ISSUE TITLE
Vulnerability report for jquery@1.12.4

### ISSUE THREAD

**Issue by stavackoli** [jquery/jquery#4086]
### Description ###
We have an application that runs only in IE and only with compatibility mode, then we can not upgrade it to jQuery 3.0.0.
Is it possible to fix this issue for this version?

**Comment by dmethvin** [comment]
The jQuery project does not generate vulnerability reports. Your report provides no details on the vulnerability that you're talking about. Vulnerabilities that were fixed in 3.0 involved breaking changes so they cannot be back-ported into semver-minor versions. If you need additional help with security issues you should contact a security consultant. They can help with fixing the application but be aware that a naive vulnerability scanner will not recognize a patched version of jQuery.
