### ISSUE TITLE
GetClientRects error for disconnected node in IE

### ISSUE THREAD

**Issue by ellyfb123** [jquery/jquery#4097]
I meet an error after I upgrade the jQuery from 2.1.0 to 3.3.1.
error message is "object doesn't support property or method 'getclientrects'" caused by the code: "if (!elem.getClientRects().length)"

in old version, there is code to handle the disconnected DOM node:
if (!jQuery.contains(docElem, elem)) {
 return box;
}

Is there any special reason you deleted the disconnected DOM node handling code in latest version? If so, do you have any suggestion for us to resolve that error from our side?

Thanks.

**Comment by mgol** [comment]
Calling `offset()` (I assume that's what's you're doing, you haven't written that) is not valid on disconnected nodes; any input we'd return would still be invalid and can only mask errors. That's why it was removed, see:
https://jquery.com/upgrade-guide/3.0/#breaking-change-invalid-input-to-the-offset-method

If your code computes offsets for disconnected nodes there's a high chance you already have a bug in your app.
