### ISSUE TITLE
Firefox: outerHeight() not taking <caption> height into account for tables

### ISSUE THREAD

**Issue by Payn** [jquery/jquery#4105]
### Description ###
outerHeight() returns only \<table\> height even if it contains \<caption\> in Firefox 61, IE 11 and Edge.
Works fine in Chrome

### Link to test case ###
https://jsfiddle.net/a6c4jdt3/6/

outerHeight() returns 100 instead of 130

**Comment by 1jj** [comment]
This should be fixed in Firefox 63
https://bugzilla.mozilla.org/show_bug.cgi?id=820891

**Comment by TruptiM18** [comment]
Can I work on this issue?

**Comment by timmywil** [comment]
@TruptiM18 Sure, feel free! Have a look at our Contributing guide if you need a place to start https://github.com/jquery/jquery/blob/master/CONTRIBUTING.md.

**Comment by timmywil** [comment]
It says the bug is fixed, but I don't see any difference in FF 64 on Windows. Could anyone else confirm this is still an issue?

**Comment by timmywil** [comment]
Nvm, updated test case. It seems native `offsetHeight` does take caption into account, but jQuery's `outerHeight` does not (note that jQuery does in Chrome). https://jsfiddle.net/timmywil/Lqrwhnxu/1/

**Comment by timmywil** [comment]
Opened new bug on Firefox to see if we can get this fixed in native `computedStyle`.

**Comment by TruptiM18** [comment]
@timmywil I tested the test case code in following browsers on Windows and results are mentioned below-
Microsoft Edge 42
jQuery outerHeight 100
window.getComputedStyle(elem).height 100
getBoundingClientRect 130
offsetHeight 130
clientHeight 130
scrollHeight 130

Chrome 71
jQuery outerHeight 130
window.getComputedStyle(elem).height 128
getBoundingClientRect 130
offsetHeight 130
clientHeight 130
scrollHeight 130

IE 11
jQuery outerHeight 130
window.getComputedStyle(elem).height 98
getBoundingClientRect 130
offsetHeight 130
clientHeight 130
scrollHeight 130

Mozilla 61
jQuery outerHeight 100 
window.getComputedStyle(elem).height 100
getBoundingClientRect 130
offsetHeight 100
clientHeight 100
scrollHeight 100

As you mentioned, Mozilla does not take caption height into account while returning offsetHeight.
getComputedStyle().height in Chrome does consider caption height.
Whereas, IE 11 does not consider caption height and also subtracts the border height (-2px) from the rectangles height 100 and returns 98 instead of 100 in getComputedStyle().height.

Can we open a bug to IE team as getComputedStyle(elem).height computed by IE is different than the other browsers?

Please let me know if Mozilla team is not updating their code and we need a code change for this issue.

Thanks.

**Comment by mgol** [comment]
I added the "Needs review" label to discuss latest arguments from the discussion in the Firefox ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1520264

**Comment by mgol** [comment]
@TruptiM18 Thanks for testing it in various browsers!

> Can we open a bug to IE team as getComputedStyle(elem).height returned by IE is different than the other browsers?

It doesn't buy us anything to report an issue to IE as IE is never going to change again, it's a frozen legacy browser and we'll have to live with its bugs until it dies.

Edge is soon going to switch to Chromium so it only really makes sense to submit issues to Chrome, Firefox or Safari (or rather WebKit) bug trackers.

**Comment by TruptiM18** [comment]
@mgol Thanks for the explanation!

**Comment by mgol** [comment]
We've discussed it today. While it may look surprising that an element may be higher than its set height, its not really isolated behavior. With the default `content-box` value for `box-sizing` specifying a `padding` or `border` on an element will cause that behavior already. It turns out tables have similar behavior - captions make the table higher than the specified height.

Now, `outerHeight` is supposed to cover `padding` & `border` (and optionally even `margin`) but it doesn't say anything about `<caption>`. Also, what if someone really wants the current behavior? Should we introduce a separate flag that will handle `caption`? This is all introducing complexity for an edge case as captions are way less prevalent than paddings or borders.

Also, as Boris Zbarsky rightly noticed in https://bugzilla.mozilla.org/show_bug.cgi?id=1520264#c1/show_bug.cgi?id=1520264, Chrome behavior has an unfortunate behavior where setting `elem.style.height` to the value returned from the same element with `getCompitedStyle(elem).height` would change its height.

Therefore, it seems we might be closer to accept Firefox behavior. But since the spec seems unclear what's desired here and browsers disagree, we wouldn't want to end up in a situation where we implement behavior opposite to the one that's specced. Until that's resolved, we're not going to normalize either way.

**Comment by mgol** [comment]
I've just documented the issue at https://github.com/jquery/jquery/wiki/Won't-Fix#outerheight-behavior-for-tables-with-captions
