### ISSUE TITLE
HTML hidden attribute on elements made visible with show() or toggle()

### ISSUE THREAD

**Issue by gunnarbittersmann** [jquery/jquery#4164]
### Description ###
When a hidden element `<div id="foo" hidden>` is made visible with `$('#foo').show()` or `$('#foo').toggle()` it still has the `hidden` attribute.
Apart from semantics, this is wrong because with a rule `[hidden] { display: none !important }` in the stylesheet, `show()` and `toggle()` will not work. (Uncomment this rule in the CodePen.)
Thus, `show()` and `toggle()` should remove `hidden` attributes from the elements.

### Link to test case ###
https://codepen.io/gunnarbittersmann/pen/jvNNpx?editors=1111

**Comment by mgol** [comment]
Thanks for the report. `show()` & `hide()` are one of the most complex jQuery CSS-related features as there are a lot of scenarios to handle, especially in connection to elements being visible or hidden not due to default `display` values or inline styles but some other conditions like having the `hidden` attribute. More on the changes in jQuery 3 here: https://jquery.com/upgrade-guide/3.0/#breaking-change-show-hide-and-toggle-methods-now-respect-more-stylesheet-changes

We've tried to make the methods way simpler for jQuery 3.0, basically only relying on inline styles but, alas, that didn't work as people expected `show()` being called on an element hidden via stylesheets to actually show that element. Still, I don't think we want to further complicate the implementation by modifying element attributes. Working on elements hidden with `!important` priority is also out of scope, unfortunately.

I'm closing the issue for now but feel free to elaborate further in this thread.

**Comment by gunnarbittersmann** [comment]
Hm, I don’t see how calling `prop( "hidden", false )` (or `removeProp("hidden")`?) inside `show()` (and `toggle()` when switching from hidden to shown status) would “complicate the implementation”.

I’m not saying to put `hidden` back on the element when `hide()` is called; setting `display: none` would be sufficient.

I’m just that `hidden` should be removed once the element is shown.

**Comment by dmethvin** [comment]
Our definition of "hidden" is meant to address only the CSS `display` property, and it has always been that way. If we try to incorporate the `hidden` attribute *sometimes* we are just making things more complex and causing  inconsistent edge cases. For example, if we start clearing `hidden` when showing wouldn't the next logical step be to pay attention to it for deciding whether something is hidden? 

If `.show()` and `.hide()` don't work for your needs, it's easy to create your own plugin of a few lines to implement some other behavior. That way you get what you want and no existing users have their code broken.
