### ISSUE TITLE
error in line 3887 (3.2.0), the same for all jquery-3.x.x 

### ISSUE THREAD

**Issue by marcoponta** [jquery/jquery#4177]
Dreaweaver shows error line in line 3887 (version 3.2.0). Same error for all 3.x.x.
------
Result: applying this JQUERY code:

$(window).load(function(){
	var maxHeight=$('list').height(); 
	$('.fitcol').each(function() { maxHeight = maxHeight > $(this).height() ? maxHeight : $(this).height(); })
	$('.fitcol').each(function() { $(this).css('padding-bottom', maxHeight - $(this).height() + 'px'); })
})

to this HTML:

<-div>
  <-ul class="list">
    <-li class="lt fitcol">xxxxxxxx</li>
    <-li class="rt fitcol">xxxxxxx</li>
  <-/ul>
<-/div>

the height control for "li" doesn´t work.
BUT THIS WORK PERFECTLY WITH UP TO 2.2.4

------------------------------------------------------------------------------------
jQuery.fn.ready = function( fn ) {

3881	readyList
3882		.then( fn )

		// Wrap jQuery.readyException in a function so that the lookup
		// happens at the time of error handling instead of callback
		// registration.
**3887**		.catch( function( error ) {
3888			jQuery.readyException( error );
3889		} );

3891	return this;
};
-------------------------------------------
![image](https://user-images.githubusercontent.com/12519355/45679573-2ef2e380-bb39-11e8-86e8-89922ea4793c.png)

**Comment by timmywil** [comment]
Thanks for opening an issue. Please provide a working test case from https://jsfiddle.net or https://jsbin.com to help us assess any issue.

**Comment by mgol** [comment]
There’s no syntax error here, Dreamweaver is wrong. Using a “catch” method unquoted is perfectly fine in ES5 and all of our supported browsers support this syntax. Are you perhaps using an older version?

That said, our [ESLint config](https://github.com/jquery/jquery/blob/dfa92ccead70d7dd5735a36c6d0dd1af680271cd/.eslintrc-browser.json) currently specifies `ecmaScript: 3` due to IE 9 so I wonder why it doesn't require us to quote the method...

**Comment by marcoponta** [comment]
Hi Timmy,
Here you have a demo. 
Change between JQuery versions 2.2.4 to 3.3.1 and check the background color in second "li".
http://jsfiddle.net/yowrqcf1/24/

**Comment by marcoponta** [comment]
Hi Timmy,

 

Here you have a demo. 

Change between JQuery versions 2.2.4 to 3.3.1 and check the background color in second "li".

 

http://jsfiddle.net/yowrqcf1/24/

**Comment by HTMLandJSVSCode** [comment]
It is correct

**Comment by timmywil** [comment]
Seems to me it doesn't work because the code doesn't run. I had overlooked the `$(window).load(...` line and was just reading the height lines. There are a few problems with this.

1. This event shortcut was deprecated and removed in jQuery 3.0. The method used to have 2 completely different purposes in one and it was better to remove the ambiguity (it kept the other purpose, which is for loading html content with ajax and inserting it on the DOM) This is documented here: https://api.jquery.com/load/. 
2. You should be able to use `ready` instead.
3. The fiddle seems to work fine after making this change. The background color of the second li looks the same using jQuery edge.
4. Issues like this are better fleshed out on stackoverflow.com or in the [jQuery gitter](https://gitter.im/jquery/jquery) before reporting it here.
