### ISSUE TITLE
fadeToggle() with siblings() selector returns the entire script to the DOM

### ISSUE THREAD

**Issue by lechien73** [jquery/jquery#4179]
### Description ###

Using fadeToggle() with the siblings() selector returns the text of the entire function on the DOM.

This issue arose in a class where I was teaching jQuery. We reverted to an older version, and the problem goes away. I've replicated the issue in JSFiddle.

In the test case, click on any of the red boxes to see the problem in action. Spurious JavaScript is appended to the DOM.

### Link to test case ###

http://jsfiddle.net/qtpezLyw/

**Comment by TruptiM18** [comment]
I am able to recreate a similar problem by using just toggle() instead of fadeToggle().

**Comment by lechien73** [comment]
Yes, it seems to be the same with all toggle functions. slideToggle() does the same.
@TruptiM18

**Comment by timmywil** [comment]
We looked this over in the meeting and noticed that this is indeed working as expected. The appearance of script text can be confusing, but there is in fact a sibling script element in the fiddle (next to the divs). Script elements are not visible by default, obviously, but can be animated like other elements. There are use cases for this, such as in demos or documentation, so it's not something we want to disable.

This particular case can be fixed by adding a selector to siblings.

https://jsfiddle.net/timmywil/jzd3mn0s/7/
