### ISSUE TITLE
Pause / Resume a CSS animation on tab change

### ISSUE THREAD

**Issue by rahulVerma27** [jquery/jquery#4202]
### Description ###

I was creating a code which pauses / resumes a CSS animation when the browser tab is changed.

> I wanted the animation to stop when the current browser tab is inactive and restart when the current tab is active again

I used the `focus` and `blur` events to achieve this, and they worked as expected. But, the `.css()` method failed to work, which was supposed to stop the animation. [Here is a detailed discussion on this issue](https://stackoverflow.com/questions/52892889/pause-resume-css-animations-when-switching-tabs)

I tested the code in Google Chrome `v70.0.3538.67` and in Firefox Quantum `v62.0.3 (32-bit)`

jQuery version used: `3.3.1`

### Link to test case: ### 

[JSFiddle](https://jsfiddle.net/r_v_7/gjt3146q/5/)

**Comment by timmywil** [comment]
Thanks for opening an issue. After review, `.css` is doing its job. The confusion seems to be related to how focus works on iframes. Note that changing tabs does not necessarily trigger blur on an iframe window, but your example actually works for me in Chrome and Firefox. I still might consider the visibility api rather than relying on window focus. Regardless, I don't see a jQuery issue.
