### ISSUE TITLE
AngularJS's ng-disabled doesn't remove "disabled" attribute when jquery is loaded

### ISSUE THREAD

**Issue by charlemagnelasse** [jquery/jquery#4249]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
ng-disable creates disabled="false"/ng-disabled="true" attributes for elements when jquery was loaded before angularjs. This was observed only for XHTML

**Expected / new behavior:**
disabled attribute is removed when ng-disabled evaluates to false

**Minimal reproduction of the problem with instructions:**
http://next.plnkr.co/edit/1GxYGSKho4H0nDAD
(tested in chromium - should be the same behavior in any XHTML aware browser)

**AngularJS version:** 1.7.5 (or whatever your server currently ships)

**Browser:** all? (tested in chrome 70.0.3538.110 | Firefox 60.3.0esr)

This was already submitted to angularJS but they say it is the fault of jquery: https://github.com/angular/angular.js/issues/16778

**Comment by jbedard** [comment]
Here's a jQuery only version: http://next.plnkr.co/edit/QlL18WpsOlkofGJ0

**Comment by charlemagnelasse** [comment]
I don't need a jQuery only version. I am talking about a bug which breaks angularJS.

**Comment by charlemagnelasse** [comment]
See the discussion at https://github.com/angular/angular.js/issues/16778

**Comment by timmywil** [comment]
This was 7 years ago so bear with me if I misremember some details. I'll attempt to explain.

The boolean hook is there both for back-compat-lots of code still out there with `.attr(<boolean>, false)` that would not work as intended-and compliance with the [standard](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes).

> If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.

Not even the strings "true" and "false" are technically allowed. 

> The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether.

The point is simply to write valid DOM despite common, predictable misuse of the API.

An attribute in an XML document that happens to have the same name as a boolean attribute, such as `disabled` does not have any special meaning. The boolean attribute behavior only applies to HTML documents (and even then limited to certain nodeNames as @mgol pointed out).

The original bug wasn't really related to XML exactly, but it did make me think of this distinction when the user tried to access what looked like boolean attributes on a custom tag. As @mgol said, the `disabled` attribute on a custom tag has no special meaning or behavior. In the old boolean hook, we used to check the corresponding property to construct a valid return value. In this case, the property of course returned `undefined`, just as it would in XML, and so it always returned `undefined` for the attribute value. At some point, we started sharing a lot more attribute code with Sizzle and instead checked the attribute using `.getAttribute`. If it returns any value at all, we can assume the boolean attribute is `true`.

The boolean setter hook remains in place to remove boolean attributes whenever someone tries to set `false`, which as @dmethvin pointed out is an artifact of the old attroperties and far too common and technically incorrect. However, Angular should have been using `.removeAttr` all along. `.attr("disabled", false)` really makes no sense. If we were completely aligned with the spec, what we should have done is set the value `"false"`, which would both be invalid and work as if the value `"disabled"` or literally any string value were set instead, because browsers are lenient.

As for what changes to make, I'm not sure. It's my understanding that boolean attributes also have no special meaning or behavior in a pure XML document (which is different than XML in HTML), even on tags that happen to be named `INPUT`, hence the different path for XML documents. However, XHTML presents a challenge if we cannot distinguish between XHTML and XML.

**Comment by timmywil** [comment]
Sizzle has a PR that should address this. XHTML will follow the HTML path and all *should* work as expected, unless anything we haven't foreseen comes up, which sometimes happens.

**Comment by mgol** [comment]
Sizzle PR: https://github.com/jquery/sizzle/pull/436

**Comment by mgol** [comment]
I added this to the `3.4.0` milestone as all we need is merging that Sizzle PR, publishing it & updating the Sizzle dependency in jQuery.
