### ISSUE TITLE
Image Tag is changed to Img Tag

### ISSUE THREAD

**Issue by LRagji** [jquery/jquery#4283]
`<Image>` tag changes to `<Img>` tag when using append in JQuery

While img tag is valid for Html, it is not inside svg element so it breaks the svg tag and fails to render the specified image.

Demo Link: https://jsfiddle.net/LaukikR/509wL67x/2/

**Comment by LRagji** [comment]
I am a bit confused if `Image ` is a non-standard `Img `is standard why doesn't the above fiddle work? my assumption is this is still a standard way of loading images inside a svg element is it not?

**Comment by mgol** [comment]
Your fiddle doesn’t try to load any images, all relevant attributes are empty...

**Comment by LRagji** [comment]
I just updated the fiddle, by default it will not render as jquery is appending a `img` tag, but if you want  to verify `image` tag works then just paste it directly into html it should render the svg

**Comment by dmethvin** [comment]
Yeah, this seems like a ["don't cross the streams"](https://www.youtube.com/watch?v=wyKQe_i9yyo#t=47) problem to me. This line is trying to append an SVG DOM element to an SVG element. 
```js
$("#portal").append(`<image xlink:href="" src="" height="100%" width="100%" />`)
```
jQuery serializes that string to an HTML DOM because it's an HTML library meant to manipulate HTML elements. jQuery does not even know the element being appended to is an SVG element at the point where the string is serialized. Even if it could determine the target DOM is SVG for this particular case, there are many cases where it cannot;  those kind of special cases would just create more confusing inconsistencies.
