### ISSUE TITLE
html() function not work as expetced when using selector list

### ISSUE THREAD

**Issue by balalaXD** [jquery/jquery#4287]
*  What do you expect to happen?
It should trim all leading and trailing whitespaces.
*  What actually happens?
It only trim whitespaces contents of `<pre>` but not `<code>`
*  Which browsers are affected?
Currently test on firefox not working.

### Description ###
Consider you have some html like below, you want to trim the whitespaces
```html
      <pre>
      
      
      
      
        <code class="language-lisp">
          (defun multiply-by-seven (number)
            "Multiply NUMBER by seven."
          (* 7 number))
        </code>
        
        
        
        
      </pre>
```

With 
```javascript
$ ("pre, code").html (function (_, html) { return $.trim (html) })
```
become
```html
<pre><code class="language-lisp">
          (defun multiply-by-seven (number)
            "Multiply NUMBER by seven."
          (* 7 number))
        </code></pre>
```

With 
```javascript
$ ("pre").html (function (_, html) { return $.trim (html) })
$ ("code").html (function (_, html) { return $.trim (html) })
```
become
```html
<pre><code class="language-lisp">(defun multiply-by-seven (number)
            "Multiply NUMBER by seven."
          (* 7 number))</code></pre>
```
### Link to test case ###
http://jsfiddle.net/mLt1wu3y/

**Comment by gibson042** [comment]
The `.html` setter _replaces_ the contents of its context elements, disconnecting from the DOM any previously existing descendants. So in your \<code> inside \<pre> example, if it is invoked on the \<pre> element first (as is the case with a `$(…)` that selects both, since matching elements are returned in DOM order), then the selected \<pre> element is no longer part of the DOM and any manipulation of its HTML will not be visible unless it is reattached.

If you want to recursively trim whitespace, then you should either work in reverse order (e.g., `$($("pre, code").get().reverse()).html(…)`) or—if preserving all the original elements is important—operate directly on their contents to remove leading whitespace from `firstChild` text nodes and trailing white space from `lastChild` text nodes (for which direct use of jQuery won't be much help, cf. http://jsfiddle.net/Ln1x2uda/ ).
