### ISSUE TITLE
Temporary Sizzle nodes trigger mutationObserver and no easy way to identify their nature. Related performance problems on running against different window.

### ISSUE THREAD

**Issue by exteon** [jquery/jquery#4332]
### Description ###

We are adding an element via jQuery to an inner frame (different window object) which is watched by a `MutationObserver` set on `window.document`.

When adding the element, a blank node with an id of `#sizzle<numeric_id>`  is created on the document.

What is the documented purpose of this node? We would like to be able to either avoid its creation or a reliable way to determine its nature and ignore it (matching id against `sizzle\d+` seems a bit contrived, undocumented and prone to break in the future...!?).

Searching for this revealed it's some internal functionality in jQuery related to supporting IE. However we  are actually seing this in Chrome/FF so we are at a loss for any documentation of this behavior.

**Update:** the manipulations on these nodes seem to happen even in the most innocent-looking of operations, such as calling `:is(':hidden')` on any node. It's a storm of DOM changes for any operation.

**Update2:** We took a look at the jQuery source files and did some more behavior testing; it's apparent to us that `Sizzle.setDocument()` (which does this) is called on every invocation on any selector. There is no way this can not be a performance hog. Also we found it also creates `<div></div>` nodes without id directly in the document, so there is no way to tell the nature of the created nodes.

**Comment by gibson042** [comment]
Your observations are correct. Creation of test elements such as those from https://github.com/jquery/sizzle/blob/67e9691e8689b824387affb9da06dc663da63598/src/sizzle.js#L634 cannot be avoided, and giving them unpredictable ids is intentional because it keeps multiple instances of jQuery and/or Sizzle from confusing each other's data.

`setDocument` itself is necessary because almost every DOM implementation has bugs that Sizzle must detect in order to fix, and those bugs are different across e.g. HTML and XML DOMs within the same browser. `setDocument` aborts when it detects that the context document has not changed since the last invocation, but we do not cache beyond that so switching between frames incurs the penalty.

This could potentially be addressed, but it is an unusual case that we haven't optimized for (and would not optimize for unless it could be done without significantly increasing gzipped file size). And since a future release of jQuery will replace Sizzle anyway, we are unlikely to devote much effort to this. But if you wish to open a pull request against Sizzle, I promise to help you work through it. Absent that, I would probably instrument the mutation observer to be aware of and ignore the automatically-created elements (all of which should relate to selection, and all of which are also removed immediately).

**Comment by exteon** [comment]
Ok, thanks, notes:

> setDocument itself is necessary because almost every DOM implementation has bugs

Yes, but it runs on every invocation of $(selector)... it seems if there is any caching it only works in the root document.

> I would probably instrument the mutation observer to be aware of and ignore the automatically-created elements

I would too, but the nodes created are nothing more than `<div></div>`. So there is absolutely no sane way of determining the nature of the created nodes. Methinks for ~50 characters in the ungzipped file size the created elements could at least bear some `data-jquery-temporary` property of sorts.

So, since this is undocumented, undocumentable and contrary to any good practices (changing content in an undocumented and untraceable way), I ponder dropping jQuery altogether for all cross-window manipulations as the sane design choice. Luckily the codebase is not too big (yet). However, if we find that the frame's local instance of jQuery behaves the same way internally (temporary node create/delete storm for every selector), that will be a problem, as the frame does make extensive use of jQuery internally.

**Comment by gibson042** [comment]
The nodes are guaranteed to exist only during a selection, so you could use either aspect (that they are only created after a selection starts or that they are removed immediately), or just wait for a Sizzle-free jQuery. As for jQuery within the frame, selection should not modify the DOM provided you always select within the same document.

**Comment by mgol** [comment]
@exteon I just landed a PR that achieves what we need via different means for most selectors: https://github.com/jquery/jquery/pull/4454. This will land in jQuery 4.0.0 and maybe we can do it in 3.4.2 as well.

**Comment by exteon** [comment]
Hoorah! We had adopted the no-cross-frame-jquery solution, it'd be good to go back to the ole' playful  `$`

**Comment by mgol** [comment]
@exteon Oh, sorry, I thought this issue was about temporary IDs being assigned to queried elements but it's actually bigger than that. Those issues will not be solved in Sizzle but they shouldn't exist in jQuery 4.0 that inlines & simplifies Sizzle and, thus, most of its support tests.
