### ISSUE TITLE
Sort dom elements not working properly on google chrome

### ISSUE THREAD

**Issue by Seb33300** [jquery/jquery#4349]
Hello,

It looks like something wrong happens with Google Chrome when using `sort` on elements selection.

You can check this simple example working on Firefox but not on Google Chrome:
https://jsfiddle.net/0jg7o4hx/

Con you confirm is it is a jQuery bug?

Thank you

**Comment by timmywil** [comment]
I think the real issue is that it works in Firefox. I suspect it either has to do with the way each browser handles boolean values (rather than the standard number greater than, equal to, or less than 0) or the order in which the elements are passed to the comparator. Note that sort is just a standard JavaScript sort. Here's how you might do this: https://jsfiddle.net/timmywil/z8goxu0t/

**Comment by gibson042** [comment]
Also note that `sort` is not part of the documented interface of jQuery collections. We make no guarantees about its behavior or even its presence. Please rewrite expressions like `$(selector).sort(fn)` to e.g. `$( $(selector).toArray().sort(fn) )`.
