### ISSUE TITLE
Is there intentionally no support for `cancelAnimationFrame` for animation frames created through $.fx.start?

### ISSUE THREAD

**Issue by MeoMix** [jquery/jquery#4351]
I have a view which is currently rendering an animation. I am attempting to destroy the view and ensure its state is fully cleaned up. I'm failing to properly clean up the view due to a requested animation frame lingering.

It looks like jQuery's implementation of `$.fx.start` (and its `schedule` method) do not store the handle to each RAF callback. Is this intentional and, if so, why?

```
function schedule() {
	if ( inProgress ) {
		if ( document.hidden === false && window.requestAnimationFrame ) {
			window.requestAnimationFrame( schedule );
		} else {
			window.setTimeout( schedule, jQuery.fx.interval );
		}

		jQuery.fx.tick();
	}
}
```

Ideally, a call to `.stop()` would be able to cancel any pending animation frames.

Thanks!

**Comment by dmethvin** [comment]
The `inProgress` flag takes care of ensuring that any call occurring after being cancelled is ignored. That's sufficient for what jQuery animations do. It seems like it would be a major refactor to use `cancelAnimationFrame` rather than that flag and we's also need `cancelTimeout` if we wanted to continue to support that case.

**Comment by timmywil** [comment]
This seems to be a question about internals. I don't suspect this will lead to any changes.
