### ISSUE TITLE
jQuery 3.3.1 High Security Risk reported by blackducksoftware.com

### ISSUE THREAD

**Issue by gibbonyang** [jquery/jquery#4366]
### Description ###
jQuery 3.3.1 High Security Risk reported by blackducksoftware.com's HUG scan:

jQuery is vulnerable to a denial-of-service (DoS) that is caused by the modification of assumed immutable data (MAID). An attacker can inject properties that will cause the server to crash or return a `500` error message to every subsequent request.   This vulnerability may also lead to remote code execution (RCE) in some applications, depending on the implementation.

Vulnerability id: BDSA-2019-0945

**Comment by mgol** [comment]
Thanks for the report but I'm not sure what do you want us to do here. First of all, this is not the correct place to submit security issues as the bug tracker is public. Secondly, if specific code in a client-side library can cause your server to crash or "return a 500 error message to every subsequent request" then the main problem lies in the server, not in the library. Plus, there are no details about the issue here and googling the number doesn't return any results.

**Comment by timmywil** [comment]
It sounds like the real issue lies elsewhere. Not enough information to go on regardless. We can reopen if this turns into something credible, but I doubt it.
