### ISSUE TITLE
find() method can't find elements using a selector that includes the parent element

### ISSUE THREAD

**Issue by VioletRose** [jquery/jquery#4391]
### Description ###
When using the find() method, it should be able to find elements matching a selector that includes the class of the element it is run on. Instead, it finds 0 results. querySelector() and querySelectorAll() do not have this issue. I've repro'd this bug in Firefox and Chromium.

### Link to test case ###
https://codepen.io/anon/pen/XwmwRo

**Comment by mgol** [comment]
This is an intentional difference and you’re actually the first person I see preferring the qSA behavior to the jQuery one; since the very beginning of the qSA standard, which originated after jQuery selection was already available, it’s been widely considered to be a spec bug. We’re even intentionally getting a slight performance hit just to achieve our desired scoping behavior.

If you want the qSA scoping, use it directly. You can also compile Sizzle out of jQuery (see README) but I’m not sure if that’s still going to be possible in jQuery 4.
