### ISSUE TITLE
$.fn.contents throws if the collection contains the window

### ISSUE THREAD

**Issue by fabiospampinato** [jquery/jquery#4394]
The following throws in v3.3.1, maybe it shouldn't:

```js
jQuery(window).contents ()
```

**Comment by fabiospampinato** [comment]
Actually a whole bunch of methods throw if there's either a window or document object involved, should I try to list the ones I can find?

**Comment by mgol** [comment]
One of jQuery's design decisions is not to validate input as it would otherwise get way larger & slower. The [`contents` API page](https://api.jquery.com/contents/) states (emphasis mine):

> Given a jQuery object that _represents a set of DOM elements_, the `.contents()` method allows us to search through the immediate children of these elements in the DOM tree and construct a new jQuery object from the matching elements.

`window` is not a DOM element so using `.contents()` on a jQuery object containing `window` is disallowed.

A lot of these issues can be caught statically if you're using TypeScript with jQuery typings via `@types/jquery` but this one may be harder to catch.

I've noticed `window` isn't even listed as a valid input to `jQuery` but that should be changed as we support e.g. `$( window ).on( "resize", handler )`. Perhaps we could document that together with a note that many DOM-related jQuery methods won't work on such an object?

**Comment by fabiospampinato** [comment]
> One of jQuery's design decisions is not to validate input as it would otherwise get way larger & slower. 

I think that's probably the right move with regards to errors being thrown because the current collection contains a Window or Document object. After all it's pretty difficult to hit these sorts of errors as one doesn't just "accidentally" add `window` or `document` to a collection.

> A lot of these issues can be caught statically if you're using TypeScript with jQuery typings via @types/jquery but this one may be harder to catch.

I don't think there's a way to express things like this (e.g. this method will throw if the current collection contains a Window object) with TS, is there? 🤔 

> I've noticed window isn't even listed as a valid input to jQuery

Yeah that's one of the reasons why I don't like third-party types, if they aren't generated from the actual code they aren't very reliable.

> Perhaps we could document that together with a note that many DOM-related jQuery methods won't work on such an object?

I'm not sure such a note is actually necessary, at best something like: "some methods are meant to be used on DOM elements, if you have a Window or Document object in your jQuery collection those methods may throw" could be added somewhere, but I doubt it would be that useful.

Listing where these issues may happen is actually non trivial, I had to more strictly type [cash](https://github.com/kenwheeler/cash) to make them surface there, and even though cash is about 6x smaller than jQuery I still found 70+ issues related to this, listing all the existing ones in jQuery won't be an easy feat.

**Comment by dmethvin** [comment]
The jQuery API is definitely a tough one to use with bulletproof static typing. I'm sure it would look different if it was designed today. 

There are only a small number of places where `window` and `document` are allowed in a jQuery collection and generally it's when they're the only element in the collection. You can come up with pathological statements with a mix of DOM elements and `window` that actually do work fine today but seem really useless, such as `$("button").add(window).prop("something", 52)`.

We dealt with a similar problem in #3181 that was more prominent because jQuery UI did it. This one hasn't even been reported by anyone who encountered it in the wild as far as I can tell, and if they did it would still be a case of API misuse.

**Comment by fabiospampinato** [comment]
>  This one hasn't even been reported by anyone who encountered it in the wild as far as I can tell, and if they did it would still be a case of API misuse.

Yeah I only found the issue because I was kind of looking for these sorts of things.

I'm closing this issue as there doesn't seem to be anything worth changing because of it.
