### ISSUE TITLE
Memory leak in frameset (Chrome)

### ISSUE THREAD

**Issue by NeArh** [jquery/jquery#4408]
### Description ###
If you use jQuery in several frames of the frameset Chrome (74.0.3729.169 64-bit) start leaking. I shot a small video with the replication procedure:
https://monosnap.com/file/9GtVsjze5joTl2zkp4lUQHz0Ec9ym0

As far as I can see the window objects are captured somehow and can't be collected:
https://monosnap.com/file/yCymu6vxH1IHbcNnw2xgtEy7YkdyAK

### Link to test case ###
Sorry neither JS Bin nor CodePen support projects with several html files, so here the Plunker link:
http://plnkr.co/edit/bguAmTkUxFSxQkDy43Q5

I also attached files to the ticket. Just in case.
[leak.zip](https://github.com/jquery/jquery/files/3208397/leak.zip)

**Comment by mgol** [comment]
Thanks for the report! Unfortunately, your Plunker doesn't work due to cross-origin reasons: clicking on menu items just triggers an error. I've checked it locally and although I see the memory rising, I also see it when jQuery gets removed from your test case, only slower - which makes sense as jQuery itself takes some size so the documents loaded take less space than they do with the library. Therefore, it doesn't look like jQuery issue to me.
