### ISSUE TITLE
Layout thrashing in jQuery code

### ISSUE THREAD

**Issue by jankhunter** [jquery/jquery#4411]
### Description ###
I could see Layout thrashing due to jQuery show method and sometimes even with jQuery find method.

 *  What do you expect to happen?
          jQuery show method is a write statement (statement which changes the DOM). Expected not to get any layout thrashing due to this statement.

*  What actually happens?
          There is a style read statement (statement which reads the DOM style) internally in the jQuery show method, which is causing the Layout thrashing. 

### Link to test case ###
Whereever i use jQuery show method, i get layout thrashing. Kindly make use of performance timeline graph attachment to analyse the issue

<img width="1600" alt="Screenshot 2019-05-28 at 12 15 44 PM" src="https://user-images.githubusercontent.com/32759296/58551840-987dd280-822e-11e9-80fa-c65f89285971.png">
<img width="1002" alt="Screenshot 2019-05-28 at 12 16 18 PM" src="https://user-images.githubusercontent.com/32759296/58551841-987dd280-822e-11e9-8642-ce8879b1e281.png">

.

**Comment by mgol** [comment]
It'd be good to see a test case so that it's clear what flow is causing issues. That said, some style recalculation is necessary, though as we need to know whether to set non-empty `display` on an element or not - this depend on whether the element is hidden via a stylesheet or not. If you know exactly what `display` you want to achieve, it's better to call `.css( "display", value )` explicitly.

As for selection, because of a design bug of `querySelectorAll` (which causes a div containing a single span to match it on `div.querySelector('div span')` we need to assign a temporary ID on a queried element unless it already has one - and that causes a style recalculation. We cannot avoid that one unless browsers implement `queryAll` and we can switch to that. Unfortunately, progress on that is slow and this method was even removed from the spec 3 years ago & it hasn't returned yet: https://github.com/whatwg/dom/commit/10b6cf1ba02806220d5461a3bdb7939728b73635.

If you're calling `find` frequently on a particular element, you can avoid the issue by assigning it an ID.

I'll close it since I don't think there's anything we can do at this point but feel free to continue the discussion here.

**Comment by jankhunter** [comment]
It might be a good idea to use  .css( "display", value ). But despite of the problems(layout thrashing) it is causing, what forces you to still follow the fact to check the style.display of the element to be shown? Why can't it be, just show the given element. 

My point is there will be no big problem even if the element whose style.display is already "block" is shown again, comparing to the problem it is causing due to method we follow now. 

Also, we can't expect every developers to use .css() even after educating them, as they are already used to the .show() method.

**Comment by mgol** [comment]
If an element is already visible, we shouldn't change its display. Therefore, we need to know whether it's hidden or not and for that we need to compute its CSS.

And even if we could, we don't want to add an inline `display` style for an element that's already visible to not break responsive stylesheets (see #1767 for more info).

The `show` & `hide` methods are quite complex and they are working based on some heuristics; it's not possible to make them work as desired in all cases. They work in most cases which was the goal. Also, a lot of the usage of these methods is not performance-sensitive. In cases where performance is an issue, there's unfortunately no other way than to set `display` by yourself.
