### ISSUE TITLE
jQuery 3.4.1 breaks jQuery UI datepicker?

### ISSUE THREAD

**Issue by christopheroussy** [jquery/jquery#4420]
I recently moved to jQuery 3.4.1 which **deprecates** selectors using `:first`, `:last` and such in preparation for jQuery 4.x.

I was wondering how much this impacts jQueryUI datepicker because I grepped into all `.js` files in my project and in jQueryUI I see: `e.dpDiv.find("select.ui-datepicker-year:first").replaceWith(e.yearshtml)` and `.filter(":first")`.

Will major jquery libraries like jQuery UI also be updated to remove/replace the deprecated selectors ?

**Comment by mgol** [comment]
Thanks for the report.

Libraries using jQuery need to adapt to its breaking changes. Because if that, we try to minimize them but from time to time they’re necessary.

Updating jQuery UI to stop relying on positional selectors is a responsibility of jQuery UI. Its bugtracker is https://bugs.jqueryui.com/. Because of that, I’m going to close this issue as this is a jQuery bug tracker.

**Comment by christopheroussy** [comment]
Thanks for the quick response:
https://bugs.jqueryui.com/ticket/15348
