### ISSUE TITLE
Clarify jQuery 4 plans

### ISSUE THREAD

**Issue by goba** [jquery/jquery#4421]
https://github.com/jquery/jquery/milestone/7 lists 46 open issues left for version 4 and 19 closed. On the roadmap at https://github.com/jquery/jquery/wiki/Roadmap there was a minor edit this March and before that last edits in September 2018. Based on the activity on the version 4 issues, it is very hard to tell what is the estimated version 4 release date (if it is even still a goal to release version 4).

**Comment by dmethvin** [comment]
What would you like to see in jQuery 4? Is there a particular feature you are waiting for?

**Comment by goba** [comment]
Not interested in features, but rather timelines/risks :)

I am one of the core committers to Drupal, which relies on jQuery *and* jQuery UI. With jQuery UI being in Emeritus (end of life) status, it puts us into a hard place once/if jQuery 4 comes out **if** jQuery 3 support is stopped, because that would mean that we are using an end of life JS library based on an unsupported version of another library. So knowing what is planned with jQuery 4 could help us support decisions we need to take one way or another.

**Comment by timmywil** [comment]
Since this is a question, I'll go ahead and close. While I can't say for sure when jQuery 4 will be ready, I  can say it won't be very soon so there's plenty of time. jQuery 4 will come with some major changes and removal of previous deprecations. When jQuery 4 does get released, it will come with the jQuery-migrate plugin and a migration guide that should make it easy to support both jQuery 3 and jQuery 4.

In the past, we have not supported previous versions once a new version comes out. However, I am fine with making an exception for jQuery 3 (covering any critical issues and providing patches), since jQuery 4 will be such a major upgrade.

**Comment by xjm** [comment]
Thanks for the quick reply!

How long after jQuery 4.0 would 3.x receive this coverage for critical issues? Could it be provided for as long as three years after 4.0?

For Drupal, we have a major version coming out next year that we hope to support until at least the end of 2023. Our primary concern is ensuring security coverage for our dependencies (including jQuery) until then, and based on the jQuery 4 development timeline, it looks like our upcoming release will still need to use jQuery 3. I'm sure many other projects would value this info as well though.

Thank you!

**Comment by timmywil** [comment]
We're discussing this in our meeting today, but 3 years sounds perfectly reasonable.

**Comment by timmywil** [comment]
We discussed this in the meeting. While 3 years sounds fine, I hesitate to give an exact date for when 3.x would be EOL. I don't know if it's 3 years or less or more, but 3.x will receive patches to fix bugs and regressions after 4.0 is released for as long as needed. We actually did this with 1.x/2.x when 3.0 was released. But as those 1.x/2.x branches became more stable, we eventually focused our attention on 3.x updates. I think we'd do something similar. In other words, 3.x would be in a good place.

**Comment by xjm** [comment]
Thanks for the followup! 

Part of the reason we asked is precisely based on the 1.x/2.x history when 3.0 came out. Our release was November 2015; jQuery 3.0 came out in 2016. By 2017 there were security fixes not being backported to jQuery 2, so we had to do a major version upgrade to jQuery 3 mid-major and it was a big breaking change for many Drupal sites and themes. So we're hoping to try to avoid that this time around.

**Comment by mgol** [comment]
> By 2017 there were security fixes not being backported to jQuery 2

This is more nuanced. The only security fix I remember that we haven't backported to 2.x a few years ago is #2588 which was a fix for #2432. We didn't do it not because we didn't want to but because the original logic, while potentially dangerous if used incorrectly, was technically something sites might have relied on as being guaranteed by our API. Changing that logic was a breaking change so we couldn't have backported it. Something similar may very well happen in 3.x or even in 4.x, the length of the support is not that relevant here.

The only security issue that I know of that we technically could backport without introducing a breaking change (except in very arcane use cases) but we chose not to was #4333 from March, 2019. A pretty recent event, almost 3 years after we released jQuery 3.0.0.

**Comment by xjm** [comment]
Thanks @mgol! #2432 was indeed the issue that prompted us to upgrade as there were vulnerable projects in our ecosystem. We also implemented our own mitigation pre-filtering for Ajax requests in our LTS version, Drupal 7 (which only uses jQuery 1.x and so the major version upgrade was too risky). (Come to think of it, we took a similar approach for #4333 as well, implementing our own mitigation.)

So it sounds like the security policy is that security issues will be evaluated for backport (or not) on a case-by-case basis?

**Comment by mgol** [comment]
> So it sounds like the security policy is that security issues will be evaluated for backport (or not) on a case-by-case basis?

In case of the recent security issue we decided not to backport the fix as it wasn't that easy to exploit and the build process in 3.x diverged from what we used to have in 1.x/2.x so it'd be hard to do the release (we publish to a lot of places: npm, bower, our CDN, various other CDNs, etc.). I think that for some time after the 4.0 release we will fix all the security issues and even maybe some more serious non-security ones but as more time passes since the 4.0 release we may start to evaluate them on a case-by-case basis as you mentioned.

Security issues in jQuery are quite rare so there may not be a lot for us to do here, we'll see.

**Comment by dmethvin** [comment]
So is the need to use jQuery 3 based on the current jQuery UI using deprecated features? Or is it more that code in Drupal's own ecosystem is going to break with jQuery 4? (Or some of both?) I'd like to find someone willing to tackle jQuery UI for minimal updates. It seems like the changes there would be minimal but who knows until it's investigated.

Sorry I wasn't at the meeting today, but I agree that jQuery 3 should be supported for a while since jQuery 4 will have some changes that are likely to break older code. I'm still hopeful that Migrate can help people get there, but wouldn't recommend that Drupal ship Migrate the way Wordpress did.

**Comment by goba** [comment]
> So is the need to use jQuery 3 based on the current jQuery UI using deprecated features? Or is it more that code in Drupal's own ecosystem is going to break with jQuery 4? (Or some of both?)

Both yes. Drupal made the unfortunate choice of exposing all the jQuery UI components as part of its API for Drupal extensions, despite only using some on its own. That said, Drupal core is still using various jQuery UI things itself (dialogs, autocomplete, sortable, etc). Because we are exposing jQuery UI and JQuery as part of our API, if we would need to update to a backwards compatibility breaking version of either, we'd need to do a new major Drupal version as well. Our current major version Drupal 8 was released 3.5 years ago and we plan to release our next major version Drupal 9 2020 June and support it roughly until end of 2023.

We are looking at whether we need to scramble to get rid of jQuery UI entirely so it does not appear in Drupal 9.0.0 anymore, or risk being on a version that goes unsupported in this timeframe and leads us to need to release a new major platform version (much?) sooner. There is also the risk for us of jQuery itself stopping version 3 support before we can move to jQuery 4 (in Drupal 10 probably given the unlikely timeframe of jQuery 4 happening in time to be possible to integrate into Drupal 9.0.0).

**Comment by dmethvin** [comment]
> Drupal made the unfortunate choice of exposing all the jQuery UI components as part of its API for Drupal extensions, despite only using some on its own.

Yeah, we made the same mistake of exposing a lot of unnecessary things in jQuery core and have been working for years to take them back. It's super hard! 

> We are looking at whether we need to scramble to get rid of jQuery UI entirely so it does not appear in Drupal 9.0.0 anymore

I don't think there's *that* much that's broken in jQuery UI, it just needs to have some deprecated jQuery core functionality removed. I don't think anyone has reported security vulns in it have they? If we could find a few willing souls to do basic maintenance on jQuery UI I think it would be usable for quite a few more years, especially since they already have dropped support for any IE older than IE11.
