### ISSUE TITLE
Support for API Fetch ES6/ES7...

### ISSUE THREAD

**Issue by cacuestai** [jquery/jquery#4425]
Hello:

I know that it is not the most suitable place for this suggestion, but I would like version 4 to have support for the API Fetch.

Thank,
Carlos

**Comment by mgol** [comment]
What do you mean in particular by support for fetch API? What would you like jQuery to be able to do?

**Comment by crh3675** [comment]
Fetch is problematic in it's own right.  Mainly because "The Promise returned from fetch() won’t reject on HTTP error status even if the response is an HTTP 404 or 500. Instead, it will resolve normally (with ok status set to false), and it will only reject on network failure or if anything prevented the request from completing."

I too have been interested in using fetch but for legitimate reason, I don't see the need to reinvent the wheel on this one.  https://gomakethings.com/why-i-still-use-xhr-instead-of-the-fetch-api/

**Comment by dmethvin** [comment]
> The Promise returned from fetch() won’t reject on HTTP error status even if the response is an HTTP 404 or 500. Instead, it will resolve normally (with ok status set to false), and it will only reject on network failure or if anything prevented the request from completing.

This is exactly the design philosophy that keeps `fetch` simple and not complex like `$.ajax`. As soon as an API incorporates automagic behavior for the 80% case, it makes the 20% case difficult or impossible. In the documentation at api.jquery.com you will see that `$.ajax` is the most complex API in the whole library, and it is due to having a lot of built-in behavior that needs to be overridden, extended, or reconfigured in many cases.

A typical call using `fetch` isn't any longer than one using `$.ajax`. Yes, the error paths are different, but that only matters if your program intends to do something intelligent with errors. Otherwise you just use the `catch` to catch whatever went wrong, regardless of what it was. There are [plenty of examples at MDN](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).

**Comment by timmywil** [comment]
Even if the changes were well-defined, I don't see changes being made here. As Dave said, `$.ajax` does a lot. Common cases work the same way as fetch and then there's a ton of configuration that can be done for the rest. Neither using `fetch` internally nor realigning `$.ajax` behavior to match `fetch` for 100% of cases gives very much benefit. We also publish a slim build that removes `$.ajax` altogether, in case you prefer to use `fetch`.
