### ISSUE TITLE
Why is the ready function not working properly after the Jquery version is upgraded from 1.12.4 to 3.4.1?

### ISSUE THREAD

**Issue by mouzhengjie** [jquery/jquery#4522]
My code format is as follows:

$(document).ready(function(){
        debugger;
        ......###
        ......###
})

For testing, I added a debugger to the first line of the ready function, but the browser didn't execute, and the debugger didn't work. And console no error printing.

I am using Firefox version 59.0.3 browser, and my problem only appears on Firefox, Google Chrome and IE will not appear.

Is there a problem with my code format? This problem does not occur with Jquery 1.12.4.

**Comment by mgol** [comment]
I hope you mean Firefox 69.0.3, not 59.0.3; that'd be very old. :)

`console.log` will not execute immediately because of the `debugger` statement that halts execution. If you continue, it'll work.

Note: try to use the `$(function() { /* ready code */ });` form instead of `$(document).ready(function() { /* ready code */ });`, the latter is deprecated.
