### ISSUE TITLE
show and hide spinner with jquery : does not work on Iphone, safary etc

### ISSUE THREAD

**Issue by zskiredj** [jquery/jquery#4531]
I am trying to show / hide a spinner with JQuery. Basicaly I have this code :

```
function unLoader(e) {
    $(".site-content").hide();
    $(".loading").show();    
    }

   $(window).on('load', function() {
         $(".loading").hide();
         $(".site-content").show();
          window.onbeforeunload = unLoader;
    });
```

It works fine with Chrome and FireFox on Windows , on Chrome on MacOS. But it does not work on Safari MacOS. It does not work on Safari Iphone or Chrome Iphone.

Trying to change the eventName does not resolve the problem :

```
var isOnIOS = navigator.userAgent.match(/iPad/i)|| navigator.userAgent.match(/iPhone/i);    
var eventNameHide = isOnIOS ? "pagehide" : "beforeunload";
var eventNameShow = isOnIOS ? "pageshow" : "load";
```

Any help would be apreciated.

**Comment by mgol** [comment]
Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by zskiredj** [comment]
here is the code :

https://jsbin.com/cimeheqeta/edit?html,css,js,output

**Comment by timmywil** [comment]
Thanks for opening an issue. However, this is more of a support question. Setting onbeforeunload in order to show a spinner probably isn't going to work the way you intend. The page will be completely unloaded (including the spinner you want to show) and a new page will take its place. That said, showing a spinner on load for any page, and then hiding that spinner when you've finished loading something asynchronous is very common. I've modified your example to show how something like that might look https://jsbin.com/heyapaj/1/edit?html,css,js,output. Most often this is done for single page apps loading user-specific data.

However, if you don't have anything asynchronous to do on load (even your JS is loaded synchronously), I don't think there's a point trying to show a spinner.
