### ISSUE TITLE
Unexpect behavior in .ajax

### ISSUE THREAD

**Issue by claytron5000** [jquery/jquery#4533]
### Description ###
If I pass a JavaScript object containing methods into `jQuery.ajax` request data, the methods are unexpectedly called. Basically I overloaded a `data` object with a method I wanted to use later. Note, the method is not called in a callback, but in the processing of the request.

```
const data = {
  key: "value to send to the server",
  method: function() { console.log("I will use this later, and for convenience it is here.")}
}
jQuery.post("someurl", data);
```
- The expected result is the object's key/values are sent to the server, what is actually sent as the value of the `method` key, I am not sure, nor do I care.
- The actual result is any method on the object is called. Resulting in an unexpected call to that `method` method.

I haven't been able to find any documentation of this behavior, nor any discussions. (Granted, my search-foo might be failing me with searches like "jQuery ajax data object method"...

### Link to test case ###
https://codepen.io/claytron5000/pen/YzzZGKr

**Comment by dmethvin** [comment]
The reason it  happens is because [`jQuery.ajax()` calls `jQuery.param()` to serialize its `data`](https://github.com/jquery/jquery/blob/master/src/ajax.js#L568-L571) and that method [calls properties that are functions](https://github.com/jquery/jquery/blob/bcbcdd2b2c1bb7075f4f73dc89ca7d65db2a09ed/src/serialize.js#L64). The documentation for `JQuery.param()` [mentions it does this](https://api.jquery.com/jQuery.param/) so we wouldn't remove it. If anything we would document that is how `data` is serialized by linking to the `jQuery.param()` docs, assuming we think it won't change for any reason.

**Comment by claytron5000** [comment]
I don't see any mention on the [.param](https://api.jquery.com/jQuery.param/) page describing this behavior. I can understand a reluctance to change the behavior, but maybe some mention in the documentation.

**Comment by claytron5000** [comment]
I'm closing this case, and I'll make a suggestion on the website repo.

**Comment by dmethvin** [comment]
> I don't see any mention on the .param page describing this behavior. 

"As of jQuery 1.3, the return value of a function is used instead of the function as a String"
