### ISSUE TITLE
jQuery fails to catch scroll events on full-height pages with smooth scrolling and hidden overflow

### ISSUE THREAD

**Issue by mashedkeyboard** [jquery/jquery#4551]
### Description ###
By applying the following CSS properties, you break jQuery's ability to correctly capture scroll events:
```css
html, body {
  height: 100%;
  scroll-behavior: smooth;
  overflow-x: hidden;
}
```
**What should happen**: `$(window).on("scroll", handler)` and `$(window).scroll(handler)` should call `handler` when the `scroll` event bubbles.
**What does happen**: jQuery's scroll handlers fail to catch any scroll events at all, whereas native JS catches them just fine.
**Affected browsers**: Appears to affect all browsers in this generalised case (I've tried Firefox desktop, Chromium desktop, Firefox mobile, Chromium mobile). Having said that, in the specific case I was initially troubleshooting, the bug only actually appeared when using Firefox on a mobile device.

### Link to test case ###
https://codepen.io/mashedkeyboard/pen/dyyxNow

**Comment by mgol** [comment]
Thanks for the report.

This is an issue with native `addEventListener` as well, it's just that your test case uses the capture phase instead of the default bubble phase and it works in the former. jQuery doesn't support the capture phase.

`scroll-behavior: smooth` doesn't cause the issue, `overflow-x: hidden` does. See https://jsbin.com/huxorih/1/edit?html,css,js,console,output for a test case not involving jQuery.

I couldn't quickly find why it's behaving like that, looks weird! However, if we're not getting the event propagated to `window` there's not much we can do on the jQuery side - switching to the `capture` phase would be too invasive as it'd change the order of events that are triggered.

See also #2215.

**Comment by mashedkeyboard** [comment]
Thanks for the amazingly fast response Michał - that's really useful! Try not to respond to GitHub tickets at 20 past midnight though, it's probably not great for you 😛
