### ISSUE TITLE
Not all root nodes created by `$.parseHTML` have a `parentNode`

### ISSUE THREAD

**Issue by fabiospampinato** [jquery/jquery#4580]
I think that partially in order to better deal with detached nodes jQuery ensures that root nodes created via `$.parseHTML` have a `parentNode`, but not all nodes created this way have a `parentNode`:

```js
jQuery('<div>')[0].parentNode // => null
jQuery('<div>hello</div>')[0].parentNode // => #document-fragment
```

That looks like an issue worth fixing.

**Comment by mgol** [comment]
@fabiospampinato Could you explain what's your use case? Technically speaking, whatever parent the nodes may have is not public API, just a result of using fragments to construct more complex elements.

**Comment by fabiospampinato** [comment]
@mgol I don't really have a use case for this, I was just running jQuery's test suite with [Cash](https://github.com/kenwheeler/cash) trying to discover some more bugs in it, and I noticed that some tests are not passing with Cash because  the root nodes it generates via `$.parseHTML` don't have a `parentNode`.

I'm just saying for consistency maybe _all_ root nodes generated via jQuery's `parseHTML` should have a `parentNode`.

**Comment by mgol** [comment]
@fabiospampinato Since the code path that generates a node without a `parentNode` is a performance optimization, we'd rather not add wrappers around it that's not needed by other jQuery APIs. We'd be more likely to _remove_ `parentNode` from the collection but that'd require looping over the elements of the fragment but that'd affect performance negatively.

Therefore, I'm going to close the issue. If there are more real-life examples where consistency in this undocumented detail matters, I'd be happy to reopen.

Thanks!
