### ISSUE TITLE
JavaScript not Minify

### ISSUE THREAD

**Issue by Theolodewijk** [jquery/jquery#4610]
jquery.min.js not minified

**Comment by mgol** [comment]
Looks minified to me: https://code.jquery.com/jquery-3.4.1.min.js

**Comment by Theolodewijk** [comment]
yes online, but when you using composer not.

**Comment by mgol** [comment]
We only maintain our npm & Bower packages, our CDN, and we send files to the Google/Microsoft CDNs.

Issues only reproducible elsewhere should be reported to maintainers of these distributions.

**Comment by Theolodewijk** [comment]
where can i report that if i pick it up with composer?

**Comment by mgol** [comment]
I didn't know that when you asked the question but a quick google for `composer jquery` leads to https://packagist.org/packages/components/jquery which, in turn, leads to https://github.com/components/jquery. Looking at the `3.4.1` tag, it's true the "minified" file is not minified:
https://github.com/components/jquery/blob/3.4.1/jquery.min.js
And the issue is already reported at https://github.com/components/jquery/issues/64.
