### ISSUE TITLE
Problem with the getStyles function

### ISSUE THREAD

**Issue by jhonnytuba** [jquery/jquery#4701]
### Description ###
* I have a problem with my application in the getStyles function, see below:

![image](https://user-images.githubusercontent.com/5703319/80783612-af205e00-8b50-11ea-82d2-4ec338563671.png)

* I should like share my solution with a condition that checks the element's nodeType:

![image](https://user-images.githubusercontent.com/5703319/80783483-59e44c80-8b50-11ea-9c38-68e2aed2b171.png)

**Comment by mgol** [comment]
Thanks for the report. However, it's quite hard for us to do anything here, just with a screenshot of an error, no test case, not even a mention of which jQuery version is used.

I'm going to close it now since there's nothing we can do with such a report. If you provide a test case on [JS Bin](https://jsbin.com/) & provide all the necessary details, we can reopen.
