### ISSUE TITLE
trim() is deprecated, but trim() is not equal to $.trim()

### ISSUE THREAD

**Issue by Daijobou** [jquery/jquery#4703]
$trim() working on strings and arrays (like multi select boxes). trim() working only for strings.
So its not a complete replacement and can make breaks in code.

**Comment by mgol** [comment]
`jQuery.trim` has always only supported string input: https://api.jquery.com/jQuery.trim/

Using it on arrays doesn’t make a lot of sense, output is nonsensical then.

**Comment by Daijobou** [comment]
Yeah, it does more than it was supposed to. That's why it's causing problems now.

Its make arrays as joined with "," and check for undefined variable. I don't say that $.trim() should not removed, but more information would be very important. Because it creates problems that you don't even think about.

Like here https://select2.org/searching#customizing-how-results-are-matched and many other plugins, where its check a string, but its check that this variable exists too. When you that not have in mind you replace $.trim() with .trim() and do not notice that in certain cases here comes "undefined".

**Comment by dmethvin** [comment]
There have certainly been many cases in the past where jQuery has change APIs and non-documented uses have broken. Since you've found an incorrect use of the API in Select2  I would definitely suggest that you submit a PR to fix it there so it won't break when jQuery 4 comes out. Do you know of other jQuery plugins that do this? If so we could add something to Migrate to detect it.

**Comment by uspnick** [comment]
`function $trim(s) { return s ? s.trim() : '' } `
can be used as a replacement for $.trim (since it's deprecated in jQuery). To verify its accuracy, I've set up unit tests that compare $trim and $.trim across various test cases involving different whitespace characters.

Check out the tests and results here: https://jsfiddle.net/NickU/p1uk3gzr/
