### ISSUE TITLE
.outerWidth() and .outerHeight() don't work with <a> elements in <svg>

### ISSUE THREAD

**Issue by php4fan** [jquery/jquery#4741]
### Description ###

See the example jsfiddle:

In the output, in the `<pre>` above the map of Spain, which is an inline svg, a number should show up which should be the width in pixel of one of the links in the map, namely the one that links to "#madrid".

Instead, the number that shows up is 0.

With older versions of jquery I got an even more pathetic "NaNpx".

The `<a>` element does have a size, so it doesn't really make sense that `.outerWidth()` shouldn't work.

Same for `.outerHeight()`.

### Link to test case ###

https://jsfiddle.net/97he8dxa/

**Comment by php4fan** [comment]
and also `.width()` and `.height()`

**Comment by dmethvin** [comment]
Although the HTML link element and the SVG link element share the same node name of `a`, they are not the same thing and don't have the same interfaces. jQuery is meant for manipulating HTML DOM, not SVG DOM.  This looks out of scope to me.

https://github.com/jquery/jquery/wiki/Won't-Fix#svg-or-vml

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/a

**Comment by php4fan** [comment]
> Although the HTML link element and the SVG link element share the same node name of a, they are not the same thing

I know. I would have expected to be able to call width, height and the like also on elements like  `<g>`, `<path>`, etc, for that matter.

Since it's a thing inside the document that has a physical position and a  bounding box, I thought it would be natural to be able to get its offset and size the same way you do with html nodes. Anyway, I understand that if the SVG subtree has a completely different kind of DOM and a completely different API, perhaps it's not worth the effort.

**Comment by dmethvin** [comment]
The unfortunate thing is, the more jQuery supports SVG the more people complain that its not exactly like HTML support--even when the reason is because SVG works differently than HTML. We can't abstract that away without creating a new set of anomalies, ones that we would now own. 

I haven't dived into SVG for a few years, but as I recall there are also cross-browser problems where if you draw a `rect` the BBox dimensions of that box on some browsers is measured from the centerline of the stroke, but on others from the outer edge of the stroke width. Kind of like the `content-box` vs `border-box` mess in CSS. Also I think those dimensions are against the `viewBox` and don't change when the SVG is resized.
