### ISSUE TITLE
Keyboard event.which incorrectly deprecated or documentation out of date?

### ISSUE THREAD

**Issue by ChrisHSandN** [jquery/jquery#4755]
### Description ###
The TypeScript definitions [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jquery/misc.d.ts#L4163) state `event.which` is:

```js
@deprecated ​ Deprecated since 3.3. See \`{@link https://github.com/jquery/api.jquery.com/issues/821 }\`.
```

But on the deprecated 3.3 list there is no mention of deprecation:
https://api.jquery.com/category/deprecated/deprecated-3.3/

On the `event.which` page there is no mention of deprecation:
https://api.jquery.com/event.which/

On the `keydown` page there is no mention of deprecation and it even specifically advises to use `event.which`:
https://api.jquery.com/keydown/
> To determine which key was pressed, examine the event object that is passed to the handler function. While browsers use differing properties to store this information, jQuery normalizes the .which property so you can reliably use it to retrieve the key code.

***
As an aside, surely while the native `event.which` may have been [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which) this is the JQuery `event.which` and this kind of cross browser normalisation is exactly why we use JQuery in the first place?

5 years after those issues were resolved and there is still no completely [reliable native property to use](https://caniuse.com/#search=KeyboardEvent).

**Comment by mgol** [comment]
Thanks for the report. The linked API issue is the one that tracks documenting this.

As for normalizing, jQuery is indeed trying to normalize browser differences but at the same time we try to align with where the standards are going. Instead of undeprecating `which`, we'd rather make sure the replacements can be used.

@dmethvin What do you think?

**Comment by timmywil** [comment]
We're considering un-deprecating this property. Event if `KeyboardEvent.code` and `KeyboardEvent.key` were supported in all our supported browsers, they are not direct replacements.

**Comment by dmethvin** [comment]
For key-related events, this is all `event.which` does:
```js
  if ( event.which == null && rkeyEvent.test( event.type ) ) {
    return event.charCode != null ? event.charCode : event.keyCode;
  }
```
However, the native `KeyboardEvent.which` is already [supported everywhere](https://caniuse.com/#feat=keyboardevent-which). I think the question here was around whether we could remove that shim code (which isn't even that good) and just pass through the (deprecated) native value as we do with most other properties. I think we can? It would be a good idea to call it deprecated since we're just passing it through and it's not up to us whether it continues to be supported, although I doubt browsers would remove it.

**Comment by timmywil** [comment]
That makes sense. Then again, it's confusing to say `event.which` is deprecated, and then say use native `event.which`. I'd say just remove the shim and call it a day.

**Comment by dmethvin** [comment]
Also, `MouseEvent.which` is supported everywhere too so we're safe just removing the whole thing as far as I can tell.

**Comment by ChrisHSandN** [comment]
> It would be a good idea to call it deprecated since we're just passing it through and it's not up to us whether it continues to be supported, although I doubt browsers would remove it.

If you deprecate the JQuery `event.which` just because w3 has then you just become an unopinionated wrapper around the native properties which are not cross browser compliant enough to satisfy your own browser compatibility list.

Your [active browser support](https://jquery.com/browser-support/) covers iOS7 but the only non-deprecated property left exposed on the keyboard events is `event.key` which is [not supported until iOS10](https://caniuse.com/#feat=keyboardevent-key).

What am I, as an end user, supposed to use? 

* If it is `event.which` then surely it should not be marked as deprecated and JQuery should guarantee it will always exist across all the browsers you support?
* If it is `event.key` then this would need to be shimmed so it works across all browsers you support?

**Comment by mgol** [comment]
@ChrisHSandN Any change we make here won't happen before jQuery 4.0 and that version will only support last 3 iOS versions so only 11+ as of now. You can see a draft PR with support updates for jQuery 4 here: https://github.com/jquery/jquery.com/pull/194/files.

@dmethvin @timmywil Removing the shim is one thing but I wouldn't mark a property as deprecated on our API site if it's not deprecated by us. We could add a note that it's deprecated in standards but it's available in all supported browsers & there's no direct replacement & just leave it at that. There's no danger browsers will remove it in a predictable future as it's so widespread.

**Comment by dmethvin** [comment]
> If you deprecate the JQuery event.which just because w3 has then you just become an unopinionated wrapper around the native properties which are not cross browser compliant enough to satisfy your own browser compatibility list.

With this property, that is already the case for most of the browsers we support today. I posted the shim code above, but it doesn't come into play AFAICT on any current browser. We're just passing through what the browser gives us.

In most if not all cases, jQuery doesn't have the information it needs to "fix" or "enhance" whatever is in the `event` object. Even with that shim, the `charCode` and `keyCode` values are different and we're just trying to patch in something so that `event.which` is correct for some subset of common cases. 

We don't _have_ to call the jQuery `event.which` property deprecated, but inevitably if someone reported a bug against it we would need to close it as "can't fix" because we wouldn't have the information we need to fix it in the event object, or the solution would require hard-wiring key property repair maps into the library that are specific to a browser, sometimes even specific to a particular platform (Unix, Linux, MacOS, Windows).

For some historical context, see tickets like [trac-15220](https://bugs.jquery.com/ticket/15220), [trac-14880](https://bugs.jquery.com/ticket/14880), and [trac-12742](https://bugs.jquery.com/ticket/12742).

**Comment by timmywil** [comment]
We talked about this more in the meeting. We're going to un-deprecate, as there's no direct native replacement, but remove the shim as it's no longer required. Browser support for this property is widespread, despite native deprecation, and I don't see the browsers changing or removing it either. Nor do I really see a lot of bug reports being opened for this property in the future, but that could be my famous last words. 🤷

**Comment by mgol** [comment]
The API issue is now closed so the deprecation effectively never happened. One action item is that we can remove the `event.which` shim now but that's not directly fixing this issue. Should we just close it then instead of setting the `4.0.0` milestone, @timmywil?

**Comment by timmywil** [comment]
I as thinking of using this issue as the reminder to remove the shim.

**Comment by mgol** [comment]
I've submitted a PR to remove the shim: #4765. I think there's nothing else to do in this ticket so I'll close it, removing the milestone.

**Comment by timmywil** [comment]
Still need the milestone so this issue shows up in the changelog.
