### ISSUE TITLE
Angular 10 Warning

### ISSUE THREAD

**Issue by Christian-Seiler** [jquery/jquery#4761]
Angular 10 now gives a warning to users who are using this library due to it being a CommonJS package.

```
WARNING in file.ts depends on jquery. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

```

**Comment by mgol** [comment]
jQuery 4 will be available as ES modules as well. That said, due to its legacy architecture of attaching all the utils to the main `jQuery` object or to the `jQuery` prototype, jQuery will not be tree-shakable in a traditional sense; you'd need to either use the slim build or to do a custom compilation, or to import individual modules that you want to have available.

Configuring how the jQuery modules will be shared via the `jquery` npm package is tracked in #4592 so let's continue the discussion there.
