### ISSUE TITLE
:disabled selector and IE

### ISSUE THREAD

**Issue by ymTm7KuhCnIjkZAl2x2m2** [jquery/jquery#4783]
If you have HTML with an input inside a disabled label, you will get results with $(":disabled") or .filter(":disabled") while Chrome and Firefox will not. In the following jsbin, Chrome and Firefox show 0 while IE shows 1. Chrome and Firefox seem to be using the correct interpretation of the standard (https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-fe-disabled) but IE always does its own thing.

https://output.jsbin.com/vaqanur/

**Comment by dmethvin** [comment]
The spec doesn't say an `input` should be disabled if it's a descendant of a disabled `label`. It only says that for `fieldset`. I can see where that might be a useful interpretation, but the spec doesn't say it so you'd need to get that to change. That same section says the `disabled` attribute should be reflected to the property, and `label`s don't do that either, which is a change that should be made at the same time. https://jsbin.com/zupamitana/1/edit?js,console

**Comment by mgol** [comment]
@dmethvin The issue is that IE incorrectly reflects the disable attribute & property from `label` to `input`.

However, since in IE setting this attribute on a label does, indeed, make the input disabled as well, jQuery correctly reports that it's disabled. We'd have to intercept all calls to `prop` or `attr` on labels as well as in the `html` setter which is impractical. I think in this case it's a developer responsibility to not set incorrect attributes like `disabled` on labels.

**Comment by timmywil** [comment]
Thanks for the issue, but since the input is actually disabled, the difference in the results is necessary to reflect the difference in browser behavior.

**Comment by ymTm7KuhCnIjkZAl2x2m2** [comment]
Perhaps a note in the documentation would be useful. It actually links to the spec that IE doesn't follow which is a little confusing. Though hopefully if someone else runs into this and Googles it they'll find their way here.

**Comment by mgol** [comment]
@ymTm7KuhCnIjkZAl2x2m2 Feel free to submit a PR at https://github.com/jquery/api.jquery.com with your proposed wording.
