### ISSUE TITLE
append() doesn't guarantee sequential execution of <script> tags

### ISSUE THREAD

**Issue by jruales** [jquery/jquery#4801]
### Description ###
When running something like
```js
$("#foo").append(`
    <script src="https://d3js.org/d3.v3.min.js"></script>
    <script>console.log(d3)</script>
`);
```
I would expect the `d3` variable from *d3.v3.min.js* to be available in the second script tag, since that is the behavior when a page is just loading, where script tags with `src` finish downloading before proceeding with the next script.

However, it seems like jQuery is loading the script *d3.v3.min.js* asynchronously, so the second script fails to find variable `d3`.

### Link to test case ###
This JS Bin shows the failure scenario:
https://jsbin.com/jisuxijoxa/1/edit?html,js,output

**Comment by jruales** [comment]
Looking a bit deeper at the code, this is what *I think* is happening:
- The [code](https://github.com/jquery/jquery/blob/5c2d08704e289dd2745bcb0557b35a9c0e6af4a4/src/manipulation.js#L306) behind `append()` uses [jQuery._evalUrl()](https://github.com/jquery/jquery/blob/master/src/manipulation/_evalUrl.js) to evaluate <script> tags with a `src` attribute
- _evalUrl() calls jQuery.ajax() with `async: false` [here](https://github.com/jquery/jquery/blob/5c2d08704e289dd2745bcb0557b35a9c0e6af4a4/src/manipulation/_evalUrl.js#L11), which would *normally* make the request synchronous...
- ...however, the [documentation](https://api.jquery.com/jquery.ajax/) for jQuery.ajax() mentions that "Cross-domain requests [...] do not support synchronous operation."
- So, I'm guessing that jQuery.ajax() falls back to doing an asynchronous call in the repro above, because `https://d3js.org/d3.v3.min.js` is in a different domain?

**Comment by mgol** [comment]
Thanks for the report.

Your thinking is right, cross-domain scripts are loaded asynchronously and that's been the case for as long as I remember, try switching jQuery to version 1.7.2 in your JS Bin; that version was released in 2012.

While I realize this may be a problem, making especially async scripts synchronous would lead to a detrimental user experience so we'd rather not go that route. For synchronous requests this is still an issue but not as big as you usually have more control over the loading speed of such resources. Also, changing that would be a big breaking change now.

We do have a plan to make all scripts loaded asynchronously but to still preserve script ordering. That will mean the scripts will not fire before the subsequent content but issues like this one would be fixed. See #1895 which tracks this idea for jQuery 4.0.

I'll close it since there's nothing we plan to do here apart from what's already tracked in #1895 but feel free to continue the discussion in this issue.

**Comment by jruales** [comment]
Thanks @mgol! I'll subscribe to that issue to track it.

In the meantime, I'm thinking of using as a workaround something akin to the idea in [this blog post](https://ghinda.net/article/script-tags/), where the scripts are loaded asynchronously, but having a callback chain to ensure they're run in order. (which seems similar to what you've mentioned you're doing for 4.0 "We do have a plan to make all scripts loaded asynchronously but to still preserve script ordering.")
