### ISSUE TITLE
Refused to apply inline style because it violates the following content security policy directive

### ISSUE THREAD

**Issue by calaluis** [jquery/jquery#4811]
### Description ###

Hi,

I am writing to you, regarding the application of Content Security Policy (CSP). That is, to which any dependent library is applied to it, triggering a vulnerability error.

For example, the use of the BlockUI library.

### Link to test case ###

![image](https://user-images.githubusercontent.com/33674615/99967621-e4073300-2d76-11eb-8461-e27bc363813d.png)

**Comment by ygj6** [comment]
I think this issue has nothing to do with jquery, because the issue is triggered only when the inline style or script is set in the dynamically created element, such as: `$(".test").append("<h1 style='color: red' onclick='console.log(1)'>test</h1>>test</h1>")`, if you want to comply with CSP developers can extract the inline style, such as
https://developers.google.com/web/fundamentals/security/csp?utm_source=devtools#inline_code_is_considered_harmful
```
<script>
  function doAmazingThings() {
    alert('YOU AM AMAZING!');
  }
</script>
<button onclick='doAmazingThings();'>Am I amazing?</button>
```
to something more like:
```
<!-- amazing.html -->
<script src='amazing.js'></script>
<button id='amazing'>Am I amazing?</button>
```
```
// amazing.js
function doAmazingThings() {
  alert('YOU AM AMAZING!');
}
document.addEventListener('DOMContentLoaded', function () {
  document.getElementById('amazing')
    .addEventListener('click', doAmazingThings);
});
```

**Comment by timmywil** [comment]
Thanks for opening an issue. As per @ygj6's comment, the inline scripts should be removed to comply with CSP.
