### ISSUE TITLE
Jquery +datatables causing CSP errors for inline style

### ISSUE THREAD

**Issue by ripjal** [jquery/jquery#4827]
I have been trying to get rid of the unsafe-inline from the CSP style-src headers as it is vulnerable. While removing this, I am getting below errors in jQuery execution in chrome:

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-TXYxR0tlamZ1emk2a3Y4RHFwdTdTZ0JaR1R2TTdEaUk=' 'unsafe-eval' ". Either the 'unsafe-inline' keyword, a hash ('sha256-Z0MkpGRk0/9QW+7eJ/G1D//1i6WKVbat+HlIwkiFln4='), or a nonce ('nonce-...') is required to enable inline execution

While debugging I found that it is failing at

> From jquery 3.5.1
`tmp.innerHTML = wrap[ 1 ] + jQuery.htmlPrefilter( elem ) + wrap[ 2 ]; `

in buildFragment method. At failing point ,elem is evaluated as a string which contains the html for tr containing inline style generated by the datatables.Even though the datatables seems to be applying CSP safe way as below but when it gets passed back to jQuery whole TR containing inline style is loaded as innerHTML which gets failed due to unsafe-inline

> from datatables.js 1.10.21
`_fnApplyToChildren( function(nSizer, i) {
            nSizer.innerHTML = '<div class="dataTables_sizing">'+footerContent[i]+'</div>';
            nSizer.childNodes[0].style.height = "0";
            nSizer.childNodes[0].style.overflow = "hidden";
            nSizer.style.width = footerWidths[i];
        }, footerSrcEls );
    }

As seen above datatables is applying inline styles in CSP acceptable way as they are applying style property directly on the elements style property Below is the run time value that gets evaluated in "elem" in jquery buildFragment method containing inline styles
`<tr role="row"><th class="dataGridCheckBoxCell sorting" aria-controls="tablegrid" rowspan="1" colspan="1" aria-label=": activate to sort column ascending" style="padding-top: 0px; padding-bottom: 0px; border-top-width: 0px; border-bottom-width: 0px; height: 0px; width: 41px;" role="columnheader"><div class="dataTables_sizing" **style="height: 0px; overflow: hidden;"**><div id="checkAllQueues" class="selectable" role="checkbox"></div>`

I am not sure if it is a data tables issue or jquery or combination of both. Any insight on the issue will be helpful or any workaround that can be applied

i am using jQuery 3.5.1, datatables 1.10.21 and jquery migrate 3.3.2

**Comment by mgol** [comment]
Thanks for the report. This was fixed already in #4724 and the fix will be included in jQuery 4.0. We don't currently plan to backport it to the 3.x line as we'd have to duplicate the code - the CSP-compliant version wouldn't work in IE 9.

**Comment by rhu25** [comment]
@mgol is jquery 4.0 released? we still hv this CSP issue on 3.6

**Comment by mgol** [comment]
@rhu25 it hasn't been released yet. That said, we decided to postpone some of the tasks originally planned for 4.0 to 5.0 and we'll be working on preparing a 4.0.0 beta soon, maybe within the next few weeks.

That said, looking at the original report now, it seems the issue here may have lied elsewhere. The code path being modified was the one used for creating elements from passed HTML - and if you pass it as HTML with inline style definitions inside that element, you may very well trigger the same warning even if we don't modify the input.

That said, it's hard to tell without a test case. For now, you can try the [jQuery Git build](https://releases.jquery.com/jquery/) and see if it resolves your issue. Don't use it in production, though, as it's still a development version.

**Comment by gsteri1** [comment]
This bug is biting a lot of projects. jsgrid is failing in my project when we turn on CSP. Some of the "..follow us on LinkedIn" widgets are complaining about it as well.

**Comment by gsteri1** [comment]
I manually applied some of the changes in https://github.com/jquery/jquery/pull/4724 and find that it does not cure the CSP problem. The problem is in the htmlPrefilter call which remains in the pull request. The CSP gets triggered because of the style tags embed in the html. Happy to be wrong, but I don't think the pull will fix the problem. Here is my change:

				tag = ( rtagName.exec( elem ) || [ "", "" ] )[ 1 ].toLowerCase();
				wrap = wrapMap[ tag ] || arr; //wrap = wrapMap[ tag ] || wrapMap._default;
				//tmp.innerHTML = wrap[ 1 ] + jQuery.htmlPrefilter( elem ) + wrap[ 2 ]; <<---- The browser had been complaining about this line

				// Descend through wrappers to the right content
				j = wrap.length; //j = wrap[ 0 ];
				while ( --j > -1 ) { //while ( j-- ) {
					tmp = tmp.appendChild( context.createElement( wrap[ j ] ) ); //tmp = tmp.lastChild;
				}
				tmp.innerHTML = jQuery.htmlPrefilter( elem ); //new complaints from browser if all style tags are renamed data-style, there are no errors (and no formatting).


The commented lines are my attempt to be consistent with the pull.

**Comment by mgol** [comment]
`jQuery.htmlPrefilter` is an identity function by default in jQuery >=3.5.0 so that shouldn't matter.

That said, if you have a test case that causes CSP issues with the jQuery 4.0.0-pre (you can take if from https://releases.jquery.com/git/jquery-git.js for testing purposes; just don't use it in a production app), please open a new issue with more details.
