### ISSUE TITLE
slow creation of complex element

### ISSUE THREAD

**Issue by paolobenve** [jquery/jquery#4876]
As pointed out in https://stackoverflow.com/questions/9614932/best-way-to-create-large-static-dom-elements-in-javascript/28136956#28136956, executing something like

`$("#my-div").append($("<div><table><tr><td>1</td><td>2</td></tr></table></div>"));`

is very slow in comparation with

`document.getElementById("my-div").innerHTML("<div><table><tr><td>1</td><td>2</td></tr></table></div>")`

The ratio of the execution times of the two solutions is 300ms/5ms, i.e. jquery solution is about 60 times slower with respect with the pure js solution.

A better execution time would be appreciated.

**Comment by dmethvin** [comment]
1. Those aren't even the same thing. The jQuery example is appending to whatever is in the element, the DOM one is replacing everything in the element.
2. It does not take anywhere close to 300ms to execute that code once, even on the jQuery that existed in 2015 when the answer was written.
3. There is no `tbody` in the markup being appended. jQuery modifies the created DOM with one so that all supported browsers work properly.
4. If you definitely know your use case doesn't need jQuery workarounds and the bottleneck is really DOM creation, use the native methods.
