### ISSUE TITLE
Syntax error caused by $('.hello').filter(':is(.world) > .hello') (unrecognized expression: unsupported pseudo: is) when multiple elements need to be filtered at once

### ISSUE THREAD

**Issue by ianthedev** [jquery/jquery#4884]
The issue is about the [`:is()` pseudo-class](https://drafts.csswg.org/selectors-4/#matches). Please note that the demos below are simplified from real use cases, and therefore their `:is()` contains only a class selector.

----

When there is only one element to be filtered, it works fine:
```html
<div class="world">
    <div class="hello">Test</div>
</div>

<script>
$('.hello').filter(':is(.world) > .hello').css('background-color', 'yellow');
</script>
```
**[Demo](https://codepen.io/IanY/pen/LYWEGBR)**

----

However, when there are multiple elements to be filtered at once:
```html
<div class="world">
    <div class="hello">Test</div>
    <div class="hello">Test</div>
</div>

<script>
$('.hello').filter(':is(.world) > .hello').css('background-color', 'yellow');
</script>
```
The following error occurs:
```
Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: is
```
**[Demo](https://codepen.io/IanY/pen/KKWwzmw)**

----

Using `$(this)` inside `.each` to filter elements one by one works fine:

```html
<div class="world">
    <div class="hello">Test</div>
    <div class="hello">Test</div>
</div>

<script>
$('.hello').each(function () {
    $(this).filter(':is(.world) > .hello').css('background-color', 'yellow');
});
</script>
```
**[Demo](https://codepen.io/IanY/pen/mdWyPmG)**

----

Using `$(this)` inside an event handler works fine, too:

```html
<div class="world">
    <div class="hello">Click me to test</div>
    <div class="hello">Click me to test</div>
</div>

<script>
$('.hello').on('click', function () {
    $(this).filter(':is(.world) > .hello').css('background-color', 'yellow');
});
</script>
```
**[Demo](https://codepen.io/IanY/pen/yLMyOoY)**

----

The issue have been observed on the desktop versions of Mozilla Firefox and Google Chrome.

**Comment by mgol** [comment]
Thanks for the report! This is because some code paths are going through native `querySelectorAll` and some through Sizzle which has no support for more modern CSS features (https://github.com/jquery/sizzle/issues/44). Instead of adding such support to Sizzle which would make it much larger, for jQuery 4.0 we have plans to rely even more on native qSA, rewriting selectors that don't work to ones that do instead of the current logic which more or less is: if the selector doesn't work, skip `qSA` completely and use our own custom Sizzle selection.

I'm actually surprised we don't have a task for this yet, let me use this issue to track this then.
