### ISSUE TITLE
Deprecated JSON parser thing doesn't like just commas

### ISSUE THREAD

**Issue by suspiciousfellow** [jquery/jquery#4901]
### Description ###

This is undoubtedly extremely anal and probably not affecting anyone, but the JSON parser in jQuery doesn't like commas

### Link to test case ###

No link, but in console on a page with jQuery do:

```
delete window.JSON
$.parseJSON(',')
```

expected result should be `Invalid JSON: ,`

Instead gets on chrome `Uncaught SyntaxError: Unexpected token , in JSON at position 0`

Once again I genuinely apologise for bringing up this practically pointless thing that doesn't matter.

**Comment by mgol** [comment]
All jQuery versions since 2.0.0 define `jQuery.parseJSON` as an alias for `JSON.parse`, some with just a slight modification to account for an old Android bug:
```js
jQuery.parseJSON = function( data ) {
	return JSON.parse( data + "" );
};
```
Therefore, I assume this is about jQuery 1.x which hasn't been supported for many years now.

Even if it was, it doesn't sound like an issue; both in jQuery and in the native method you're getting an SyntaxError, just with a different message and the message isn't standardized.

**Comment by suspiciousfellow** [comment]
Fair; didn't realise 1.x wasn't supported (should have checked)
