### ISSUE TITLE
Argument unused inside jquery 3.6.0

### ISSUE THREAD

**Issue by YKProg** [jquery/jquery#4918]
### Low Priority (not a bug) ###

Inside https://code.jquery.com/jquery-3.6.0.min.js ,
I saw this code:

even: function() { return this.pushStack(S.grep(this,**function(e,t)**{ return(t+1)%2 }))} ,
odd: function() { return this.pushStack(S.grep(this,**function(e,t)**{ return t%2 }))}

For me its looks like function(e,t) takes "e" with no reason.

**Comment by fecore1** [comment]
**Mainly because the index is injected in the second parameter.**

---

And the detailed analysis is as follows:

function odd uncompressed: https://github.com/jquery/jquery/blob/3.6.0/dist/jquery.js#L234-L238

```js
	odd: function() {
		return this.pushStack( jQuery.grep( this, function( _elem, i ) {
			return i % 2;
		} ) );
	},
```

so `function(e,t){ return t%2 }` eq 

```js
jQuery.grep( this, function( _elem, i ) {
	return i % 2;
}
```

and callback in `jQuery.grep` injected like [`callback( elems[ i ], i )`](https://github.com/jquery/jquery/blob/3.6.0/dist/jquery.js#L448)

and the index is injected in the second parameter，"e" just to fill the first position.

**Comment by YKProg** [comment]
So **grep()** makes **_elem** to be **this[i]** , and its for **grep()** [conditional statement](https://github.com/jquery/jquery/blob/3.6.0/dist/jquery.js#L450)
thanks @fecore1 for the explanation.

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com
