### ISSUE TITLE
.remove( selector ) is broken

### ISSUE THREAD

**Issue by dotnetCarpenter** [jquery/jquery#4934]
### Description ###
Using jQuery 3.6.0.

[.remove( selector )](https://api.jquery.com/remove/) is broken.

```html
<div id="test1">
	<div class="remove-this">remove-this</div>
	<div class="do-not-remove-this">do-not-remove-this</div>
</div>

<div id="test2">
	<div class="remove-this">remove-this</div>
	<div class="do-not-remove-this">do-not-remove-this</div>
</div>
```

```js
$('#test1').remove('.remove-this');

console.log ($('#test1').html());
// <div class="remove-this">remove-this</div>
// <div class="do-not-remove-this">do-not-remove-this</div>


$('#test2').find('.remove-this').remove();

console.log ($('#test2').html());
// <div class="do-not-remove-this">do-not-remove-this</div>
```

### Link to test case ###

https://jsbin.com/batuqimute/edit?html,js,console,output

Tested in Microsoft Edge | 93.0.961.47 (Official build) (64-bit) and Firefox 93.0b6 (64-bit)

**Comment by mgol** [comment]
Thanks for the report. However, that's not how this API works. The selector filters within DOM nodes in the jQuery object, not their descendants. Since the element with the `test1` ID doesn't have the `remove-this` class, nothing gets matched. Please have another look at the relevant example on the API page, it demonstrates how this works.
