### ISSUE TITLE
$(this).val() returns wrong value - changes double space to single space

### ISSUE THREAD

**Issue by nroakton** [jquery/jquery#4941]
Bug Reports:
I have found that $(this).val() does not return the actual value of an <option> value.  My example shows that if an option value is "Option  1" i.e. "Option[space][space]1", $(this).val() removes a [space] from the string and returns "Option[space]1".

see test case.

Thanks

### Link to test case ###
https://jsbin.com/qolovivuga/1/edit?html,js,console,output

**Comment by nroakton** [comment]
https://jsbin.com/qolovivuga/1/edit?html,js,console,output

**Comment by fecore1** [comment]
First, you shouldn't use `Option[space][space]1` for double spaces because [multiple spaces will show up as a single space in the browser](https://stackoverflow.com/questions/433493/why-does-html-require-that-multiple-spaces-show-up-as-a-single-space-in-the-brow).

and it's [in the specification](https://www.w3.org/TR/REC-html40/struct/text.html#h-9.1):
> In particular, user agents should collapse input white space sequences when producing output inter-word space.

you can get `Option[space][space]1` by using `&nbsp;` , see [test case](https://jsbin.com/vicubon/edit?html,js,console,output)


btw. In my opinion, `this.options[this.selectedIndex].innerText` gets the text of the option instead of the value of the select. `this.value` will return `Option[space]1` and equals to `$(this).val()`

**Comment by mgol** [comment]
Thanks for the report. `innerText` actually also collapses whitespace in most cases (with exceptions like `white-space: pre`) as it returns more or less what the browser renders. `textContent` would return the true text content.

However, if you look at the spec, the `value` of the `option` element is ([spec](https://html.spec.whatwg.org/#attr-option-value)):

> The value attribute provides a value for element. The value of an option element is the value of the value content attribute, if there is one, or, if there is not, the value of the element's text IDL attribute.

This links to the [text IDL attribute](https://html.spec.whatwg.org/#dom-option-text) section (emphasis mine):

> The text IDL attribute, on getting, must return the result of **stripping and collapsing ASCII whitespace** from the concatenation of data of all the Text node descendants of the option element, in tree order, excluding any that are descendants of descendants of the option element that are themselves script or SVG script elements.

So the behavior is expected. And, indeed, if instead of trying `innerText` or `textContent` you access `this.options[this.selectedIndex].value`, you'll see that whitespace is collapsed.

If you don't want any special transformations done on your options values, provide the `value` attribute in addition to the `option` text content: https://jsbin.com/yutoquk/1/edit?html,js,console

**Comment by goarblt** [comment]
hello
https://www.evil.com
