### ISSUE TITLE
e.replace is not a function

### ISSUE THREAD

**Issue by philiprbrenan** [jquery/jquery#4942]
TypeError: e.replace is not a function at Function.htmlPrefilter (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:47609) 

We are getting a number of these reported on our web site - I am not sure whether the message above is enough to help locate the bug or whether there is something else I should do: so far we have not been able to reliably reproduce this error.

**Comment by mgol** [comment]
The call happens here: https://github.com/jquery/jquery/blob/3.3.1/src/manipulation/buildFragment.js#L45; this is what gets invoked when you call manipulation methods like `.append(something)`; that `something` is problematic here. I don't know, though, what kind of argument you'd have to pass so that it's not a string but it still goes to this `else` clause in `buildFragment` that executes `jQuery.htmlPrefilter`. It's hard to tell more with just such small info, without a stack trace, more info about passed arguments. etc.

That said, the replacement in `jQuery.htmlPrefilter` caused security issues so [we removed it in jQuery 3.5.0](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/); I'd advise to update to the latest 3.x version, currently 3.6.0.

**Comment by goarblt** [comment]
hello
https://www.evil.com
