### ISSUE TITLE
Null value in jQuery.get doesn't allow use of dataType

### ISSUE THREAD

**Issue by jcubic** [jquery/jquery#4989]
### Description ###
According to [jQuery.get documentation](https://api.jquery.com/jQuery.get/) you can use `null` as success function to be able to use `dataType`. But it seems that it's not working. The only way to get text from JSON response is to use `$.noop`. So this need to be fixed or documentation needs to be updated.

I use jQuery 3.6.0.

### Link to test case ###

```javascript
await $.get("https://httpbin.org/json", null, "text")
await $.get("https://httpbin.org/json", $.noop, "text")
```

https://jsbin.com/safuliduje/edit?html,css,js,output

**Comment by mgol** [comment]
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) as the issue template requested? Thanks!

**Comment by jcubic** [comment]
@mgol Added link.

**Comment by mgol** [comment]
OK, it looks like the current implementation allows you to provide `null` as a placeholder for the callback but doesn't allow you to skip the `data` parameter then. This means the following:
```js
await $.get("https://httpbin.org/json", null, "text");
```
doesn't work as expected but the following:
```js
await $.get("https://httpbin.org/json", null, null, "text");
```
does. With hindsight, all of these short forms of `jQuery.ajax` with their positional parameters were a mistake as there's always a lot of parameter juggling. Perhaps we should update the doc that if you provide `null` for the callback then you also need to provide the `data` parameter, even if `null` or `undefined`.

We could also update the implementation to handle this case as well but that wouldn't fix all those past versions anyway so I'm not sure if it's worth it; we'd need to update the docs as well anyway.

Thoughts, @jquery/core?

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by goarblt** [comment]
hello
https://www.evil.com

**Comment by gibson042** [comment]
Even though parameter hockey isn't great and we don't want to encourage the pattern, I think it's worth fixing code to match documentation. The interesting cases are those with parameter gaps, and since `dataType` is documented to require `success` (excluding `jQuery.get(url, data, dataType)` and `jQuery.get(url, dataType)`), those are limited to missing `data` (i.e., `jQuery.get(url, fnOrNull, strOrUndef)`).

AFAICT, we just need to update [`if ( typeof data === "function" )` in the definition of jQuery.{get,post}](https://github.com/jquery/jquery/blob/2525cffc42934c0d5c7aa085bc45dd6a8282e840/src/ajax.js#L850) to include an alternative such as `|| data == null` or `|| data === null`.

**Comment by mgol** [comment]
PR: #5139.
