### ISSUE TITLE
Strange behaviour on .html() method

### ISSUE THREAD

**Issue by moz667** [jquery/jquery#5020]
### Description ###
*  What do you expect to happen?

    .html() would get content of an element

*  What actually happens?
   
    got the content of the element + `</p>`

*  Which browsers are affected?

    chrome (last version)
    firefox (last version)

### Link to test case ###
https://jsfiddle.net/bu91k6hg/3/

**Comment by dmethvin** [comment]
Looks right to me. There's a `<p>` in the "JSON data" (the browser doesn't know it's JSON, and the code is treating it as HTML which has different parsing rules). You can see the `<p>` in the browser's visual presentation and in the devtools. The paragraph is auto-closed by the browser's HTML parser when it reaches the end of the enclosing div. Notice that JSFiddle shows the closing `</div>` in red because it sees that the paragraph is not closed. 

It seems like `.text()` would be more appropriate here. There's no reason to interpret this as HTML.
