### ISSUE TITLE
[Q & A] Registers an unload listener

### ISSUE THREAD

**Issue by tranngocson1996** [jquery/jquery#5056]
### Description ###
Hi everyone, I used [https://pagespeed.web.dev](https://pagespeed.web.dev) to check speed my website. I have one problem for js, specifically it is with jquery.
It's `Registers an unload listener`
Note: `The most important way to optimize for bfcache in all browsers is to never use the unload event. Ever!`
I see with jquery is still using `unload`, Do you have any idea ?
Thank you

**Comment by dmethvin** [comment]
More detail (jQuery version, specific message, etc.) always helps narrow down the problem and make sure we're not chasing the wrong thing. Could you provide that?

There's only one place that I see the unload event being used, and it's in Sizzle: https://github.com/jquery/sizzle/blob/main/src/sizzle.js#L624-L641

So that code is needed for IE and Edge compatibility. It looks like the event is attached on all browsers though, so it might be possible to reduce the scope to just do it on IE. But again, let's see a complete test case to ensure we're chasing the right thing.

**Comment by tranngocson1996** [comment]
@dmethvin Exactly, It's this piece of code
Any ideas to make it run only on IE.

**Comment by dmethvin** [comment]
AFAICT that code only runs if you have an iframe as the document. My reply did ask for a test case to be sure this is where the message is coming from.

**Comment by tranngocson1996** [comment]
ok Thank you

**Comment by mgol** [comment]
FWIW, jQuery 4+ will have this code scoped to IE only. We can't do the same for jQuery 3.x as we can't detect Edge that easily without using userAgent which we avoid.
