### ISSUE TITLE
[BUG] Documentation says `this` refers to the iterated element, inside `.map()` 

### ISSUE THREAD

**Issue by Pictor13** [jquery/jquery#5097]
### Description ###

As per title, the [documentation](https://api.jquery.com/map/) suggest one can use `this`, into `.map()` callback, to access the current DOM element:

>Within the callback function, this refers to the current DOM element for each iteration.

but according to https://bugs.jquery.com/ticket/2445 this should have been corrected to not mislead the user.

### Link to test case ###

* https://api.jquery.com/map/ (just before **"Examples"**)
* https://bugs.jquery.com/ticket/2445 (maybe a regression after this issue?)
* https://jsfiddle.net/5wmva0o1/ (test case about current behaviour)

**Comment by dmethvin** [comment]
The reason `this` isn't the element is because the example is using an arrow function, which does not have its own `this` and inherits the value from its outer scope. Use `function` if you want to use `this`. 

I'm not sure if we need any documentation change here because it's a JavaScript thing and not a jQuery thing. Keep in mind that there are likely to be _many_ places in the API where this same change would apply, including [`.each()`](https://api.jquery.com/each/#each-function), all the setters that take a function (which is most of them), such as [`.css( propertyName, function)`](https://api.jquery.com/css/#css-propertyName-function), and event handlers. 

The old [trac-2445](https://bugs.jquery.com/ticket/2445) ticket is about [`jQuery.map()`](https://api.jquery.com/jQuery.map/#jQuery-map-array-callback) and not [`jQuery().map()`](https://api.jquery.com/map/) so it's not relevant here.

**Comment by Pictor13** [comment]
You are right; have to keep it in mind, instead of defaulting to lambdas!
Thank you @dmethvin for taking the time to give a clear answer; I close the issue.

**Comment by mgol** [comment]
I wouldn't rule out adding something to the docs as this can be confusing to users that don't think about the JS aspect here but Dave is right that there are many affected places and there doesn't seem to be a good place to put this without duplicating such a warning too much.

**Comment by dmethvin** [comment]
One thing that might work would be to add a paragraph or two in https://api.jquery.com/Types/#Function to describe the situation. In almost every case it's possible to use an arrow function because what would normally be the `this` object is duplicated somewhere in the args.

**Comment by mgol** [comment]
Sounds like a good idea!

@Pictor13 would you like to submit such a PR?
