### ISSUE TITLE
Inconsistency in using prop with autocapitalize across browsers

### ISSUE THREAD

**Issue by jdlrobson** [jquery/jquery#5202]
It seems like the behaviour of $( '#searchInput' ).prop( 'autocapitalize' ) differs on browser. On Firefox it returns undefined and on Chrome it returns "none".

autocapitalize acts like a property in Chrome (document.getElementById('searchInput').autocapitalize returns 'sentences' in Chrome but undefined in Firefox. According to specs it should probably be a treated as an attribute.

I'm not sure if jQuery is behaving as expected here.
I would expect prop to always return undefined, if we want to follow the spec.

### Link to test case ###
```
$('<input>').attr('autocapitalize', 'none').prop('autocapitalize')
```
In Firefox 109: undefined
In Chrome 109: none.

**Comment by mgol** [comment]
While jQuery normalizes a lot of cross-browser behaviors, it is not our goal to implement new APIs in browsers that don't have native implementation yet. You need to account for that in your code by checking if an API you'd like to use is available everywhere - and, if not, either not rely on this API or accept the browser differences and just make sure it degrades gracefully in browsers without this API.

Due to that, I'm going to close the issue. Feel free to continue the discussion here if you have some doubts.
