### ISSUE TITLE
issue with .eq method in versions  > 3.6.0

### ISSUE THREAD

**Issue by contradictionary** [jquery/jquery#5210]
### Description
When selecting with the .eq(index) method, on version 3.6.0 chaining methods don't give runtime error even if the index is incorrect. where as in the version starting from 3.6.1, it gives runtime error.

_Error occurs when the index is within the length limit and is in decimal points. example 1.2,2.1 etc_

### Link to test case
 where there is error  (version 3.6.3): https://codepen.io/rvsingh42/pen/ExexzqY?editors=1011
 where it works fine (version 3.6.0) : https://codepen.io/rvsingh42/pen/vYzYqEx

**Comment by mgol** [comment]
Thanks for the report.

This is caused by #5003 which fixed #4998. We used to stop at the first element that was falsy in `3.6.0`:
https://github.com/jquery/jquery/blob/0cc1ad64ab0f482c13d6edd2a5226f309dd00006/src/attributes/classes.js#L40-L41
Now, we no longer do since `3.6.1`:
https://github.com/jquery/jquery/blob/6ad26fc72ddbc9d3f3886f98164efabc112d6c78/src/attributes/classes.js#L39-L40

However, the main issue here is that `3.2` is not a valid input to `.eq()` and thus it provides you with nonsensical output - a jQuery object with a single element being `undefined`. For such an incorrect input we generally don't guarantee sensible behavior. There are a lot of ways in which such an incorrect element may not work correctly with jQuery APIs; fixing such issues looks like a possible Pandora Box.

How did you get such a fractional input passed to `.eq()`?

**Comment by timmywil** [comment]
I think the error might be even more helpful than silently failing. Neither really "works", and one explains why.

**Comment by contradictionary** [comment]
> How did you get such a fractional input passed to `.eq()`?

in slick-carousel
 slidesToShow:2.5
