### ISSUE TITLE
Breaking change on height(Upgrading from 3.5.1 to 3.6/3.7)

### ISSUE THREAD

**Issue by parallels999** [jquery/jquery#5270]
Using `.height()` is rounding the value

  *  **What do you expect to happen?**
  get the real height
  *  **What actually happens?**
 the browser shows the real height but jquery get it rounded
  *  **Which browsers are affected?** tested on
  chrome 114.0.5735.110
  opera 99.0.4788.65
  chromium:113.0.5672.127
  edge 114.0.1823.43
  firefox 103.0.2
 
### Description ###
having rounded height produces misaligned objects

**V3.5:** 
![image](https://github.com/jquery/jquery/assets/109294935/f9e166f1-1f3e-42eb-bd37-07d70ef57464)
**V3.6/V3.7:** 
![image](https://github.com/jquery/jquery/assets/109294935/633ed634-e266-4201-981e-f64d8271730d)

### Link to test case ###

Same code, just different versions of jquery
**V3.7.0:**  https://jsfiddle.net/6jqh4pmb/1/ (fails)
**V3.6.4:**  https://jsfiddle.net/6jqh4pmb/2/ (fails)
**V3.5.1:**  https://jsfiddle.net/6jqh4pmb/3/ (This is working fine)

**Comment by parallels999** [comment]
ping @mgol

**Comment by mgol** [comment]
Note: we will fix it only in Chrome & Safari. In Firefox & IE it will remain an integer. This is because those browsers fail the `reliableTrDimensions` support test and we need to use `outerHeight` as a workaround - which does not return fractional values.

If Firefox ever starts passing the support test, it will automatically get fractional values here.

**Comment by mgol** [comment]
PRs:
* `main` (`4.x`): #5278
* `3.x-stable`: #5279

**Comment by cyfung1031** [comment]
This is still not making sense in 3.7.1

https://jsfiddle.net/lunarlogic489/Las4vtbz/

<img width="521" alt="Screen Shot 2024-03-25 at 19 38 33" src="https://github.com/jquery/jquery/assets/44498510/c17ce0bb-fffa-4d15-af8b-f1af3db7079e">

Why tr height can be larger than tbody height?

**Comment by timmywil** [comment]
The difference was noted in a previous comment https://github.com/jquery/jquery/issues/5270#issuecomment-1608269121. Further explanation in your issue.

**Comment by mgol** [comment]
It's a bit unfortunate that we penalize Firefox here though its behavior is technically correct according to the current spec. That said, there's a spec issue at https://github.com/w3c/csswg-drafts/issues/4444 that is still open; the discussion there suggests the current spec may not be what's wanted and may need to change. Changing this behavior would be a breaking change in jQuery and there's a risk we'd have to change back once the spec issue is clarified. That's why I'd prefer to wait with changes here until after the spec issue is clarified. It seems the discussion there stalled, though.
