### ISSUE TITLE
Strange error behavior of event delegation when customizing jQuery

### ISSUE THREAD

**Issue by ajiho** [jquery/jquery#5379]
### Description ###
My build script is as follows:

```
npm run build -- --esm --include=event --include=traversing
```
When I use event delegation

html
```
<button data-test1="test1" data-test2="test2">test</button>
```

```
$(document).on('click', '[data-test1][data-test2]', function () {
    //error: Uncaught TypeError: jQuery.attr is not a function
});
```

According to the description of readme.md,**selector: The full jQuery selector engine. When this module is excluded, it is replaced with a rudimentary selector engine based on the browser's querySelectorAll**,However, querySelectorAll supports this type of selector
I would like to ask if this design is intentional or is it a flaw?

By the way, I have already tested it in the full version and there is no such issue

Thank you.

**Comment by mgol** [comment]
Thanks for the report. This is on the `main` branch, isn't it? That's code for future jQuery 4.0 which is not stable yet. When building for production use, it's recommended to check out the latest tag and build there.

In jQuery 3.x, the `ATTR` filter uses `find.attr`:
https://github.com/jquery/jquery/blob/87467a6f62b5fbd820ab387836e2a6fb186cbc1b/src/selector.js#L1057
defined in the same file:
https://github.com/jquery/jquery/blob/87467a6f62b5fbd820ab387836e2a6fb186cbc1b/src/selector.js#L853-L876

On the `main` branch, I removed the selector version and started using `jQuery.attr`:
https://github.com/jquery/jquery/blob/c98597eaf5e144ee5e549cb41984687cd1033068/src/selector.js#L454
which lies outside of this module and this dependency was not made explicit.

Depending on `attr.js` is a bit hard because that module depends on `selector` itself:
https://github.com/jquery/jquery/blob/c98597eaf5e144ee5e549cb41984687cd1033068/src/attributes/attr.js#L7
but that's mostly an artifact from jQuery 3.x previously depending on `jQuery.find.attr` from the selector module here:
https://github.com/jquery/jquery/blob/87467a6f62b5fbd820ab387836e2a6fb186cbc1b/src/attributes/attr.js#L68
while on the `main` branch a native `getAttribute` is used:
https://github.com/jquery/jquery/blob/c98597eaf5e144ee5e549cb41984687cd1033068/src/attributes/attr.js#L61

We should remove the dependency on `selector.js` from `attr.js`. As for fixing the selector issue, we have then two options:
1. Move from using `jQuery.attr` to the native `getAttribute` directly - this is more in line with what jQuery 3.x was doing as the `find.attr` wrapper was in most cases deferring to the native method. However, that avoids `attrHooks` for attribute matching which is consulted when using the jQuery `attr` method.
2. Add the dependency on `attr.js` to `selector.js`. That will make `attrHooks` respected.

I'm gravitating towards the first option for the following reasons:
1. It's more in line with the current `selector` behavior that has been followed for many years.
2. There are not that many built-in `attrHooks` left on the `main` branch. There's one for `type` but that's just for IE and only a setter (`selector` only needs getters) and there's one for boolean attributes - this latter one may actually constitute a breaking change as the value for all boolean attributes is always its lowercase name.

**Comment by mgol** [comment]
Actually, I was wrong about the logic change. `Expr.attrHandle` used to be populated in `src/attr.js` in `3.x`:
https://github.com/jquery/jquery/blob/b922eed934a4dcdcb13496eaf951f0623a496041/src/attributes/attr.js#L13
https://github.com/jquery/jquery/blob/b922eed934a4dcdcb13496eaf951f0623a496041/src/attributes/attr.js#L13

On the `4.x` line, this has been moved to be a regular member of `jQuery.attrHooks`:
https://github.com/jquery/jquery/blob/99151d7ab0923aa3aeeb1b957a9063e4e20d31ae/src/attributes/attr.js#L102-L128

Thus, the logic is fine, we just need to declare the dependency explicitly.

I submitted removing unneeded `selector.js` dependencies in PR #5383, I'll submit a separate one to add the dependency on `attr.js` to `selector.js`.

**Comment by mgol** [comment]
PR: #5384
