### ISSUE TITLE
jQuery 3.7.1 is still making wrong calculation of dimensions in Firefox.

### ISSUE THREAD

**Issue by cyfung1031** [jquery/jquery#5456]
This is still not making sense in 3.7.1

https://jsfiddle.net/lunarlogic489/6qc5bmL3/

```html
<div>
  <table style="width:600px;">
    <tbody>
    <tr>
      <td style="white-space:normal;width:120px;">INGRESOS DE ACTIVIDADES ORDINARIAS</td>
      <td style="white-space:normal;width:79px;">VENTA DE BIENES</td>
      <td id="td" style="width:235px;"></td>
      <td></td>
    </tr>
    </tbody>
  </table>
</div>
```

```
$('tr').height()
$('tbody').height()
```

<img width="482" alt="Screen Shot 2024-03-25 at 20 18 13" src="https://github.com/jquery/jquery/assets/44498510/4e56659b-7139-44bc-9d50-fe00c4b5c42f">

Why tr height can be larger than tbody height? (Firefox)

Same as 4.0.0 beta

Related to #5270

**Comment by timmywil** [comment]
Thanks for opening an issue. The difference is expected. The browser you are using is not passing the `reliableTrDimensions` support test, so jQuery must use a different way to determine the dimensions, which unfortunately does not return fractional values.

And #5270 is not related because removing bootstrap gives the same results.
