### ISSUE TITLE
Add back tick ` 

### ISSUE THREAD

**Issue by Yasinrabiee** [jquery/jquery#5552]
In the some function back tick or ( ` ) doesn't work.
For example if you want to use CSS function or animate function to set more than one properties you must surround the properties with single quotation or double quotation but you can't use back tick.

Please fix this if possible.

**Comment by timmywil** [comment]
Thanks for opening an issue. I can't say for sure without seeing a test case, but this sounds more like a misunderstanding of CSS or JS syntax than a bug in jQuery. You might find https://developer.mozilla.org/ helpful. Otherwise, I'd refer you to https://stackoverflow.com.

If you can create a working, reduced test case on https://jsfiddle.net, and it turns out to be jQuery-related, we can reopen.

**Comment by Yasinrabiee** [comment]
Thanks, but only backtick in jQuery can't be used in this part, it can be used in other parts.
This problem is not considered, but since backtick is used more often, it is better to use backtick if possible.
